7 
    de.renew.gui.CPNDrawing 37 
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 296 "MarkingAppearance" "Int" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 485 370 56 31 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4 "TraceMode" "Boolean" "FALSE" 2 514 400 514 436 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 503 436 24 16 NULL    REF 6 
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 297 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 508 409 "#1" "Helvetica" 0 12 0 REF 2
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 298 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 48 207 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 300 "TraceMode" "Boolean" "FALSE" 2 59 223 59 320 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 301 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 49 319 20 20 NULL    REF 15 
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 302 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 30 243 "[Any\n waste:#2\n lane:#1]" "Helvetica" 0 12 0 REF 11
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 3 "" "lane" "waste"  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "FigureWithID" "Int" 219 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 9 12 "access _BDItypes;\naccess _WasteCollectorTypes;\nimport de.renew.simulator.Net;\nimport de.renew.call.*;\nimport java.awt.*;\nimport java.awt.event.*;\nimport de.renew.formalism.fsnet.ActionListenerFSNet;\nimport de.renew.formalism.fsnet.TextListenerFSNet;\nimport de.renew.formalism.fsnet.BorderLayoutPanel;" "Helvetica" 0 12 0 NULL NULL 1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 304 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 188 342 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 454 456 " action RESULT.instantiate()@v0@f.pack()" "Helvetica" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 54 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 299 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 20 150 "[Link\n param:\n [ActionEvent\n  actionCommand:#1\n  source:[Button]]]" "Helvetica" 0 12 0 REF 10
            CH.ifa.draw.standard.OffsetLocator 22 -37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 4 "param:source" "param:actionCommand" "" "param"  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 308 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 186 208 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 310 "TraceMode" "Boolean" "FALSE" 2 199 305 198 343 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 320 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 188 289 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 20   
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 311 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 192 315 "#2" "Helvetica" 0 12 0 REF 28
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 312 "TraceMode" "Boolean" "FALSE" 3 194 344 180 320 193 305 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 20  
            CH.ifa.draw.standard.ChopBoxConnector REF 31   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 314 "TraceMode" "Boolean" "FALSE" 2 68 223 192 346 NULL NULL 
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector REF 20   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 316 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 194 345 "\"\"" "Helvetica" 0 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 317 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 114 267 "#2" "Helvetica" 0 12 0 REF 40
            CH.ifa.draw.standard.OffsetLocator -10 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 318 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 156 254 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 319 "TraceMode" "Boolean" "FALSE" 2 172 257 192 224 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 49  
            CH.ifa.draw.standard.ChopBoxConnector REF 27   REF 31 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 321 "TraceMode" "Boolean" "FALSE" 2 203 224 226 259 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 27  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 322 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 221 256 20 20 NULL    REF 58 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 323 "TraceMode" "Boolean" "FALSE" 2 225 273 208 289 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 58  
            CH.ifa.draw.standard.ChopBoxConnector REF 31   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 324 "TraceMode" "Boolean" "FALSE" 2 191 289 173 271 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 31  
            CH.ifa.draw.figures.ChopEllipseConnector REF 49   
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 326 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 162 256 "[]" "Helvetica" 0 12 0 REF 49
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 325 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 215 278 "#1[TextField text:#2]" "Helvetica" 0 12 0 REF 59
            CH.ifa.draw.standard.OffsetLocator 32 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 2 "" "text"  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 328 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 246 212 24 16 NULL  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 309 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 162 165 "[Link\n param:\n [TextEvent\n  source:#1]]" "Helvetica" 0 12 0 REF 27
            CH.ifa.draw.standard.OffsetLocator -1 -32 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 3 "param:source" "param" ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 329 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 237 168 "[Link\n param:\n [TextEvent\n  source:#1]]" "Helvetica" 0 12 0 REF 73
            CH.ifa.draw.standard.OffsetLocator 14 -33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 3 "" "param" "param:source"  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 330 "TraceMode" "Boolean" "FALSE" 2 236 258 253 228 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 58  
            CH.ifa.draw.standard.ChopBoxConnector REF 73   
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 331 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 208 232 "#1[]" "Helvetica" 0 12 0 REF 54
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 332 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 238 234 "#1[]" "Helvetica" 0 12 0 REF 80
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 333 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 176 231 "#1[]" "Helvetica" 0 12 0 REF 50
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 334 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 176 271 "#1[]" "Helvetica" 0 12 0 REF 63
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 "FigureWithID" "Int" 335 406 62 "[Any\n f:[CloseableFrame\n title:(\"Waste Creation\")\n visible:(true)\n components:<[BorderLayoutPanel\n                            center: #3[TextField columns:(20)]\n                            south: [Panel\n                                         components:\n                                          <#1[Button label:(\"A\")]\n                                            #2[Button label:(\"C\")]>]]>\n                            background:(Color.lightGray)]\nal1:[ActionListenerFSNet\n        listener: (this) component:#1]\nal2:[ActionListenerFSNet\n        listener: (this) component:#2]\nal3:[TextListenerFSNet\n        listener: (this) component:#3]\n]" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 27 -188 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  20 122 747 519 
