7 
    de.renew.gui.CPNDrawing 40 
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 14 2 96 189 96 205 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 1 "FillColor" "Color" 255 255 255 40 151 112 38 26 38   
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 149 "FillColor" "Color" 255 255 255 40 205 112 38 26 38    
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 5 "FillColor" "Color" 0 0 0 223 40 14 14  
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8 3 209 136 210 136 210 166 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.contrib.ChopPolygonConnector 
                CH.ifa.draw.contrib.DiamondFigure "attributes" "attributes" 2 "FigureWithID" "Int" 160 "FillColor" "Color" 255 255 255 209 125 42 23   
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 151 "FillColor" "Color" 0 0 0 179 166 63 5    
        CH.ifa.draw.contrib.DiamondFigure "attributes" "attributes" 2 "FigureWithID" "Int" 10 "FillColor" "Color" 255 255 255 346 375 42 23  REF 11 
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 163 2 179 168 152 168 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 152 "FillColor" "Color" 0 0 0 179 166 23 5   
            CH.ifa.draw.standard.ChopBoxConnector REF 4   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 164 2 230 171 230 195 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 153 "FillColor" "Color" 0 0 0 219 166 23 5   
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 147 "FillColor" "Color" 255 255 255 174 195 112 38 26 38    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 165 2 195 233 130 269 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 154 "FillColor" "Color" 255 255 255 40 269 112 38 26 38    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 166 3 152 288 230 288 230 324 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 30  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 16 "FillColor" "Color" 0 0 0 219 324 23 5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 167 4 40 224 25 224 25 326 179 326 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 15 "FillColor" "Color" 0 0 0 179 324 23 5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 168 3 210 329 210 340 311 340 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 11 "FillColor" "Color" 0 0 0 179 324 63 5   
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 156 "FillColor" "Color" 255 255 255 311 322 112 38 26 38    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 169 2 367 360 367 375 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 46  
            CH.ifa.draw.contrib.ChopPolygonConnector REF 14   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 170 4 388 386 443 386 443 281 423 281 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.contrib.ChopPolygonConnector REF 14  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 161 "FillColor" "Color" 255 255 255 311 262 112 38 26 38    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 171 2 367 398 367 417 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.contrib.ChopPolygonConnector REF 14  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 158 "FillColor" "Color" 255 255 255 311 417 112 38 26 38    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 172 3 366 262 366 136 251 136 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 55  
            CH.ifa.draw.contrib.ChopPolygonConnector REF 11   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 173 2 230 108 230 125 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 184 "FillColor" "Color" 255 255 255 174 70 112 38 26 38   
            CH.ifa.draw.contrib.ChopPolygonConnector REF 11   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 174 2 367 455 367 472 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 60  
            CH.ifa.draw.figures.ChopEllipseConnector 
                CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 7 "FillColor" "Color" 255 255 255 357 471 20 20    
        CH.ifa.draw.figures.GroupFigure 3 REF 13 REF 18 REF 23  
        CH.ifa.draw.figures.GroupFigure 3 REF 44 REF 40 REF 35  
        CH.ifa.draw.figures.GroupFigure 2 REF 74 
            CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 6 "FillColor" "Color" 0 0 0 360 474 14 14   
        CH.ifa.draw.figures.GroupFigure 2 REF 46 
            CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 157 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 346 326 "Produkt\nprüfen" "Helvetica" 0 12 0 REF 46 
                CH.ifa.draw.standard.OffsetLocator 0 0 
                    CH.ifa.draw.standard.RelativeLocator 0.5 0.5     
        CH.ifa.draw.figures.GroupFigure 2 REF 6 
            CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 150 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 67 209 "Produkt\nversenden" "Helvetica" 0 12 0 REF 6 
                CH.ifa.draw.standard.OffsetLocator 0 0 
                    CH.ifa.draw.standard.RelativeLocator 0.5 0.5     
        CH.ifa.draw.figures.GroupFigure 2 REF 30 
            CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 155 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 51 273 "Rechnungsaus-\ndruck versenden" "Helvetica" 0 12 0 REF 30 
                CH.ifa.draw.standard.OffsetLocator 0 0 
                    CH.ifa.draw.standard.RelativeLocator 0.5 0.5     
        CH.ifa.draw.figures.GroupFigure 2 REF 4 
            CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 2 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 68 155 "Produkt\nverpacken" "Helvetica" 0 12 0 REF 4 
                CH.ifa.draw.standard.OffsetLocator 0 0 
                    CH.ifa.draw.standard.RelativeLocator 0.5 0.5     
        CH.ifa.draw.figures.GroupFigure 2 REF 25 
            CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 148 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 202 199 "Rechnung\nerstellen" "Helvetica" 0 12 0 REF 25 
                CH.ifa.draw.standard.OffsetLocator 0 0 
                    CH.ifa.draw.standard.RelativeLocator 0.5 0.5     
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 177 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 119 3 "Versandhändeler" "Helvetica" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 1 "FigureWithID" "Int" 182 2 298 4 298 489 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 180 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 74 22 "Aushilfe" "Helvetica" 0 12 0 NULL NULL  REF 55 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 162 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 329 266 "Produkt\nzurücksenden" "Helvetica" 0 12 0 REF 55 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 60 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 159 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 337 421 "Rechnung\nbezahlen" "Helvetica" 0 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 175 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 390 369 "[else]" "Helvetica" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator -10 43 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 176 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 374 397 "[Produkt ok]" "Helvetica" 0 12 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator 39 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 1 "FigureWithID" "Int" 183 2 166 21 166 489 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 179 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 190 22 "Sachbearbeiter" "Helvetica" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 178 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 349 22 "Kunde" "Helvetica" 0 12 0 NULL NULL  REF 68 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 185 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 199 74 "Bestellung\naufnehmen" "Helvetica" 0 12 0 REF 68 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 187 2 230 54 230 70 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector REF 68   NULL  11 173 491 541 
