11 
    de.renew.gui.CPNDrawing 62 
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3418 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 13 215 116 33  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3419 4 
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3420 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 255 138 221 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3423 2 56 231 139 231 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3421 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 32 224 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 3   REF 7 REF 1  REF 3 REF 7 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3422 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 154 222 ">" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 4 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3424 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 30 224 ">" "SansSerif" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3425 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 22 251 ":start(p)" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -1 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3426 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 417 37 163 220 5  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3427 15 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3436 "Visibility" "Boolean" "TRUE" 2 448 121 479 164 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3430 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 431 105 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3433 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 474 161 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3437 "Visibility" "Boolean" "TRUE" 2 490 179 522 224 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 25  
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3432 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 516 224 24 16 NULL    
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3428 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 474 221 20 20 NULL  
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3429 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 431 224 24 16 NULL  REF 18 REF 23 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3440 "Visibility" "Boolean" "TRUE" 2 455 231 475 231 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 32  
                CH.ifa.draw.figures.ChopEllipseConnector REF 31   
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3431 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 432 167 20 20 NULL  REF 30 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3443 "Visibility" "Boolean" "TRUE" 2 494 231 516 231 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 31  
                CH.ifa.draw.standard.ChopBoxConnector REF 30   REF 25 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3445 2 540 231 572 231 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 30  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3434 571 221 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3446 "Visibility" "Boolean" "TRUE" 2 442 224 442 187 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 32  
                CH.ifa.draw.figures.ChopEllipseConnector REF 37   REF 46 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3447 "Visibility" "Boolean" "TRUE" 2 442 168 442 121 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 37  
                CH.ifa.draw.standard.ChopBoxConnector REF 23    REF 31 REF 32 REF 23 REF 37 REF 30 REF 25 REF 46 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3435 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 587 222 ">" "SansSerif" 1 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 20 REF 26 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3438 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 428 83 ":out(p2)" "SansSerif" 0 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 6 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3439 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 467 190 "OUT" "SansSerif" 1 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator -5 -33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 33 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3441 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 438 131 "p2" "SansSerif" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 3 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3442 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 435 197 "p2" "SansSerif" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 38 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3444 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 429 223 ">" "SansSerif" 1 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator -11 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 42 REF 47 REF 51 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 3448 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 418 263 "action p2=p.reply(\"inform\",\nmail)" "SansSerif" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 46 47 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3449 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 197 215 116 33  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3450 4 
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3451 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 255 322 221 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3454 2 240 231 323 231 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3452 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 216 224 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 78   REF 82 REF 76  REF 78 REF 82 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3453 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 338 222 ">" "SansSerif" 1 12 0 REF 78 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 79 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3455 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 214 224 ">" "SansSerif" 1 12 0 REF 82 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3456 2 44 224 44 178 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 3457 "FillColor" "Color" 255 175 175 255 34 158 20 20 NULL    REF 94 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3458 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 41 193 "p" "SansSerif" 0 12 0 REF 90 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3459 2 158 231 216 231 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector REF 82   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3460 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 198 252 ":srvc(\"getmail\",mail,null,null)" "SansSerif" 0 12 0 REF 82 
            CH.ifa.draw.standard.OffsetLocator 47 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3461 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 194 273 "[service call]" "SansSerif" 0 18 0 REF 77 
            CH.ifa.draw.standard.OffsetLocator -26 54 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3462 2 228 224 228 176 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 82  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 3463 "FillColor" "Color" 255 255 0 255 218 156 20 20 NULL    REF 112 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3464 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 216 192 "mail" "SansSerif" 0 12 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3465 2 342 231 431 231 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 78  
            CH.ifa.draw.standard.ChopBoxConnector REF 32   
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3466 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 0 255 336 165 20 20 NULL REF 112  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3467 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 356 131 20 20 NULL REF 94  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3468 2 372 149 436 224 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 121  
            CH.ifa.draw.standard.ChopBoxConnector REF 32   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3469 2 355 180 431 224 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 120  
            CH.ifa.draw.standard.ChopBoxConnector REF 32   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3470 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 401 178 "p" "SansSerif" 0 12 0 REF 122 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3471 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 356 195 "mail" "SansSerif" 0 12 0 REF 126 
            CH.ifa.draw.standard.OffsetLocator -25 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3472 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 0 255 0 255 640 223 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3473 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 637 202 ":stop()" "SansSerif" 0 12 0 REF 136 
            CH.ifa.draw.standard.OffsetLocator 2 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3474 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 637 243 "STOP" "SansSerif" 1 12 0 REF 136 
            CH.ifa.draw.standard.OffsetLocator 1 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3475 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 636 222 ">" "SansSerif" 1 12 0 REF 136 
            CH.ifa.draw.standard.OffsetLocator -13 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3476 2 591 231 640 231 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 46  
            CH.ifa.draw.standard.ChopBoxConnector REF 136   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3477 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 416 6 "[to robot]" "SansSerif" 0 18 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator -47 -129 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 3478 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 722 17 "import de.renew.agent.repr.acl.*;\nimport de.renew.extras.imagenets.*;\nAclMessage p,p2;\nObject mail;" "SansSerif" 0 12 0 NULL NULL 1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3479 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 409 296 "[sender: ams\nsends: assignment\nto get mail from postbox]" "SansSerif" 0 18 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 8 185 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    NULL  775 180 730 450 