
    CH.ifa.draw.cpn.CPNDrawing 52 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 384 265 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 232 257 20 20  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 235 279 "KB" "Helvetica" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 2 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 462 98 "kb:addBelief([location OBJECT:[bin] LOCATION:[a]])" "Monospaced" 0 10 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 216 -169 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 462 81 "kb:addBelief([location OBJECT:[robot] LOCATION:[a]])" "Monospaced" 0 10 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 222 -186 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 462 118 "kb:addBelief([location OBJECT:[waste] LOCATION:[a]])" "Monospaced" 0 10 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 222 -149 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 130 184 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 76 72 ":new()" "Monospaced" 0 10 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -45 -114 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 287 73 "kb:new KB6" "Monospaced" 0 10 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 175 -113 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 286 92 "kb:setOwner(ed)" "Monospaced" 0 10 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 189 -94 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 152 200 235 262 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 15  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.ArcConnection 2 252 267 384 272 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 176 229 "kb" "Monospaced" 0 10 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator -11 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 304 272 "kb" "Monospaced" 0 10 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator -8 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 223 462 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 336 378 240 466 NULL NULL 0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.cpn.TransitionFigure "no_attributes" 333 362 24 16   
            CH.ifa.draw.figures.ChopEllipseConnector REF 38   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 257 453 "list" "Helvetica" 0 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator -24 38 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 173 465 "Actions" "Helvetica" 1 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator -38 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.ArcConnection 2 144 200 231 463 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 15  
            CH.ifa.draw.figures.ChopEllipseConnector REF 38   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 72 96 "f=new java.awt.Frame(\"Actions:\")" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 19 -89 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 150 309 "list" "Helvetica" 0 12 0 REF 49 
            CH.ifa.draw.standard.OffsetLocator -30 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 71 154 "action f.show()" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -32 -31 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 75 126 "action f.add(list)" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -24 -59 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 72 110 "list = new java.awt.List(10)" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 1 -75 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 72 139 "action f.setSize(300,200)" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -3 -46 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 230 331 20 20  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 221 211 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 154 195 222 219 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 15  
            CH.ifa.draw.figures.ChopEllipseConnector REF 72   
        CH.ifa.draw.cpn.ArcConnection 2 241 224 384 269 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 72  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        CH.ifa.draw.cpn.ArcConnection 2 147 200 236 334 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 15  
            CH.ifa.draw.figures.ChopEllipseConnector REF 71   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 82 499 "ed:addPlan(\n[plan\n TRIGGER:[eventIntention\n          EVENT:[newBelief\n                 BELIEF:[location\n                         OBJECT:#4[waste]\n                         LOCATION:#1]]\n          INTENT:#3]\n CONTEXT:<[location\n           OBJECT:#5[robot]\n           LOCATION:#6]\n          [location\n           OBJECT:[bin]\n           LOCATION:#2]>\n INTENT:<[newGoal\n          BELIEF:[location\n                  OBJECT:#5\n                  LOCATION:#1]]\n         [pick \n          OBJECT:#4]\n         [newGoal\n          BELIEF:[location\n                  OBJECT:#5\n                  LOCATION:#2]]\n         [drop\n          OBJECT:#4]\n         | #3>])" "Monospaced" 0 10 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -191 388 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 391 492 "ed:addPlan(\n[plan\n TRIGGER:[eventIntention\n          EVENT:[newGoal\n                 BELIEF:#1]\n          INTENT:#3]\n CONTEXT: #1\n INTENT: #3])" "Monospaced" 0 10 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 76 267 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 199 355 "EventDispatcher" "Helvetica" 1 12 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator 7 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 184 260 "ed" "Helvetica" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 249 338 384 278 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 71  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 293 301 "ed" "Helvetica" 0 12 0 REF 97 
            CH.ifa.draw.standard.OffsetLocator -16 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "attributes" "attributes" 1 "ArrowMode" "Int" 0 235 395 20 20  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 217 416 "Performer" "Helvetica" 1 12 0 REF 103 
            CH.ifa.draw.standard.OffsetLocator 1 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.ArcConnection 2 145 200 242 397 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 15  
            CH.ifa.draw.figures.ChopEllipseConnector REF 103   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 182 322 "perf" "Helvetica" 0 12 0 REF 107 
            CH.ifa.draw.standard.OffsetLocator -1 31 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 282 107 "ed:new EventDispatcher" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 206 -78 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 281 127 "ed:setKB(kb)" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 174 -58 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 278 144 "perf:new Performer" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 188 -41 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 275 166 "perf:setKB(kb)" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 171 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 41 
        CH.ifa.draw.cpn.ArcConnection 2 250 344 333 366 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 71  
            CH.ifa.draw.standard.ChopBoxConnector REF 41   
        CH.ifa.draw.cpn.ArcConnection 2 254 403 333 374 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 103  
            CH.ifa.draw.standard.ChopBoxConnector REF 41   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 303 343 "ed" "Helvetica" 0 12 0 REF 126 
            CH.ifa.draw.standard.OffsetLocator 19 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 290 395 "perf" "Helvetica" 0 12 0 REF 129 
            CH.ifa.draw.standard.OffsetLocator 7 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 361 355 "ed:perform(Action)" "Helvetica" 0 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator 66 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 361 370 "perf:perform(Action)" "Helvetica" 0 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator 70 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 334 387 "action list.add(Action.toString())" "Helvetica" 0 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator 74 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
