11 
    de.renew.gui.CPNDrawing 29 
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 170 140 "TreeElement\n\n+ filename: String" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 6 "FillColor" "Color" 255 255 255 255 2 109 290 207 174 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 50 290 "Directory\n\n+ opened: bool" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 1  0  REF 5 
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8 3 95 290 95 157 165 157 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 9 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 150 140 "*" "SansSerif" 0 12 0 NULL NULL  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 11 "FillColor" "Color" 255 255 255 255 2 295 290 230 174 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 10 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 230 290 "File\n\n+ type: NavigatorFileFilter" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 1  0  REF 15 
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 380 100 "CH.ifa.draw.io.SimpleFileFilter\n\n" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 15 "FillColor" "Color" 255 255 255 255 2 237 140 347 26 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 14 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 320 10 "Observable" "SansSerif" 0 12 0 NULL NULL   0
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 16 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 110 450 "TreeController" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 17 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 320 450 "AutosaveController" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 18 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 250 380 "Observer" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 19 "FillColor" "Color" 255 255 255 255 2 169 450 263 396 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 23  
            CH.ifa.draw.standard.ChopBoxConnector REF 25  0  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 20 "FillColor" "Color" 255 255 255 255 2 368 450 289 396 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 24  
            CH.ifa.draw.standard.ChopBoxConnector REF 25  0  
        de.renew.gui.fs.UMLNoteFigure "attributes" "attributes" 3 "FigureWithID" "Int" 21 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 30 540 "Observes changes from the NavigatorTree\nand constructs the Swing gui." "SansSerif" 0 12 0 NULL NULL
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "LineStyle" "String" "10" "FigureWithID" "Int" 22 2 155 466 178 535 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 23  
            CH.ifa.draw.contrib.ChopPolygonConnector REF 34   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "LineStyle" "String" "10" "FigureWithID" "Int" 24 2 379 466 380 605 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 24  
            CH.ifa.draw.contrib.ChopPolygonConnector 
                de.renew.gui.fs.UMLNoteFigure "attributes" "attributes" 3 "FigureWithID" "Int" 23 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 240 610 "Loads and saves the navigator model." "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 27 2 156 94 204 140 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 25 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 40 60 "NavigatorModel\n\n+ activeFilters: NavigatorFileFilter[]" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 28 "FillColor" "Color" 255 255 255 255 2 201 60 325 26 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 45  
            CH.ifa.draw.standard.ChopBoxConnector REF 22  0  REF 22 
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 30 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 410 160 "NavigatorFileFilter\n\n+ icon: Icon\n\n+ save(AutosaveInfo)\n+ load(AutosaveInfo)" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 31 "FillColor" "Color" 255 255 255 255 2 471 160 471 122 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 51  
            CH.ifa.draw.standard.ChopBoxConnector REF 17  0  REF 45 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 29 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 210 120 "*" "SansSerif" 0 20 0 NULL NULL  
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 32 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 540 450 "FilesystemController" "SansSerif" 0 12 0 NULL NULL  REF 41
        de.renew.gui.fs.UMLNoteFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 33 "FillColor" "Color" 255 255 255 255 500 560 "Loads the navigator model from the filesystem." "SansSerif" 0 12 0 NULL NULL
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 34 "LineStyle" "String" "10" 2 607 466 662 555 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 57  
            CH.ifa.draw.contrib.ChopPolygonConnector REF 58   
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 35 "FillColor" "Color" 255 255 255 255 2 567 450 311 395 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 57  
            CH.ifa.draw.standard.ChopBoxConnector REF 25  0  NULL  465 255 1148 606 