11 
    de.renew.gui.CPNDrawing 55 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1007 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 408 312 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1008 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1254 479 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1009 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 407 295 "NIR" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1012 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1252 459 "End" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 1 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1014 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 143 481 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1015 2 167 481 411 327 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 9  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1017 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 439 638 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1018 2 459 648 723 648 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 14  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1032 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 723 641 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1019 2 167 495 441 644 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 9  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1020 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 436 621 "Red" "SansSerif" 1 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 0 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1022 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 587 641 "B" "SansSerif" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1024 2 167 489 258 489 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 9  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1025 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 257 479 20 20 NULL    REF 34 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1026 2 277 489 391 489 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 34  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1027 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 391 481 24 16 NULL    REF 39 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1028 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 286 440 "action calc = new r__mapcalculator();\n\n\n" "SansSerif" 0 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1029 2 415 489 492 489 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 39  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1030 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 491 479 20 20 NULL    REF 47 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1031 2 509 495 723 641 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 47  
            CH.ifa.draw.standard.ChopBoxConnector REF 19   REF 19 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1033 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 604 561 "calc" "SansSerif" 0 12 0 REF 48 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1034 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 441 482 "calc" "SansSerif" 0 12 0 REF 43 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1037 2 428 322 683 322 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1038 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 683 314 24 16 NULL    REF 61 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1040 2 509 483 685 330 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 47  
            CH.ifa.draw.standard.ChopBoxConnector REF 61   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1041 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 585 399 "calc" "SansSerif" 0 12 0 REF 62 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1042 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 551 315 "A" "SansSerif" 0 12 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1043 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 586 300 "action calc.$$amapPARAMETER=A;\n\n" "SansSerif" 0 12 0 REF 61 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1044 2 707 322 889 322 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 61  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1045 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 888 312 20 20 NULL    REF 78 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1047 2 907 327 1158 481 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 78  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1057 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1158 481 24 16 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1048 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 786 315 "calc" "SansSerif" 0 12 0 REF 74 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1049 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1020 397 "calc" "SansSerif" 0 12 0 REF 79 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1054 2 747 648 899 648 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 19  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1055 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 898 638 20 20 NULL    REF 94 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1056 2 917 644 1158 496 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 94  
            CH.ifa.draw.standard.ChopBoxConnector REF 83   REF 83 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1058 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 811 641 "calc" "SansSerif" 0 12 0 REF 90 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1062 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1025 563 "calc" "SansSerif" 0 12 0 REF 95 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1068 2 1182 489 1255 489 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 83  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1035 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 634 665 "action calc.$$bmapPARAMETER=B;\n\n" "SansSerif" 0 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator 8 38 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 1051 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 10 181 "import org.osgeo.grass.r.r__mapcalculator;" "SansSerif" 0 12 0 NULL NULL 1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1072 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 80 554 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1074 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 88 395 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1076 2 97 557 148 497 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 113  
            CH.ifa.draw.standard.ChopBoxConnector REF 9   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1077 2 104 413 149 481 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 114  
            CH.ifa.draw.standard.ChopBoxConnector REF 9   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1078 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 122 440 "A" "SansSerif" 0 12 0 REF 119 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1079 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 118 520 "B" "SansSerif" 0 12 0 REF 115 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1080 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 285 397 "A" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1081 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 300 562 "B" "SansSerif" 0 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1082 2 511 489 1158 489 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 47  
            CH.ifa.draw.standard.ChopBoxConnector REF 83   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1083 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 822 482 "calc" "SansSerif" 0 12 0 REF 135 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1067 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 681 431 "action calc.$$formulaPARAMETER=\"1.0*'(A-B)'/'(A+B)'\";\naction calc.$$outfilePARAMETER=\"nc_spm_08/PERMANENT/cell/ndvi\";\naction calc.process();" "SansSerif" 0 12 0 REF 83 
            CH.ifa.draw.standard.OffsetLocator -276 -36 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1023 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 9 584 "\"nc_spm_08/PERMANENT/cell/lsat7_2002_30\"" "SansSerif" 0 12 0 REF 113 
            CH.ifa.draw.standard.OffsetLocator 58 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1021 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 10 368 "\"nc_spm_08/PERMANENT/cell/lsat7_2002_40\"" "SansSerif" 0 12 0 REF 114 
            CH.ifa.draw.standard.OffsetLocator 51 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  63 24 1303 744 