
    CH.ifa.draw.cpn.CPNDrawing 4 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 96 90 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 124 81 "complete" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 42 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 124 94 ":process(t)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 44 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 125 109 "t:join1()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 37 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
