7 
    de.renew.gui.CPNDrawing 27 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 4 "FigureWithID" "Int" 94 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 4 341 224 341 204 386 204 386 184 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 119 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 335 224 "e1" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 5 "FigureWithID" "Int" 118 "TraceMode" "Boolean" "FALSE" "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 363 60 "Proc\n\nm: M\nb1: Proc\nb2: Proc\nb3: Proc\nb4: Proc\nb5: Proc\nb6: Proc" "Dialog" 0 12 0 NULL NULL   1
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 4 "FigureWithID" "Int" 95 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 4 368 224 368 204 386 204 386 184 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 97 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 362 224 "e2" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 4 "FigureWithID" "Int" 96 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 4 395 224 395 204 386 204 386 184 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 98 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 389 224 "e3" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  REF 15 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 4 "FigureWithID" "Int" 99 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 4 422 224 422 204 386 204 386 184 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 100 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 416 224 "e4" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  REF 20 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 4 "FigureWithID" "Int" 101 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 2 277 132 277 109 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 115 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 250 132 "PEff\n\nproc: Proc\npostc: M\nb1: Proc\nb2: Proc\nb3: Proc\nb4: Proc\nb5: Proc\nb6: Proc" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 107 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 258 60 "Eff\n\npre: M\npost: M" "Helvetica" 0 12 0 NULL NULL   0
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 4 "FigureWithID" "Int" 102 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 4 159 126 159 101 137 101 137 76 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 111 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 152 126 "BT" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 120 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 120 60 "Token" "Helvetica" 0 12 0 NULL NULL   1
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 4 "FigureWithID" "Int" 103 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 4 117 126 117 101 137 101 137 76 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 110 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 114 126 "E" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 33  1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 4 "FigureWithID" "Int" 104 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 4 59 60 59 41 167 41 167 22 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 121 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 35 60 "M\n\nb1: Token\nb2: Token\nb3: Token\nb4: Token\nb5: Token\nb6: Token" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 113 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 164 6 "T" "Helvetica" 0 12 0 NULL NULL   1
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 4 "FigureWithID" "Int" 105 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 4 137 60 137 41 167 41 167 22 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 33  
            CH.ifa.draw.standard.ChopBoxConnector REF 44  1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 4 "FigureWithID" "Int" 106 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 4 206 60 206 41 167 41 167 22 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 114 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 189 60 "Tr\n\nrule: T\neff: Eff" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 44  1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 4 "FigureWithID" "Int" 108 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 4 278 60 278 41 167 41 167 22 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 27  
            CH.ifa.draw.standard.ChopBoxConnector REF 44  1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 4 "FigureWithID" "Int" 109 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 4 389 60 390 41 167 41 167 22 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 44  1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 4 "FigureWithID" "Int" 116 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 4 449 224 449 204 386 204 386 184 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 117 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 443 224 "e5" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  REF 65 REF 4 REF 10 REF 44 REF 42 REF 37 REF 31 REF 6 REF 25 REF 27 REF 33 REF 52 NULL  428 122 593 328 
