5 
    de.renew.gui.CPNDrawing 33 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3 "FontName" "String" "Dialog" "FillColor" "Color" 255 255 255 19 72 75 36 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4 "FontName" "String" "Dialog" 2 93 90 116 90 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5 "FontName" "String" "Dialog" "FillColor" "Color" 255 255 255 116 78 63 24 NULL    REF 6 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 6 "FontName" "String" "Dialog" 2 153 78 165 55 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7 "FontName" "String" "Dialog" "FillColor" "Color" 255 255 255 158 36 20 20 NULL    REF 11 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 8 "FontName" "String" "Dialog" 2 153 102 164 122 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9 "FontName" "String" "Dialog" "FillColor" "Color" 255 255 255 158 120 20 20 NULL    REF 16 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 10 "FontName" "String" "Dialog" 2 178 130 193 130 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 11 "FontName" "String" "Dialog" "FillColor" "Color" 255 255 255 193 108 119 44 NULL    REF 21 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 12 "FontName" "String" "Dialog" 2 178 46 211 46 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13 "FontName" "String" "Dialog" "FillColor" "Color" 255 255 255 211 15 82 63 NULL    REF 26 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 14 "FontName" "String" "Dialog" 2 293 46 331 46 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 26  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 15 "FontName" "String" "Dialog" "FillColor" "Color" 255 255 255 330 36 20 20 NULL    REF 31 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 16 "FontName" "String" "Dialog" 2 312 130 331 130 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 21  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 17 "FontName" "String" "Dialog" "FillColor" "Color" 255 255 255 330 120 20 20 NULL    REF 36 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 18 "FontName" "String" "Dialog" 2 347 124 360 112 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 36  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 47 "FontName" "String" "Dialog" "FillColor" "Color" 255 255 255 344 68 81 44 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 20 "FontName" "String" "Dialog" 2 347 53 362 68 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 31  
            CH.ifa.draw.standard.ChopBoxConnector REF 41   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 21 "FontName" "String" "Dialog" 2 425 90 474 90 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 41  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 22 "FontName" "String" "Dialog" "FillColor" "Color" 255 255 255 473 80 20 20 NULL    REF 50 
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 24 "FontName" "String" "Dialog" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 "Visibility" "Boolean" "FALSE" 227 152 20 20 NULL  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 37 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 28 82 "[Account]" "Helvetica" 0 12 0 REF 1
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 42 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 125 143 "[Account]" "Helvetica" 0 12 0 REF 16
            CH.ifa.draw.standard.OffsetLocator -15 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 45 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 474 101 "[ID]" "Helvetica" 0 12 0 REF 50
            CH.ifa.draw.standard.OffsetLocator 1 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 44 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 329 142 "[Account]" "Helvetica" 0 12 0 REF 36
            CH.ifa.draw.standard.OffsetLocator 17 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 41 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 319 18 "[UniAccount]" "Helvetica" 0 12 0 REF 31
            CH.ifa.draw.standard.OffsetLocator 17 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 40 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 128 18 "[Account]" "Helvetica" 0 12 0 REF 11
            CH.ifa.draw.standard.OffsetLocator -12 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 39 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 215 18 "[UniAccount\n name: #1\n login: #1]" "Helvetica" 0 12 0 REF 26
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 43 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 197 111 "[Account\n name: [Wienberg]]" "Helvetica" 0 12 0 REF 21
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 26 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 255 255 431 82 "login" "Dialog" 0 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator -4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 38 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 30 107 "[Account]" "Helvetica" 0 12 0 REF 1
            CH.ifa.draw.standard.OffsetLocator 1 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 46 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 120 82 "[Account]" "Helvetica" 0 12 0 REF 6
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 41 
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 48 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 347 71 "[UniAccount\n login: []]" "Helvetica" 0 12 0 REF 41
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    NULL  91 129 531 221 
