5 
    de.renew.gui.CPNDrawing 8 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 1 "FontName" "String" "Dialog" 2 217 81 217 50 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 2 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 186 81 "UniAccount\nlogin: ID" "Dialog" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 26 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 193 20 "Account\nname: ID" "Dialog" 0 12 0 NULL NULL   0  REF 6 REF 4
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 1 "FigureWithID" "Int" 45 4 55 66 55 51 89 51 89 36 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 43 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 31 66 "Kummer" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 42 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 83 21 "ID" "Helvetica" 0 12 0 NULL NULL   1
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 44 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 104 66 "Wienberg" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 1 "FigureWithID" "Int" 46 4 130 66 130 51 89 51 89 36 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 13  
            CH.ifa.draw.standard.ChopBoxConnector REF 12  1  REF 10 REF 12 NULL  -1 97 311 184 
