11 
    de.renew.gui.CPNDrawing 17 
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FrameColor" "Color" 224 224 224 255 "FigureWithID" "Int" 3503 "FillColor" "Color" 240 240 240 255 6 -130 135 264 6  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3525 "FillColor" "Color" 255 199 158 255 12 
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3504 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" -7 -5 24 16 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3505 "Visibility" "Boolean" "TRUE" 2 17 3 60 3 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 3  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3506 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 59 -7 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3509 "Visibility" "Boolean" "TRUE" 2 75 11 104 55 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 8  
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3510 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 98 55 24 16 NULL    REF 13 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3515 2 116 -65 150 -106 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3508 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 98 -65 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3516 145 -124 20 20 NULL    REF 8 
            de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3514 134 103 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3513 2 115 71 139 106 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 13  
                CH.ifa.draw.figures.ChopEllipseConnector REF 20   REF 1 REF 17 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3507 "Visibility" "Boolean" "TRUE" 2 75 -4 104 -49 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 8  
                CH.ifa.draw.standard.ChopBoxConnector REF 17   REF 19  REF 3 REF 13 REF 8 REF 20 REF 17 REF 19 REF 4 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 3522 "TextColor" "Color" 255 0 0 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 -10 -5 ">" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -10 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 9 REF 14 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 3519 "TextColor" "Color" 255 0 0 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 159 -122 ">" "SansSerif" 1 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 3521 "TextColor" "Color" 255 0 0 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 "FrameColor" "Color" 255 199 158 255 148 105 ">" "SansSerif" 1 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3520 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 65 -32 "IF" "SansSerif" 1 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 2 -28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 21 REF 25 NULL  