11 
    de.renew.gui.CPNDrawing 36 
        de.renew.gui.TransitionFigure "attributes" "attributes" 8 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 690 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Monospaced" "FontSize" "Int" 12 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 255 53 242 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 691 "FontName" "String" "Monospaced" "FontSize" "Int" 12 "FontStyle" "Int" 0 2 77 250 366 250 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FigureWithID" "Int" 694 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Monospaced" "FontSize" "Int" 12 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 255 365 240 20 20 NULL    
        de.renew.gui.TransitionFigure "attributes" "attributes" 7 "FigureWithID" "Int" 692 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Monospaced" "FontSize" "Int" 12 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 255 248 197 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 693 "FontName" "String" "Monospaced" "FontSize" "Int" 12 "FontStyle" "Int" 0 2 367 247 272 209 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 7   REF 6 
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 695 "FontName" "String" "Monospaced" "FontSize" "Int" 12 "FontStyle" "Int" 0 2 248 197 138 121 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FigureWithID" "Int" 696 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Monospaced" "FontSize" "Int" 12 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 255 120 105 20 20 NULL    REF 16 
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 698 "FontName" "String" "Monospaced" "FontSize" "Int" 12 "FontStyle" "Int" 0 2 140 114 363 62 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 7 "FigureWithID" "Int" 699 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Monospaced" "FontSize" "Int" 12 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 255 363 52 24 16 NULL    REF 21 
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 701 "FontName" "String" "Monospaced" "FontSize" "Int" 12 "FontStyle" "Int" 0 2 75 60 363 60 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 6 "FigureWithID" "Int" 708 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Monospaced" "FontSize" "Int" 12 "FillColor" "Color" 112 219 147 255 55 50 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 21   
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 702 "FontName" "String" "Monospaced" "FontSize" "Int" 12 "FontStyle" "Int" 0 2 375 68 375 241 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 21  
            CH.ifa.draw.figures.ChopEllipseConnector REF 6   
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 705 "FontName" "String" "Monospaced" "FontSize" "Int" 12 "FontStyle" "Int" 0 2 248 205 135 205 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FigureWithID" "Int" 706 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Monospaced" "FontSize" "Int" 12 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 255 115 195 20 20 NULL    REF 35 REF 25 
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 709 "FontName" "String" "Monospaced" "FontSize" "Int" 12 2 65 70 65 242 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 710 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 47 149 "fruit" "Monospaced" 0 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator -1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 712 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 44 33 "\"Lime\"" "Monospaced" 0 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 0 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 713 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 37 8 "\"Orange\"" "Monospaced" 0 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 0 -45 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 714 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 41 18 "\"Lemon\"" "Monospaced" 0 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 0 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 716 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 352 258 "Kitchen" "SansSerif" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 0 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 721 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 310 28 "pick and make" "SansSerif" 1 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator -20 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 722 "FrameColor" "Color" 0 0 0 255 "FontSize" "Int" 12 "FillColor" "Color" 112 219 147 255 55 300 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 723 "FontSize" "Int" 12 2 65 301 65 258 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 58  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 724 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 61 303 "()" "SansSerif" 0 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 720 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 234 213 "separate" "SansSerif" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 0 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 715 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 6 63 "Orchard" "SansSerif" 1 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator -35 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 725 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 97 251 "(let* ((maker #f)\n       (return (lambda (x) x))\n       (marmalade\n        (string-append\n         (call/cc\n          (lambda (c)\n            (set! maker\n                  (lambda (ret fruit)\n                    (set! return ret)\n                    (c fruit)))\n            fruit))\n         \" Marmalade\")))\n  (return (cons marmalade maker)))" "Monospaced" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 5 98 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 704 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 184 43 "new-fruit" "Monospaced" 0 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator -4 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 719 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 27 220 "pick\nand\nfirst\ntry" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -25 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 689 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 304 116 "(call/cc\n (lambda (c)\n   (maker c\n          new-fruit)))" "Monospaced" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 6 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 718 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 106 218 "Fridge" "SansSerif" 1 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator 0 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 717 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 89 123 "Garage" "SansSerif" 1 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator -20 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 697 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 154 143 "(cdr pair)" "Monospaced" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator -4 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 700 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 222 84 "maker" "Monospaced" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator -12 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 703 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 311 221 "pair" "Monospaced" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 6 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 707 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 147 188 "(car pair)" "Monospaced" 0 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator -9 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  590 141 483 491 