
    CH.ifa.draw.cpn.CPNDrawing 33 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 151 145 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 214 143 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 273 145 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 335 143 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 395 145 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 97 143 20 20  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 454 143 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 117 153 151 153 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        CH.ifa.draw.cpn.ArcConnection 2 175 153 215 153 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.ArcConnection 2 234 153 273 153 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        CH.ifa.draw.cpn.ArcConnection 2 297 153 336 153 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        CH.ifa.draw.cpn.ArcConnection 2 355 153 395 153 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector REF 5   
        CH.ifa.draw.cpn.ArcConnection 2 419 153 455 153 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 113 131 "[]" "Helvetica" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 9 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 208 185 "acc" "Helvetica" 0 12 0 
            CH.ifa.draw.cpn.ArcConnection 2 175 159 277 211 NULL 
                CH.ifa.draw.figures.ArrowTip  0 0 0 
                CH.ifa.draw.standard.ChopBoxConnector REF 1  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    CH.ifa.draw.cpn.PlaceFigure "no_attributes" 275 205 20 20    
            CH.ifa.draw.standard.OffsetLocator -9 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 40 REF 36 
        CH.ifa.draw.cpn.ArcConnection 2 285 161 285 206 NULL NULL 0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 40   
        CH.ifa.draw.cpn.ArcConnection 2 395 159 294 211 NULL NULL 0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.figures.ChopEllipseConnector REF 40   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 289 176 "acc" "Helvetica" 0 12 0 REF 43 
            CH.ifa.draw.standard.OffsetLocator 13 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 338 187 "acc" "Helvetica" 0 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 3 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 104 89 "action acc=new \n  samples.call.Account()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 5 -49 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 239 90 "action\n  acc.deposit(500)" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 2 -48 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 362 90 "action amount=\n  acc.currentAmount()" "Helvetica" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 13 -48 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 262 225 "account" "Helvetica" 1 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 0 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 98 164 "init" "Helvetica" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator -1 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 219 162 "created" "Helvetica" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 17 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 312 162 "deposited" "Helvetica" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -5 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 472 159 "amount" "Helvetica" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 29 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 417 159 "amount" "Helvetica" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 0 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 144 123 "create" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -1 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 264 123 "deposit" "Helvetica" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 0 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 391 123 "query" "Helvetica" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 0 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2   
