11 
    de.renew.gui.CPNDrawing 5 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6973 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 255 0 255 53 -2 97 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 6974 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 78 4 "delegate" "Arial" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 6975 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "TextType" "Int" 0 "FillColor" "Color" 255 255 255 255 -1 91 204 66 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 6978 2 101 25 101 92 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 6980 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 57 116 "DWF[roleName]" "SansSerif" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  530 276 830 600 