11 
    de.renew.gui.CPNDrawing 22 
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 23 "FillColor" "Color" 255 255 255 255 10 10 232 208 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 21 "FillColor" "Color" 255 255 255 255 533 10 327 208 8 8  
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 170 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 281 71 "«remote interface»\nBindingAccessor\n\nexecute(RemoteBindingSynchronizer)\ngetDescription(): String" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 171 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 631 94 "BindingAccessorImpl" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 2 2 211 102 276 102 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 181 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 45 94 "RemoteBindingExecutable" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 4 "FillColor" "Color" 255 255 255 255 2 626 102 498 102 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector REF 3  0  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 6 2 696 110 696 144 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 168 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 548 144 "DistributeBinding\n\nexecute(StepIdentifier, boolean): boolean\nexecute(StepIdentifier, RemoteBindingSynchronizer)\ngetDescription(): String" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 675 115 "binding" "SansSerif" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 0 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 18 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 10 "FillColor" "Color" 255 255 255 255 2 125 94 125 67 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 9 "FrameColor" "Color" 0 0 255 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 77 36 "«interface»\nEarlyExecutable" "SansSerif" 0 12 0 NULL NULL   0
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 16 "FillColor" "Color" 255 255 255 255 2 232 176 274 176 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 15 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 24 144 "RemoteBindingSynchronizerImpl\n\nwaitUntilLocked()\ngetSuccess(): boolean\nreportLocalSuccess(boolean)" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 11 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 279 145 "«remote interface»\nRemoteBindingSynchronizer\n\nreportLocked()\nremoteSynchronize(boolean): boolean" "SansSerif" 0 12 0 NULL NULL   0
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 17 2 125 110 125 144 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 30   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 18 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 113 115 "sync" "SansSerif" 0 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator 0 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 19 2 543 176 501 176 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 18  
            CH.ifa.draw.standard.ChopBoxConnector REF 32   REF 32 REF 8 REF 26 REF 30 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 22 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 666 14 "child firing" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 0 -93 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 24 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 98 14 "root firing" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 -93 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 182 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 218 95 "binding" "SansSerif" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 184 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 514 169 "sync" "SansSerif" 0 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  220 498 964 308 