11 
    de.renew.gui.CPNDrawing 32 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 4614 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 11 12 "DWF;\nname=providePaperBody;\norganization=paper;\nrefines=paper.dfw_submitPaper.providePaperBody;" "SansSerif" 0 18 0 NULL NULL  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 2 "LineStyle" "String" "10" "FigureWithID" "Int" 4615 2 305 188 305 733 NULL NULL "CH.ifa.draw.figures.ArrowTip"  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4616 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 199 158 255 219 163 " writeRelatedWorkSec " "SansSerif" 0 16 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 2 -288 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4617 132 320 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4618 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 95 341 "ppf:topicGoals" "SansSerif" 1 11 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator -1 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4619 229 323 154 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4620 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 237 324 "researchRelatedWork" "SansSerif" 1 11 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4621 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 317 308 "role=writeRelatedWorkSec;" "SansSerif" 2 9 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 71 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4622 2 152 330 229 330 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 10   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4623 295 390 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4624 2 305 339 305 391 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector REF 21   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4625 131 438 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4626 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 91 459 "ppf:paperSetup" "SansSerif" 1 11 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator -1 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4632 134 549 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4634 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 86 573 "wpb:contribution" "SansSerif" 1 11 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator -4 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 2 "LineStyle" "String" "10" "FigureWithID" "Int" 4635 2 599 188 599 733 NULL NULL "CH.ifa.draw.figures.ArrowTip"  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4636 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 199 158 255 544 163 " writeMainPart " "SansSerif" 0 16 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator 2 -288 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4637 530 441 139 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4638 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 559 442 "addMainPart" "SansSerif" 1 11 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4639 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 617 428 "role=writeMainPart;" "SansSerif" 2 9 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 62 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4641 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 317 391 "relatedWork" "SansSerif" 1 11 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator 51 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4642 2 151 448 530 448 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector REF 38   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4643 457 549 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4645 3 599 457 599 559 477 559 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 38  
            CH.ifa.draw.figures.ChopEllipseConnector REF 52   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4646 228 551 154 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4647 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 241 552 "addRelatedWorkSec" "SansSerif" 1 11 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4648 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 316 537 "role=writeRelatedWorkSec;" "SansSerif" 2 9 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator 71 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4649 2 458 559 382 559 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 52  
            CH.ifa.draw.standard.ChopBoxConnector REF 57   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4644 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 432 571 "wc:mainPart" "SansSerif" 1 11 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator 4 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4650 2 228 559 154 559 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 57  
            CH.ifa.draw.figures.ChopEllipseConnector REF 30   
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4652 "FrameColor" "Color" 255 255 255 255 "FillColor" "Color" 255 255 255 255 299 438 12 23  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4651 2 305 410 305 551 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 21  
            CH.ifa.draw.standard.ChopBoxConnector REF 57   NULL  784 25 962 932 