
    CH.ifa.draw.cpn.CPNDrawing 36 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 140 145 24 16  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 140 275 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 89 319 ":nextElement(inst)" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -14 43 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 91 302 "inst=new Object()" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -14 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 226 273 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 164 283 227 283 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector REF 9   
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 142 206 20 20  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 160 193 "2" "Helvetica" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 11 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 87 123 ":hasMoreElements(inst)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -1 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 152 161 152 207 NULL NULL 0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 119 178 "num" "Helvetica" 0 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator -21 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 377 142 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 164 152 378 152 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 27   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 88 105 "inst=new Object()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -17 -41 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 196 154 "[inst,num>0]" "Helvetica" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator -42 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 366 124 "result" "Helvetica" 1 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator -5 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 464 144 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 397 152 464 152 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 27  
            CH.ifa.draw.standard.ChopBoxConnector REF 41   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 407 155 "[inst,res]" "Helvetica" 0 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator -1 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 152 226 152 275 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 14  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 123 240 "num" "Helvetica" 0 12 0 REF 49 
            CH.ifa.draw.standard.OffsetLocator -17 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 107 336 "guard num>0" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -9 60 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 304 275 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 246 283 304 283 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 9  
            CH.ifa.draw.standard.ChopBoxConnector REF 59   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 171 285 "[inst,num]" "Helvetica" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 2 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 249 285 "[inst,num]" "Helvetica" 0 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator 0 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 304 278 161 220 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 59  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 213 225 "num-1" "Helvetica" 0 12 0 REF 70 
            CH.ifa.draw.standard.OffsetLocator 0 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 306 205 20 20  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 294 191 "\"socks\"" "Helvetica" 0 12 0 REF 77 
            CH.ifa.draw.standard.OffsetLocator -3 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 279 175 "\"token game\"" "Helvetica" 0 12 0 REF 77 
            CH.ifa.draw.standard.OffsetLocator -1 -33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 316 225 316 275 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 77  
            CH.ifa.draw.standard.ChopBoxConnector REF 59   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 319 233 "thing" "Helvetica" 0 12 0 REF 84 
            CH.ifa.draw.standard.OffsetLocator 16 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 3 328 282 387 282 387 162 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 59  
            CH.ifa.draw.figures.ChopEllipseConnector REF 27   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 396 223 "[inst,thing]" "Helvetica" 0 12 0 REF 91 
            CH.ifa.draw.standard.OffsetLocator 66 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 440 127 ":result(inst,res)" "Helvetica" 0 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator 4 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   