7 
    de.renew.gui.CPNDrawing 53 
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 23 "FillColor" "Color" 255 255 255 225 177 39 37  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 1 "FigureWithID" "Int" 28 2 225 195 264 195 NULL NULL  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 20 "TextAlignment" "Int" 1 "FillColor" "Color" 255 255 255 199 102 90 47 8 8  
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 22 "LineStyle" "Int" 2 2 243 76 243 102 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.contrib.ChopPolygonConnector 
                CH.ifa.draw.contrib.PolygonFigure "attributes" "attributes" 2 "FigureWithID" "Int" 84 "FillColor" "Color" 255 255 255 6 212 11 274 11 294 43 274 76 212 76 192 43   
            CH.ifa.draw.figures.ShortestDistanceConnector REF 3   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 24 "LineStyle" "Int" 2 2 244 149 244 178 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 25 "LineStyle" "Int" 2 3 226 195 148 195 148 219 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.contrib.ChopPolygonConnector 
                CH.ifa.draw.contrib.PolygonFigure "attributes" "attributes" 2 "FigureWithID" "Int" 85 "FillColor" "Color" 255 255 255 6 118 219 180 219 200 251 180 284 118 284 98 251    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 26 "LineStyle" "Int" 2 3 263 195 325 195 325 219 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.contrib.ChopPolygonConnector 
                CH.ifa.draw.contrib.PolygonFigure "attributes" "attributes" 2 "FigureWithID" "Int" 87 "FillColor" "Color" 255 255 255 6 294 219 356 219 376 251 356 284 294 284 274 251    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 29 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 232 195 "XOR" "Helvetica" 0 12 0 
            CH.ifa.draw.figures.GroupFigure 2 REF 1 REF 2  
            CH.ifa.draw.standard.OffsetLocator 0 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 21 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 216 110 "Bestimme\nKreditart" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 31 "TextAlignment" "Int" 1 "FillColor" "Color" 255 255 255 41 353 90 47 8 8  
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 38 "LineStyle" "Int" 2 2 148 284 148 304 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.contrib.ChopPolygonConnector REF 17  
            CH.ifa.draw.figures.ChopEllipseConnector 
                CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 32 "FillColor" "Color" 255 255 255 128 303 39 37    REF 35 
        CH.ifa.draw.figures.PolyLineFigure "attributes" "attributes" 1 "FigureWithID" "Int" 36 3 141 332 147 324 153 333 NULL NULL  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 1 "FigureWithID" "Int" 33 2 128 321 167 321 NULL NULL  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 39 "TextAlignment" "Int" 1 "FillColor" "Color" 255 255 255 164 353 90 47 10 8  
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 51 "LineStyle" "Int" 2 3 129 321 86 321 86 353 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 35  
            CH.ifa.draw.standard.ChopBoxConnector REF 30   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 52 "LineStyle" "Int" 2 3 166 321 209 321 209 353 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 35  
            CH.ifa.draw.standard.ChopBoxConnector REF 38   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 53 "LineStyle" "Int" 2 2 85 400 85 423 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector REF 30  
            CH.ifa.draw.contrib.ChopPolygonConnector 
                CH.ifa.draw.contrib.PolygonFigure "attributes" "attributes" 2 "FigureWithID" "Int" 89 "FillColor" "Color" 255 255 255 6 54 423 116 423 136 455 116 488 54 488 34 455    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 54 "LineStyle" "Int" 2 2 208 400 208 423 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector REF 38  
            CH.ifa.draw.contrib.ChopPolygonConnector 
                CH.ifa.draw.contrib.PolygonFigure "attributes" "attributes" 2 "FigureWithID" "Int" 91 "FillColor" "Color" 255 255 255 6 177 423 239 423 259 455 239 488 177 488 157 455    
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 56 "TextAlignment" "Int" 1 "FillColor" "Color" 255 255 255 281 311 90 47 8 8  
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63 "FillColor" "Color" 255 255 255 225 534 39 37  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 1 "FigureWithID" "Int" 64 2 225 552 264 552 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 65 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 232 537 "XOR" "Helvetica" 0 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator 0 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 57 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 294 312 "Hole Lohn-\nbestätigung\nein" "Helvetica" 0 12 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 66 "TextAlignment" "Int" 1 "FillColor" "Color" 255 255 255 199 590 90 47 8 8  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 67 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 219 598 "Gewähre\nKredit" "Helvetica" 0 12 0 REF 66 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 73 "FillColor" "Color" 255 255 255 128 499 39 37  
        CH.ifa.draw.figures.PolyLineFigure "attributes" "attributes" 1 "FigureWithID" "Int" 74 3 141 513 147 505 153 514 NULL NULL  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 1 "FigureWithID" "Int" 75 2 128 517 167 517 NULL NULL  
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 76 "LineStyle" "Int" 2 3 85 488 85 517 129 517 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.contrib.ChopPolygonConnector REF 51  
            CH.ifa.draw.figures.ChopEllipseConnector REF 70   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 77 "LineStyle" "Int" 2 3 208 488 208 517 166 517 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.contrib.ChopPolygonConnector REF 56  
            CH.ifa.draw.figures.ChopEllipseConnector REF 70   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 78 "LineStyle" "Int" 2 2 325 284 325 311 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.contrib.ChopPolygonConnector REF 22  
            CH.ifa.draw.figures.ShortestDistanceConnector REF 57   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 79 "LineStyle" "Int" 2 2 325 358 325 381 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector REF 57  
            CH.ifa.draw.contrib.ChopPolygonConnector 
                CH.ifa.draw.contrib.PolygonFigure "attributes" "attributes" 2 "FigureWithID" "Int" 92 "FillColor" "Color" 255 255 255 6 294 381 356 381 376 413 356 446 294 446 274 413    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 80 "LineStyle" "Int" 2 3 325 446 325 552 263 552 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.contrib.ChopPolygonConnector REF 89  
            CH.ifa.draw.figures.ChopEllipseConnector REF 58   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 81 "LineStyle" "Int" 2 3 148 535 148 552 226 552 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 70  
            CH.ifa.draw.figures.ChopEllipseConnector REF 58   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 82 "LineStyle" "Int" 2 2 244 570 244 590 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 58  
            CH.ifa.draw.figures.ShortestDistanceConnector REF 66   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 83 "LineStyle" "Int" 2 2 243 637 243 661 NULL 
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector REF 66  
            CH.ifa.draw.contrib.ChopPolygonConnector 
                CH.ifa.draw.contrib.PolygonFigure "attributes" "attributes" 2 "FigureWithID" "Int" 93 "FillColor" "Color" 255 255 255 6 212 661 274 661 294 693 274 726 212 726 192 693    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 30 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 54 353 "Hole\nGrundbuch-\nauszug ein" "Helvetica" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 40 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 174 361 "Schätze\nLiegenschaft" "Helvetica" 0 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 7 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 9 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 202 28 "Kreditantrag ist\neingetroffen" "Helvetica" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 17 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 14 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 116 229 "Hypothekar-\nkredit ist\nbeantragt" "Helvetica" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 22 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 19 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 295 229 "Privatkredit\nist\nbeantragt" "Helvetica" 0 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 51 REF 56 REF 89 REF 106 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 50 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 53 433 "Grundbuch-\nauszug\neingeholt" "Helvetica" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 45 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 173 440 "Liegenschaft\ngeschätzt" "Helvetica" 0 12 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 62 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 292 391 "Lohn-\nbestätigung\nist eingeholt" "Helvetica" 0 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 72 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 213 678 "Kredit\nist gewährt" "Helvetica" 0 12 0 REF 106 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    NULL  -1 124 459 619 
