
    CH.ifa.draw.cpn.CPNDrawing 30 
        CH.ifa.draw.cpn.PlaceFigure "attributes" "attributes" 1 "TraceMode" "Boolean" "TRUE" 150 309 20 20  
        CH.ifa.draw.cpn.PlaceFigure "attributes" "attributes" 1 "TraceMode" "Boolean" "TRUE" 332 309 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 247 350 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 169 323 247 353 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        CH.ifa.draw.cpn.ArcConnection 2 271 352 334 323 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 148 205 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 160 221 160 310 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 12  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 165 243 "f1" "Helvetica" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 10 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 3 172 215 342 251 342 310 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 12  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 208 228 "f2" "Helvetica" 0 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator -44 -27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 138 128 ":new()" "Helvetica" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator -8 -78 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 202 343 "f" "Helvetica" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -5 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 304 345 "f" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 3 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 139 147 "f1: new FiremanNet" "Helvetica" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 33 -59 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 139 164 "f2: new FiremanNet" "Helvetica" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 33 -42 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 220 369 "f:approachFire()" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 5 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 330 424 24 16  
        CH.ifa.draw.cpn.ArcConnection 3 340 329 325 371 339 424 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 45   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 317 398 "f1" "Helvetica" 0 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator -10 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 259 447 "f1:extinguish()" "Helvetica" 0 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator -44 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 278 461 "f2:refill()" "Helvetica" 0 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator -42 36 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 274 147 "f1: init2()" "Helvetica" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 138 -59 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 276 162 "f2: new()" "Helvetica" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 137 -44 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 242 332 "AtoB" "Helvetica" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -3 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 130 303 "A" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -26 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 350 297 "B" "Helvetica" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 12 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 263 425 "ExchangeB" "Helvetica" 1 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator -46 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.ArcConnection 2 342 329 342 424 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 45   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 346 398 "f2" "Helvetica" 0 12 0 REF 78 
            CH.ifa.draw.standard.OffsetLocator 9 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 120 205 "init" "Helvetica" 1 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator -31 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2   
