11 
    de.renew.gui.CPNDrawing 20 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 264 58 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 2 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 261 38 ":ch(y)" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -1 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 1906 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 99 59 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 1911 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 19 57 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 1912 "MarkingAppearance" "Int" 1 2 39 67 99 67 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 5   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1925 "MarkingAppearance" "Int" 1 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 26 58 "[]" "SansSerif" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 1945 "MarkingAppearance" "Int" 1 2 123 66 200 66 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 1946 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 199 56 20 20 NULL    REF 18 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1986 "MarkingAppearance" "Int" 1 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 90 76 "register" "SansSerif" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 1 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1987 "MarkingAppearance" "Int" 1 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 175 76 "registered" "SansSerif" 1 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator -5 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3 2 219 66 264 66 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 18  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4 2 288 66 331 66 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 330 56 20 20 NULL    REF 32 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 21 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 138 143 "Netz \"consumer\"" "SansSerif" 1 18 0 NULL NULL  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 1988 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 25 123 "import de.renew.cloudnative.spring.resilientdistribute.adapter.ResDistPluginAdapter;" "SansSerif" 0 12 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1993 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 307 58 "y" "SansSerif" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 1985 "MarkingAppearance" "Int" 1 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 13 18 "action ResDistPluginAdapter.registerNetInstance(\"consumer\", ResDistPluginAdapter.wrap(this));\na : new localAdapter;" "SansSerif" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 167 -33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1994 2 123 74 163 101 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1995 160 96 20 20 NULL    REF 45 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1997 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 140 79 "a" "SansSerif" 0 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  