11 
    de.renew.gui.CPNDrawing 42 
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 525 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -33 -112 152 150 114 114  
        de.renew.bpmn.roundtrip.RoundtripNetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 526 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 23 REF 1 
            de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 289 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 224 224 255 255 -46 -111 20 20 NULL 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 288 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 224 224 255 255 -49 -270 20 20 NULL   
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 281 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 73 -83 24 16 NULL  
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 276 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 31 -86 20 20 NULL  
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 267 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -12 -50 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 280 "FillColor" "Color" 254 254 254 255 2 51 -76 73 -76 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 6  
                CH.ifa.draw.standard.ChopBoxConnector REF 5   
            de.renew.gui.DoubleArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 273 2 -2 -7 -2 -30 NULL 
                de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  "de.renew.gui.DoubleArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 265 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -14 -7 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 7   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 275 2 11 -76 32 -76 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 269 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -13 -84 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 6   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 277 2 -1 -84 -1 -118 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 20  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 278 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 -11 -138 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 274 2 10 1 34 1 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 15  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 268 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 33 -9 20 20 NULL    REF 15 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 287 2 -13 -84 -28 -95 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 20  
                CH.ifa.draw.figures.ChopEllipseConnector REF 3   REF 31 
            de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 266 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 73 -7 24 16 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 282 "FillColor" "Color" 254 254 254 255 2 84 -67 84 -46 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 5  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 283 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 74 -47 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 270 "Visibility" "Boolean" "TRUE" 2 -2 -49 -2 -68 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 7  
                CH.ifa.draw.standard.ChopBoxConnector REF 20   
            de.renew.gui.DoubleArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 279 2 84 -27 84 -7 NULL 
                de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  "de.renew.gui.DoubleArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 41  
                CH.ifa.draw.standard.ChopBoxConnector REF 36   
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 272 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 255 126 -9 20 20 NULL  REF 26 REF 41 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 286 2 53 1 73 1 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 31  
                CH.ifa.draw.standard.ChopBoxConnector REF 36   REF 20 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 271 "Visibility" "Boolean" "TRUE" 2 97 1 127 1 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 36  
                CH.ifa.draw.figures.ChopEllipseConnector REF 50   "forall"  REF 3 REF 5 REF 6 REF 7 REF 15 REF 31 REF 36 REF 50 REF 26 REF 41 REF 20 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 297 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 2 -67 "o" "SansSerif" 0 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator 7 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 296 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 75 -66 "o" "SansSerif" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator -6 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 298 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 89 -28 "os" "SansSerif" 0 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 11 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 292 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 15 -16 "os" "SansSerif" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator -1 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 8 REF 12 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 299 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 4 -28 "os" "SansSerif" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 12 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 305 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 24 -42 "ForAll" "SansSerif" 1 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator -1 -36 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 17 REF 22 REF 27 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 294 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 16 -75 "o" "SansSerif" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator -2 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 521 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 199 158 255 -18 -6 ">" "SansSerif" 1 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 523 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 199 158 255 -5 -146 "^" "SansSerif" 1 14 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 0 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 291 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 -19 -108 "o" "SansSerif" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 5 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 32 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 295 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 57 -75 "o" "SansSerif" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator -2 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 37 REF 42 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 522 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 199 158 255 139 -8 ">" "SansSerif" 1 12 0 REF 50 
            CH.ifa.draw.standard.OffsetLocator 8 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 46 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 524 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 199 158 255 82 -90 "v" "SansSerif" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 0 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 300 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 56 -16 "os" "SansSerif" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator -1 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 51 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 290 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -58 -129 "Object" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -2 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 55 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 293 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 -38 17 "action os = v.toArray();" "SansSerif" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 30 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 4 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 306 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -95 -272 "Object" "SansSerif" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -36 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  30 148 955 504 