7 
    de.renew.gui.CPNDrawing 2 
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1 "MarkingAppearance" "Int" 3 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 5 39 311 149 NULL  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 14 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 85 98 "[!de.renew.formalism.fsnet.BeanVector\n elements: <(\"a\") (\"b\") (\"c\")>].instantiate()" "Helvetica" 0 12 0 REF 1
            CH.ifa.draw.standard.OffsetLocator -1 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 8 "" "elements:tl:tl:hd" "elements:hd" "elements:tl:tl" "elements:tl:tl:tl" "elements:tl:hd" "elements" "elements:tl"  NULL  -1 98 529 518 
