
    CH.ifa.draw.cpn.CPNDrawing 67 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 111 144 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 80 144 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -30 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 112 316 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 122 160 122 317 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 128 242 "[besitzer: [lieblingsfarbe: #1]\n auto: [farbe: #1]] " "Helvetica" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 82 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        fs.TypeFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 0 0 0 363 131 "*Peter" "Helvetica" 2 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 0 0 0 380 77 "Person\nlieblingsfarbe: Farbe" "Helvetica" 2 12 0 NULL NULL 0  
        fs.IsaConnection 2 389 131 417 107 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 13  
            CH.ifa.draw.standard.ChopBoxConnector REF 14   
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 161 318 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 132 326 161 326 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 19   
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 314 283 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 232 281 20 20  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 233 350 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 315 353 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 185 319 234 296 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 19  
            CH.ifa.draw.figures.ChopEllipseConnector REF 25   
        CH.ifa.draw.cpn.ArcConnection 2 185 331 235 357 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 19  
            CH.ifa.draw.figures.ChopEllipseConnector REF 26   
        CH.ifa.draw.cpn.ArcConnection 2 253 360 315 360 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector REF 27   
        CH.ifa.draw.cpn.ArcConnection 2 252 291 314 291 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector REF 24   
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 431 281 20 20  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 428 350 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 465 317 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 541 315 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 338 291 432 291 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 24  
            CH.ifa.draw.figures.ChopEllipseConnector REF 44   
        CH.ifa.draw.cpn.ArcConnection 2 339 360 429 360 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 27  
            CH.ifa.draw.figures.ChopEllipseConnector REF 45   
        CH.ifa.draw.cpn.ArcConnection 2 445 354 468 333 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 45  
            CH.ifa.draw.standard.ChopBoxConnector REF 46   
        CH.ifa.draw.cpn.ArcConnection 2 448 298 468 317 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 44  
            CH.ifa.draw.standard.ChopBoxConnector REF 46   
        CH.ifa.draw.cpn.ArcConnection 2 489 325 542 325 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 46  
            CH.ifa.draw.figures.ChopEllipseConnector REF 47   
        fs.TypeFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 0 0 0 455 131 "*Paul" "Helvetica" 2 12 0 NULL NULL 0  
        fs.IsaConnection 2 464 131 447 107 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 68  
            CH.ifa.draw.standard.ChopBoxConnector REF 14   
        fs.TypeFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 0 0 0 249 80 "Farbe" "Helvetica" 2 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 0 0 0 228 117 "*Blau" "Helvetica" 2 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 0 0 0 284 117 "*Rot" "Helvetica" 2 12 0 NULL NULL 0  
        fs.IsaConnection 2 247 117 260 95 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 74  
            CH.ifa.draw.standard.ChopBoxConnector REF 73   
        fs.IsaConnection 2 289 117 271 95 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 75  
            CH.ifa.draw.standard.ChopBoxConnector REF 73   
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 316 226 20 20  
        CH.ifa.draw.cpn.ArcConnection 3 135 154 210 171 318 232 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 84   
        fs.TypeFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 0 0 0 516 88 "Auto\nfarbe: Farbe" "Helvetica" 2 12 0 NULL NULL 0  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 317 418 20 20  
        CH.ifa.draw.cpn.ArcConnection 3 122 160 97 391 318 427 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 90   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 235 159 "[Peter\n lieblingsfarbe: [Rot]]" "Helvetica" 0 12 0 REF 85 
            CH.ifa.draw.standard.OffsetLocator 64 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 135 156 318 233 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 84   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 157 198 "[Paul\n lieblingsfarbe: [Blau]]" "Helvetica" 0 12 0 REF 98 
            CH.ifa.draw.standard.OffsetLocator -11 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 326 246 326 283 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 84  
            CH.ifa.draw.standard.ChopBoxConnector REF 24   
        CH.ifa.draw.cpn.ArcConnection 2 327 419 327 369 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 90  
            CH.ifa.draw.standard.ChopBoxConnector REF 27   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 171 370 "[Auto\n farbe: [Blau]]" "Helvetica" 0 12 0 REF 91 
            CH.ifa.draw.standard.OffsetLocator -1 92 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 3 121 160 78 408 318 428 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 90   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 180 425 "[Auto\n farbe: [Rot]]" "Helvetica" 0 12 0 REF 116 
            CH.ifa.draw.standard.OffsetLocator 14 146 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 144 330 "r" "Helvetica" 0 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 0 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 200 294 "r" "Helvetica" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator -7 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 197 342 "r" "Helvetica" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator -11 5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 281 277 "r" "Helvetica" 0 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 0 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 281 363 "r" "Helvetica" 0 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator -1 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 331 252 "p" "Helvetica" 0 12 0 REF 105 
            CH.ifa.draw.standard.OffsetLocator 8 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 341 272 "r + [besitzer: [(p)]]" "Helvetica" 0 12 0 REF 48 
            CH.ifa.draw.standard.OffsetLocator 2 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 331 388 "a" "Helvetica" 0 12 0 REF 109 
            CH.ifa.draw.standard.OffsetLocator 7 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 343 363 "r + [auto: [(a)]]" "Helvetica" 0 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator -4 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 462 291 "rb" "Helvetica" 0 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator 9 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 454 344 "ra" "Helvetica" 0 12 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator 3 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 496 309 "ra+rb" "Helvetica" 0 12 0 REF 64 
            CH.ifa.draw.standard.OffsetLocator -5 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 530 298 "Antwort" "Helvetica" 1 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 1 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 432 283 "RB" "Helvetica" 1 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 429 352 "RA" "Helvetica" 1 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 118 318 "R" "Helvetica" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 234 283 "R1" "Helvetica" 1 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 235 352 "R2" "Helvetica" 1 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 316 207 "Personen" "Helvetica" 1 12 0 REF 84 
            CH.ifa.draw.standard.OffsetLocator 17 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 317 441 "Autos" "Helvetica" 1 12 0 REF 90 
            CH.ifa.draw.standard.OffsetLocator 7 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2   
