11 
    de.renew.gui.CPNDrawing 27 
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1 177 159 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 2 105 162 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3 "FrameColor" "Color" 0 0 0 255 2 178 169 129 169 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 153 153 "0" "SansSerif" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 4 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 5 256 162 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 6 "FrameColor" "Color" 0 0 0 255 3 197 171 224 176 256 171 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 10   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 7 "FrameColor" "Color" 0 0 0 255 3 197 168 225 163 256 168 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 10   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 8 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 224 146 "i" "SansSerif" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -1 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 224 179 "j" "SansSerif" 0 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 0 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 10 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 236 125 "guard i>=j;\nguard j>0" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 2 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 11 349 159 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 12 "FrameColor" "Color" 0 0 0 255 3 280 172 314 178 350 171 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 13 "FrameColor" "Color" 0 0 0 255 3 280 167 315 161 350 168 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 14 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 308 146 "i%j" "SansSerif" 0 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator 0 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 15 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 314 180 "j" "SansSerif" 0 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 1 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 16 256 239 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 17 "FrameColor" "Color" 0 0 0 255 2 352 176 277 239 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector REF 43   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 18 "FrameColor" "Color" 0 0 0 255 2 259 239 194 176 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 43  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 19 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 318 212 "i" "SansSerif" 0 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator 5 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 20 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 219 212 "i" "SansSerif" 0 12 0 REF 48 
            CH.ifa.draw.standard.OffsetLocator -6 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 21 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 159 191 "60" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -20 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 22 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 177 198 "42" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -2 36 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 23 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 168 181 "105" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -7 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 24 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 422 152 "int i;\nint j;" "SansSerif" 0 12 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 25 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 187 143 "int" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 7 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 26 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 363 144 "int" "SansSerif" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 11 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 31 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 132 127 "@test_result" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -17 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  559 135 555 562 