11 
    de.renew.gui.CPNDrawing 108 
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "Location" "Boolean" "FALSE" "FigureWithID" "Int" 1182 "FillColor" "Color" 192 192 192 255 96 327 93 39 8 8  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1131 710 185 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1134 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 712 188 "p0" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1133 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 650 165 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1132 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 650 210 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1130 2 674 177 712 192 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1129 2 674 213 712 199 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1168 2 966 134 1081 51 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1163 948 129 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1135 1081 35 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1167 2 964 226 1087 51 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1162 948 223 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 21   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1166 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1008 147 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1165 2 966 239 1083 339 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1121 1081 339 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1164 2 963 147 1087 339 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 19  
            CH.ifa.draw.standard.ChopBoxConnector REF 32   REF 25 REF 19 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1159 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 884 225 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1160 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 884 258 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1161 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 884 193 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1158 2 968 233 1008 234 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1157 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1008 227 24 16 NULL    REF 44 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1156 2 909 151 949 142 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1154 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 885 147 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 19   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1155 2 909 126 949 138 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1153 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 885 116 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 19   REF 48 REF 53 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1152 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1008 116 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1151 2 968 138 1008 126 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 19  
            CH.ifa.draw.standard.ChopBoxConnector REF 55   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1150 2 968 141 1008 151 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 19  
            CH.ifa.draw.standard.ChopBoxConnector REF 27   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1149 2 908 207 950 229 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 39  
            CH.ifa.draw.figures.ChopEllipseConnector REF 25   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1148 2 908 233 949 233 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 37  
            CH.ifa.draw.figures.ChopEllipseConnector REF 25   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1147 2 908 259 950 238 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 38  
            CH.ifa.draw.figures.ChopEllipseConnector REF 25   REF 21 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1136 2 1105 37 1138 21 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 21  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1138 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1136 7 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1137 2 1105 49 1138 66 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 21  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1139 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1136 60 20 20 NULL    REF 80 REF 85 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1140 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1083 36 "t12" "SansSerif" 1 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 32 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1122 2 1104 339 1139 315 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 32  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1125 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1136 299 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1123 2 1103 355 1139 381 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 32  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1126 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1136 376 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1124 2 1105 347 1137 347 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 32  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1127 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1136 337 20 20 NULL    REF 93 REF 98 REF 103 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1128 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1083 340 "t22" "SansSerif" 1 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1172 2 729 192 1081 47 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 21   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1173 2 729 199 1081 342 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 32   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1179 2 540 201 606 201 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1178 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 498 181 42 40   
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1176 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 606 181 42 40    REF 121 REF 119 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1101 2 64 187 114 51 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 879 50 185 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 950 106 35 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1102 2 64 204 114 339 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 125  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 970 106 339 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1103 2 130 43 157 43 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 127  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1105 156 33 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1104 2 176 43 421 43 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 137  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 952 421 35 24 16 NULL    REF 137 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1106 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 158 36 "p1" "SansSerif" 1 12 0 REF 137 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1108 2 176 347 421 347 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1109 156 337 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 972 421 339 24 16 NULL    REF 151 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 973 2 444 339 479 315 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 151  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 977 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 476 299 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 974 2 443 355 479 381 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 151  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 978 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 476 376 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 975 2 445 347 477 347 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 151  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 979 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 476 337 20 20 NULL    REF 156 REF 161 REF 166 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 987 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 423 340 "t22" "SansSerif" 1 12 0 REF 151 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 873 2 14 213 52 199 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 880 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -10 210 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 125   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 874 2 14 177 52 192 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 881 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -10 165 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 125   REF 125 REF 173 REF 178 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 927 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 52 188 "p0" "SansSerif" 1 12 0 REF 125 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 142 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 953 2 445 37 478 21 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 142  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 955 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 476 7 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 954 2 445 49 478 66 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 142  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 956 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 476 60 20 20 NULL    REF 187 REF 192 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 959 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 423 36 "t12" "SansSerif" 1 12 0 REF 142 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 127 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 957 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 112 36 "t1" "SansSerif" 1 12 0 REF 127 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 998 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 185 283 "arbitrary but equal preset \nfor t12 and t22 except p1, p2" "SansSerif" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 988 "FillColor" "Color" 235 199 158 255 263 93 70 186 8 8  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 966 2 248 259 290 238 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 983 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 224 258 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 981 288 223 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 967 2 248 233 289 233 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 982 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 224 225 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 206   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 980 2 248 207 290 229 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 984 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 224 193 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 206   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1076 2 308 141 348 151 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 962 288 129 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "FALSE" "FigureWithID" "Int" 1028 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 348 147 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1075 2 308 138 348 126 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 220  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "FALSE" "FigureWithID" "Int" 1027 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 348 116 24 16 NULL    REF 227 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 945 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 225 116 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 965 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 225 147 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 964 2 249 126 289 138 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 228  
            CH.ifa.draw.figures.ChopEllipseConnector REF 220   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 963 2 249 151 289 142 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 229  
            CH.ifa.draw.figures.ChopEllipseConnector REF 220   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "Location" "Boolean" "FALSE" "FigureWithID" "Int" 1077 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 348 227 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1089 2 308 233 348 234 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 206  
            CH.ifa.draw.standard.ChopBoxConnector REF 238   REF 210 REF 204 REF 215 REF 206 REF 220 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 999 2 303 147 427 339 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 220  
            CH.ifa.draw.standard.ChopBoxConnector REF 151   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1003 2 306 239 423 339 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 206  
            CH.ifa.draw.standard.ChopBoxConnector REF 151   REF 222 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 992 2 304 226 427 51 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 206  
            CH.ifa.draw.standard.ChopBoxConnector REF 142   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 991 2 306 134 421 51 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 220  
            CH.ifa.draw.standard.ChopBoxConnector REF 142   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1107 2 130 347 157 347 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 132  
            CH.ifa.draw.figures.ChopEllipseConnector REF 149   REF 149 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 1110 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 158 340 "p2" "SansSerif" 1 12 0 REF 149 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 132 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "Location" "Boolean" "TRUE" "FigureWithID" "Int" 985 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 112 340 "t2" "SansSerif" 1 12 0 REF 132 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 1183 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 109 372 "optional" "SansSerif" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 1092 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 128 413 "there may be an arbitrary amount of branches" "SansSerif" 0 12 0 NULL NULL  NULL  92 205 1253 614 