5 
    de.renew.gui.CPNDrawing 10 
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 144 66 92 96 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 270 35 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3 105 34 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4 "FrameColor" "Color" 0 0 0 2 227 86 271 51 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 5 "FrameColor" "Color" 0 0 0 2 125 50 158 82 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 6 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 255 15 ":take(thing)" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 5 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 84 10 ":deposit(thing)" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 9 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 122 56 "thing" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator -5 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 234 61 "thing" "Helvetica" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -1 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.GroupFigure 3 
            CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 11 "FillColor" "Color" 192 192 192 8 26 58 41  
            CH.ifa.draw.contrib.PolygonFigure "attributes" "attributes" 2 "FigureWithID" "Int" 12 "FillColor" "Color" 192 192 192 9 37 15 42 8 45 12 51 8 40 26 31 25 22 8 31 15 33 4  
            CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 15 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 15 37 "BAG $ID" "Helvetica" 1 12 0 NULL NULL   REF 24  402 245 345 222 
