11 
    de.renew.gui.CPNDrawing 35 
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 4 "Location" "Boolean" "FALSE" "FigureWithID" "Int" 7368 "FontName" "String" "Arial" "FillColor" "Color" 204 204 204 255 18 22 713 539 8 8  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 7370 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "TextType" "Int" 0 "FillColor" "Color" 255 255 255 255 104 68 205 85 NULL  
        de.renew.gui.fs.UMLNoteFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7371 "FrameColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 37 49 "initial task:\ntaskName" "Arial" 0 16 0 REF 2
            CH.ifa.draw.standard.OffsetLocator -116 -37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7372 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 148 86 "dwf_submitPaper\n[providePaperBody,\nprovidePaperFrame]" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 7373 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "TextType" "Int" 0 "FillColor" "Color" 255 255 255 255 203 246 204 66 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7384 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 0 0 255 206 184 97 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7385 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 239 190 "refine" "Arial" 1 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7386 2 229 151 247 184 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 10   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7387 2 262 211 286 248 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector REF 9   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7390 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 253 257 "dwf_submitPaper\n[providePaperBody]" "SansSerif" 1 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 4 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 7205 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "TextType" "Int" 0 "FillColor" "Color" 255 255 255 255 492 225 204 66 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7394 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 528 242 "dwf_providePaperBody\n[writeMainPart]" "SansSerif" 1 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7395 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 610 322 97 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7396 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 636 328 "execute" "Arial" 1 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7397 2 318 312 338 360 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 9  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7408 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 0 0 255 295 360 97 27 NULL    
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7401 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 0 0 255 520 178 97 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7402 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 553 184 "refine" "Arial" 1 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 7403 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "TextType" "Int" 0 "FillColor" "Color" 255 255 255 255 436 74 205 85 NULL  
        de.renew.gui.fs.UMLNoteFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7404 "FrameColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 369 55 "initial task:\ntaskName" "Arial" 0 16 0 REF 42
            CH.ifa.draw.standard.OffsetLocator -116 -37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7405 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 482 100 "dwf_submitPaper\n[providePaperBody]" "SansSerif" 1 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7406 2 555 157 563 178 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 42  
            CH.ifa.draw.standard.ChopBoxConnector REF 38   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7407 2 573 205 582 226 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 38  
            CH.ifa.draw.figures.ChopEllipseConnector REF 25   REF 37 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7409 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 328 366 "refine" "Arial" 1 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 7410 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "TextType" "Int" 0 "FillColor" "Color" 255 255 255 255 242 435 204 66 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7411 2 343 387 344 436 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 37  
            CH.ifa.draw.figures.ChopEllipseConnector REF 60   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7412 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 286 444 "dwf_submitPaper\n[providePaperBody,\nprovidePaperFrame]" "SansSerif" 1 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7414 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 148 512 97 27 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7416 2 279 493 231 512 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 60  
            CH.ifa.draw.standard.ChopBoxConnector REF 68   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7417 2 620 290 647 322 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector REF 29   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7369 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 255 255 255 "TextType" "Int" 0 "FillColor" "Color" 64 64 64 255 37 407 "position;\nname=positionName;" "Arial" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -253 138 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6973 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 0 255 "FontName" "String" "Arial" 512 500 97 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6974 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 537 506 "delegate" "Arial" 1 12 0 REF 80 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7418 2 591 291 562 500 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector REF 80   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7415 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 178 517 "execute" "Arial" 1 12 0 REF 68 
            CH.ifa.draw.standard.OffsetLocator 5 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  1016 144 751 419 