11 
    de.renew.gui.CPNDrawing 46 
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3457 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 13 -122 137 144  
        de.renew.bpmn.roundtrip.RoundtripNetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3458 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 24 
            de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3459 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -14 -9 24 16 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 3472 "BSplineDegree" "Int" 2 "Visibility" "Boolean" "TRUE" "LineShape" "Int" 1 "BSplineSegments" "Int" 15 3 93 -94 123 -89 127 -58 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3467 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 73 -106 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3468 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 117 -58 24 16 NULL    
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3460 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 255 213 -11 20 20 NULL  
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3461 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 72 -60 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3476 "Visibility" "Boolean" "TRUE" 2 91 -45 151 -9 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 11  
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3462 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 151 -9 24 16 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3479 "Visibility" "Boolean" "TRUE" 2 35 -57 35 -114 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3465 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 23 -57 24 15 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 3466 "Visibility" "Boolean" "TRUE" 25 -134 20 20 NULL    REF 16 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3480 "Visibility" "Boolean" "TRUE" 2 93 -2 151 -2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3463 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 73 -12 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector REF 16   REF 26 
            de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 3483 "BSplineDegree" "Int" 2 "Visibility" "Boolean" "TRUE" "LineShape" "Int" 1 "BSplineSegments" "Int" 15 3 127 -42 123 -11 93 -3 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 9  
                CH.ifa.draw.figures.ChopEllipseConnector REF 26   
            de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3464 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 224 224 255 255 -9 -99 20 20 NULL 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3500 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 224 224 255 255 -7 -178 20 20 NULL   
            de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 3486 "BSplineDegree" "Int" 2 "Visibility" "Boolean" "TRUE" "LineShape" "Int" 1 "BSplineSegments" "Int" 15 3 36 -57 44 -89 74 -94 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 20  
                CH.ifa.draw.figures.ChopEllipseConnector REF 7   
            de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 3487 "BSplineDegree" "Int" 2 "Visibility" "Boolean" "TRUE" "LineShape" "Int" 1 "BSplineSegments" "Int" 15 3 74 -3 41 -11 36 -42 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 26  
                CH.ifa.draw.standard.ChopBoxConnector REF 20   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3489 "Visibility" "Boolean" "TRUE" 2 73 -50 47 -50 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 11  
                CH.ifa.draw.standard.ChopBoxConnector REF 20   REF 20 REF 1 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3491 "Visibility" "Boolean" "TRUE" 2 28 -57 8 -81 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 20  
                CH.ifa.draw.figures.ChopEllipseConnector REF 32   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3493 "Visibility" "Boolean" "TRUE" 2 10 -2 74 -2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 3  
                CH.ifa.draw.figures.ChopEllipseConnector REF 26   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3494 "Visibility" "Boolean" "TRUE" 2 10 -9 74 -45 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 3  
                CH.ifa.draw.figures.ChopEllipseConnector REF 11   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3495 "Visibility" "Boolean" "TRUE" 2 92 -50 117 -50 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 11  
                CH.ifa.draw.standard.ChopBoxConnector REF 9   REF 22 REF 7 REF 9 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3499 "Visibility" "Boolean" "TRUE" 2 175 -1 214 -1 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 16  
                CH.ifa.draw.figures.ChopEllipseConnector REF 10   "iterator"  REF 3 REF 10 REF 11 REF 16 REF 26 REF 32 REF 20 REF 22 REF 7 REF 9 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3469 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 -16 -113 "Object" "SansSerif" 1 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 3 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3470 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 227 -9 ">" "SansSerif" 3 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3471 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 135 -32 "it" "SansSerif" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 17 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 4 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3473 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 -18 -9 ">" "SansSerif" 3 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -11 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3474 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 15 -35 "it" "SansSerif" 0 12 0 REF 55 
            CH.ifa.draw.standard.OffsetLocator -24 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 3475 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 148 -68 "cond = \nit.hasNext();" "SansSerif" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 54 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 12 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3477 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 58 -65 "it" "SansSerif" 0 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator 1 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3478 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 86 -31 "cond" "SansSerif" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator -10 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 17 REF 23 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 7 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3481 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "TextType" "Int" 0 "FillColor" "Color" 255 199 158 255 129 -70 "v" "SansSerif" 0 15 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 4 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 3482 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 -32 14 "action it = v.iterator();" "SansSerif" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 33 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 28 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3484 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 30 -143 "^" "SansSerif" 3 17 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator 0 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3485 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 102 -65 "it" "SansSerif" 0 12 0 REF 59 
            CH.ifa.draw.standard.OffsetLocator 1 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 34 REF 38 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3488 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 16 -84 "o" "SansSerif" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 1 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 42 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3490 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 21 -9 "cond" "SansSerif" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator -7 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 47 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 3492 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 -39 -69 "action o =\n it.next();" "SansSerif" 0 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator -45 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 51 REF 55 REF 59 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3496 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 48 -30 "true" "SansSerif" 0 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3497 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 60 -80 "Iterator" "SansSerif" 1 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 1 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3498 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 110 -8 "false" "SansSerif" 0 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 1 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 64 REF 33 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3501 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 -18 -194 "Object" "SansSerif" 1 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator -1 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 3502 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 -32 28 "action cond =  it.hasNext();" "SansSerif" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 49 36 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  44 211 657 554 