
    CH.ifa.draw.cpn.CPNDrawing 14 
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 239 237 63 66  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 241 108 24 16  
        CH.ifa.draw.cpn.ArcConnection 3 258 124 287 169 275 239 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 276 108 ":setze(X)" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 47 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 299 167 "X" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 31 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 103 266 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 240 271 127 273 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 13   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 101 291 ":lies(X)" "Helvetica" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 5 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 173 252 "X" "Helvetica" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator -6 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 145 118 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 163 134 251 246 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 23  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 173 118 ":new()" "Helvetica" 0 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 29 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 267 238 253 124 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 237 169 "alt" "Helvetica" 0 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator -17 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
