
    CH.ifa.draw.cpn.CPNDrawing 42 
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 171 241 20 20  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 126 242 "Beliefs" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -35 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 172 665 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 213 664 ":sync(X, [SYNC: #1(X)\n          UPLINK: #1<>]@UPLINK)" "Monospaced" 0 10 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 122 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 203 294 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 187 259 209 294 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 9   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 204 267 "B" "Monospaced" 0 10 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 9 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 267 87 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 267 69 ":new()" "Helvetica" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 1 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 3 267 101 192 144 182 242 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 85 91 "[atPlace\n OBJECT:[robot]\n PLACE:[a]]" "Monospaced" 0 10 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator -94 -62 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 464 142 20 20  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 493 144 "Queries" "Helvetica" 1 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 41 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.ArcConnection 2 291 98 465 150 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 27   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 379 87 "[atSamePlace\n OBJ1:[robot]\n OBJ2: [thing]]" "Monospaced" 0 10 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator 46 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 463 191 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 474 162 474 191 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 27  
            CH.ifa.draw.standard.ChopBoxConnector REF 38   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 481 165 "q" "Helvetica" 0 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 10 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 499 192 "this:sync(q,a)" "Helvetica" 0 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 60 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 465 250 20 20  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 491 252 "Answers" "Helvetica" 1 12 0 REF 49 
            CH.ifa.draw.standard.OffsetLocator 41 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.ArcConnection 2 475 207 475 251 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 38  
            CH.ifa.draw.figures.ChopEllipseConnector REF 49   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 484 218 "a" "Helvetica" 0 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 12 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 3 268 103 201 152 183 242 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 86 195 "[atPlace \n OBJECT:[bin]\n PLACE:[a]]" "Monospaced" 0 10 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator -100 41 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 3 271 103 214 165 185 243 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 84 142 "[atPlace\n OBJECT:[waste]\n PLACE:[b]]" "Monospaced" 0 10 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator -99 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 273 103 186 244 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 263 139 "[rule\n GOAL:[atSamePlace\n       OBJ1: #1\n       OBJ2: #2]\n SUBGOALS: <[atPlace\n             OBJECT: #1\n             PLACE: #3]\n            [atPlace\n             OBJECT: #2\n             PLACE: #3]>]\n" "Monospaced" 0 10 0 REF 74 
            CH.ifa.draw.standard.OffsetLocator 109 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 165 512 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 211 501 ":sync(X,(uplink+\n[DOWNLINK1:(downlink1)\n DOWNLINK2: (downlink2)])\n@UPLINK)" "Monospaced" 0 10 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 109 5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 211 619 "this:sync(uplink@DOWNLINK1,downlink1)" "Monospaced" 0 10 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 145 105 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 211 638 "this:sync(uplink@DOWNLINK2,downlink2)" "Monospaced" 0 10 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 145 124 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 139 347 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 179 261 153 347 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 91   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 170 320 "R" "Monospaced" 0 10 0 REF 92 
            CH.ifa.draw.standard.OffsetLocator 7 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 186 465 "this:sync(uplink@DOWNLINK1,downlink1)" "Monospaced" 0 10 0 REF 91 
            CH.ifa.draw.standard.OffsetLocator 146 116 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 174 350 ":sync(X,(uplink+[DOWNLINK1: (downlink1)])@UPLINK)" "Monospaced" 0 10 0 REF 91 
            CH.ifa.draw.standard.OffsetLocator 170 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 177 365 "uplink = \n[RULE: #1(R)\n IN1:  #1[rule\n          GOAL: #2\n          SUBGOALS: #3]\n SYNC: #2(X)\n UPLINK: #2\n DOWNLINK1: #3]" "Monospaced" 0 10 0 REF 91 
            CH.ifa.draw.standard.OffsetLocator 95 58 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 211 555 "uplink =\n[SYNC: #3(X)\n UPLINK: #3<#1 | #2>\n DOWNLINK1: #1\n DOWNLINK2: #2]" "Monospaced" 0 10 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 94 65 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 234 285 ":sync(X,B)" "Monospaced" 0 10 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 49 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 243 300 "guard X<=B" "Monospaced" 0 10 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 58 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
