6 
    de.renew.gui.CPNDrawing 51 
        de.renew.gui.PlaceFigure "attributes" "attributes" 6 "FigureWithID" "Int" 1 "TraceMode" "Boolean" "FALSE" "FontName" "String" "Dialog" "FrameColor" "Color" 0 0 0 "FontSize" "Int" 12 "FillColor" "Color" 192 192 192 199 117 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 6 "FigureWithID" "Int" 5 "TraceMode" "Boolean" "FALSE" "FontName" "String" "Dialog" "FrameColor" "Color" 0 0 0 "FontSize" "Int" 12 "FillColor" "Color" 192 192 192 150 176 32 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 6 "TraceMode" "Boolean" "FALSE" "FontName" "String" "Dialog" "FrameColor" "Color" 0 0 0 "FontSize" "Int" 12 2 204 135 172 176 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        de.renew.gui.TransitionFigure "attributes" "attributes" 6 "FigureWithID" "Int" 8 "TraceMode" "Boolean" "FALSE" "FontName" "String" "Dialog" "FrameColor" "Color" 0 0 0 "FontSize" "Int" 12 "FillColor" "Color" 192 192 192 106 49 60 18 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 6 "FigureWithID" "Int" 14 "TraceMode" "Boolean" "FALSE" "FontName" "String" "Dialog" "FrameColor" "Color" 0 0 0 "FontSize" "Int" 12 "FillColor" "Color" 192 192 192 318 120 32 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 15 "TraceMode" "Boolean" "FALSE" "FontName" "String" "Dialog" "FrameColor" "Color" 0 0 0 "FontSize" "Int" 12 2 219 127 318 127 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 7   
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 19 "TraceMode" "Boolean" "FALSE" "FontName" "String" "Dialog" "FrameColor" "Color" 0 0 0 "FontSize" "Int" 12 2 145 67 203 121 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.TransitionFigure "attributes" "attributes" 6 "FigureWithID" "Int" 30 "TraceMode" "Boolean" "FALSE" "FontName" "String" "Dialog" "FrameColor" "Color" 0 0 0 "FontSize" "Int" 12 "FillColor" "Color" 192 192 192 239 51 79 18 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 45 "TraceMode" "Boolean" "FALSE" "FontName" "String" "Dialog" "FrameColor" "Color" 0 0 0 "FontSize" "Int" 12 2 216 121 269 69 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 15   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 186 146 "a" "Dialog" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 1 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 56 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 171 211 76 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 46 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 237 89 "b" "Dialog" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator -2 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 59 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 192 192 192 86 119 30 18 NULL  
        de.renew.gui.InhibitorConnection "attributes" "attributes" 2 "FigureWithID" "Int" 60 "TraceMode" "Boolean" "FALSE" 2 116 127 200 127 
            de.renew.gui.CircleDecoration  
            de.renew.gui.CircleDecoration  
            CH.ifa.draw.standard.ChopBoxConnector REF 27  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 62 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 155 120 "q" "Helvetica" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 64 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 92 121 "not" "Helvetica" 1 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 41 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 261 52 "retract" "Dialog" 1 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 191 95 "Beliefs" "Dialog" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 1 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 40 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 118 50 "assert" "Dialog" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 6 "FigureWithID" "Int" 81 "TraceMode" "Boolean" "FALSE" "FontName" "String" "Dialog" "FrameColor" "Color" 0 0 0 "FontSize" "Int" 12 "FillColor" "Color" 192 192 192 171 251 76 20 NULL  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 88 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 237 88 "#1" "Helvetica" 0 12 0 REF 16
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 86 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 169 87 "#1" "Helvetica" 0 12 0 REF 11
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 95 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 153 120 "#1" "Helvetica" 0 12 0 REF 28
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 97 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 183 148 "#1" "Helvetica" 0 12 0 REF 3
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 58 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 8 207 "query has to be fully instanciated,\nthen proceed left to right:" "Helvetica" 2 12 0 
            de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 57 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 43 211 ":s(in,(tmp+[Any t2:(t2)])@in);\ntmp=[Any thiz:(this)\n in: (in)\n k1: (k1)]\n+\n[Any\n in: <#1|#2>\n k1: #1\n t1: #1\n t2: #2];\ntmp@thiz:s(tmp@t2,t2)" "Helvetica" 0 9 0 REF 23 
                CH.ifa.draw.standard.OffsetLocator -106 56 
                    CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
            CH.ifa.draw.standard.OffsetLocator -4 -55 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 61 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 82 88 ":s(tb,tb);\ntb=[Not p:(q)]" "Helvetica" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 16 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 31 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 234 6 ":s(rb,rb+[Retract belief:(b+q)]);\nrb=[Retract belief:(q)]" "Dialog" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 37 -39 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 9 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 86 8 ":s(ab,ab);\nab=[Assert belief:(b)]" "Dialog" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 6 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 123 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 182 254 "terminate" "Helvetica" 1 12 0 REF 48 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 20 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 "Visibility" "Boolean" "FALSE" 153 71 "b" "Dialog" 0 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator -18 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 87 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 321 41 "[Link\n param:\n[Retract belief:#1]]" "Helvetica" 0 12 0 REF 15
            CH.ifa.draw.standard.OffsetLocator 72 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 85 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 44 40 "[Link\n param:\n[Assert\n belief: #1]]" "Helvetica" 0 12 0 REF 6
            CH.ifa.draw.standard.OffsetLocator -63 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 99 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 232 133 "[Rule\n              goal: #1\n              subgoals:#2]" "Helvetica" 0 12 0 REF 8
            CH.ifa.draw.standard.OffsetLocator 1 33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 16 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 "Visibility" "Boolean" "TRUE" 261 120 "k1" "Dialog" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator -1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 94 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 47 111 "[Link\n param: [Not p:#1]]" "Helvetica" 0 12 0 REF 27
            CH.ifa.draw.standard.OffsetLocator -37 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 101 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 354 139 "[Link\n rcv: [this]\n param: #2]" "Helvetica" 0 12 0 REF 7
            CH.ifa.draw.standard.OffsetLocator 43 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 98 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 354 120 "[Link\n param: #1]" "Helvetica" 0 12 0 REF 7
            CH.ifa.draw.standard.OffsetLocator 28 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 96 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 128 176 "[Link\n param:#1]" "Helvetica" 0 12 0 REF 2
            CH.ifa.draw.standard.OffsetLocator -30 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 121 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 176 213 "processList" "Helvetica" 1 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 38 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 324 120 "rule" "Dialog" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 37 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 156 176 "test" "Dialog" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 52 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 71 177 ":s(q,q+a)" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -71 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 124 "TraceMode" "Boolean" "FALSE" 2 209 137 209 211 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 23   
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 115 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 251 253 "[Link\n param:<>]" "Helvetica" 0 12 0 REF 48
            CH.ifa.draw.standard.OffsetLocator 54 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 102 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 251 212 "[Link\n param: <#1|#2>]" "Helvetica" 0 12 0 REF 23
            CH.ifa.draw.standard.OffsetLocator 68 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 "FigureWithID" "Int" 125 204 167 "#1" "Helvetica" 0 12 0 REF 118
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 126 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 211 184 "k1" "Helvetica" 0 12 0 REF 118 
            CH.ifa.draw.standard.OffsetLocator 8 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 83 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 170 279 ":s(in,in+<>)" "Dialog" 0 9 0 REF 48 
            CH.ifa.draw.standard.OffsetLocator -16 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 47 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 351 166 ":s(in,(tmp+[Any t2:(t2)])@in);\ntmp=[Any thiz:(this)\nin:(in)\nk1:(k1)]\n+\n[Any\n in: #1[Predicate]\n k1: [Rule goal:#1 subgoals:#2]\n t1: #1\n t2: #2];\ntmp@thiz:s(tmp@t2,t2)" "Dialog" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 102 120 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 62 
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 106 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 251 233 "[Link\n rcv: [this]\n param: #2]" "Helvetica" 0 12 0 REF 23
            CH.ifa.draw.standard.OffsetLocator 65 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  NULL  125 99 654 426 
