7 
    de.renew.gui.CPNDrawing 28 
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 9 48 73 35 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 2 "Visibility" "Boolean" "TRUE" 2 81 65 112 65 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 112 57 24 16 NULL    REF 6 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4 "Visibility" "Boolean" "TRUE" 2 136 65 260 65 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 259 55 20 20 NULL    REF 11 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 6 "Visibility" "Boolean" "TRUE" 3 265 74 247 104 264 135 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 257 135 24 16 NULL    REF 16 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 8 "Visibility" "Boolean" "TRUE" 3 274 135 292 107 274 74 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 11   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 9 "Visibility" "Boolean" "TRUE" 2 279 65 397 65 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 10 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 397 57 24 16 NULL    REF 25 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 11 "Visibility" "Boolean" "TRUE" 2 421 65 458 65 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 25  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 12 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 457 55 20 20 NULL    REF 30 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 13 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 264 135 "t2" "Helvetica" 1 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 25 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 460 35 "p3" "Helvetica" 1 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 0 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 28 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 40 29 "p1" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 2 -29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 29 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 120 57 "t1" "Helvetica" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 31 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 404 57 "t3" "Helvetica" 1 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 24 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 262 24 "p2" "Helvetica" 1 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 0 -34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 39 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 90 58 "#1" "Helvetica" 0 12 0 REF 2
            CH.ifa.draw.standard.OffsetLocator -1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 44 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 134 80 "[Working\n remains: <#2 | #3>\n backwards: #4]" "Helvetica" 0 12 0 REF 12
            CH.ifa.draw.standard.OffsetLocator -66 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 5 "" "remains:hd" "remains:tl" "backwards" "remains"  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 43 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 294 80 "[Working\n remains: #3\n backwards: <#2 | #4>]" "Helvetica" 0 12 0 REF 17
            CH.ifa.draw.standard.OffsetLocator 74 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 5 "remains" "backwards" "backwards:hd" "backwards:tl" ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 41 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 298 10 "[Working\n remains: <>\n backwards: #5]" "Helvetica" 0 12 0 REF 21
            CH.ifa.draw.standard.OffsetLocator 4 -28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 3 "" "remains" "backwards"  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 67 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 241 39 "[Working]" "Helvetica" 0 12 0 REF 11
            CH.ifa.draw.standard.OffsetLocator -1 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0 1 ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 40 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 146 10 "[Working\n remains: #1\n backwards: <>]" "Helvetica" 0 12 0 REF 7
            CH.ifa.draw.standard.OffsetLocator -9 -28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 3 "backwards" "remains" ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 42 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 431 58 "#5" "Helvetica" 0 12 0 REF 26
            CH.ifa.draw.standard.OffsetLocator -3 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 69 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 454 76 "[List]" "Helvetica" 0 12 0 REF 30
            CH.ifa.draw.standard.OffsetLocator 0 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 68 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 31 84 "[List]" "Helvetica" 0 12 0 REF 1
            CH.ifa.draw.standard.OffsetLocator -1 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 50 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 12 57 "<[A] [B] [C]>" "Helvetica" 0 12 0 REF 1
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 7 "tl" "tl:tl" "" "tl:hd" "tl:tl:hd" "hd" "tl:tl:tl"  NULL  0 264 527 205 
