7 
    de.renew.gui.CPNDrawing 93 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 10 "FrameColor" "Color" 0 0 255 "FillColor" "Color" 255 255 255 "Visibility" "Boolean" "TRUE" 400 28 116 75 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 255 "FillColor" "Color" 255 255 255 "Visibility" "Boolean" "TRUE" 15 48 176 87 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3 "FrameColor" "Color" 0 0 255 "FillColor" "Color" 255 255 255 "Visibility" "Boolean" "TRUE" 203 27 116 76 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 4 "FrameColor" "Color" 0 0 255 "FillColor" "Color" 0 0 255 "Visibility" "Boolean" "TRUE" 2 286 47 353 71 NULL 
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 75 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 241 32 "Working" "Helvetica" 1 12 0 NULL NULL
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 255 "FillColor" "Color" 255 255 255 "Visibility" "Boolean" "TRUE" 351 63 20 20 NULL    REF 9 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7 "FrameColor" "Color" 0 0 255 "FillColor" "Color" 255 255 255 "Visibility" "Boolean" "TRUE" 232 132 254 108 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 8 "FrameColor" "Color" 0 0 255 "FillColor" "Color" 0 0 255 "Visibility" "Boolean" "TRUE" 2 440 143 369 80 NULL 
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 44 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 425 143 "Working" "Helvetica" 1 12 0 NULL NULL
            CH.ifa.draw.figures.ChopEllipseConnector REF 9   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 9 "FrameColor" "Color" 0 0 255 "FillColor" "Color" 0 0 255 "Visibility" "Boolean" "TRUE" 2 370 71 437 48 NULL 
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.figures.ChopEllipseConnector REF 9  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 88 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 436 33 "Working" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 11 "FrameColor" "Color" 0 0 255 "FillColor" "Color" 0 0 255 "Visibility" "Boolean" "TRUE" 2 500 91 539 91 NULL 
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 85 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 492 84 " " "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 12 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 255 "FillColor" "Color" 255 255 255 "Visibility" "Boolean" "TRUE" 538 81 20 20 NULL    REF 26 
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 46 2 441 158 417 183 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 14  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 55 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 409 183 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 48 2 279 158 297 184 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 41 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 250 143 "Working" "Helvetica" 1 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 49 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 35 142 104 301 184 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 54 2 309 191 404 190 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 37  
            CH.ifa.draw.standard.ChopBoxConnector REF 31   
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 57 2 309 193 352 207 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 37  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 58 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 357 202 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63 3 449 158 449 195 417 221 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 14  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 47 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 35 142 104 409 219 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 65 2 404 224 365 211 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 51  
            CH.ifa.draw.standard.ChopBoxConnector REF 46   
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 67 2 404 226 308 226 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 51  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 68 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 300 219 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 70 3 274 158 274 197 295 219 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 35  
            CH.ifa.draw.standard.ChopBoxConnector REF 60   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 6 "FrameColor" "Color" 0 0 255 "FillColor" "Color" 0 0 255 "Visibility" "Boolean" "TRUE" 2 355 80 282 143 NULL 
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.figures.ChopEllipseConnector REF 9  
            CH.ifa.draw.standard.ChopBoxConnector REF 35   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 66 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 387 206 "hd" "Helvetica" 0 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator 10 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 59 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 314 199 "hd" "Helvetica" 0 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator -9 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 50 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 281 158 "remains" "Helvetica" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 16 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 76 2 259 47 230 84 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 77 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 223 84 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 79 2 267 47 282 84 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 80 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 0 0 0 284 84 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 2 "FrameColor" "Color" 0 0 255 "FillColor" "Color" 0 0 255 "Visibility" "Boolean" "TRUE" 2 191 91 218 91 NULL 
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 82   
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 82 2 453 48 421 84 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 20  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 86 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 0 0 0 413 84 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 84 2 464 48 488 84 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 20  
            CH.ifa.draw.standard.ChopBoxConnector REF 24   REF 96 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 30 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 353 117 "t2" "Helvetica" 1 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator -1 -62 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 96 2 62 76 86 75 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 95 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 35 142 104 54 69 " " "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 97 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 35 142 104 91 68 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 98 2 99 75 121 75 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 109  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 99 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 35 142 104 126 68 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 102 2 55 84 55 108 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 107  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 103 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 52 108 "A" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 104 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 48 85 "hd" "Helvetica" 0 12 0 REF 115 
            CH.ifa.draw.standard.OffsetLocator 0 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 105 2 92 83 91 108 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 109  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 106 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 87 108 "B" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 107 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 84 84 "hd" "Helvetica" 0 12 0 REF 123 
            CH.ifa.draw.standard.OffsetLocator 0 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 108 2 127 83 126 108 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 114  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 109 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 122 108 "C" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 111 2 134 75 158 75 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 114  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 112 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 0 0 0 163 68 " " "Helvetica" 0 12 0 NULL NULL    REF 119
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 113 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 105 68 "tl" "Helvetica" 0 12 0 REF 110 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 115 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 141 69 "tl" "Helvetica" 0 12 0 REF 136 
            CH.ifa.draw.standard.OffsetLocator -2 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 110 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 120 84 "hd" "Helvetica" 0 12 0 REF 131 
            CH.ifa.draw.standard.OffsetLocator 1 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 116 2 104 49 104 33 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 93 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 94 18 "List" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 120 2 548 82 548 59 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 89 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 538 44 "List" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 121 2 362 64 362 43 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 9  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 92 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 339 28 "Working" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 2 "FigureWithID" "Int" 122 "FrameColor" "Color" 0 0 255 2 30 69 49 74 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 107   REF 37 
        de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 125 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 62 191 "NEList" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 130 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 62 212 "EList" "Helvetica" 1 12 0 NULL NULL
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 126 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 44 191 "=" "Helvetica" 0 12 0 NULL NULL  REF 87 REF 82 
        de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 132 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 62 171 "List" "Helvetica" 1 12 0 NULL NULL
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 131 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 44 212 "=" "Helvetica" 0 12 0 NULL NULL  
        de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 129 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 0 0 0 28 212 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 134 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 28 171 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 135 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 62 151 "T" "Helvetica" 0 12 0 NULL NULL
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 133 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 44 171 "=" "Helvetica" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 136 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 44 151 "=" "Helvetica" 0 12 0 NULL NULL  
        de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 137 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 28 151 " " "Helvetica" 0 12 0 NULL NULL  REF 24 REF 31 REF 35 REF 20 REF 7 REF 107
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 100 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 67 68 "tl" "Helvetica" 0 12 0 REF 104 
            CH.ifa.draw.standard.OffsetLocator -4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 109 REF 127 REF 114 REF 135 REF 164 REF 60 REF 51 REF 46 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 56 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 355 182 "tl" "Helvetica" 0 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 69 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 356 218 "tl" "Helvetica" 0 12 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator 3 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 14 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 64 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 421 188 "backwards" "Helvetica" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 18 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 28 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 260 14 "t1" "Helvetica" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 4 -44 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 13 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 453 13 "t3" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 -45 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 83 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 410 62 "remains" "Helvetica" 0 12 0 REF 92 
            CH.ifa.draw.standard.OffsetLocator -4 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 87 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 455 52 "backwards" "Helvetica" 0 12 0 REF 97 
            CH.ifa.draw.standard.OffsetLocator 9 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 78 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 221 50 "remains" "Helvetica" 0 12 0 REF 78 
            CH.ifa.draw.standard.OffsetLocator 0 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 81 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 251 62 "backwards" "Helvetica" 0 12 0 REF 83 
            CH.ifa.draw.standard.OffsetLocator 7 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 23 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 75 33 "p1" "Helvetica" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -21 -51 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 71 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 236 190 "backwards" "Helvetica" 0 12 0 REF 61 
            CH.ifa.draw.standard.OffsetLocator -18 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 60 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 399 160 "remains" "Helvetica" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator -7 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 127 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 35 142 104 28 191 " " "Helvetica" 0 12 0 NULL NULL  REF 140 REF 154 REF 159
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 36 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 369 51 "p2" "Helvetica" 1 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 15 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 14 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 556 68 "p3" "Helvetica" 1 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 15 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  40 329 627 300 
