7 
    de.renew.gui.CPNDrawing 96 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 10 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 442 30 130 83 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 7 28 176 87 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 246 30 131 83 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4 "Visibility" "Boolean" "TRUE" 2 377 71 398 71 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 397 61 20 20 NULL    REF 8 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 268 146 278 108 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 8 "Visibility" "Boolean" "TRUE" 3 418 146 426 113 411 80 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 9  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 9 "Visibility" "Boolean" "TRUE" 2 417 71 442 71 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 11 "Visibility" "Boolean" "TRUE" 2 572 71 648 71 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 12 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 647 61 20 20 NULL    REF 22 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 14 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 649 46 "p3" "Helvetica" 1 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator -1 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 46 2 494 172 466 198 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 44 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 479 157 "Working" "Helvetica" 1 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 55 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 456 198 "*" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 48 2 319 172 339 198 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 41 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 290 157 "Working" "Helvetica" 1 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 49 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 341 198 "+" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 54 2 353 205 451 205 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 37  
            CH.ifa.draw.standard.ChopBoxConnector REF 31   
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 57 2 353 208 393 219 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 37  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 58 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 398 215 "T" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63 3 502 172 502 208 467 234 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 29  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 47 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 455 233 "+" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 65 2 450 237 410 225 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 51  
            CH.ifa.draw.standard.ChopBoxConnector REF 46   
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 67 2 450 240 352 240 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 51  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 68 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 342 233 "*" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 70 3 313 172 313 210 337 233 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 35  
            CH.ifa.draw.standard.ChopBoxConnector REF 60   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 6 "Visibility" "Boolean" "TRUE" 3 404 80 389 114 395 146 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 9   REF 60 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 56 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 400 197 "tl" "Helvetica" 0 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 69 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 402 231 "tl" "Helvetica" 0 12 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator 4 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 51 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 60 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 451 175 "remains" "Helvetica" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator -6 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 66 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 433 220 "hd" "Helvetica" 0 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator 10 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 59 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 357 212 "hd" "Helvetica" 0 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator -9 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 46 REF 29 REF 35 
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 76 2 308 56 278 78 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 75 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 295 41 "Working" "Helvetica" 1 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 77 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 268 77 "*" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 79 2 321 56 337 95 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 87  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 80 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 333 95 "<>" "Helvetica" 1 12 0 NULL NULL    REF 89
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 2 "Visibility" "Boolean" "TRUE" 2 183 71 246 71 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   REF 94 
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 82 2 502 56 476 95 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 88 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 484 41 "Working" "Helvetica" 1 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 86 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 464 95 "<>" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 84 2 511 56 526 84 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 102  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 85 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 528 84 "*" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 83 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 463 72 "remains" "Helvetica" 0 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator -3 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 104 
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 96 2 53 55 72 55 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 95 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 41 48 "+" "Helvetica" 1 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 97 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 77 48 "+" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 98 2 89 55 108 55 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 118  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 99 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 113 48 "+" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 102 2 44 63 44 87 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 116  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 103 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 41 87 "A" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 105 2 80 63 80 87 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 118  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 106 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 76 87 "B" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 107 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 73 64 "hd" "Helvetica" 0 12 0 REF 129 
            CH.ifa.draw.standard.OffsetLocator 0 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 108 2 116 63 116 87 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 123  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 109 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 112 87 "C" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 111 2 125 55 144 55 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 123  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 112 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 149 48 "<>" "Helvetica" 1 12 0 NULL NULL    REF 133 REF 128
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 100 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 57 46 "tl" "Helvetica" 0 12 0 REF 113 
            CH.ifa.draw.standard.OffsetLocator -2 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 113 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 93 48 "tl" "Helvetica" 0 12 0 REF 119 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 115 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 129 49 "tl" "Helvetica" 0 12 0 REF 142 
            CH.ifa.draw.standard.OffsetLocator -2 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 141 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 110 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 110 64 "hd" "Helvetica" 0 12 0 REF 137 
            CH.ifa.draw.standard.OffsetLocator 1 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 116 2 95 114 95 145 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 93 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 85 145 "List" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 120 2 657 81 657 105 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 22  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 89 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 647 105 "List" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 121 2 408 62 408 47 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 92 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 385 32 "Working" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 122 2 22 49 36 52 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 116   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 13 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 502 17 "t3" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 -47 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 28 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 306 16 "t1" "Helvetica" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 0 -48 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 78 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 267 55 "remains" "Helvetica" 0 12 0 REF 84 
            CH.ifa.draw.standard.OffsetLocator -3 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 81 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 301 71 "backwards" "Helvetica" 0 12 0 REF 90 
            CH.ifa.draw.standard.OffsetLocator 2 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 123 2 318 31 318 41 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 4 "FigureWithID" "Int" 124 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 "Visibility" "Boolean" "FALSE" 308 16 "root" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.figures.ShortestDistanceConnector REF 87   REF 87 
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 128 2 507 31 507 41 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 4 "FigureWithID" "Int" 125 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 "Visibility" "Boolean" "FALSE" 497 16 "root" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.figures.ShortestDistanceConnector REF 102   REF 198 
        de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 4 "FigureWithID" "Int" 129 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 "Visibility" "Boolean" "FALSE" 405 132 "root" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 130 2 412 147 412 157 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector REF 200  
            CH.ifa.draw.figures.ShortestDistanceConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 131 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 395 157 "Rule" "Helvetica" 1 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 132 2 390 164 343 164 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector REF 205  
            CH.ifa.draw.figures.ShortestDistanceConnector REF 35   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 133 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 361 157 "in" "Helvetica" 0 12 0 REF 206 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 205 
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 134 2 425 164 474 164 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector REF 205  
            CH.ifa.draw.figures.ShortestDistanceConnector REF 29   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 135 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 441 157 "out" "Helvetica" 0 12 0 REF 213 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 173 REF 163 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 140 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 188 64 "remains" "Helvetica" 0 12 0 REF 95 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 141 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 576 64 "backwards" "Helvetica" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator -4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 139 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 415 108 "out" "Helvetica" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 5 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 137 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 386 108 "in" "Helvetica" 0 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator -5 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 193 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 104 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 37 64 "hd" "Helvetica" 0 12 0 REF 124 
            CH.ifa.draw.standard.OffsetLocator 0 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 102 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 30 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 251 193 "t2" "Helvetica" 1 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -151 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 36 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 416 50 "p2" "Helvetica" 1 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 16 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 31 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 71 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 271 203 "backwards" "Helvetica" 0 12 0 REF 61 
            CH.ifa.draw.standard.OffsetLocator -24 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 64 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 483 203 "backwards" "Helvetica" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 29 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 146 REF 118 REF 123 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 50 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 316 173 "remains" "Helvetica" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 10 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 109 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 87 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 504 59 "backwards" "Helvetica" 0 12 0 REF 105 
            CH.ifa.draw.standard.OffsetLocator 16 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 23 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 88 11 "p1" "Helvetica" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 0 -53 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 116 REF 37 REF 168 NULL  5 153 702 305 
