3 
    de.renew.gui.CPNDrawing 193 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 444 90 24 16  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 483 122 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 98 472 23 24 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 116 476 191 390 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 182 374 33 16    REF 8 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 207 390 288 464 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 8  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 284 460 20 20 NULL    REF 13 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "Visibility" "Boolean" "TRUE" 2 294 480 294 544 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 13  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 280 544 29 15    REF 18 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "Visibility" "Boolean" "TRUE" 2 294 559 294 625 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 18  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 200 0 "Visibility" "Boolean" "TRUE" 282 624 25 20 NULL    REF 23 
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 97 626 25 25 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 109 627 109 573 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 100 557 20 16    REF 29 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 109 557 109 496 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 29  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 693 371 63 20 NULL  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "Visibility" "Boolean" "TRUE" 2 215 381 694 381 NULL 
            de.renew.gui.DoubleArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 8  
            CH.ifa.draw.figures.ChopEllipseConnector REF 34   
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 218 192 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 740 609 55 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 3 762 610 651 441 215 384 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 40  
            CH.ifa.draw.standard.ChopBoxConnector REF 8   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 198 542 198 390 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 188 541 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 8   
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 385 541 49 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 "Visibility" "Boolean" "TRUE" 531 480 27 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 557 490 629 490 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 50  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 255 0 0 "Visibility" "Boolean" "TRUE" 629 483 20 16    REF 55 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 645 499 692 554 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 55  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 "Visibility" "Boolean" "TRUE" 687 551 20 20 NULL    REF 60 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 692 569 652 613 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 60  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 255 0 0 "Visibility" "Boolean" "TRUE" 634 613 24 16    REF 65 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 634 621 549 621 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 65  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 "Visibility" "Boolean" "TRUE" 529 611 20 20 NULL    REF 70 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 534 614 493 560 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 70  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 255 0 0 "Visibility" "Boolean" "TRUE" 476 544 24 16    REF 75 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 495 544 538 498 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 75  
            CH.ifa.draw.figures.ChopEllipseConnector REF 50   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 632 499 594 544 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 55  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 578 541 20 20 NULL    REF 84 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 579 551 500 551 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 84  
            CH.ifa.draw.standard.ChopBoxConnector REF 75   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 3 428 546 451 538 476 547 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 49  
            CH.ifa.draw.standard.ChopBoxConnector REF 75   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 636 483 "e" "Helvetica" 1 12 0 REF 55 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 563 559 "message" "Helvetica" 1 12 0 REF 84 
            CH.ifa.draw.standard.OffsetLocator 1 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 650 541 "first\ntime" "Helvetica" 1 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator -35 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 644 613 "f" "Helvetica" 1 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 485 544 "g" "Helvetica" 1 12 0 REF 75 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 3 476 555 453 561 430 556 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 75  
            CH.ifa.draw.figures.ChopEllipseConnector REF 49   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 583 483 "[x,y]" "Helvetica" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 658 519 "[x,y]" "Helvetica" 0 12 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 662 584 "[x,y]" "Helvetica" 0 12 0 REF 61 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 503 580 "[x,y]" "Helvetica" 0 12 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 705 354 "demanded" "Helvetica" 1 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator 11 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 718 391 645 483 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 34  
            CH.ifa.draw.standard.ChopBoxConnector REF 55   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 603 514 "[y,x]" "Helvetica" 0 12 0 REF 80 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 658 620 741 619 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 65  
            CH.ifa.draw.figures.ChopEllipseConnector REF 40   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 689 612 "[x,y]" "Helvetica" 0 12 0 REF 134 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 852 611 22 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 730 391 858 611 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 34  
            CH.ifa.draw.standard.ChopBoxConnector REF 141   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 784 494 "[x,y]" "Helvetica" 0 12 0 REF 142 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 776 707 32 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 777 743 "after use" "Helvetica" 1 12 0 REF 149 
            CH.ifa.draw.standard.OffsetLocator 10 34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 799 709 857 627 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 149  
            CH.ifa.draw.standard.ChopBoxConnector REF 141   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 782 711 658 628 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 149  
            CH.ifa.draw.standard.ChopBoxConnector REF 65   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 818 661 "[x,y]" "Helvetica" 0 12 0 REF 153 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 4 638 629 618 652 455 652 413 561 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 65  
            CH.ifa.draw.figures.ChopEllipseConnector REF 49   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 465 653 "[x,y]" "Helvetica" 0 12 0 REF 164 
            CH.ifa.draw.standard.OffsetLocator -50 54 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 852 619 794 619 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 141  
            CH.ifa.draw.figures.ChopEllipseConnector REF 40   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 581 614 "[x,y]" "Helvetica" 0 12 0 REF 66 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 813 612 "[x,y]" "Helvetica" 0 12 0 REF 171 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 4 852 624 711 690 422 690 410 561 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 141  
            CH.ifa.draw.figures.ChopEllipseConnector REF 49   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 574 677 "[x,y]" "Helvetica" 0 12 0 REF 181 
            CH.ifa.draw.standard.OffsetLocator -47 59 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 529 544 "[x,y]" "Helvetica" 0 12 0 REF 85 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 487 126 464 106 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 511 88 24 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 516 104 499 125 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 195  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 528 517 "[x,y]" "Helvetica" 0 12 0 REF 76 
            CH.ifa.draw.standard.OffsetLocator 22 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 187 710 24 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 287 641 208 710 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 23  
            CH.ifa.draw.standard.ChopBoxConnector REF 203   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 190 710 118 646 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 203  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 244 668 "x" "Helvetica" 0 12 0 REF 204 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 151 671 "x" "Helvetica" 0 12 0 REF 208 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 211 717 777 717 NULL 
            de.renew.gui.DoubleArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 203  
            CH.ifa.draw.figures.ChopEllipseConnector REF 149   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 198 561 198 710 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 47  
            CH.ifa.draw.standard.ChopBoxConnector REF 203   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 129 476 "pend1" "Helvetica" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 37 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 317 451 "pend2" "Helvetica" 1 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 40 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 304 642 "critical" "Helvetica" 1 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 29 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 126 616 "quiet" "Helvetica" 1 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 31 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 442 518 "[x,y]" "Helvetica" 0 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator 0 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 447 569 "[y,x]" "Helvetica" 0 12 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator 4 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 760 242 232 50  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 128 559 "reaktiv" "Helvetica" 2 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 479 524 "fair" "Helvetica" 2 12 0 REF 75 
            CH.ifa.draw.standard.OffsetLocator -1 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 107 557 "a" "Helvetica" 1 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 196 710 "d" "Helvetica" 1 12 0 REF 203 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 860 611 "h" "Helvetica" 1 12 0 REF 141 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 795 253 "r(x) = {x} x N(x)" "Helvetica" 0 24 0 REF 243 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 586 251 558 301 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 580 232 20 20 NULL REF 2   
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 543 299 20 20 NULL 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 625 122 20 20 NULL     
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 563 309 622 309 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 264  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 621 299 20 20 NULL 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 771 121 20 20 NULL     
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 595 251 627 301 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 262  
            CH.ifa.draw.figures.ChopEllipseConnector REF 269   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 140 423 "x" "Helvetica" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -10 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 431 487 "this:hide(x,y);\nthis:show(y,x)" "Helvetica" 0 12 0 REF 75 
            CH.ifa.draw.standard.OffsetLocator -20 -50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DoubleArcConnection "no_attributes" 2 386 551 309 551 NULL 
            de.renew.gui.DoubleArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 49  
            CH.ifa.draw.standard.ChopBoxConnector REF 18   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 209 627 "t" "Helvetica" 0 12 0 REF 222 
            CH.ifa.draw.standard.OffsetLocator 12 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 2 208 551 280 551 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 47  
            CH.ifa.draw.standard.ChopBoxConnector REF 18   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 249 538 "t" "Helvetica" 0 12 0 REF 287 
            CH.ifa.draw.standard.OffsetLocator 6 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 686 406 "[x,y]" "Helvetica" 0 12 0 REF 127 
            CH.ifa.draw.standard.OffsetLocator 15 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 257 416 "x" "Helvetica" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 13 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 283 507 "x" "Helvetica" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator -8 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 245 189 "P" "Helvetica" 1 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 21 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 109 190 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 116 193 "[]" "Helvetica" 0 12 0 REF 305 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 2 119 210 119 248 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 305  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 107 248 24 16    REF 313 
        de.renew.gui.ArcConnection "no_attributes" 2 220 206 131 250 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 39  
            CH.ifa.draw.standard.ChopBoxConnector REF 313   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 169 212 "p" "Helvetica" 0 12 0 REF 314 
            CH.ifa.draw.standard.OffsetLocator -3 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 2 121 264 196 542 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 313  
            CH.ifa.draw.figures.ChopEllipseConnector REF 47   REF 47 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 424 723 "t.r(x)" "Helvetica" 0 12 0 REF 218 
            CH.ifa.draw.standard.OffsetLocator -58 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 420 392 "t.r(x)" "Helvetica" 0 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator -56 -98 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 340 529 "t.r(x)" "Helvetica" 0 12 0 REF 280 
            CH.ifa.draw.standard.OffsetLocator 5 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 205 125 "import samples.reisig.*;" "Helvetica" 0 12 0 NULL NULL 1  
        de.renew.gui.DoubleArcConnection "no_attributes" 2 131 255 367 236 NULL 
            de.renew.gui.DoubleArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 313  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 366 225 27 20 NULL REF 50    
        de.renew.gui.DoubleArcConnection "no_attributes" 2 131 256 353 262 NULL 
            de.renew.gui.DoubleArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 313  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 352 252 55 20 NULL REF 40    
        de.renew.gui.DoubleArcConnection "no_attributes" 2 131 258 356 298 NULL 
            de.renew.gui.DoubleArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 313  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 355 289 20 20 NULL REF 70    
        de.renew.gui.DoubleArcConnection "no_attributes" 2 131 261 222 302 NULL 
            de.renew.gui.DoubleArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 313  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 213 298 49 20 NULL REF 49    REF 339 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 508 460 "missing" "Helvetica" 1 12 0 REF 50 
            CH.ifa.draw.standard.OffsetLocator -14 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 395 218 "missing" "Helvetica" 1 12 0 REF 339 
            CH.ifa.draw.standard.OffsetLocator 38 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 344 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 761 634 "ready" "Helvetica" 1 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 10 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 409 246 "ready" "Helvetica" 1 12 0 REF 344 
            CH.ifa.draw.standard.OffsetLocator 46 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 40 148 "pi=new InverseTopology(p)" "Helvetica" 0 12 0 REF 313 
            CH.ifa.draw.standard.OffsetLocator -5 -101 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 45 166 "t=new UnionTopology(p,pi)" "Helvetica" 0 12 0 REF 313 
            CH.ifa.draw.standard.OffsetLocator 0 -83 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 207 557 "this:showall(x,\n  t.neighbors(x))" "Helvetica" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator -45 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 300 585 "x" "Helvetica" 0 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator 9 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 860 630 "this:show(x,y)" "Helvetica" 0 12 0 REF 141 
            CH.ifa.draw.standard.OffsetLocator 34 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 349 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 509 633 "repeated" "Helvetica" 1 12 0 REF 70 
            CH.ifa.draw.standard.OffsetLocator -5 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 382 290 "repeated" "Helvetica" 1 12 0 REF 349 
            CH.ifa.draw.standard.OffsetLocator 42 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 285 235 "pi.all()" "Helvetica" 0 12 0 REF 335 
            CH.ifa.draw.standard.OffsetLocator 53 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 257 277 "p.all()" "Helvetica" 0 12 0 REF 345 
            CH.ifa.draw.standard.OffsetLocator 29 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 264 253 "t.all()" "Helvetica" 0 12 0 REF 340 
            CH.ifa.draw.standard.OffsetLocator 35 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 213 171 "new TupleTopology([[1,2],[2],[]])" "Helvetica" 0 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 70 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 143 384 "t" "Helvetica" 0 12 0 REF 321 
            CH.ifa.draw.standard.OffsetLocator -14 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 354 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 173 278 "p.all()" "Helvetica" 0 12 0 REF 350 
            CH.ifa.draw.standard.OffsetLocator 12 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 352 565 "available" "Helvetica" 1 12 0 REF 49 
            CH.ifa.draw.standard.OffsetLocator -32 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 247 314 "available" "Helvetica" 1 12 0 REF 354 
            CH.ifa.draw.standard.OffsetLocator 35 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 405 362 "t.r(x)" "Helvetica" 0 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator -37 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FillColor" "Color" 235 199 158 481 165 24 16  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 1 "FillColor" "Color" 235 199 158 2 493 165 493 142 NULL 
            de.renew.gui.DoubleArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 415  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 478 103 "x" "Helvetica" 0 12 0 REF 191 
            CH.ifa.draw.standard.OffsetLocator 6 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 498 104 "x" "Helvetica" 0 12 0 REF 196 
            CH.ifa.draw.standard.OffsetLocator -6 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 715 647 "[x,y]" "Helvetica" 0 12 0 REF 157 
            CH.ifa.draw.standard.OffsetLocator 5 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 568 591 "this:show(x,y)" "Helvetica" 0 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator -41 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 426 74 ":hide(0,x)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -5 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 501 72 ":show(0,x)" "Helvetica" 0 12 0 REF 195 
            CH.ifa.draw.standard.OffsetLocator 6 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 501 145 "x" "Helvetica" 0 12 0 REF 416 
            CH.ifa.draw.standard.OffsetLocator 11 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 465 186 ":showall(0,x)" "Helvetica" 0 12 0 REF 415 
            CH.ifa.draw.standard.OffsetLocator 6 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 586 90 24 16  REF 265 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 629 126 606 106 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 265  
            CH.ifa.draw.standard.ChopBoxConnector REF 444   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 653 88 24 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 658 104 641 125 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 449  
            CH.ifa.draw.figures.ChopEllipseConnector REF 265   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FillColor" "Color" 235 199 158 623 165 24 16  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 1 "FillColor" "Color" 235 199 158 2 635 165 635 142 NULL 
            de.renew.gui.DoubleArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 454  
            CH.ifa.draw.figures.ChopEllipseConnector REF 265   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 620 100 "x" "Helvetica" 0 12 0 REF 445 
            CH.ifa.draw.standard.OffsetLocator 6 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 640 101 "x" "Helvetica" 0 12 0 REF 450 
            CH.ifa.draw.standard.OffsetLocator -6 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 643 69 ":show(1,x)" "Helvetica" 0 12 0 REF 449 
            CH.ifa.draw.standard.OffsetLocator 6 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 643 142 "x" "Helvetica" 0 12 0 REF 455 
            CH.ifa.draw.standard.OffsetLocator 11 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 607 183 ":showall(1,x)" "Helvetica" 0 12 0 REF 454 
            CH.ifa.draw.standard.OffsetLocator 6 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 732 89 24 16  REF 270 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 775 125 752 105 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 270  
            CH.ifa.draw.standard.ChopBoxConnector REF 474   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 799 87 24 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 804 103 787 124 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 479  
            CH.ifa.draw.figures.ChopEllipseConnector REF 270   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FillColor" "Color" 235 199 158 769 164 24 16  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 1 "FillColor" "Color" 235 199 158 2 781 164 781 141 NULL 
            de.renew.gui.DoubleArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 484  
            CH.ifa.draw.figures.ChopEllipseConnector REF 270   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 766 99 "x" "Helvetica" 0 12 0 REF 475 
            CH.ifa.draw.standard.OffsetLocator 6 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 786 100 "x" "Helvetica" 0 12 0 REF 480 
            CH.ifa.draw.standard.OffsetLocator -6 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 714 70 ":hide(2,x)" "Helvetica" 0 12 0 REF 474 
            CH.ifa.draw.standard.OffsetLocator -5 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 789 68 ":show(2,x)" "Helvetica" 0 12 0 REF 479 
            CH.ifa.draw.standard.OffsetLocator 6 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 789 141 "x" "Helvetica" 0 12 0 REF 485 
            CH.ifa.draw.standard.OffsetLocator 11 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 753 182 ":showall(2,x)" "Helvetica" 0 12 0 REF 484 
            CH.ifa.draw.standard.OffsetLocator 6 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 568 71 ":hide(1,x)" "Helvetica" 0 12 0 REF 444 
            CH.ifa.draw.standard.OffsetLocator -5 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 262 REF 264 REF 269 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 525 318 "Knoten 1" "Helvetica" 1 12 0 REF 264 
            CH.ifa.draw.standard.OffsetLocator -3 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 607 319 "Knoten 2" "Helvetica" 1 12 0 REF 269 
            CH.ifa.draw.standard.OffsetLocator 1 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 567 215 "Knoten 0" "Helvetica" 1 12 0 REF 262 
            CH.ifa.draw.standard.OffsetLocator 2 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 206 468 "t" "Helvetica" 0 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator 9 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 102 593 "x" "Helvetica" 0 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator -4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 100 521 "x" "Helvetica" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator -6 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DoubleArcConnection "no_attributes" 3 117 264 57 596 101 631 NULL 
            de.renew.gui.DoubleArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 313  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 63 393 "t.nodes()" "Helvetica" 0 12 0 REF 528 
            CH.ifa.draw.standard.OffsetLocator 0 -47 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  