5 
    de.renew.gui.CPNDrawing 189 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 444 90 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 2 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 483 122 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 98 472 23 24 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 4 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 116 476 191 390 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 182 374 33 16 NULL    REF 8 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 6 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 207 390 288 464 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 8  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 7 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 284 460 20 20 NULL    REF 13 
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 8 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "Visibility" "Boolean" "TRUE" 2 294 480 294 544 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 13  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 280 544 29 15 NULL    REF 18 
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 10 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "Visibility" "Boolean" "TRUE" 2 294 559 294 625 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 18  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 11 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 200 0 "Visibility" "Boolean" "TRUE" 282 624 25 20 NULL    REF 23 
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 12 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 97 626 25 25 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 13 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 109 627 109 573 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 14 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 100 557 20 16 NULL    REF 29 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 15 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 109 557 109 496 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 29  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 16 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 693 371 63 20 NULL  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 17 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "Visibility" "Boolean" "TRUE" 2 215 381 694 381 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 8  
            CH.ifa.draw.figures.ChopEllipseConnector REF 34   
        de.renew.gui.PlaceFigure "attributes" "attributes" 6 "FigureWithID" "Int" 18 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 218 192 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 19 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 740 609 55 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 20 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 2 198 542 198 390 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 111 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 188 541 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 8   
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 21 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 385 541 49 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 22 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 "Visibility" "Boolean" "TRUE" 531 480 27 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 23 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 557 490 629 490 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 46  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 24 "MarkingAppearance" "Int" 2 "FillColor" "Color" 255 0 0 "Visibility" "Boolean" "TRUE" 629 483 20 16 NULL    REF 51 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 25 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 645 499 692 554 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 51  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 26 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 "Visibility" "Boolean" "TRUE" 687 551 20 20 NULL    REF 56 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 27 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 692 569 652 613 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 56  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 28 "MarkingAppearance" "Int" 2 "FillColor" "Color" 255 0 0 "Visibility" "Boolean" "TRUE" 634 613 24 16 NULL    REF 61 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 29 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 634 621 549 621 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 61  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 30 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 "Visibility" "Boolean" "TRUE" 529 611 20 20 NULL    REF 66 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 31 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 534 614 493 560 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 66  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 32 "MarkingAppearance" "Int" 2 "FillColor" "Color" 255 0 0 "Visibility" "Boolean" "TRUE" 476 544 24 16 NULL    REF 71 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 33 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 495 544 538 498 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 71  
            CH.ifa.draw.figures.ChopEllipseConnector REF 46   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 34 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 632 499 594 544 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 51  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 35 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 578 541 20 20 NULL    REF 80 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 36 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 579 551 500 551 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 80  
            CH.ifa.draw.standard.ChopBoxConnector REF 71   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 37 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 3 428 546 451 538 476 547 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 45  
            CH.ifa.draw.standard.ChopBoxConnector REF 71   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 38 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 636 483 "e" "Helvetica" 1 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 39 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 563 559 "message" "Helvetica" 1 12 0 REF 80 
            CH.ifa.draw.standard.OffsetLocator 1 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 40 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 644 613 "f" "Helvetica" 1 12 0 REF 61 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 41 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 485 544 "g" "Helvetica" 1 12 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 42 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 3 476 555 453 561 430 556 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 71  
            CH.ifa.draw.figures.ChopEllipseConnector REF 45   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 43 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 583 483 "[x,y]" "Helvetica" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 44 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 658 519 "[x,y]" "Helvetica" 0 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 45 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 662 584 "[x,y]" "Helvetica" 0 12 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 46 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 503 580 "[x,y]" "Helvetica" 0 12 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 47 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 705 354 "demanded" "Helvetica" 1 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator 11 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 48 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 718 391 645 483 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 34  
            CH.ifa.draw.standard.ChopBoxConnector REF 51   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 49 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 603 514 "[y,x]" "Helvetica" 0 12 0 REF 76 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 50 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 658 620 741 619 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 61  
            CH.ifa.draw.figures.ChopEllipseConnector REF 40   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 51 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 689 612 "[x,y]" "Helvetica" 0 12 0 REF 127 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 852 611 22 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 53 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 730 391 858 611 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 34  
            CH.ifa.draw.standard.ChopBoxConnector REF 134   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 54 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 784 494 "[x,y]" "Helvetica" 0 12 0 REF 135 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 55 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 776 707 32 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 56 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 799 709 857 627 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 142  
            CH.ifa.draw.standard.ChopBoxConnector REF 134   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 57 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 782 711 658 628 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 142  
            CH.ifa.draw.standard.ChopBoxConnector REF 61   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 58 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 818 661 "[x,y]" "Helvetica" 0 12 0 REF 143 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 59 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 4 638 629 618 652 455 652 413 561 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 61  
            CH.ifa.draw.figures.ChopEllipseConnector REF 45   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 60 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 465 653 "[x,y]" "Helvetica" 0 12 0 REF 154 
            CH.ifa.draw.standard.OffsetLocator -50 54 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 61 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 852 619 794 619 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 134  
            CH.ifa.draw.figures.ChopEllipseConnector REF 40   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 62 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 581 614 "[x,y]" "Helvetica" 0 12 0 REF 62 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 63 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 813 612 "[x,y]" "Helvetica" 0 12 0 REF 161 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 64 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 4 852 624 711 690 422 690 410 561 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 134  
            CH.ifa.draw.figures.ChopEllipseConnector REF 45   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 65 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 574 677 "[x,y]" "Helvetica" 0 12 0 REF 171 
            CH.ifa.draw.standard.OffsetLocator -47 59 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 66 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 529 544 "[x,y]" "Helvetica" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 67 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 487 126 464 106 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 68 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 511 88 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 69 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 516 104 499 125 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 185  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 70 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 528 517 "[x,y]" "Helvetica" 0 12 0 REF 72 
            CH.ifa.draw.standard.OffsetLocator 22 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 71 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 187 710 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 72 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 287 641 208 710 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 23  
            CH.ifa.draw.standard.ChopBoxConnector REF 193   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 73 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 190 710 118 646 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 193  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 74 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 244 668 "x" "Helvetica" 0 12 0 REF 194 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 75 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 151 671 "x" "Helvetica" 0 12 0 REF 198 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 76 "MarkingAppearance" "Int" 2 "Visibility" "Boolean" "TRUE" 2 211 717 777 717 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 193  
            CH.ifa.draw.figures.ChopEllipseConnector REF 142   
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 77 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 112 219 147 "Visibility" "Boolean" "TRUE" 2 198 561 198 710 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 43  
            CH.ifa.draw.standard.ChopBoxConnector REF 193   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 78 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 129 476 "pend1" "Helvetica" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 37 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 79 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 317 451 "pend2" "Helvetica" 1 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 40 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 80 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 304 642 "critical" "Helvetica" 1 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 29 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 81 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 126 616 "quiet" "Helvetica" 1 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 31 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 82 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 442 518 "[x,y]" "Helvetica" 0 12 0 REF 85 
            CH.ifa.draw.standard.OffsetLocator 0 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 83 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 447 569 "[y,x]" "Helvetica" 0 12 0 REF 101 
            CH.ifa.draw.standard.OffsetLocator 4 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 84 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 670 244 232 50  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 85 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 128 559 "reaktiv" "Helvetica" 2 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 86 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 479 524 "fair" "Helvetica" 2 12 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator -1 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 87 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 107 557 "a" "Helvetica" 1 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 88 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 196 710 "d" "Helvetica" 1 12 0 REF 193 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 89 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 860 611 "h" "Helvetica" 1 12 0 REF 134 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 90 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 705 255 "r(x) = {x} x N(x)" "Helvetica" 0 24 0 REF 233 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 5 "FigureWithID" "Int" 91 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 586 251 558 301 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 159 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 580 232 20 20 NULL REF 2   
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 160 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 543 299 20 20 NULL 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 142 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 625 122 20 20 NULL     
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 5 "FigureWithID" "Int" 92 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 563 309 622 309 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 254  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 161 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 621 299 20 20 NULL 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 150 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 771 121 20 20 NULL     
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 4 "FigureWithID" "Int" 93 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 595 251 627 301 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 252  
            CH.ifa.draw.figures.ChopEllipseConnector REF 259   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 94 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 140 423 "x" "Helvetica" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -10 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FigureWithID" "Int" 95 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 431 487 "this:hide(x,y);\nthis:show(y,x)" "Helvetica" 0 12 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator -20 -50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 96 2 386 551 309 551 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 45  
            CH.ifa.draw.standard.ChopBoxConnector REF 18   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FigureWithID" "Int" 97 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 209 627 "t" "Helvetica" 0 12 0 REF 212 
            CH.ifa.draw.standard.OffsetLocator 12 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 98 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 112 219 147 2 208 551 280 551 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 43  
            CH.ifa.draw.standard.ChopBoxConnector REF 18   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 99 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 249 538 "t" "Helvetica" 0 12 0 REF 277 
            CH.ifa.draw.standard.OffsetLocator 6 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 100 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 686 406 "[x,y]" "Helvetica" 0 12 0 REF 120 
            CH.ifa.draw.standard.OffsetLocator 15 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 101 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 257 416 "x" "Helvetica" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 13 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 102 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 283 507 "x" "Helvetica" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator -8 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 103 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 245 189 "P" "Helvetica" 1 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 21 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 6 "FigureWithID" "Int" 104 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 109 190 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 105 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 116 193 "[]" "Helvetica" 0 12 0 REF 295 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 106 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 2 119 210 119 248 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 295  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 107 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 107 248 24 16 NULL    REF 303 
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 108 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 2 220 206 131 250 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 39  
            CH.ifa.draw.standard.ChopBoxConnector REF 303   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 109 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 169 212 "p" "Helvetica" 0 12 0 REF 304 
            CH.ifa.draw.standard.OffsetLocator -3 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 110 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 2 121 264 196 542 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 303  
            CH.ifa.draw.figures.ChopEllipseConnector REF 43   REF 43 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FigureWithID" "Int" 112 "MarkingAppearance" "Int" 2 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 424 723 "t.r(x)" "Helvetica" 0 12 0 REF 208 
            CH.ifa.draw.standard.OffsetLocator -58 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FigureWithID" "Int" 113 "MarkingAppearance" "Int" 2 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 340 529 "t.r(x)" "Helvetica" 0 12 0 REF 270 
            CH.ifa.draw.standard.OffsetLocator 5 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 114 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 2 131 255 367 236 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 303  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 118 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 366 225 27 20 NULL REF 46    
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 115 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 2 131 256 353 262 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 303  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 121 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 352 252 55 20 NULL REF 40    
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 116 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 2 131 257 364 295 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 303  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 173 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 363 286 32 20 NULL REF 142    
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 117 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 2 131 259 366 330 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 303  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 176 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 365 322 20 20 NULL REF 56    REF 325 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 119 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 508 460 "missing" "Helvetica" 1 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator -14 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FigureWithID" "Int" 120 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 395 218 "missing" "Helvetica" 1 12 0 REF 325 
            CH.ifa.draw.standard.OffsetLocator 38 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 330 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 122 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 761 634 "ready" "Helvetica" 1 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 10 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FigureWithID" "Int" 123 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 409 246 "ready" "Helvetica" 1 12 0 REF 330 
            CH.ifa.draw.standard.OffsetLocator 46 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 124 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 40 148 "pi=new InverseTopology(p)" "Helvetica" 0 12 0 REF 303 
            CH.ifa.draw.standard.OffsetLocator -5 -101 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 125 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 45 166 "t=new UnionTopology(p,pi)" "Helvetica" 0 12 0 REF 303 
            CH.ifa.draw.standard.OffsetLocator 0 -83 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 126 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 300 585 "x" "Helvetica" 0 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator 9 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 127 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 509 633 "repeated" "Helvetica" 1 12 0 REF 66 
            CH.ifa.draw.standard.OffsetLocator -5 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 128 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 285 235 "pi.all()" "Helvetica" 0 12 0 REF 321 
            CH.ifa.draw.standard.OffsetLocator 53 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 129 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 261 275 "p.all()" "Helvetica" 0 12 0 REF 331 
            CH.ifa.draw.standard.OffsetLocator 29 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 130 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 260 253 "pi.all()" "Helvetica" 0 12 0 REF 326 
            CH.ifa.draw.standard.OffsetLocator 35 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FigureWithID" "Int" 131 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 213 171 "new TupleTopology([[1,2],[2],[]])" "Helvetica" 0 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 70 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 132 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 143 384 "t" "Helvetica" 0 12 0 REF 311 
            CH.ifa.draw.standard.OffsetLocator -14 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 133 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 245 291 "p.all()" "Helvetica" 0 12 0 REF 336 
            CH.ifa.draw.standard.OffsetLocator 12 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 134 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 352 565 "available" "Helvetica" 1 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator -32 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FigureWithID" "Int" 135 "MarkingAppearance" "Int" 2 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 405 362 "t.r(x)" "Helvetica" 0 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator -37 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 136 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 478 103 "x" "Helvetica" 0 12 0 REF 181 
            CH.ifa.draw.standard.OffsetLocator 6 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 137 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 498 104 "x" "Helvetica" 0 12 0 REF 186 
            CH.ifa.draw.standard.OffsetLocator -6 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 138 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 715 647 "[x,y]" "Helvetica" 0 12 0 REF 147 
            CH.ifa.draw.standard.OffsetLocator 5 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 139 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 426 74 ":hide(0,x)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -5 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 140 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 501 72 ":show(0,x)" "Helvetica" 0 12 0 REF 185 
            CH.ifa.draw.standard.OffsetLocator 6 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 141 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 586 90 24 16 NULL  REF 255 
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 143 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 629 126 606 106 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 255  
            CH.ifa.draw.standard.ChopBoxConnector REF 404   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 144 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 653 88 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 145 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 658 104 641 125 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 409  
            CH.ifa.draw.figures.ChopEllipseConnector REF 255   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 146 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 620 100 "x" "Helvetica" 0 12 0 REF 405 
            CH.ifa.draw.standard.OffsetLocator 6 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 147 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 640 101 "x" "Helvetica" 0 12 0 REF 410 
            CH.ifa.draw.standard.OffsetLocator -6 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 148 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 643 69 ":show(1,x)" "Helvetica" 0 12 0 REF 409 
            CH.ifa.draw.standard.OffsetLocator 6 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 149 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 732 89 24 16 NULL  REF 260 
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 151 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 775 125 752 105 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 260  
            CH.ifa.draw.standard.ChopBoxConnector REF 423   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 152 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 799 87 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 153 "MarkingAppearance" "Int" 2 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 2 804 103 787 124 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 428  
            CH.ifa.draw.figures.ChopEllipseConnector REF 260   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 154 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 766 99 "x" "Helvetica" 0 12 0 REF 424 
            CH.ifa.draw.standard.OffsetLocator 6 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 155 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 786 100 "x" "Helvetica" 0 12 0 REF 429 
            CH.ifa.draw.standard.OffsetLocator -6 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 156 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 714 70 ":hide(2,x)" "Helvetica" 0 12 0 REF 423 
            CH.ifa.draw.standard.OffsetLocator -5 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 157 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 789 68 ":show(2,x)" "Helvetica" 0 12 0 REF 428 
            CH.ifa.draw.standard.OffsetLocator 6 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 158 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 568 71 ":hide(1,x)" "Helvetica" 0 12 0 REF 404 
            CH.ifa.draw.standard.OffsetLocator -5 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 252 REF 254 REF 259 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 162 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 525 318 "Knoten 1" "Helvetica" 1 12 0 REF 254 
            CH.ifa.draw.standard.OffsetLocator -3 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 163 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 607 319 "Knoten 2" "Helvetica" 1 12 0 REF 259 
            CH.ifa.draw.standard.OffsetLocator 1 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FigureWithID" "Int" 164 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 567 215 "Knoten 0" "Helvetica" 1 12 0 REF 252 
            CH.ifa.draw.standard.OffsetLocator 2 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 166 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 102 593 "x" "Helvetica" 0 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator -4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 167 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 100 521 "x" "Helvetica" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator -6 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 168 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 3 117 264 57 596 101 631 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 303  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 169 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 63 393 "t.nodes()" "Helvetica" 0 12 0 REF 463 
            CH.ifa.draw.standard.OffsetLocator 0 -47 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 170 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 186 336 20 20 NULL  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 171 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 2 125 264 190 339 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 303  
            CH.ifa.draw.figures.ChopEllipseConnector REF 470   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 172 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 159 315 "p.nodes()" "Helvetica" 0 12 0 REF 471 
            CH.ifa.draw.standard.OffsetLocator 28 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 335 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 174 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 777 743 "after use" "Helvetica" 1 12 0 REF 142 
            CH.ifa.draw.standard.OffsetLocator 10 34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FigureWithID" "Int" 175 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 399 285 "after use" "Helvetica" 1 12 0 REF 335 
            CH.ifa.draw.standard.OffsetLocator 45 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 340 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 177 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 650 541 "first\ntime" "Helvetica" 1 12 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator -35 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FigureWithID" "Int" 178 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 394 315 "first\ntime" "Helvetica" 1 12 0 
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 "Visibility" "Boolean" "TRUE" 687 551 20 20 NULL  
            CH.ifa.draw.standard.OffsetLocator -291 -230 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 179 3 762 610 643 431 215 383 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 40  
            CH.ifa.draw.standard.ChopBoxConnector REF 8   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FigureWithID" "Int" 180 "MarkingAppearance" "Int" 2 "TextColor" "Color" 0 0 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 420 391 "t.r(x)" "Helvetica" 0 12 0 REF 491 
            CH.ifa.draw.standard.OffsetLocator -56 -98 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 181 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 200 0 579 277 25 20 NULL REF 23  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 6 "FigureWithID" "Int" 182 "MarkingAppearance" "Int" 2 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 205 125 "import samples.reisig.*;" "Helvetica" 0 12 0 NULL NULL 1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 183 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 260 209 20 20 NULL  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 184 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 2 131 253 261 221 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 303  
            CH.ifa.draw.figures.ChopEllipseConnector REF 500   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 185 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 192 227 "p.all()" "Helvetica" 0 12 0 REF 501 
            CH.ifa.draw.standard.OffsetLocator 11 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 186 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 2 280 219 334 209 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 500  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 187 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 334 200 24 16 NULL    REF 512 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 188 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 295 197 "[x,y]" "Helvetica" 0 12 0 REF 508 
            CH.ifa.draw.standard.OffsetLocator -2 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 189 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 366 199 "this:show(x,y)" "Helvetica" 0 12 0 REF 512 
            CH.ifa.draw.standard.OffsetLocator 57 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 165 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 206 468 "t" "Helvetica" 0 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator 9 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  -10 102 960 836 