
    CH.ifa.draw.cpn.CPNDrawing 7 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 315 101 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 345 100 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 31 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 316 206 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 326 117 326 207 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 340 120 "[Verkäufer\n WARE: [StandardPKW\n                hersteller: [VW]\n                lackierung:[rot]]\n FARBE:[blau] ]" "Helvetica" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 79 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 3 316 117 269 153 320 210 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 176 116 "[FARBE:[rot]\n AUCH: [rot]]\n.equals( \n[FARBE:#1[rot]\n AUCH:#1])" "Helvetica" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator -78 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
