
    CH.ifa.draw.cpn.CPNDrawing 38 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 225 122 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 276 78 ":new(obj)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 64 -45 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 227 202 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 237 138 237 203 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 212 164 "obj" "Helvetica" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator -17 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 276 98 "obj:tail(tail)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 69 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 276 135 "guard head>tail" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 82 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 337 265 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 243 138 342 268 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 19   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 315 193 "[tail+1,head,max]" "Helvetica" 0 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 69 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 276 116 "obj:head(head)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 81 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 276 153 "obj:element(tail,max)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 96 30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 226 268 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 237 222 237 268 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 33   
        CH.ifa.draw.cpn.ArcConnection 2 338 275 250 275 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 19  
            CH.ifa.draw.standard.ChopBoxConnector REF 33   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 213 230 "obj" "Helvetica" 0 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator -16 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 241 253 "[curr,head,max]" "Helvetica" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator -11 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 455 268 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 357 275 455 275 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 19  
            CH.ifa.draw.standard.ChopBoxConnector REF 47   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 360 252 "[head,head,max]" "Helvetica" 0 12 0 REF 48 
            CH.ifa.draw.standard.OffsetLocator -1 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 228 416 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 398 349 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 437 285 ":result(max)" "Helvetica" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 2 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 238 284 238 417 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 33  
            CH.ifa.draw.figures.ChopEllipseConnector REF 55   
        CH.ifa.draw.cpn.ArcConnection 2 247 423 398 361 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 55  
            CH.ifa.draw.standard.ChopBoxConnector REF 56   
        CH.ifa.draw.cpn.ArcConnection 2 403 349 353 283 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 56  
            CH.ifa.draw.figures.ChopEllipseConnector REF 19   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 105 347 "[curr+1,head,max,elem]" "Helvetica" 0 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator -69 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 113 267 "obj:elem(curr,elem)" "Helvetica" 0 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator -72 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 432 350 "guard elem>max" "Helvetica" 0 12 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator 68 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 335 418 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 366 417 "guard elem<=max" "Helvetica" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 68 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 248 426 335 426 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 55  
            CH.ifa.draw.standard.ChopBoxConnector REF 81   
        CH.ifa.draw.cpn.ArcConnection 2 347 418 347 285 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 81  
            CH.ifa.draw.figures.ChopEllipseConnector REF 19   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 235 436 "[curr,head,max,elem]" "Helvetica" 0 12 0 REF 85 
            CH.ifa.draw.standard.OffsetLocator 1 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 267 362 "[curr,head,\n  max,elem]" "Helvetica" 0 12 0 REF 64 
            CH.ifa.draw.standard.OffsetLocator -24 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 350 386 "[curr,head,max]" "Helvetica" 0 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator 45 42 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 391 311 "[curr,head,elem]" "Helvetica" 0 12 0 REF 68 
            CH.ifa.draw.standard.OffsetLocator 57 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 130 281 "guard curr<head" "Helvetica" 0 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator -63 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
