1 
    de.renew.gui.CPNDrawing 58 
        de.renew.gui.PlaceFigure "no_attributes" 192 274 68 73  
        de.renew.gui.PlaceFigure "no_attributes" 198 78 49 50  
        de.renew.gui.ArcConnection "no_attributes" 2 203 116 137 156 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 113 156 24 16    REF 7 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 203 319 "\"B\"" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -14 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 166 122 "x" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -1 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "no_attributes" 208 217 28 30  
        de.renew.gui.ArcConnection "no_attributes" 2 136 172 211 225 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14   
        de.renew.gui.ArcConnection "no_attributes" 2 234 225 313 174 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 300 158 53 16    REF 23 
        de.renew.gui.ArcConnection "no_attributes" 2 207 282 130 172 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 7   
        de.renew.gui.PlaceFigure "no_attributes" 215 28 23 26  
        de.renew.gui.ArcConnection "no_attributes" 2 220 51 131 156 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector REF 7   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 106 136 "pickup" "Helvetica" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 0 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 204 193 "holding" "Helvetica" 1 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 2 -32 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 311 148 "putdown" "Helvetica" 1 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 10 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "no_attributes" 2 235 228 377 170 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 377 158 24 16    REF 46 
        de.renew.gui.ArcConnection "no_attributes" 2 378 158 235 48 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 46  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.ArcConnection "no_attributes" 3 384 174 345 242 256 294 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 46  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.ArcConnection "no_attributes" 2 202 287 77 169 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 57 153 24 16    REF 59 
        de.renew.gui.ArcConnection "no_attributes" 2 218 48 79 153 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector REF 59   
        de.renew.gui.ArcConnection "no_attributes" 3 72 169 104 244 197 295 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 59  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.ArcConnection "no_attributes" 2 320 158 233 51 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 23  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.ArcConnection "no_attributes" 2 320 174 246 282 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 23  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 200 127 "on_table" "Helvetica" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 3 31 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 407 158 "stack" "Helvetica" 1 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 34 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 201 349 "on / clear" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 2 46 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 9 156 "unstack" "Helvetica" 1 12 0 REF 59 
            CH.ifa.draw.standard.OffsetLocator -37 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 244 26 "hand_empty" "Helvetica" 1 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 54 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 267 184 "x" "Helvetica" 0 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator -3 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 169 183 "x" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -1 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 156 216 "x" "Helvetica" 0 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator -9 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 223 34 "[]" "Helvetica" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 201 303 "\"C\"" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -16 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 202 287 "[\"C\",\"A\"]" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 125 240 "[x,y]" "Helvetica" 0 12 0 REF 55 
            CH.ifa.draw.standard.OffsetLocator -3 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 354 252 "[x,y]" "Helvetica" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 45 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 121 222 "x" "Helvetica" 0 12 0 REF 55 
            CH.ifa.draw.standard.OffsetLocator -15 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 88 252 "y" "Helvetica" 0 12 0 REF 64 
            CH.ifa.draw.standard.OffsetLocator -43 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 330 166 "x" "Helvetica" 0 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator 27 -26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 2 81 166 210 227 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 59  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 94 149 "x" "Helvetica" 0 12 0 REF 124 
            CH.ifa.draw.standard.OffsetLocator -48 -40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "no_attributes" 458 302 24 16  
        de.renew.gui.ArcConnection "no_attributes" 2 260 310 458 310 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 131   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 353 295 "[\"B\",\"C\"]" "Helvetica" 0 12 0 REF 132 
            CH.ifa.draw.standard.OffsetLocator 17 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 353 279 "[\"A\",\"B\"]" "Helvetica" 0 12 0 REF 132 
            CH.ifa.draw.standard.OffsetLocator 17 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 2 470 302 470 171 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 131  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "no_attributes" 460 151 20 20    REF 146 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 282 235 "x" "Helvetica" 0 12 0 REF 72 
            CH.ifa.draw.standard.OffsetLocator 2 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 2 313 158 243 116 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 23  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 275 121 "x" "Helvetica" 0 12 0 REF 150 
            CH.ifa.draw.standard.OffsetLocator 0 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 2 252 288 379 174 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 46   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 325 223 "y" "Helvetica" 0 12 0 REF 157 
            CH.ifa.draw.standard.OffsetLocator 13 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 367 231 "x" "Helvetica" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 50 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 217 106 "\"B\"" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 4 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 208 89 "\"A\"" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -5 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   