7 
    de.renew.gui.CPNDrawing 64 
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 6 2 295 14 295 28 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 294 -1 " " "Helvetica" 0 12 0 NULL NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 260 28 "<2,0,0,0,0,2>" "Helvetica" 0 12 0 NULL NULL    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 12 2 301 43 344 93 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 315 93 "<1,0,1,0,0,2>" "Helvetica" 0 12 0 NULL NULL    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13 2 343 108 307 148 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 10 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 265 148 "<0,1,1,0,0,2>" "Helvetica" 0 12 0 NULL NULL    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 14 2 354 108 381 158 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 11 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 350 158 "<0,0,2,0,0,2>" "Helvetica" 0 12 0 NULL NULL    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 16 2 292 43 238 208 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 200 208 "<1,1,0,0,0,2>" "Helvetica" 0 12 0 NULL NULL    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 18 2 229 223 186 278 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 9 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 145 278 "<0,2,0,0,0,2>" "Helvetica" 0 12 0 NULL NULL    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 21 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 204 243 "a" "Helvetica" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 22 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 364 126 "d" "Helvetica" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 27 2 243 208 292 163 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector REF 16   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 19 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 319 61 "d" "Helvetica" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 40 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 322 121 "a" "Helvetica" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 78 2 173 278 122 223 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 31  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 55 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 200 0 80 208 "<0,1,0,1,0,1>" "Helvetica" 0 12 0 NULL NULL    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 79 2 228 208 122 88 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 77 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 200 0 80 73 "<1,0,0,1,0,1>" "Helvetica" 0 12 0 NULL NULL    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 82 2 58 133 107 88 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 70 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 200 0 15 133 "<0,0,0,2,0,0>" "Helvetica" 0 12 0 NULL NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 57   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 83 2 145 73 265 43 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 57  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 84 2 151 215 200 215 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 52  
            CH.ifa.draw.standard.ChopBoxConnector REF 26   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 85 2 108 208 57 148 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 52  
            CH.ifa.draw.standard.ChopBoxConnector REF 61   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 86 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 79 103 "c" "Helvetica" 0 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 87 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 202 51 "c" "Helvetica" 0 12 0 REF 63 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 88 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 172 208 "c" "Helvetica" 0 12 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 92 2 115 88 115 208 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 57  
            CH.ifa.draw.standard.ChopBoxConnector REF 52   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 97 2 386 100 550 100 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 100 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 235 199 158 550 93 "<1,0,0,0,1,0>" "Helvetica" 0 12 0 NULL NULL    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 98 2 402 158 448 138 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 21  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 96 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 235 199 158 430 123 "<0,0,1,0,1,0>" "Helvetica" 0 12 0 NULL NULL    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 99 2 436 123 379 108 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 97  
            CH.ifa.draw.standard.ChopBoxConnector REF 11   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 101 2 552 93 328 43 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 92  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 109 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 465 93 "e" "Helvetica" 0 12 0 REF 88 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 111 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 422 141 "e" "Helvetica" 0 12 0 REF 93 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 112 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 403 108 " f " "Helvetica" 0 12 0 REF 98 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 113 2 555 108 495 123 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 92  
            CH.ifa.draw.standard.ChopBoxConnector REF 97   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 115 2 571 108 379 208 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 92  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 105 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 235 199 158 330 208 "<0,1,0,0,1,0>" "Helvetica" 0 12 0 NULL NULL    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 117 2 330 215 271 215 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 123  
            CH.ifa.draw.standard.ChopBoxConnector REF 26   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 118 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 296 208 " f " "Helvetica" 0 12 0 REF 124 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 114 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 522 108 "d" "Helvetica" 0 12 0 REF 115 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 123 2 308 163 357 208 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 123   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 124 2 288 148 222 108 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 107 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 200 0 175 93 "<0,0,1,1,0,1>" "Helvetica" 0 12 0 NULL NULL    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 126 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 329 178 "e" "Helvetica" 0 12 0 REF 134 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 129 2 246 100 315 100 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 142  
            CH.ifa.draw.standard.ChopBoxConnector REF 11   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 160 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 112 141 "a" "Helvetica" 0 12 0 REF 84 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 166 2 151 87 175 93 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 57  
            CH.ifa.draw.standard.ChopBoxConnector REF 142   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 110 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 437 62 " f " "Helvetica" 0 12 0 REF 102 
            CH.ifa.draw.standard.OffsetLocator 1 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 169 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 136 76 "d" "Helvetica" 0 12 0 REF 153 
            CH.ifa.draw.standard.OffsetLocator -24 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 20 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 264 114 "a" "Helvetica" 0 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator 2 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 130 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 279 93 "c" "Helvetica" 0 12 0 REF 146 
            CH.ifa.draw.standard.OffsetLocator 2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 34 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 263 178 "d" "Helvetica" 0 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator -1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 89 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 80 172 "b" "Helvetica" 0 12 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator 1 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 80 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 173 141 "b" "Helvetica" 0 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 81 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 144 242 "b" "Helvetica" 0 12 0 REF 48 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 3 "Location" "Boolean" "TRUE" "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 30 2 "<lok,la,sa,l,s,r>" "Helvetica" 1 12 0 NULL NULL  REF 6 REF 4 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 116 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 472 153 "a" "Helvetica" 0 12 0 REF 119 
            CH.ifa.draw.standard.OffsetLocator 0 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 26 REF 11 REF 92 REF 61 REF 123 REF 52 REF 57 REF 31 REF 16 REF 142 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 125 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 244 117 "b" "Helvetica" 0 12 0 REF 138 
            CH.ifa.draw.standard.OffsetLocator -8 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 21 REF 97 NULL  355 17 672 357 
