5 
    de.renew.gui.CPNDrawing 138 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 11 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" 2 262 201 429 201 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 195 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 242 191 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FigureWithID" "Int" 12 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 429 193 24 16 NULL    REF 6 
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 25 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 430 285 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 27 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" 2 431 295 265 295 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FigureWithID" "Int" 28 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 241 287 24 16 NULL    REF 12 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 35 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" 2 434 302 355 381 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FigureWithID" "Int" 36 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 336 381 24 16 NULL    REF 17 
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FigureWithID" "Int" 46 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 428 474 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 48 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" 2 440 305 440 474 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector REF 18   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 26 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 455 284 "candidate" "Helvetica" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 43 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 56 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" 2 452 482 537 482 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 18  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 57 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 536 472 20 20 NULL    REF 30 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 67 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 481 466 "myid" "Helvetica" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 0 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 58 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 515 494 "terminated\nas leader" "Helvetica" 1 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 0 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 74 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 294 589 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 75 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 327 588 ":show(3,n)" "Helvetica" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator 49 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 76 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 296 638 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 77 3 313 642 332 623 314 605 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 41  
            CH.ifa.draw.standard.ChopBoxConnector REF 37   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4 3 297 605 280 622 300 642 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 37  
            CH.ifa.draw.figures.ChopEllipseConnector REF 41   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 316 616 "o" "Helvetica" 0 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 78 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 290 616 "n" "Helvetica" 0 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 318 641 "\"?\"" "Helvetica" 0 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator 19 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 79 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 293 682 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 80 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 326 681 ":show(4,n)" "Helvetica" 0 12 0 REF 59 
            CH.ifa.draw.standard.OffsetLocator 49 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 81 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 295 731 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 82 3 312 735 331 716 313 698 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 63  
            CH.ifa.draw.standard.ChopBoxConnector REF 59   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 83 3 296 698 279 715 299 735 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 59  
            CH.ifa.draw.figures.ChopEllipseConnector REF 63   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 84 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 315 709 "o" "Helvetica" 0 12 0 REF 64 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 85 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 289 709 "n" "Helvetica" 0 12 0 REF 68 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 86 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 327 744 "\"?\"" "Helvetica" 0 12 0 REF 63 
            CH.ifa.draw.standard.OffsetLocator 29 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 87 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 441 591 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 88 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 475 590 ":show(6,n)" "Helvetica" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 50 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 89 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 443 640 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 90 3 460 644 479 625 461 607 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 85  
            CH.ifa.draw.standard.ChopBoxConnector REF 81   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 91 3 444 607 427 624 447 644 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 81  
            CH.ifa.draw.figures.ChopEllipseConnector REF 85   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 92 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 464 618 "o" "Helvetica" 0 12 0 REF 86 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 93 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 438 618 "n" "Helvetica" 0 12 0 REF 90 
            CH.ifa.draw.standard.OffsetLocator 4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 94 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 466 643 "\"?\"" "Helvetica" 0 12 0 REF 85 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 95 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 442 685 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 96 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 476 684 ":show(7,n)" "Helvetica" 0 12 0 REF 103 
            CH.ifa.draw.standard.OffsetLocator 50 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 97 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 444 734 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 98 3 461 738 480 719 462 701 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 107  
            CH.ifa.draw.standard.ChopBoxConnector REF 103   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 99 3 445 701 428 718 448 738 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 103  
            CH.ifa.draw.figures.ChopEllipseConnector REF 107   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 100 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 465 712 "o" "Helvetica" 0 12 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 101 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 439 712 "n" "Helvetica" 0 12 0 REF 112 
            CH.ifa.draw.standard.OffsetLocator 4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 102 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 467 737 "\"?\"" "Helvetica" 0 12 0 REF 107 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 103 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 291 784 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 104 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 323 792 ":show(5,n)" "Helvetica" 0 12 0 REF 125 
            CH.ifa.draw.standard.OffsetLocator 48 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 105 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 293 833 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 106 3 310 837 329 818 311 800 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 129  
            CH.ifa.draw.standard.ChopBoxConnector REF 125   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 107 3 294 800 277 817 297 837 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 125  
            CH.ifa.draw.figures.ChopEllipseConnector REF 129   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 108 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 314 811 "o" "Helvetica" 0 12 0 REF 130 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 109 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 288 811 "n" "Helvetica" 0 12 0 REF 134 
            CH.ifa.draw.standard.OffsetLocator 4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 110 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 316 836 "\"?\"" "Helvetica" 0 12 0 REF 129 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 111 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 139 588 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 41 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 173 587 ":show(0,n)" "Helvetica" 0 12 0 REF 147 
            CH.ifa.draw.standard.OffsetLocator 50 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 42 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 141 637 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 43 3 158 641 177 622 159 604 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 151  
            CH.ifa.draw.standard.ChopBoxConnector REF 147   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 44 3 142 604 124 621 145 641 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 147  
            CH.ifa.draw.figures.ChopEllipseConnector REF 151   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 45 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 162 615 "o" "Helvetica" 0 12 0 REF 152 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 112 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 136 615 "n" "Helvetica" 0 12 0 REF 156 
            CH.ifa.draw.standard.OffsetLocator 5 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 47 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 164 640 "\"?\"" "Helvetica" 0 12 0 REF 151 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 113 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 139 686 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 114 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 172 685 ":show(1,n)" "Helvetica" 0 12 0 REF 169 
            CH.ifa.draw.standard.OffsetLocator 49 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 115 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 141 735 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 116 3 158 739 177 720 159 702 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 173  
            CH.ifa.draw.standard.ChopBoxConnector REF 169   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52 3 142 702 125 719 145 739 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 169  
            CH.ifa.draw.figures.ChopEllipseConnector REF 173   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 53 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 161 713 "o" "Helvetica" 0 12 0 REF 174 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 117 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 135 713 "n" "Helvetica" 0 12 0 REF 178 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 55 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 163 738 "\"?\"" "Helvetica" 0 12 0 REF 173 
            CH.ifa.draw.standard.OffsetLocator 19 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 118 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 140 783 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 119 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 173 782 ":show(2,n)" "Helvetica" 0 12 0 REF 191 
            CH.ifa.draw.standard.OffsetLocator 49 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 120 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 142 832 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 59 3 159 836 178 817 160 799 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 195  
            CH.ifa.draw.standard.ChopBoxConnector REF 191   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 60 3 143 799 126 816 146 836 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 191  
            CH.ifa.draw.figures.ChopEllipseConnector REF 195   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 61 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 162 810 "o" "Helvetica" 0 12 0 REF 196 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 62 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 136 810 "n" "Helvetica" 0 12 0 REF 200 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 164 835 "\"?\"" "Helvetica" 0 12 0 REF 195 
            CH.ifa.draw.standard.OffsetLocator 19 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 127 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 646 261 20 20 NULL REF 173  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 128 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 691 280 20 20 NULL REF 195  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 129 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 708 326 20 20 NULL REF 41  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 130 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 692 372 20 20 NULL REF 63  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 131 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 646 389 20 20 NULL REF 129  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 132 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 601 371 20 20 NULL REF 85  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 133 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 582 326 20 20 NULL REF 107  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 134 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 602 282 20 20 NULL REF 151  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 144 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 651 242 "1" "Helvetica" 1 12 0 REF 213 
            CH.ifa.draw.standard.OffsetLocator -2 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 145 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 711 266 "2" "Helvetica" 1 12 0 REF 214 
            CH.ifa.draw.standard.OffsetLocator 13 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 146 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 734 327 "3" "Helvetica" 1 12 0 REF 215 
            CH.ifa.draw.standard.OffsetLocator 19 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 147 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 713 391 "4" "Helvetica" 1 12 0 REF 216 
            CH.ifa.draw.standard.OffsetLocator 14 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 148 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 652 412 "5" "Helvetica" 1 12 0 REF 217 
            CH.ifa.draw.standard.OffsetLocator -1 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 149 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 592 383 "6" "Helvetica" 1 12 0 REF 218 
            CH.ifa.draw.standard.OffsetLocator -16 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 150 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 595 271 "0" "Helvetica" 1 12 0 REF 220 
            CH.ifa.draw.standard.OffsetLocator -14 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 151 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 572 323 "7" "Helvetica" 1 12 0 REF 219 
            CH.ifa.draw.standard.OffsetLocator -17 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 152 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 430 93 20 20 NULL  
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 160 2 609 301 596 328 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 220  
            CH.ifa.draw.figures.ChopEllipseConnector REF 219   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 164 2 705 374 716 345 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 216  
            CH.ifa.draw.figures.ChopEllipseConnector REF 215   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 165 2 716 328 704 299 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 215  
            CH.ifa.draw.figures.ChopEllipseConnector REF 214   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 166 2 693 287 665 275 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 214  
            CH.ifa.draw.figures.ChopEllipseConnector REF 213   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 167 2 648 275 621 289 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 213  
            CH.ifa.draw.figures.ChopEllipseConnector REF 220   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 168 2 665 397 694 385 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 217  
            CH.ifa.draw.figures.ChopEllipseConnector REF 216   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 169 2 620 385 648 396 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 218  
            CH.ifa.draw.figures.ChopEllipseConnector REF 217   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 170 2 596 345 608 373 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 219  
            CH.ifa.draw.figures.ChopEllipseConnector REF 218   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 172 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 242 44 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 174 "FrameColor" "Color" 192 192 192 2 252 64 252 95 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 278  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 175 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 241 95 24 16 NULL    REF 283 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 176 "FrameColor" "Color" 192 192 192 2 431 103 265 103 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 245  
            CH.ifa.draw.standard.ChopBoxConnector REF 283   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 180 "FrameColor" "Color" 192 192 192 2 440 113 440 193 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 245  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 192 2 440 209 440 286 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   REF 4 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 196 2 252 287 252 211 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 12  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 191 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 373 362 "[myid,id]" "Helvetica" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 1 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 187 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 257 238 "[myid,id]" "Helvetica" 0 12 0 REF 294 
            CH.ifa.draw.standard.OffsetLocator 27 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 16 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 328 204 "[myid,id]" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 5 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 185 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 327 278 "[myid,id]" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 1 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 201 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 453 372 "[myid,myid]" "Helvetica" 0 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator 43 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 40 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 355 399 "guard\nmyid>id" "Helvetica" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 28 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 3 "FigureWithID" "Int" 171 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 613 160 "import samples.reisig.*;" "Helvetica" 0 12 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 158 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 431 48 "new InverseTopology(\n  new RingTopology(8))" "Helvetica" 0 12 0 REF 245 
            CH.ifa.draw.standard.OffsetLocator 55 -40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 203 "FrameColor" "Color" 192 192 192 2 241 103 148 103 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 283  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 205 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 128 93 20 20 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 193 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 449 221 "t.prod(\n  t.neighbors(myid),\n  id)" "Helvetica" 0 12 0 REF 290 
            CH.ifa.draw.standard.OffsetLocator 61 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 204 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 396 494 "this:show(myid,\"!\")" "Helvetica" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 5 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 324 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 206 "FrameColor" "Color" 192 192 192 2 138 113 138 193 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 324  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 207 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 126 193 24 16 NULL    REF 335 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 181 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 445 144 "t" "Helvetica" 0 12 0 REF 287 
            CH.ifa.draw.standard.OffsetLocator 6 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 173 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 249 47 "[]" "Helvetica" 0 12 0 REF 278 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 208 "FrameColor" "Color" 192 192 192 2 150 201 243 201 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 335  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FigureWithID" "Int" 211 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 163 204 "[myid,myid]" "Helvetica" 0 12 0 REF 342 
            CH.ifa.draw.standard.OffsetLocator -3 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 212 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 146 142 "myid" "Helvetica" 0 12 0 REF 331 
            CH.ifa.draw.standard.OffsetLocator 21 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 10 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 232 172 "outgoing" "Helvetica" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 4 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 215 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 114 78 "all" "Helvetica" 1 12 0 REF 324 
            CH.ifa.draw.standard.OffsetLocator -18 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 199 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 181 107 "t.nodes()" "Helvetica" 0 12 0 REF 320 
            CH.ifa.draw.standard.OffsetLocator 11 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 177 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 346 107 "t" "Helvetica" 0 12 0 REF 284 
            CH.ifa.draw.standard.OffsetLocator -1 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 214 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 456 93 "topology" "Helvetica" 1 12 0 REF 245 
            CH.ifa.draw.standard.OffsetLocator 40 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 213 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 150 168 "this:show(\n  myid,myid)" "Helvetica" 0 12 0 REF 335 
            CH.ifa.draw.standard.OffsetLocator 44 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 34 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 186 275 "guard\n  myid<id" "Helvetica" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator -43 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 194 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 207 312 "this:show(myid,id)" "Helvetica" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 3 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  94 68 818 933 