11 
    de.renew.hierarchicalworkflownets.gui.HNViewDrawing 1 "IO" 
        de.renew.hierarchicalworkflownets.gui.HNPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1 "rpir" "Storable" 
            de.renew.hierarchicalworkflownets.gui.layout.Vec2d 0.0 0.0  "FillColor" "Color" 192 192 192 255 0 0 24 20 NULL  3 "IO_p1" 
        de.renew.hierarchicalworkflownets.gui.HNPlaceFigure "attributes" "attributes" 3 "lp" "UNKNOWN" "FigureWithID" "Int" 4 "rpir" "Storable" 
            de.renew.hierarchicalworkflownets.gui.layout.Vec2d 48.0 0.0  220 26 20 20 NULL  0 "IO_p0" 
        de.renew.hierarchicalworkflownets.gui.HNPlaceFigure "attributes" "attributes" 3 "lp" "UNKNOWN" "FigureWithID" "Int" 2 "rpir" "Storable" 
            de.renew.hierarchicalworkflownets.gui.layout.Vec2d -48.0 0.0  0 26 20 20 NULL  0 "IO_t0" 
        de.renew.hierarchicalworkflownets.gui.HNTransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3 "rpir" "Storable" 
            de.renew.hierarchicalworkflownets.gui.layout.Vec2d 0.0 0.0  "FillColor" "Color" 192 192 192 255 52 2 24 16 NULL  3 "IO_t0_p0" 
        de.renew.hierarchicalworkflownets.gui.HNPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8 "rpir" "Storable" 
            de.renew.hierarchicalworkflownets.gui.layout.Vec2d 0.0 0.0  "FillColor" "Color" 192 192 192 255 112 0 20 20 NULL  2 "IO_t0_p0_p1" 
        de.renew.hierarchicalworkflownets.gui.HNPlaceFigure "attributes" "attributes" 3 "lp" "UNKNOWN" "FigureWithID" "Int" 15 "rpir" "Storable" 
            de.renew.hierarchicalworkflownets.gui.layout.Vec2d 0.0 15.0  112 52 20 20 NULL  0 "IO_t0_p0_p0" 
        de.renew.hierarchicalworkflownets.gui.HNPlaceFigure "attributes" "attributes" 3 "lp" "UNKNOWN" "FigureWithID" "Int" 14 "rpir" "Storable" 
            de.renew.hierarchicalworkflownets.gui.layout.Vec2d 0.0 -15.0  112 0 20 20 NULL  0 "IO_t0_t0" 
        de.renew.hierarchicalworkflownets.gui.HNTransitionFigure "attributes" "attributes" 3 "lp" "UNKNOWN" "FigureWithID" "Int" 7 "rpir" "Storable" 
            de.renew.hierarchicalworkflownets.gui.layout.Vec2d -46.0 0.0  52 28 28 16 NULL  0 "IO_t0_t1" 
        de.renew.hierarchicalworkflownets.gui.HNTransitionFigure "attributes" "attributes" 3 "lp" "UNKNOWN" "FigureWithID" "Int" 9 "rpir" "Storable" 
            de.renew.hierarchicalworkflownets.gui.layout.Vec2d 48.0 0.0  164 28 24 16 NULL  0 6 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 18 2 131 59 164 41 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector REF 17   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 19 2 131 14 164 30 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 13  
            CH.ifa.draw.standard.ChopBoxConnector REF 17   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 12 2 188 36 221 36 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 17  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13 2 20 36 52 36 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 15   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 17 2 80 29 114 14 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 15  
            CH.ifa.draw.figures.ChopEllipseConnector REF 13   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 16 2 80 42 114 59 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 15  
            CH.ifa.draw.figures.ChopEllipseConnector REF 11   1 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 5 29 "[]" "SansSerif" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   67 27 800 400 