7 
    de.renew.gui.CPNDrawing 39 
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 3 "FigureWithID" "Int" 76 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 167 100 37 38  
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 3 "FigureWithID" "Int" 77 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 167 141 37 38  
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 3 "FigureWithID" "Int" 78 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 228 57 37 38  
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 3 "FigureWithID" "Int" 64 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 88 57 37 103  
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 3 "FigureWithID" "Int" 59 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 192 192 192 167 57 37 38  
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 2 2 51 74 101 74 NULL
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 255 255 40 66 "q" "Serif" 2 12 0 NULL NULL
            CH.ifa.draw.figures.ShortestDistanceConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 106 67 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9 2 185 27 185 68 NULL
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 10 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 255 255 184 11 "q" "Serif" 2 12 0 NULL NULL
            CH.ifa.draw.figures.ShortestDistanceConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 29 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 184 68 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 20 2 49 136 101 136 NULL
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 21 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 255 255 38 129 "q" "Serif" 2 12 0 NULL NULL
            CH.ifa.draw.figures.ShortestDistanceConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 6 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 106 129 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 28 2 114 74 179 74 NULL
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector REF 11  
            CH.ifa.draw.figures.ShortestDistanceConnector REF 17   REF 21 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 27 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 39 120 "_ " "Serif" 0 12 0 NULL NULL  
        de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 18 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 255 255 211 17 "q" "Serif" 2 12 0 NULL NULL
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 26 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 212 8 "_ " "Serif" 0 12 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 49 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 142 58 "f" "Serif" 2 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator -3 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 23 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 34 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 44 130 "¢" "Symbol" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator -28 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 50 2 114 133 179 122 NULL
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector REF 23  
            CH.ifa.draw.figures.ShortestDistanceConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 184 112 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 53 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 149 110 "f" "Serif" 2 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator 4 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 41 
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 55 2 114 139 179 155 NULL
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector REF 23  
            CH.ifa.draw.figures.ShortestDistanceConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 57 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 184 151 " " "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 58 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 141 148 "¹" "Symbol" 0 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator -3 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 49 REF 15 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 25 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 185 2 "_ " "Serif" 0 12 0 NULL NULL  REF 17 
        de.renew.gui.fs.FeatureConnection "attributes" "attributes" 1 "FigureWithID" "Int" 60 2 192 75 240 75 NULL
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector REF 17  
            CH.ifa.draw.figures.ShortestDistanceConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 61 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 245 68 " " "Helvetica" 0 12 0 NULL NULL    REF 58
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63 2 210 33 194 61 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector REF 29  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 56 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 149 149 "f" "Serif" 2 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator 4 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 67 2 106 34 106 58 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.figures.ShortestDistanceConnector 
                de.renew.gui.fs.FSNodeFigure "attributes" "attributes" 3 "FigureWithID" "Int" 65 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 255 255 103 18 "q" "Serif" 2 12 0 NULL NULL
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   REF 69 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 66 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 104 9 "_ " "Serif" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 19 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 216 25 "@" "Serif" 0 8 0 NULL NULL  REF 9 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 24 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 41 57 "_ " "Serif" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 "FigureWithID" "Int" 68 46 77 "f" "Serif" 2 9 0 NULL NULL  REF 11 
        CH.ifa.draw.contrib.PolygonFigure "attributes" "attributes" 2 "FigureWithID" "Int" 75 "FillColor" "Color" 255 199 158 4 109 29 117 33 117 29 109 34  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 48 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 141 109 "¹" "Symbol" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator -3 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  -1 192 315 253 
