
    CH.ifa.draw.cpn.CPNDrawing 14 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 210 131 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 212 222 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 211 318 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 213 408 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 211 504 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 213 572 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 222 147 222 223 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.ArcConnection 2 222 242 222 318 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        CH.ifa.draw.cpn.ArcConnection 2 223 334 223 409 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        CH.ifa.draw.cpn.ArcConnection 2 223 428 223 504 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector REF 5   
        CH.ifa.draw.cpn.ArcConnection 2 223 520 223 573 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.figures.ChopEllipseConnector REF 6   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 237 130 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 29 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 242 318 ":a()" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 28 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 241 503 ":b()" "Helvetica" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 27 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
