7 
    de.renew.gui.CPNDrawing 34 
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 2 "FigureWithID" "Int" 41 "LineStyle" "Int" 10 2 117 13 117 248 NULL NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 2 2 111 55 82 79 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 36 "Location" "Boolean" "TRUE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 107 38 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 54 79 36 18 NULL    REF 7 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4 2 90 88 108 88 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 107 78 20 20 NULL    REF 12 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 6 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 12 120 40 40 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7 2 44 125 65 97 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 13  
            CH.ifa.draw.standard.ChopBoxConnector REF 7   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8 2 72 97 72 131 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 62 130 20 20 NULL    REF 21 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 10 2 122 97 144 132 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 12  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 11 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 137 132 24 16 NULL    REF 26 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 12 2 144 148 122 185 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 26  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 107 183 20 20 NULL    REF 31 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 14 2 72 150 72 184 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 21  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 15 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 54 184 36 18 NULL    REF 36 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 16 2 108 193 90 193 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 31  
            CH.ifa.draw.standard.ChopBoxConnector REF 36   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 17 3 54 187 39 182 35 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 36  
            CH.ifa.draw.figures.ChopEllipseConnector REF 13   REF 5 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 47 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 170 40 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 48 2 170 48 127 48 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 45  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 49 2 182 56 182 79 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 45  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 50 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 172 78 20 20 NULL    REF 54 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 51 2 178 96 154 132 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 54  
            CH.ifa.draw.standard.ChopBoxConnector REF 26   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 75 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 179 41 "c" "Helvetica" 1 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 77 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 59 186 "unify" "Helvetica" 1 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 28 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 19 103 "Data" "Helvetica" 1 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 0 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 78 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 29 133 "[]" "Helvetica" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 79 3 47 154 59 165 67 184 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 13  
            CH.ifa.draw.standard.ChopBoxConnector REF 36   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 25 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 165 125 "read /\nmodify" "Helvetica" 1 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 35 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 76 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 59 81 "copy" "Helvetica" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 27 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 84 125 "copy\ncnt" "Helvetica" 1 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator 25 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 38 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 36 227 "Server" "Helvetica" 2 14 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 40 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 142 227 "Client" "Helvetica" 2 14 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 37 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 2 "FillColor" "Color" 255 199 158 62 30 "request\ndata" "Helvetica" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -33 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  0 125 262 311 
