1 
    de.renew.gui.CPNDrawing 23 
        de.renew.gui.TransitionFigure "no_attributes" 61 146 24 16  
        de.renew.gui.PlaceFigure "no_attributes" 51 73 42 35  
        de.renew.gui.ArcConnection "no_attributes" 2 72 107 72 146 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.ArcConnection "no_attributes" 2 85 154 104 154 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "no_attributes" 103 138 42 33    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 69 83 "3" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 2 93 90 146 90 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 146 82 24 16    REF 19 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 176 79 ":die()" "Helvetica" 0 18 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator 39 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "no_attributes" 61 18 24 16  
        de.renew.gui.ArcConnection "no_attributes" 2 72 34 72 74 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 23  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 93 16 ":reanimate()" "Helvetica" 0 18 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 67 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 11 
        de.renew.gui.ArcConnection "no_attributes" 2 124 139 124 123 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 113 107 24 16    REF 35 
        de.renew.gui.ArcConnection "no_attributes" 2 113 109 90 98 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 35  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 79 42 "5" "Helvetica" 0 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 10 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 60 117 "x" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -9 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 88 157 "x" "Helvetica" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -3 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 128 125 "x" "Helvetica" 0 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator 7 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 87 107 "x-1" "Helvetica" 0 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator -4 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 123 62 "guard x==0" "Helvetica" 0 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator -4 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 3 148 "guard x>0" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -42 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 104 75 "x" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -12 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   