11 
    de.renew.gui.CPNDrawing 33 
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4985 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -27 -195 163 220 5  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5009 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 15 
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4989 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -13 -8 24 16 NULL  
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4987 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 30 -71 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 5001 "Visibility" "Boolean" "TRUE" 2 -2 -8 -2 -45 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 3  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4990 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -12 -65 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4997 "Visibility" "Boolean" "TRUE" 2 -2 -64 -2 -111 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 9  
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4992 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -13 -127 24 16 NULL    
            de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4988 127 -10 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 5005 "Visibility" "Boolean" "TRUE" 2 11 0 31 0 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 3  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4991 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 30 -10 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5002 2 96 0 128 0 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4986 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 72 -8 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 15   REF 1 REF 14 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 5000 "Visibility" "Boolean" "TRUE" 2 4 -111 35 -68 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 14  
                CH.ifa.draw.figures.ChopEllipseConnector REF 4   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 5003 "Visibility" "Boolean" "TRUE" 2 46 -53 78 -8 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 4  
                CH.ifa.draw.standard.ChopBoxConnector REF 24   REF 24 REF 20 REF 9 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4999 "Visibility" "Boolean" "TRUE" 2 50 0 72 0 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 20  
                CH.ifa.draw.standard.ChopBoxConnector REF 24    REF 3 REF 4 REF 15 REF 14 REF 24 REF 20 REF 9 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4998 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 -18 -148 ":out(p2)" "SansSerif" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 6 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 5 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5007 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 -21 -220 "[toAgent]" "SansSerif" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -35 -124 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4994 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 -10 -34 "p2" "SansSerif" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 10 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4995 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 -17 -8 ">" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -11 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5008 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 -30 71 "$comment" "SansSerif" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -37 167 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4996 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 22 -40 "OUT" "SansSerif" 1 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator -5 -33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 16 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4993 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 -7 -100 "p2" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 3 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 21 REF 26 REF 30 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 5006 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -17 30 "$generateMessage" "SansSerif" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 38 37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 34 
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 742 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 185 -17 116 33  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 759 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 4 
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 740 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 "Visibility" "Boolean" "TRUE" 310 -11 20 20 NULL  
            de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 737 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 204 -8 24 16 NULL  REF 62 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 738 2 228 -1 311 -1 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 65  
                CH.ifa.draw.figures.ChopEllipseConnector REF 64    REF 64 REF 65 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 745 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 205 37 "$sequenceAction" "SansSerif" 0 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator 38 44 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextColor" "Color" 0 0 255 255 "FigureWithID" "Int" 758 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 185 68 "$comment" "SansSerif" 0 18 0 REF 62 
            CH.ifa.draw.standard.OffsetLocator -11 80 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 741 "TextAlignment" "Int" 1 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" 324 -9 ">" "SansSerif" 1 12 0 REF 64 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 66 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5010 2 147 0 204 0 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 15  
            CH.ifa.draw.standard.ChopBoxConnector REF 65   NULL  90 451 710 632 