11 
    de.renew.gui.CPNDrawing 24 
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 0 "FigureWithID" "Int" 190 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 31 159 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 0 "FigureWithID" "Int" 191 2 51 169 105 169 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 192 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 105 161 24 16 NULL    REF 6 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 193 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 21 104 "action DistributePlugin\n  .registerNetInstance(\"Anbieter\", this);" "SansSerif" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 14 -50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 194 2 129 169 184 169 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 0 "FigureWithID" "Int" 195 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 183 159 20 20 NULL    REF 14 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 196 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 37 162 "[]" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 197 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 5 4 "import de.renew.distribute.DistributePlugin;\nimport de.renew.distribute.DistributeNetInstance;\nDistributeNetInstance ni;\nString ware;\nint geld;" "SansSerif" 0 12 0 NULL NULL 1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 198 2 193 179 193 228 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 14  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 199 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 181 228 24 16 NULL    REF 23 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 200 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 93 143 "register" "SansSerif" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 201 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 127 229 "Handel" "SansSerif" 1 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator -45 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 202 2 193 244 193 341 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 23  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 0 "FigureWithID" "Int" 203 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 183 340 20 20 NULL    REF 34 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 210 2 205 243 271 285 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 23  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 211 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 269 279 20 20 NULL    REF 39 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 212 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 226 257 "geld" "SansSerif" 0 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 213 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 262 263 "Einnahme" "SansSerif" 1 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 13 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 549 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 252 154 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 552 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 275 156 "\"Schokolade\";\"Eis\";\"Eistee\"" "SansSerif" 0 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 86 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 556 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 236 138 "Angebot" "SansSerif" 1 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 215 2 256 171 200 228 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 46  
            CH.ifa.draw.standard.ChopBoxConnector REF 23   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 216 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 214 192 "ware" "SansSerif" 0 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 214 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 223 208 ":h(ni);\nni!s(ware) -> geld;\nguard geld >= 2;" "SansSerif" 0 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 85 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  661 30 619 600 