1 
    de.renew.gui.CPNDrawing 20 
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FontSize" "Int" 18 94 107 51 20  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FontSize" "Int" 18 403 109 24 16  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FontSize" "Int" 18 200 109 24 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FontSize" "Int" 18 2 144 117 200 117 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 151 84 "this:lookup(x,y)" "Helvetica" 0 18 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 2 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 368 84 ":lookup(a,b)" "Helvetica" 0 18 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 2 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 108 107 "42" "Helvetica" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -1 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 167 117 "x" "Helvetica" 0 18 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 0 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FontSize" "Int" 18 301 107 54 20  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FontSize" "Int" 18 2 224 117 302 117 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 20   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 256 117 "y" "Helvetica" 0 18 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator -2 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FontSize" "Int" 18 502 90 75 53  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FontSize" "Int" 18 2 427 116 503 116 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 449 116 "[a,b]" "Helvetica" 0 18 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 1 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 506 94 "[42,\"6x7\"]" "Helvetica" 0 18 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 4 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 506 115 "[56,\"8x7\"]" "Helvetica" 0 18 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 4 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 107 87 "int" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -6 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 525 75 "Tuple" "Helvetica" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 1 -34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 8 15 "import de.renew.unify.*;\nint x;\nString y;\nint a;\nString b;" "Helvetica" 0 18 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 314 87 "String" "Helvetica" 0 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 2 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   