11 
    de.renew.gui.CPNDrawing 246 
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 8172 "FillColor" "Color" 0 0 255 51 483 235 351 240 8 8  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7883 458 895 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7884 459 760 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7885 460 615 20 20 NULL  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7886 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 307 754 116 33  
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7887 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 345 582 103 377 6  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7888 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 17 REF 2 
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7943 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 353 760 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "Visibility" "Boolean" "TRUE" "FigureWithID" "Int" 7890 2 368 762 431 634 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 8  
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7944 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 424 618 24 16 NULL    REF 5 REF 13 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7945 2 448 770 460 770 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7948 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 424 763 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 3   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7946 2 448 906 459 906 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7949 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 424 900 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 2   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7947 2 448 625 461 625 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 13  
                CH.ifa.draw.figures.ChopEllipseConnector REF 4   REF 17 REF 22 REF 4 
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7952 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 312 763 24 16 NULL  REF 3 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "Visibility" "Boolean" "TRUE" "FigureWithID" "Int" 7950 2 336 770 354 770 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 28  
                CH.ifa.draw.figures.ChopEllipseConnector REF 8   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "Visibility" "Boolean" "TRUE" "FigureWithID" "Int" 7889 2 368 779 431 900 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 8  
                CH.ifa.draw.standard.ChopBoxConnector REF 22   REF 6 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "Visibility" "Boolean" "TRUE" "FigureWithID" "Int" 7891 2 373 770 424 770 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 8  
                CH.ifa.draw.standard.ChopBoxConnector REF 17    REF 33 REF 9 REF 37 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7892 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 99 289 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7893 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 129 290 "wasser: new waterlifecycle" "SansSerif" 0 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator 100 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7894 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 56 272 "fülle Wasser ab" "SansSerif" 1 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator 0 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7895 2 111 305 111 351 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 41  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7896 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 101 350 20 20 NULL    REF 52 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7897 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 89 321 "wasser" "SansSerif" 0 12 0 REF 48 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7898 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 652 354 20 20 NULL REF 52  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7899 "FrameColor" "Color" 255 0 0 255 "FillColor" "Color" 255 200 0 255 594 276 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7900 2 611 292 657 357 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 57  
            CH.ifa.draw.figures.ChopEllipseConnector REF 56   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7901 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 562 258 "w:schmelzen()" "SansSerif" 0 12 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7902 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 583 276 "manual" "SansSerif" 0 12 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7903 "FrameColor" "Color" 255 0 0 255 "FillColor" "Color" 255 200 0 255 706 276 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7904 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 677 258 "w:erstarren()" "SansSerif" 0 12 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7905 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 695 276 "manual" "SansSerif" 0 12 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7906 "FrameColor" "Color" 255 0 0 255 "FillColor" "Color" 255 200 0 255 762 356 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7907 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 726 338 "w:verdampfen()" "SansSerif" 0 12 0 REF 74 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7908 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 751 356 "manual" "SansSerif" 0 12 0 REF 74 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7909 "FrameColor" "Color" 255 0 0 255 "FillColor" "Color" 255 200 0 255 706 436 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7910 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 664 418 "w:kondensieren()" "SansSerif" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7911 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 695 436 "manual" "SansSerif" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7912 "FrameColor" "Color" 255 0 0 255 "FillColor" "Color" 255 200 0 255 594 436 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7913 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 559 418 "w:sublimieren()" "SansSerif" 0 12 0 REF 88 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7914 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 583 436 "manual" "SansSerif" 0 12 0 REF 88 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7915 "FrameColor" "Color" 255 0 0 255 "FillColor" "Color" 255 200 0 255 538 356 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7916 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 496 338 "w:resublimieren()" "SansSerif" 0 12 0 REF 95 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7917 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 527 356 "manual" "SansSerif" 0 12 0 REF 95 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7918 2 668 357 712 292 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 56  
            CH.ifa.draw.standard.ChopBoxConnector REF 67   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7919 2 672 364 762 364 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 56  
            CH.ifa.draw.standard.ChopBoxConnector REF 74   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7920 2 668 372 712 436 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 56  
            CH.ifa.draw.standard.ChopBoxConnector REF 81   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7921 2 657 372 611 436 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 56  
            CH.ifa.draw.standard.ChopBoxConnector REF 88   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7922 2 653 364 562 364 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 56  
            CH.ifa.draw.standard.ChopBoxConnector REF 95   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7923 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 630 317 "w" "SansSerif" 0 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7924 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 686 317 "w" "SansSerif" 0 12 0 REF 102 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7925 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 713 357 "w" "SansSerif" 0 12 0 REF 105 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7926 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 686 397 "w" "SansSerif" 0 12 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7927 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 630 397 "w" "SansSerif" 0 12 0 REF 111 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7928 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 603 357 "w" "SansSerif" 0 12 0 REF 114 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7929 "FrameColor" "Color" 255 0 0 255 "FillColor" "Color" 255 200 0 255 144 764 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7930 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 101 748 "w:getState(state)" "SansSerif" 0 12 0 REF 135 
            CH.ifa.draw.standard.OffsetLocator 0 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7931 2 168 771 251 771 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 135  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7932 250 761 20 20 NULL    REF 143 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7933 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 193 764 "state" "SansSerif" 0 12 0 REF 139 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7934 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 374 691 "\"flüssig\"" "SansSerif" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextColor" "Color" 255 0 0 255 "FigureWithID" "Int" 7935 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 473 762 ">" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 7936 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 "Visibility" "Boolean" "TRUE" 343 753 "s" "SansSerif" 0 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 1 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7937 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 255 255 255 363 832 "\"gasförmig\"" "SansSerif" 0 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7938 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 255 255 255 381 763 "\"fest\"" "SansSerif" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextColor" "Color" 255 0 0 255 "FigureWithID" "Int" 7939 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 472 897 ">" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextColor" "Color" 255 0 0 255 "FigureWithID" "Int" 7940 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 474 617 ">" "SansSerif" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7941 2 270 771 312 771 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 143  
            CH.ifa.draw.standard.ChopBoxConnector REF 28   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7942 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 288 764 "s" "SansSerif" 0 12 0 REF 168 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 8 REF 13 REF 14 REF 19 REF 24 REF 17 REF 22 REF 29 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7951 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 133 765 "manual" "SansSerif" 0 12 0 REF 135 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 28 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextColor" "Color" 255 0 0 255 "FigureWithID" "Int" 7953 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 309 763 ">" "SansSerif" 1 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator -10 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7954 2 480 625 564 625 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7955 564 617 24 16 NULL    REF 185 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7956 2 479 770 564 770 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7957 564 762 24 16 NULL    REF 190 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7958 2 478 905 564 905 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7959 564 897 24 16 NULL    REF 195 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7960 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 535 635 "w:erstarren()" "SansSerif" 0 12 0 REF 185 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7961 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 529 781 "w:sublimieren()" "SansSerif" 0 12 0 REF 190 
            CH.ifa.draw.standard.OffsetLocator 0 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7962 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 522 915 "w:kondensieren()" "SansSerif" 0 12 0 REF 195 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7963 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 124 353 "Wasser" "SansSerif" 1 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator 40 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7964 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 21 761 20 20 NULL REF 52  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7965 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 37 777 "Wasser" "SansSerif" 1 12 0 REF 208 
            CH.ifa.draw.standard.OffsetLocator 33 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7966 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 655 571 20 20 NULL REF 52  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7967 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 681 577 "Wasser" "SansSerif" 1 12 0 REF 212 
            CH.ifa.draw.standard.OffsetLocator 43 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7968 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 655 717 20 20 NULL REF 52  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7969 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 681 723 "Wasser" "SansSerif" 1 12 0 REF 216 
            CH.ifa.draw.standard.OffsetLocator 43 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7970 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 655 853 20 20 NULL REF 52  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7971 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 681 859 "Wasser" "SansSerif" 1 12 0 REF 220 
            CH.ifa.draw.standard.OffsetLocator 43 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7972 2 657 867 588 899 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 220  
            CH.ifa.draw.standard.ChopBoxConnector REF 195   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7973 2 657 731 588 764 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 216  
            CH.ifa.draw.standard.ChopBoxConnector REF 190   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7974 2 657 585 588 619 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 212  
            CH.ifa.draw.standard.ChopBoxConnector REF 185   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7975 2 41 771 144 771 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 208  
            CH.ifa.draw.standard.ChopBoxConnector REF 135   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7976 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 88 764 "w" "SansSerif" 0 12 0 REF 233 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7977 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 618 876 "w" "SansSerif" 0 12 0 REF 224 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7978 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 618 740 "w" "SansSerif" 0 12 0 REF 227 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7979 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 618 595 "w" "SansSerif" 0 12 0 REF 230 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7980 2 588 625 656 625 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 185  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7981 655 615 20 20 NULL    REF 252 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7982 2 675 625 742 625 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 252  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7983 742 617 24 16 NULL    REF 257 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7984 2 588 770 656 770 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 190  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7985 655 760 20 20 NULL    REF 262 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7986 2 675 770 742 770 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 262  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7987 742 762 24 16 NULL    REF 267 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7988 2 588 905 656 905 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 195  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7989 655 895 20 20 NULL    REF 272 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7990 2 675 905 742 905 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 272  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7991 742 898 24 16 NULL    REF 277 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7992 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 707 635 "w:sublimieren()" "SansSerif" 0 12 0 REF 257 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7993 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 700 780 "w:kondensieren()" "SansSerif" 0 12 0 REF 267 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7994 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 713 916 "w:erstarren()" "SansSerif" 0 12 0 REF 277 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7995 2 766 625 837 625 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 257  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7996 836 615 20 20 NULL    REF 291 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7997 2 766 770 837 770 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 267  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7998 836 760 20 20 NULL    REF 296 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7999 2 766 906 837 906 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 277  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8000 836 896 20 20 NULL    REF 301 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8001 2 674 585 742 619 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 212  
            CH.ifa.draw.standard.ChopBoxConnector REF 257   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8002 2 674 731 742 764 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 216  
            CH.ifa.draw.standard.ChopBoxConnector REF 267   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8003 2 674 867 742 900 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 220  
            CH.ifa.draw.standard.ChopBoxConnector REF 277   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8004 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 704 740 "w" "SansSerif" 0 12 0 REF 305 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8005 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 704 595 "w" "SansSerif" 0 12 0 REF 302 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8006 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 704 876 "w" "SansSerif" 0 12 0 REF 308 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8007 2 856 906 921 906 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 301  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8008 921 898 24 16 NULL    REF 324 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8009 2 856 770 921 770 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 296  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8010 921 763 24 16 NULL    REF 329 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8011 2 856 625 921 625 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 291  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8012 921 617 24 16 NULL    REF 334 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8013 2 945 771 1068 771 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 329  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FillColor" "Color" 0 255 0 255 "FigureWithID" "Int" 8014 1067 761 20 20 NULL    REF 339 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8015 2 940 633 1071 765 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 334  
            CH.ifa.draw.figures.ChopEllipseConnector REF 339   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8016 2 941 898 1071 778 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 324  
            CH.ifa.draw.figures.ChopEllipseConnector REF 339   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8017 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 867 784 "w:getLabel(\"Wasser\")" "SansSerif" 0 12 0 REF 329 
            CH.ifa.draw.standard.OffsetLocator 0 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8018 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 870 635 "w:getLabel(\"Dampf\")" "SansSerif" 0 12 0 REF 334 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8019 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 881 916 "w:getLabel(\"Eis\")" "SansSerif" 0 12 0 REF 324 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8020 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1064 736 "Anzahl erfolgreicher\nExperimente" "SansSerif" 1 12 0 REF 339 
            CH.ifa.draw.standard.OffsetLocator 59 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8021 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 923 717 20 20 NULL REF 52  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8022 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 952 726 "Wasser" "SansSerif" 1 12 0 REF 360 
            CH.ifa.draw.standard.OffsetLocator 46 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8023 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 923 570 20 20 NULL REF 52  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8024 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 952 579 "Wasser" "SansSerif" 1 12 0 REF 364 
            CH.ifa.draw.standard.OffsetLocator 46 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8025 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 923 850 20 20 NULL REF 52  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8026 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 952 859 "Wasser" "SansSerif" 1 12 0 REF 368 
            CH.ifa.draw.standard.OffsetLocator 46 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8027 2 933 737 933 763 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 360  
            CH.ifa.draw.standard.ChopBoxConnector REF 329   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8028 2 933 590 933 617 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 364  
            CH.ifa.draw.standard.ChopBoxConnector REF 334   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8029 2 933 870 933 898 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 368  
            CH.ifa.draw.standard.ChopBoxConnector REF 324   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8030 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 929 743 "w" "SansSerif" 0 12 0 REF 372 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8031 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 929 596 "w" "SansSerif" 0 12 0 REF 375 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8032 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 929 877 "w" "SansSerif" 0 12 0 REF 378 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8033 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 26 533 "[führe Experimente mit Prüfung durch]" "SansSerif" 0 28 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8034 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 49 290 "manual" "SansSerif" 0 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator -39 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FillColor" "Color" 204 204 204 255 "FigureWithID" "Int" 8035 39 13 664 168 50 34  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8036 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 58 24 "FA: Physiker, der den Zustand erfragt" "SansSerif" 0 18 0 REF 394 
            CH.ifa.draw.standard.OffsetLocator -146 -62 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8037 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 56 52 "Dieses Netz stellt einen Physiker dar, der Experimente an Wasser durchführt.\n\nEr kann entweder das Wasser entweder direkt manipulieren, oder konkrete Experimente durchführen.\nEsperimente sind einfache Abfolgen von Manipulationen des Wassers. Am Ende eines Experiments\nerwartet der Physiker einen bestimmten Zustand des Wassers.\n\nDer Physiker kann vor Experimenten prüfen, welchen Zustand das Wasser hat, oder er führt\nExperimente ohne explizite Prüfung des Zustands durch." "SansSerif" 0 12 0 REF 394 
            CH.ifa.draw.standard.OffsetLocator 5 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8038 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 499 192 "[maniuliere Wasser]" "SansSerif" 0 28 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8039 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 27 192 "[entnehme Wasserprobe]" "SansSerif" 0 28 0 NULL NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8050 "FrameColor" "Color" 255 0 0 255 "FillColor" "Color" 255 200 0 255 144 1277 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8052 2 168 1284 251 1284 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 403  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8053 250 1274 20 20 NULL    REF 408 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8054 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 205 1277 "w" "SansSerif" 0 12 0 REF 404 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8072 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 133 1278 "manual" "SansSerif" 0 12 0 REF 403 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8075 2 269 1281 564 1143 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 408  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8076 564 1130 24 16 NULL    REF 419 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8077 2 270 1284 564 1283 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 408  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8078 564 1275 24 16 NULL    REF 424 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8079 2 269 1288 564 1412 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 408  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8080 564 1410 24 16 NULL    REF 429 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8081 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 535 1148 "w:erstarren()" "SansSerif" 0 12 0 REF 419 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8082 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 529 1294 "w:sublimieren()" "SansSerif" 0 12 0 REF 424 
            CH.ifa.draw.standard.OffsetLocator 0 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8083 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 522 1428 "w:kondensieren()" "SansSerif" 0 12 0 REF 429 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8093 2 657 1378 588 1411 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8165 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 655 1363 20 20 NULL REF 52   
            CH.ifa.draw.standard.ChopBoxConnector REF 429   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8094 2 657 1243 588 1276 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8161 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 655 1228 20 20 NULL REF 52   
            CH.ifa.draw.standard.ChopBoxConnector REF 424   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8095 2 657 1098 588 1131 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8157 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 655 1083 20 20 NULL REF 52   
            CH.ifa.draw.standard.ChopBoxConnector REF 419   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8096 2 41 1285 144 1285 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8155 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 21 1275 20 20 NULL REF 52   
            CH.ifa.draw.standard.ChopBoxConnector REF 403   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8097 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 88 1278 "w" "SansSerif" 0 12 0 REF 451 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8098 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 618 1387 "w" "SansSerif" 0 12 0 REF 439 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8099 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 618 1252 "w" "SansSerif" 0 12 0 REF 443 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8100 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 618 1107 "w" "SansSerif" 0 12 0 REF 447 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8101 2 588 1138 656 1138 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 419  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8102 655 1128 20 20 NULL    REF 471 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8103 2 675 1138 742 1138 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 471  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8104 742 1130 24 16 NULL    REF 476 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8105 2 588 1283 656 1283 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 424  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8106 655 1273 20 20 NULL    REF 481 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8107 2 675 1283 742 1283 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 481  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8108 742 1275 24 16 NULL    REF 486 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8109 2 588 1418 656 1418 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 429  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8110 655 1408 20 20 NULL    REF 491 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8111 2 675 1418 742 1418 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 491  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8112 742 1411 24 16 NULL    REF 496 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8113 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 707 1148 "w:sublimieren()" "SansSerif" 0 12 0 REF 476 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8114 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 700 1293 "w:kondensieren()" "SansSerif" 0 12 0 REF 486 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8115 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 713 1429 "w:erstarren()" "SansSerif" 0 12 0 REF 496 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8116 2 766 1138 837 1138 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 476  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8117 836 1128 20 20 NULL    REF 510 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8118 2 766 1283 837 1283 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 486  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8119 836 1273 20 20 NULL    REF 515 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8120 2 766 1419 837 1419 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 496  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8121 836 1409 20 20 NULL    REF 520 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8122 2 674 1098 742 1131 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 449  
            CH.ifa.draw.standard.ChopBoxConnector REF 476   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8123 2 674 1243 742 1276 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 445  
            CH.ifa.draw.standard.ChopBoxConnector REF 486   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8124 2 674 1378 742 1412 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 441  
            CH.ifa.draw.standard.ChopBoxConnector REF 496   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8125 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 704 1252 "w" "SansSerif" 0 12 0 REF 524 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8126 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 704 1107 "w" "SansSerif" 0 12 0 REF 521 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8127 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 704 1388 "w" "SansSerif" 0 12 0 REF 527 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8128 2 856 1419 921 1419 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 520  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8129 921 1411 24 16 NULL    REF 543 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8130 2 856 1283 921 1283 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 515  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8131 921 1276 24 16 NULL    REF 548 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8132 2 856 1138 921 1138 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 510  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8133 921 1130 24 16 NULL    REF 553 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8134 2 945 1284 1068 1284 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 548  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FillColor" "Color" 0 255 0 255 "FigureWithID" "Int" 8135 1067 1274 20 20 NULL    REF 558 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8136 2 940 1146 1071 1278 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 553  
            CH.ifa.draw.figures.ChopEllipseConnector REF 558   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8137 2 941 1411 1071 1291 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 543  
            CH.ifa.draw.figures.ChopEllipseConnector REF 558   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8138 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 867 1297 "w:getLabel(\"Wasser\")" "SansSerif" 0 12 0 REF 548 
            CH.ifa.draw.standard.OffsetLocator 0 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8139 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 870 1148 "w:getLabel(\"Dampf\")" "SansSerif" 0 12 0 REF 553 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8140 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 881 1429 "w:getLabel(\"Eis\")" "SansSerif" 0 12 0 REF 543 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8141 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1064 1249 "Anzahl erfolgreicher\nExperimente" "SansSerif" 1 12 0 REF 558 
            CH.ifa.draw.standard.OffsetLocator 59 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8148 2 933 1251 933 1276 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8163 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 923 1231 20 20 NULL REF 52   
            CH.ifa.draw.standard.ChopBoxConnector REF 548   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8149 2 931 1105 932 1130 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8159 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 920 1085 20 20 NULL REF 52   
            CH.ifa.draw.standard.ChopBoxConnector REF 553   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8150 2 932 1386 932 1411 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8167 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 51 255 255 255 922 1366 20 20 NULL REF 52   
            CH.ifa.draw.standard.ChopBoxConnector REF 543   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8151 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 929 1256 "w" "SansSerif" 0 12 0 REF 579 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8152 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 927 1110 "w" "SansSerif" 0 12 0 REF 583 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8153 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 928 1391 "w" "SansSerif" 0 12 0 REF 587 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8154 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 26 1046 "[führe Experimente ohne Prüfung durch]" "SansSerif" 0 28 0 NULL NULL  REF 453 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8156 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 37 1291 "Wasser" "SansSerif" 1 12 0 REF 453 
            CH.ifa.draw.standard.OffsetLocator 33 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 449 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8158 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 673 1099 "Wasser" "SansSerif" 1 12 0 REF 449 
            CH.ifa.draw.standard.OffsetLocator 35 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 585 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8160 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 937 1100 "Wasser" "SansSerif" 1 12 0 REF 585 
            CH.ifa.draw.standard.OffsetLocator 34 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 445 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8162 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 672 1244 "Wasser" "SansSerif" 1 12 0 REF 445 
            CH.ifa.draw.standard.OffsetLocator 34 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 581 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8164 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 940 1244 "Wasser" "SansSerif" 1 12 0 REF 581 
            CH.ifa.draw.standard.OffsetLocator 34 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 441 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8166 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 673 1375 "Wasser" "SansSerif" 1 12 0 REF 441 
            CH.ifa.draw.standard.OffsetLocator 35 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 589 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8168 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 940 1378 "Wasser" "SansSerif" 1 12 0 REF 589 
            CH.ifa.draw.standard.OffsetLocator 35 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 8169 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 413 1276 "w" "SansSerif" 0 12 0 REF 420 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 8170 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 412 1205 "w" "SansSerif" 0 12 0 REF 415 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 8171 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 412 1343 "w" "SansSerif" 0 12 0 REF 425 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FillColor" "Color" 0 0 255 51 "FigureWithID" "Int" 8173 38 235 273 240 8 8  NULL  65 489 1535 876 