
    CH.ifa.draw.cpn.CPNDrawing 4 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 250 133 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 252 284 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 262 149 262 285 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 283 131 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 35 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
