11 
    de.renew.gui.CPNDrawing 41 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 443 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 179 26 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 444 "FillColor" "Color" 112 219 147 255 2 199 42 251 89 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 445 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 247 85 20 20 NULL    REF 6 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 446 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 115 85 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 447 "FillColor" "Color" 112 219 147 255 2 251 102 199 152 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 448 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 179 152 24 16 NULL    REF 12 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 449 "FillColor" "Color" 112 219 147 255 2 182 152 132 102 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 12  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 450 "FillColor" "Color" 112 219 147 255 2 132 89 182 42 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 451 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 180 185 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 452 "FillColor" "Color" 112 219 147 255 2 200 201 252 248 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 21  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 453 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 248 244 20 20 NULL    REF 26 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 454 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 116 244 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 455 "FillColor" "Color" 112 219 147 255 2 252 261 200 311 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 456 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 180 311 24 16 NULL    REF 32 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 457 "FillColor" "Color" 112 219 147 255 2 183 311 133 261 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 32  
            CH.ifa.draw.figures.ChopEllipseConnector REF 27   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 458 "FillColor" "Color" 112 219 147 255 2 133 248 183 201 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 27  
            CH.ifa.draw.standard.ChopBoxConnector REF 21   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 459 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 112 219 147 255 121 88 "[]" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 460 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 112 219 147 255 122 247 "[]" "SansSerif" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 461 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 213 23 "produce" "SansSerif" 1 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 60 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 462 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 204 149 "give" "SansSerif" 1 18 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 33 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 463 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 210 182 "get" "SansSerif" 1 18 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator 33 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 464 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 208 308 "consume" "SansSerif" 1 18 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 57 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 465 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 87 148 "this:get();" "SansSerif" 2 18 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator -62 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 466 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 128 181 ":get()" "SansSerif" 2 18 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator -41 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 467 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 9 333 "action System.out.println(\"Consuming...\");" "SansSerif" 2 18 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 0 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 468 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 19 1 "action System.out.println(\"Producing...\");" "SansSerif" 2 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 5 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 469 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 0 255 255 323 85 20 20 NULL  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 470 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 0 255 255 181 88 20 20 NULL REF 71  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 471 2 191 42 191 89 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 72   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 472 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 350 73 "product\nblueprint" "SansSerif" 1 18 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator 60 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 473 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 329 88 "[]" "SansSerif" 0 12 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 474 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 229 88 "p2" "SansSerif" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator -20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 475 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 97 88 "p1" "SansSerif" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 476 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 231 247 "c2" "SansSerif" 1 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator -20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 477 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 99 247 "c1" "SansSerif" 1 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator -20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 478 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 305 88 "pb" "SansSerif" 1 12 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator -20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 479 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 296 140 "ANALYSE MARKING p2:1, c2:1, pb:1" "SansSerif" 0 18 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 480 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 297 170 "FORMULA pb > 0" "SansSerif" 0 18 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 481 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 300 204 "ANALYSE MARKING p2:1, c2:1, pb:0" "SansSerif" 0 18 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 482 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 298 234 "FORMULA pb = 0" "SansSerif" 0 18 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 483 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 298 263 "ANALYSE MARKING b1:1, a2:1 OR ok=0" "SansSerif" 0 18 0 NULL NULL  NULL  753 220 619 600 