
    CH.ifa.draw.cpn.CPNDrawing 13 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 72 129 24 16  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 82 258 24 16  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 277 132 24 16  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 287 260 24 16  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 300 389 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 129 130 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 59 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 117 259 "this:tu()" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 44 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 317 132 ":tu()" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 39 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 316 260 ":tu()" "Helvetica" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 28 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 332 387 ":tu()" "Helvetica" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 31 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 286 133 "a" "Helvetica" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 296 261 "b" "Helvetica" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 309 390 "c" "Helvetica" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2   
