
    CH.ifa.draw.cpn.CPNDrawing 4 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 187 128 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 216 114 "verify" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 33 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 216 130 ":process(t)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 45 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 216 146 "t:verifying()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 47 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
