7 
    de.renew.gui.CPNDrawing 131 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 117 264 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 239 128 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 274 267 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 11 2 137 274 274 274 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 13 "MarkingAppearance" "Int" 0 2 286 283 286 325 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 14 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 276 324 20 20 NULL    REF 12 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 16 "MarkingAppearance" "Int" 0 2 286 344 286 383 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 12  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 17 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 274 383 24 16 NULL    REF 17 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 37 "MarkingAppearance" "Int" 0 2 285 399 285 439 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 17  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 38 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 275 438 20 20 NULL    REF 22 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 43 "MarkingAppearance" "Int" 0 2 295 448 353 448 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 22  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 44 "MarkingAppearance" "Int" 0 353 441 24 16 NULL    REF 27 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 50 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 274 502 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 51 "MarkingAppearance" "Int" 0 2 298 510 461 510 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 28  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 52 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 460 500 20 20 NULL    REF 33 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 55 "MarkingAppearance" "Int" 0 2 285 458 285 502 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 22  
            CH.ifa.draw.standard.ChopBoxConnector REF 28   
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 81 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 355 265 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 82 "MarkingAppearance" "Int" 0 2 356 275 298 275 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 38  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 86 "MarkingAppearance" "Int" 0 459 267 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 93 "MarkingAppearance" "Int" 0 2 459 275 375 275 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 43  
            CH.ifa.draw.figures.ChopEllipseConnector REF 38   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 39 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 177 415 "[binding,transition]" "Helvetica" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator -58 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 54 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 179 473 "[binding,transition]" "Helvetica" 0 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator -56 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 108 3 274 510 127 510 127 284 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 28  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 110 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 115 198 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 111 2 127 214 127 265 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 58  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 57 258 "possibly\nactivated" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -44 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 119 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 316 61 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 120 2 318 77 257 132 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 66  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 123 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 237 61 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 124 3 251 77 260 101 252 129 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 72  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 125 3 247 130 236 103 245 77 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 72   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 136 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 632 344 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 147 "MarkingAppearance" "Int" 0 275 616 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 150 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 188 326 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 151 "MarkingAppearance" "Int" 0 2 212 334 277 334 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 83  
            CH.ifa.draw.figures.ChopEllipseConnector REF 12   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 154 "MarkingAppearance" "Int" 0 2 296 334 404 334 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 12  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 246 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 404 326 24 16 NULL    
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 155 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 665 207 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 158 "MarkingAppearance" "Int" 0 2 677 207 677 180 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 94  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 159 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 667 160 20 20 NULL    REF 99 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 167 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 665 119 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 171 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 156 61 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 174 2 242 133 177 77 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 101   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 129 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 218 81 "old" "Helvetica" 0 12 0 REF 77 
            CH.ifa.draw.standard.OffsetLocator -15 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 177 "MarkingAppearance" "Int" 0 2 286 518 286 556 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 28  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 178 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 276 555 20 20 NULL    REF 114 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 179 "MarkingAppearance" "Int" 0 2 286 575 286 616 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 114  
            CH.ifa.draw.standard.ChopBoxConnector REF 82   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 181 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 242 585 "binding" "Helvetica" 0 12 0 REF 115 
            CH.ifa.draw.standard.OffsetLocator -24 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 180 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 242 530 "binding" "Helvetica" 0 12 0 REF 110 
            CH.ifa.draw.standard.OffsetLocator -24 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 45 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 303 456 "[null,transition]" "Helvetica" 0 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 18 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 4 "FigureWithID" "Int" 182 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 254 254 254 "FillColor" "Color" 254 254 254 358 327 14 14  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 83 "MarkingAppearance" "Int" 0 2 365 441 365 285 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 27  
            CH.ifa.draw.figures.ChopEllipseConnector REF 38   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 85 "MarkingAppearance" "Int" 0 2 470 501 470 283 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 33  
            CH.ifa.draw.standard.ChopBoxConnector REF 43   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 170 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 218 43 "guard old>=0" "Helvetica" 0 12 0 REF 72 
            CH.ifa.draw.standard.OffsetLocator 5 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 84 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 165 604 "action\n  binding.execute()" "Helvetica" 0 12 0 REF 82 
            CH.ifa.draw.standard.OffsetLocator -72 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 188 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 632 495 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 192 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 667 526 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 193 "MarkingAppearance" "Int" 0 2 671 530 652 511 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 144  
            CH.ifa.draw.standard.ChopBoxConnector REF 143   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 194 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 700 494 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 195 "MarkingAppearance" "Int" 0 2 684 530 703 510 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 144  
            CH.ifa.draw.standard.ChopBoxConnector REF 149   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 196 "MarkingAppearance" "Int" 0 2 651 495 671 475 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL 
            CH.ifa.draw.standard.ChopBoxConnector REF 143  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 197 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 667 458 20 20 NULL    REF 158 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 198 "MarkingAppearance" "Int" 0 2 703 494 684 475 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 149  
            CH.ifa.draw.figures.ChopEllipseConnector REF 158   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 199 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 665 418 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 200 "MarkingAppearance" "Int" 0 2 677 459 677 434 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 158  
            CH.ifa.draw.standard.ChopBoxConnector REF 163   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 134 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 637 384 ":startRun()" "Helvetica" 0 12 0 REF 163 
            CH.ifa.draw.standard.OffsetLocator -12 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 135 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 628 400 "this:setMode(old,2)" "Helvetica" 0 12 0 REF 163 
            CH.ifa.draw.standard.OffsetLocator 3 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 142 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 674 461 "[]" "Helvetica" 0 12 0 REF 158 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 187 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 693 455 "mutex" "Helvetica" 1 12 0 REF 158 
            CH.ifa.draw.standard.OffsetLocator 34 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 2 "FigureWithID" "Int" 203 "LineStyle" "Int" 10 2 528 40 528 646 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 206 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 176 89 "-1" "Helvetica" 0 12 0 REF 102 
            CH.ifa.draw.standard.OffsetLocator -26 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 208 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 353 198 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 211 2 365 266 365 214 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 38  
            CH.ifa.draw.standard.ChopBoxConnector REF 185   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 156 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 635 228 ":terminateRun()" "Helvetica" 0 12 0 REF 94 
            CH.ifa.draw.standard.OffsetLocator 0 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 53 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 300 517 "guard\n  binding!=null" "Helvetica" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 52 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 215 "MarkingAppearance" "Int" 0 3 671 462 602 393 635 360 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 158  
            CH.ifa.draw.standard.ChopBoxConnector REF 81   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 216 "MarkingAppearance" "Int" 0 2 651 344 671 324 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 81  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 217 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 667 307 20 20 NULL    REF 205 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 218 "MarkingAppearance" "Int" 0 2 684 324 703 344 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 205  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 219 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 700 344 24 16 NULL    REF 210 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 220 "MarkingAppearance" "Int" 0 3 720 360 753 393 684 462 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 210  
            CH.ifa.draw.figures.ChopEllipseConnector REF 158   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 137 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 566 339 ":stopRun()" "Helvetica" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator -50 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 225 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 731 337 ":stoppedRun()" "Helvetica" 0 12 0 REF 210 
            CH.ifa.draw.standard.OffsetLocator 58 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 226 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 733 352 "this:isIdle()" "Helvetica" 0 12 0 REF 210 
            CH.ifa.draw.standard.OffsetLocator 50 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 131 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 733 502 "this:isIdle()" "Helvetica" 0 12 0 REF 149 
            CH.ifa.draw.standard.OffsetLocator 50 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 228 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 362 268 "[]" "Helvetica" 0 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 227 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 246 131 "0" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 132 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 730 487 ":stepped()" "Helvetica" 0 12 0 REF 149 
            CH.ifa.draw.standard.OffsetLocator 45 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 230 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 67 227 "transition" "Helvetica" 0 12 0 REF 59 
            CH.ifa.draw.standard.OffsetLocator -35 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 80 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 292 353 "transition" "Helvetica" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 31 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 15 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 292 296 "transition" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 31 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 231 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 221 339 "transition" "Helvetica" 0 12 0 REF 84 
            CH.ifa.draw.standard.OffsetLocator 2 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 23 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 178 372 "action binding=\n  transition.find()" "Helvetica" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator -65 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 232 "MarkingAppearance" "Int" 0 "Visibility" "Boolean" "FALSE" 381 322 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 233 "Visibility" "Boolean" "FALSE" 2 298 384 383 337 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 17  
            CH.ifa.draw.figures.ChopEllipseConnector REF 251   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 235 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 415 317 "null;\n\"binding\"" "Helvetica" 0 12 0 REF 251 
            CH.ifa.draw.standard.OffsetLocator 48 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 234 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 314 362 "binding" "Helvetica" 0 12 0 REF 252 
            CH.ifa.draw.standard.OffsetLocator -6 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 204 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 411 38 "simulation\nthread" "Helvetica" 1 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 236 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 543 38 "gui\nthread" "Helvetica" 1 12 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 121 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 273 117 "mode" "Helvetica" 0 12 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator 1 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 128 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 259 78 "mode" "Helvetica" 0 12 0 REF 73 
            CH.ifa.draw.standard.OffsetLocator 19 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 237 237 198 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 238 3 246 147 236 172 245 198 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 271   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 239 3 252 198 261 175 252 148 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 271  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.InhibitorConnection "attributes" "attributes" 1 "FigureWithID" "Int" 242 2 136 270 237 212 
            de.renew.gui.CircleDecoration  
            de.renew.gui.CircleDecoration  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 271   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 243 2 261 213 357 271 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 271  
            CH.ifa.draw.figures.ChopEllipseConnector REF 38   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 213 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 335 149 ":isIdle()" "Helvetica" 0 12 0 REF 185 
            CH.ifa.draw.standard.OffsetLocator -10 -50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 244 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 311 166 "this:getMode(mode)" "Helvetica" 0 12 0 REF 185 
            CH.ifa.draw.standard.OffsetLocator 0 -33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 214 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 330 181 "guard mode<=0;" "Helvetica" 0 12 0 REF 185 
            CH.ifa.draw.standard.OffsetLocator 10 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 236 250 "guard mode>0" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -10 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 127 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 197 27 ":setMode(old,mode)" "Helvetica" 0 12 0 REF 72 
            CH.ifa.draw.standard.OffsetLocator 2 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 122 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 307 42 ":getMode(mode)" "Helvetica" 0 12 0 REF 66 
            CH.ifa.draw.standard.OffsetLocator 24 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 241 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 223 167 "1" "Helvetica" 0 12 0 REF 272 
            CH.ifa.draw.standard.OffsetLocator -15 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 240 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 268 167 "0" "Helvetica" 0 12 0 REF 276 
            CH.ifa.draw.standard.OffsetLocator 15 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 157 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 622 244 "this:setMode(old,-1)" "Helvetica" 0 12 0 REF 94 
            CH.ifa.draw.standard.OffsetLocator 0 36 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 245 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 197 234 "this:getMode(mode)" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -35 -34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 12 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 193 277 "transition" "Helvetica" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 13 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 109 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 69 312 "transition" "Helvetica" 0 12 0 REF 54 
            CH.ifa.draw.standard.OffsetLocator -106 -78 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 93 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 207 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 333 280 "idle" "Helvetica" 1 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator -22 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 200 132 "mode" "Helvetica" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -33 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 247 2 409 326 372 283 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 93  
            CH.ifa.draw.figures.ChopEllipseConnector REF 38   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 248 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 372 345 "this:getMode(-1)" "Helvetica" 0 12 0 REF 93 
            CH.ifa.draw.standard.OffsetLocator 2 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 250 2 677 161 677 135 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 99  
            CH.ifa.draw.standard.ChopBoxConnector REF 100   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 168 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 630 85 ":terminatedRun()" "Helvetica" 0 12 0 REF 100 
            CH.ifa.draw.standard.OffsetLocator -1 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 251 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 647 100 "this:isIdle()" "Helvetica" 0 12 0 REF 100 
            CH.ifa.draw.standard.OffsetLocator -1 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 152 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 156 294 "action\n  transition.search()" "Helvetica" 0 12 0 REF 83 
            CH.ifa.draw.standard.OffsetLocator 8 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 172 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 89 43 ":setMode(-1,mode)" "Helvetica" 0 12 0 REF 101 
            CH.ifa.draw.standard.OffsetLocator -26 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 175 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 440 220 "this:setMode(\n  mode,\n  (mode/2)*2)" "Helvetica" 0 12 0 REF 43 
            CH.ifa.draw.standard.OffsetLocator 5 -33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 138 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 546 354 "this:setMode(\n  old,0)" "Helvetica" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator -62 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 130 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 550 507 "this:setMode(\n  old,1)" "Helvetica" 0 12 0 REF 143 
            CH.ifa.draw.standard.OffsetLocator -58 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 114 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 590 491 ":step()" "Helvetica" 0 12 0 REF 143 
            CH.ifa.draw.standard.OffsetLocator -37 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  325 91 882 863 