11 
    de.renew.gui.CPNDrawing 45 
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4169 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 127 140 163 220 3  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4170 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 9 318 106 33  
        de.renew.bpmn.roundtrip.RoundtripNetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4171 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 22 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4182 2 278 335 310 335 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4175 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 254 328 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4181 309 325 20 20 NULL    
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4172 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 213 325 20 20 NULL  
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4173 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 254 209 24 16 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4183 "Visibility" "Boolean" "TRUE" 2 226 273 260 225 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4178 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 210 270 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector REF 11   
            de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4174 117 324 20 20 NULL  REF 7 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4184 "Visibility" "Boolean" "TRUE" 2 266 225 266 271 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 11  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4177 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 256 270 20 20 NULL    
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4176 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 21 327 24 16 NULL  REF 22 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4185 2 45 334 118 334 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 23  
                CH.ifa.draw.figures.ChopEllipseConnector REF 17   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4186 "Visibility" "Boolean" "TRUE" 2 266 290 266 328 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 22  
                CH.ifa.draw.standard.ChopBoxConnector REF 7   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4187 "Visibility" "Boolean" "TRUE" 2 193 335 214 335 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4180 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 169 327 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 10   REF 1 REF 2 REF 15 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4188 "Visibility" "Boolean" "TRUE" 2 233 335 254 335 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 10  
                CH.ifa.draw.standard.ChopBoxConnector REF 7   
            de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4179 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 224 224 255 255 293 287 20 20 NULL 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 4207 "FillColor" "Color" 224 224 255 255 115 12 20 20 NULL   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4189 2 137 334 169 334 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 17  
                CH.ifa.draw.standard.ChopBoxConnector REF 35   REF 35 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4190 "Visibility" "Boolean" "TRUE" 2 186 327 215 288 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 35  
                CH.ifa.draw.figures.ChopEllipseConnector REF 15   REF 9 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4191 2 273 328 297 304 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 7  
                CH.ifa.draw.figures.ChopEllipseConnector REF 41   "start"  REF 10 REF 11 REF 17 REF 7 REF 23 REF 22 REF 15 REF 41 REF 35 REF 9 REF 4 REF 12 REF 18 REF 24 REF 28 REF 32 REF 37 REF 43 REF 47 REF 51 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4192 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 253 189 ":in(p)" "SansSerif" 0 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 2 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4193 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 268 302 "p" "SansSerif" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 6 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4194 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 267 241 "p" "SansSerif" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 5 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4195 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 320 327 ">" "SansSerif" 1 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 6 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4196 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 300 290 "P" "SansSerif" 1 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4197 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 278 302 "p" "SansSerif" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator -3 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4198 2 135 22 164 22 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 42  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4199 164 14 24 16 NULL    REF 77 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4200 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 145 15 "p" "SansSerif" 0 12 0 REF 73 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4201 2 188 22 231 22 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 77  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 4202 "FillColor" "Color" 224 224 255 255 230 12 20 20 NULL    REF 85 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4203 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 205 15 "p" "SansSerif" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 4204 "FillColor" "Color" 224 224 255 255 230 36 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4205 3 176 30 176 46 231 46 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 77  
            CH.ifa.draw.figures.ChopEllipseConnector REF 89   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4206 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 257 16 "Perf" "SansSerif" 1 12 0 REF 85 
            CH.ifa.draw.standard.OffsetLocator 29 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 42 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4208 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 123 15 "P" "SansSerif" 1 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4209 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 12 302 ":start()" "SansSerif" 0 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator -2 -26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4210 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 126 278 "START\n( IN )" "SansSerif" 1 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator -35 -42 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4211 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 229 95 "[fromAgent]" "SansSerif" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 73 -144 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.DeclarationFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 4212 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 45 410 "import de.renew.agent.repr.acl.*;\nimport java.util.*;\nimport de.renew.agent.webgateway.ontology.*;\nimport de.renew.agent.repr.capamgmt.*;\nimport de.renew.agent.repr.common.*;\nimport de.renew.agent.repr.sl.*;\nimport de.renew.net.NetInstance;\n\nNetInstance wb,kb;\nAclMessage p, p2,message,ack ;\nAgentIdentifier aid,selfAid;\n\nBoolean bool;\nboolean cond;\nObject o;\nObject[] os;\nString s;\nVector v;\nint y,id;\nIterator  it;\nVTSet aidvts;" "SansSerif" 0 12 0 NULL NULL 1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4213 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 149 375 "[comment]" "SansSerif" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -12 136 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    NULL  395 22 881 778 