11 
    de.renew.gui.CPNDrawing 32 
        CH.ifa.draw.figures.GroupFigure 2 
            CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5639 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -19 -125 127 65 0  
            CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5640 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -20 -60 129 83   
        de.renew.bpmn.roundtrip.RoundtripNetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5641 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 15 
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 689 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 78 -48 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 690 2 56 0 77 0 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 684 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 36 -10 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 682 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 77 -8 24 16 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 692 2 2 -8 2 -31 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 681 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -10 -8 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 683 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -8 -51 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 688 2 52 -74 82 -44 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 685 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 33 -90 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 5   REF 17 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 687 2 14 0 37 0 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 15  
                CH.ifa.draw.figures.ChopEllipseConnector REF 9   
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 695 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 255 126 -10 20 20 NULL  REF 9 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 686 "Visibility" "Boolean" "TRUE" 2 9 -47 36 -74 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 17  
                CH.ifa.draw.standard.ChopBoxConnector REF 21   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 694 "Visibility" "Boolean" "TRUE" 2 101 0 127 0 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 11  
                CH.ifa.draw.figures.ChopEllipseConnector REF 27   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 693 2 88 -28 88 -8 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 5  
                CH.ifa.draw.standard.ChopBoxConnector REF 11   REF 15 REF 21 REF 1 REF 11 "subcall"  REF 5 REF 17 REF 27 REF 9 REF 15 REF 21 REF 11 REF 6 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 706 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -15 38 "!!!Bei mehreren SubCalls\nBezeichner der synchronen\nKanaele anpassen!!!" "SansSerif" 0 12 0 NULL NULL  REF 12 REF 18 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 699 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 63 9 "this:ret1()" "SansSerif" 0 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 2 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 23 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 698 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 21 -42 "SubCall" "SansSerif" 1 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -2 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 691 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 -15 -7 ">" "SansSerif" 1 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -12 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 28 REF 32 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 696 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 140 -8 ">" "SansSerif" 1 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 36 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 697 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 12 -113 "this:sub1()" "SansSerif" 0 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator -3 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 677 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -1 259 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 678 "Visibility" "Boolean" "TRUE" 2 23 267 49 267 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 56  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 679 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 255 48 257 20 20 NULL    REF 61 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 700 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -9 278 ":sub1()" "SansSerif" 0 12 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator 0 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 701 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 140 259 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 704 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 130 205 "SubCall\nend\nhere" "SansSerif" 1 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator 1 -40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 703 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 -10 211 "SubCall\nstart\nhere" "SansSerif" 1 12 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator 2 -34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 705 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 135 278 ":ret1()" "SansSerif" 0 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator 1 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 702 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 134 260 ">" "SansSerif" 1 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator -13 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 680 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 63 259 ">" "SansSerif" 1 12 0 REF 61 
            CH.ifa.draw.standard.OffsetLocator 10 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  NULL  365 276 806 636 