
    CH.ifa.draw.cpn.CPNDrawing 29 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 280 156 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 212 222 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 211 318 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 213 408 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 349 310 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 351 401 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 283 172 229 226 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.ArcConnection 2 222 242 222 318 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        CH.ifa.draw.cpn.ArcConnection 2 223 334 223 409 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        CH.ifa.draw.cpn.ArcConnection 2 361 248 361 310 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector 
                CH.ifa.draw.cpn.PlaceFigure "no_attributes" 351 228 20 20   
            CH.ifa.draw.standard.ChopBoxConnector REF 5   
        CH.ifa.draw.cpn.ArcConnection 2 361 326 361 402 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.figures.ChopEllipseConnector REF 6   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 239 154 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -39 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 243 319 "obj:a()" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 37 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 379 312 "obj:b()" "Helvetica" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 35 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 22 
        CH.ifa.draw.cpn.ArcConnection 2 299 172 355 232 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 22   
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 278 476 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 230 425 281 476 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector REF 41   
        CH.ifa.draw.cpn.ArcConnection 2 355 418 297 476 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 41   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 237 180 "obj" "Helvetica" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -11 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 229 263 "obj" "Helvetica" 0 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 15 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 228 353 "obj" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 13 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 330 183 "obj" "Helvetica" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator 11 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 334 272 "obj" "Helvetica" 0 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator -19 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 334 353 "obj" "Helvetica" 0 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator -19 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 332 442 "obj" "Helvetica" 0 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 14 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 234 454 "obj" "Helvetica" 0 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator -13 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 312 144 "obj:new object" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 61 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 312 161 "obj:new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 42 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
