11 
    de.renew.gui.CPNDrawing 26 
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 110 39 27 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 111 2 59 37 102 37 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 112 102 30 24 16 NULL    REF 6 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 113 2 126 38 159 38 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 114 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 158 28 20 20 NULL    REF 11 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 115 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 141 53 "p_end1" "SansSerif" 1 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator -2 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 116 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 10 30 "[]" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -34 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 117 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 17 75 "p_start1" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -3 45 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 118 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 15 53 "\"String\"" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -11 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 119 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 77 30 "x" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 120 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 137 31 "x" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 121 243 27 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 122 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 221 49 "p_start2" "SansSerif" 1 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator -3 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 123 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 249 30 "2" "SansSerif" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 124 2 263 37 304 37 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 30  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 125 304 29 24 16 NULL    REF 41 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 126 2 328 37 370 37 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 41  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 127 369 27 20 20 NULL    REF 46 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 128 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 352 50 "p_end2" "SansSerif" 1 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator -2 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 129 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 20 30 "{}" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -21 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 130 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 3 8 "[\"a\",1,[\"b\",\"c\"]]" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 135 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 49 124 "ANALYSE MARKING p_end1: 4, p_end2: 1" "SansSerif" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 131 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 50 146 "ANALYSE MARKING p_end1: 4, p_start2: 1, p_end2: 1" "SansSerif" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 132 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 49 190 "ANALYSE PLACE p1" "SansSerif" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 133 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 50 211 "BLA UND BLUB p1>p_end2" "SansSerif" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 109 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 50 168 "ANALYSE PLACE p_end1" "SansSerif" 0 12 0 NULL NULL  NULL  382 215 466 293 