6 
    de.renew.gui.CPNDrawing 10 
        de.renew.gui.TransitionFigure "attributes" "attributes" 6 "FigureWithID" "Int" 81 "TraceMode" "Boolean" "TRUE" "FontName" "String" "Dialog" "FrameColor" "Color" 0 0 0 "FontSize" "Int" 12 "FillColor" "Color" 192 192 192 24 49 70 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 123 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 32 52 "terminate" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 139 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 89 97 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 140 "TraceMode" "Boolean" "TRUE" 2 101 113 101 168 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 141 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 91 167 20 20 NULL    REF 10 
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 143 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 96 132 "#1[]" "Helvetica" 0 12 0 REF 6
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 142 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 123 89 "[Link\n rcv: (this)\n param: #1<>]" "Helvetica" 0 12 0 REF 5
            CH.ifa.draw.standard.OffsetLocator 55 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "FigureWithID" "Int" 144 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 20 11 "access _Links;" "Helvetica" 0 12 0 NULL NULL 1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 5 "FigureWithID" "Int" 115 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 98 39 "[Link\n param:<>]" "Helvetica" 0 12 0 REF 1
            CH.ifa.draw.standard.OffsetLocator 51 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 5 "FigureWithID" "Int" 104 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 119 110 "[Link rcv: (this)\n param: #1<>]" "Helvetica" 0 12 0 REF 5
            CH.ifa.draw.standard.OffsetLocator 51 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  124 95 274 243 
