11 
    de.renew.gui.CPNDrawing 21 
        de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FigureWithID" "Int" 1476 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "DejaVu Sans Mono" "FontSize" "Int" 12 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 255 20 34 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FigureWithID" "Int" 1477 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "DejaVu Sans Mono" "FontSize" "Int" 12 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 255 20 92 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 1478 "MarkingAppearance" "Int" 2 "FontName" "String" "DejaVu Sans Mono" "FontSize" "Int" 12 "FontStyle" "Int" 0 2 40 47 107 69 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1479 "MarkingAppearance" "Int" 2 "FontName" "String" "DejaVu Sans Mono" "FontSize" "Int" 12 "FontStyle" "Int" 0 107 65 24 16 NULL    REF 7 
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 1480 "MarkingAppearance" "Int" 2 "FontName" "String" "DejaVu Sans Mono" "FontSize" "Int" 12 "FontStyle" "Int" 0 2 40 100 107 76 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 7   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1481 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 70 51 "a" "DejaVu Sans Mono" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1482 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 70 81 "b" "DejaVu Sans Mono" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 1483 "MarkingAppearance" "Int" 2 "FontName" "String" "DejaVu Sans Mono" "FontSize" "Int" 12 "FontStyle" "Int" 0 2 131 69 199 47 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FigureWithID" "Int" 1484 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "DejaVu Sans Mono" "FontSize" "Int" 12 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 255 198 34 20 20 NULL    REF 22 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1485 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 148 51 "a + b" "DejaVu Sans Mono" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 1486 "MarkingAppearance" "Int" 2 "FontName" "String" "DejaVu Sans Mono" "FontSize" "Int" 12 "FontStyle" "Int" 0 2 131 76 199 100 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FigureWithID" "Int" 1487 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "DejaVu Sans Mono" "FontSize" "Int" 12 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 255 198 92 20 20 NULL    REF 30 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1488 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 162 81 "c" "DejaVu Sans Mono" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1489 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 95 46 "numbers" "DejaVu Sans Mono" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 0 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1490 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 23 57 "i1" "DejaVu Sans Mono" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1467 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 23 115 "i2" "DejaVu Sans Mono" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 0 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1491 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 201 57 "o1" "DejaVu Sans Mono" 1 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator 0 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1492 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 201 115 "o2" "DejaVu Sans Mono" 1 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 0 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1494 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 15 76 "4,5,6" "DejaVu Sans Mono" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 2 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1495 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 13 19 "1,2,3" "DejaVu Sans Mono" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1496 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 70 99 "b < 6 && c > 1\n  where\n    c = b - a" "DejaVu Sans Mono" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 0 48 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  4 218 268 195 