8 
    de.renew.gui.CPNDrawing 68 
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 1 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 340 245 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 263 322 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 183 252 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 263 172 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 413 172 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 6 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 413 317 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 7 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 211 301 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 8 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 340 385 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 9 "BSplineDegree" "Int" 2 "LineShape" "Int" 1 "BSplineSegments" "Int" 15 3 349 265 338 321 287 328 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 10 "BSplineDegree" "Int" 2 "LineShape" "Int" 1 "BSplineSegments" "Int" 15 3 263 328 244 326 229 316 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 11 "BSplineDegree" "Int" 2 "LineShape" "Int" 1 "BSplineSegments" "Int" 15 3 215 305 202 291 196 268 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 12 "BSplineDegree" "Int" 2 "LineShape" "Int" 1 "BSplineSegments" "Int" 15 3 195 252 197 228 212 210 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 47 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 207 192 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 13 "BSplineDegree" "Int" 2 "LineShape" "Int" 1 "BSplineSegments" "Int" 15 3 225 197 241 185 263 181 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector REF 4   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 14 "BSplineDegree" "Int" 2 "LineShape" "Int" 1 "BSplineSegments" "Int" 15 3 287 181 344 190 350 246 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 4  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 15 "BSplineDegree" "Int" 2 "LineShape" "Int" 1 "BSplineSegments" "Int" 15 3 353 265 366 311 413 322 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 16 "BSplineDegree" "Int" 2 "LineShape" "Int" 1 "BSplineSegments" "Int" 15 3 437 322 488 314 499 265 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 46 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 490 245 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 17 "BSplineDegree" "Int" 2 "LineShape" "Int" 1 "BSplineSegments" "Int" 15 3 500 246 494 190 437 181 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 42  
            CH.ifa.draw.standard.ChopBoxConnector REF 5   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 18 "BSplineDegree" "Int" 2 "LineShape" "Int" 1 "BSplineSegments" "Int" 15 5 425 188 425 221 425 253 393 256 360 255 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 19 "BSplineDegree" "Int" 2 "LineShape" "Int" 1 "BSplineSegments" "Int" 15 4 192 268 176 321 244 379 341 395 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 20 3 425 333 425 395 360 395 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 21 2 284 338 343 389 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 22 2 357 389 416 333 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 27 "BSplineDegree" "Int" 2 "LineShape" "Int" 1 "BSplineSegments" "Int" 15 3 413 182 357 192 351 246 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 31 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 236 172 "x" "SansSerif" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator -5 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 32 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 190 219 "x" "SansSerif" 0 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator -10 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 36 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 320 346 "x" "SansSerif" 0 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator 10 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 39 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 378 344 "x" "SansSerif" 0 12 0 REF 64 
            CH.ifa.draw.standard.OffsetLocator -5 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 40 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 414 377 "y" "SansSerif" 0 12 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator 25 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 43 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 231 289 "critical" "SansSerif" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 30 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 44 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 332 408 "token" "SansSerif" 1 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 0 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 45 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 224 224 255 40 40 90 90 NULL  REF 42 REF 25 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 49 "FrameColor" "Color" 255 199 158 "TextColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 112 38 "graph" "SansSerif" 1 12 0 REF 93 
            CH.ifa.draw.standard.OffsetLocator 45 -40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52 "FrameColor" "Color" 255 199 158 "TextColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 71 98 "[1,0]" "SansSerif" 0 12 0 REF 93 
            CH.ifa.draw.standard.OffsetLocator 0 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 53 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 2 85 130 85 194 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 93  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 54 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 224 224 255 73 194 24 16 NULL    REF 104 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 55 "FrameColor" "Color" 255 199 158 "TextColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 87 145 "[x,x]" "SansSerif" 0 12 0 REF 100 
            CH.ifa.draw.standard.OffsetLocator 15 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 56 "FrameColor" "Color" 192 192 192 2 97 202 208 202 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 104  
            CH.ifa.draw.figures.ChopEllipseConnector REF 25   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 57 "FrameColor" "Color" 192 192 192 4 85 210 85 413 314 413 342 399 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 104  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 59 "FrameColor" "Color" 255 199 158 "TextColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 149 185 "x" "SansSerif" 0 12 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator 0 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 60 "FrameColor" "Color" 192 192 192 2 130 85 205 85 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 93  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 61 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 224 224 255 205 77 24 16 NULL    REF 123 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 62 "FrameColor" "Color" 192 192 192 4 229 85 522 85 522 220 505 248 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 123  
            CH.ifa.draw.figures.ChopEllipseConnector REF 42   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63 "FrameColor" "Color" 255 199 158 "TextColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 150 88 "[x,y]" "SansSerif" 0 12 0 REF 119 
            CH.ifa.draw.standard.OffsetLocator -5 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 65 "FrameColor" "Color" 192 192 192 2 217 93 217 193 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 123  
            CH.ifa.draw.figures.ChopEllipseConnector REF 25   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 66 "FrameColor" "Color" 255 199 158 "TextColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 204 131 "x" "SansSerif" 0 12 0 REF 131 
            CH.ifa.draw.standard.OffsetLocator -10 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 67 "FrameColor" "Color" 255 199 158 "TextColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 91 78 "[0,0]" "SansSerif" 0 12 0 REF 93 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 68 "FrameColor" "Color" 255 199 158 "TextColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 200 53 "guard x!=y" "SansSerif" 0 12 0 REF 123 
            CH.ifa.draw.standard.OffsetLocator 15 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 69 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 255 157 "manual" "SansSerif" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 1 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 30 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 305 198 "[x,x]" "SansSerif" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 0 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 37 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 306 291 "[x,x]" "SansSerif" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 1 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 29 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 362 177 "[z,x]" "SansSerif" 0 12 0 REF 68 
            CH.ifa.draw.standard.OffsetLocator -7 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 23 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 456 169 "[x,z]" "SansSerif" 0 12 0 REF 43 
            CH.ifa.draw.standard.OffsetLocator 1 -37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 24 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 490 291 "[x,y]" "SansSerif" 0 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 34 5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 38 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 438 324 "guard x!=y" "SansSerif" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 45 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 25 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 373 289 "[x,y]" "SansSerif" 0 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator 2 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 26 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 393 232 "[x,y]" "SansSerif" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 13 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 33 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 207 276 "x" "SansSerif" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 5 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 34 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 242 323 "x" "SansSerif" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator -1 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 35 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 189 332 "x" "SansSerif" 0 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator -66 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 64 "FrameColor" "Color" 255 199 158 "TextColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 497 67 "[x,y]" "SansSerif" 0 12 0 REF 124 
            CH.ifa.draw.standard.OffsetLocator 134 -92 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 58 "FrameColor" "Color" 255 199 158 "TextColor" "Color" 192 192 192 "FillColor" "Color" 255 199 158 94 396 "x" "SansSerif" 0 12 0 REF 112 
            CH.ifa.draw.standard.OffsetLocator -116 92 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 51 "FrameColor" "Color" 255 199 158 "TextColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 56 78 "[2,0]" "SansSerif" 0 12 0 REF 93 
            CH.ifa.draw.standard.OffsetLocator -15 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 50 "FrameColor" "Color" 255 199 158 "TextColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 66 58 "[3,0]" "SansSerif" 0 12 0 REF 93 
            CH.ifa.draw.standard.OffsetLocator -5 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 41 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 223 210 "quiet" "SansSerif" 1 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 22 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 48 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 515 234 "compass" "SansSerif" 1 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator 42 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 42 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 283 247 "pending" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -42 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  2 134 612 483 