11 
    de.renew.gui.CPNDrawing 18 
        de.renew.gui.TransitionFigure "attributes" "attributes" 6 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 76 "TextAlignment" "Int" 0 "FillColor" "Color" 112 219 147 255 13 42 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 77 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FontName" "String" "Monospaced" 2 37 50 196 50 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 6 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 78 "TextAlignment" "Int" 0 "FillColor" "Color" 112 219 147 255 195 40 20 20 NULL    REF 6 
        de.renew.gui.TransitionFigure "attributes" "attributes" 6 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 79 "TextAlignment" "Int" 0 "FillColor" "Color" 112 219 147 255 13 152 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 80 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FontName" "String" "Monospaced" 2 37 160 196 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 6 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 81 "TextAlignment" "Int" 0 "FillColor" "Color" 112 219 147 255 195 150 20 20 NULL    REF 12 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 82 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FillColor" "Color" 254 254 254 255 112 53 "j" "Monospaced" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -1 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 83 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FillColor" "Color" 254 254 254 255 112 163 "k" "Monospaced" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator -1 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 84 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 6 5 "{! exchange (this) j 'b}\n{! exchange (this) j 'c}" "Monospaced" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 65 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 85 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 6 128 "{? exchange 'a k}" "Monospaced" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 40 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 6 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 86 "TextAlignment" "Int" 0 "FillColor" "Color" 112 219 147 255 13 227 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 87 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FontName" "String" "Monospaced" 2 37 235 196 235 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 25  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 6 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 88 "TextAlignment" "Int" 0 "FillColor" "Color" 112 219 147 255 195 225 20 20 NULL    REF 30 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 89 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FillColor" "Color" 254 254 254 255 112 238 "k" "Monospaced" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator -1 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 90 "FrameColor" "Color" 255 199 158 255 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 6 203 "{? exchange 'q k}" "Monospaced" 0 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 40 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 91 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 8 58 "down" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 92 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 13 168 "up1" "SansSerif" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 0 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 93 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 13 243 "up2" "SansSerif" 1 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 0 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  951 141 259 312 