11 
    de.renew.gui.CPNDrawing 31 
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1 227 58 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 2 2 251 68 312 79 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3 311 70 20 20 NULL    REF 6 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4 2 312 83 252 97 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 5 228 93 24 16 NULL    REF 11 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 6 2 228 97 185 87 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 11  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7 165 74 20 20 NULL    REF 16 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8 2 185 82 227 69 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9 2 175 94 174 143 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 10 162 143 24 16 NULL    REF 25 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 11 2 174 159 175 208 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 25  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 12 165 207 20 20 NULL    REF 30 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 14 2 185 216 236 205 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 30  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 15 236 195 24 16 NULL    REF 35 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 16 2 260 205 314 217 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 35  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 17 313 208 20 20 NULL    REF 40 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 18 2 315 221 257 242 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 40  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 19 233 239 24 16 NULL    REF 45 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 20 2 233 241 184 221 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 45  
            CH.ifa.draw.figures.ChopEllipseConnector REF 30   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 21 2 323 209 323 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 40  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 22 311 144 24 16 NULL    REF 54 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 23 2 322 144 321 90 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 54  
            CH.ifa.draw.figures.ChopEllipseConnector REF 6   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 24 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 171 77 "[]" "SansSerif" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 25 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 191 144 ":a()" "SansSerif" 0 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 26 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 26 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 339 145 ":b()" "SansSerif" 0 12 0 REF 54 
            CH.ifa.draw.standard.OffsetLocator 26 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 27 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 171 144 "a" "SansSerif" 1 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 28 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 319 145 "b" "SansSerif" 1 12 0 REF 54 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 29 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 236 59 "c" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 30 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 236 94 "d" "SansSerif" 1 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 31 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 245 196 "e" "SansSerif" 1 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 32 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 243 240 "f" "SansSerif" 1 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  0 178 619 600 