7 
    de.renew.gui.CPNDrawing 26 
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 1 "MarkingAppearance" "Int" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 88 128 74 97 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 285 "TraceMode" "Boolean" "FALSE" 2 162 176 295 176 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 298 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 295 168 45 17 NULL    
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 296 "MarkingAppearance" "Int" 3 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 79 322 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4 2 89 323 89 284 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 77 268 24 16 NULL    REF 11 
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 297 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 254 254 254 84 297 "#1[]" "Helvetica" 0 12 0 REF 7
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  REF 5 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 301 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 304 168 "event" "Helvetica" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 316 "MarkingAppearance" "Int" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 477 159 75 34 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 317 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 502 84 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 318 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 510 169 "\"\"" "Helvetica" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 321 "TraceMode" "Boolean" "FALSE" 2 514 100 514 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 19  
            CH.ifa.draw.figures.ChopEllipseConnector REF 18   
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 331 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 254 254 254 509 124 "#1" "Helvetica" 0 12 0 REF 23
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 319 3 507 160 494 133 510 100 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 18  
            CH.ifa.draw.standard.ChopBoxConnector REF 19   
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 320 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 254 254 254 484 123 "#2" "Helvetica" 0 12 0 REF 30
            CH.ifa.draw.standard.OffsetLocator -13 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 322 2 340 176 478 176 NULL NULL 
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.figures.ChopEllipseConnector REF 18   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FigureWithID" "Int" 332 81 154 "Net.forName(\n\"World\"\n).buildInstance()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 107 267 " action RESULT@v0@f.pack()" "Helvetica" 0 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 99 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 309 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 477 29 "[Link\n param:\n[ItemEvent\n item:#1[String]\n stateChange:(1)]]" "Helvetica" 0 12 0 REF 19
            CH.ifa.draw.standard.OffsetLocator 11 -37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 4 "" "param:item" "param" "param:stateChange"  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 286 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 254 254 254 226 170 "#1[]" "Helvetica" 0 12 0 REF 2
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 302 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 252 27 "[Link param:[ActionEvent\nactionCommand:#3]]" "Helvetica" 0 12 0 REF 5
            CH.ifa.draw.standard.OffsetLocator -2 -131 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 3 "param" "param:actionCommand" ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 323 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 254 254 254 402 169 "#5" "Helvetica" 0 12 0 REF 37
            CH.ifa.draw.standard.OffsetLocator -2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 14 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 113 283 "[Any\n f:[!CloseableFrame\n title:(\"Waste Creation\")\n visible:(true)\n components:<[!BorderLayoutPanel\n                            center: #3[!Choice items:<(\"Dirt\") (\"Can\") (\"Paper\")>]\n                            south: [!Panel\n                                         components:\n                                          <#1[!Button label:(\"A\")]\n                                            #2[!Button label:(\"C\")]>]]>\n                            background:(Color.lightGray)]\nal1:[!ActionListenerFSNet\n        listener: (this) component:#1]\nal2:[!ActionListenerFSNet\n        listener: (this) component:#2]\nal3:[!ItemListenerFSNet\n        listener: (this) component:#3]\n]" "Helvetica" 0 12 0 REF 6
            CH.ifa.draw.standard.OffsetLocator 209 135 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 30 "" "f:components:hd:center:items:tl:tl:hd" "f:background" "f:components:hd:center" "f:components:hd:center:items:tl:hd" "f:components:hd:south:components:tl:hd" "f:components" "f:components:tl" "f:components:hd" "f:components:hd:south" "f:components:hd:center:items" "al1" "f:components:hd:south:components" "f:components:hd:south:components:hd:label" "al2:listener" "f:components:hd:center:items:hd" "f:components:hd:south:components:tl:tl" "f" "f:components:hd:center:items:tl" "f:components:hd:south:components:hd" "al1:listener" "al3" "al2" "f:visible" "f:title" "f:components:hd:center:items:tl:tl" "f:components:hd:south:components:tl:hd:label" "f:components:hd:south:components:tl" "al3:listener" "f:components:hd:center:items:tl:tl:tl"  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "FigureWithID" "Int" 219 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 511 265 "access _BDItypes;\naccess _WasteCollectorTypes;\nimport de.renew.simulator.Net;\nimport de.renew.call.CloseableFrame;\nimport de.renew.formalism.fsnet.*;\nimport java.awt.*;\nimport java.awt.event.*;" "Helvetica" 0 12 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 314 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 107 114 "World" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -1 -55 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 305 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 254 254 254 255 69 "[Link\n rcv:#1\n param:[Located\n what:[Waste name:#5]\n at: [Lane name:#3]]]" "Helvetica" 0 12 0 REF 5
            CH.ifa.draw.standard.OffsetLocator -1 -61 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 7 "rcv" "param:what:name" "param:at" "param" "param:at:name" "" "param:what"  NULL  0 153 633 296 
