11 
    de.renew.gui.CPNDrawing 682 
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 771 283 295 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 772 315 254 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 773 314 322 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 774 2 301 295 320 272 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 775 2 303 311 318 326 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 776 2 334 260 344 253 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 777 344 239 24 16 NULL    REF 16 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 778 2 335 267 344 270 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 779 344 266 24 16 NULL    REF 21 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 780 2 333 329 342 323 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 781 342 309 24 16 NULL    REF 26 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 782 2 333 336 344 341 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 783 344 339 24 16 NULL    REF 31 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 784 2 366 316 379 316 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 26  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 785 378 306 20 20 NULL    REF 36 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 786 2 398 316 409 314 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 36  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 787 409 306 24 16 NULL    REF 41 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 788 2 433 318 450 325 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 41  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 789 448 318 20 20 NULL    REF 46 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 790 2 368 347 381 347 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 31  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 791 380 337 20 20 NULL    REF 51 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 792 2 400 347 412 346 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 51  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 793 412 338 24 16 NULL    REF 56 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 794 2 436 339 450 333 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 56  
            CH.ifa.draw.figures.ChopEllipseConnector REF 46   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 795 2 368 268 383 261 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 21  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 796 381 247 20 20 NULL    REF 65 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 797 2 368 250 382 255 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 65   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 798 2 401 257 414 257 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 65  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 799 414 249 24 16 NULL    REF 74 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 800 2 438 256 455 256 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 74  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 801 454 246 20 20 NULL    REF 79 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 802 2 471 263 494 284 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 79  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 803 491 284 24 16 NULL    REF 84 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 804 2 466 323 492 300 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 46  
            CH.ifa.draw.standard.ChopBoxConnector REF 84   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 805 282 437 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 806 314 396 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 807 313 464 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 808 2 300 437 319 414 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 89  
            CH.ifa.draw.figures.ChopEllipseConnector REF 90   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 809 2 302 453 317 468 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 89  
            CH.ifa.draw.figures.ChopEllipseConnector REF 91   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 810 2 333 402 343 395 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 90  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 811 343 381 24 16 NULL    REF 104 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 812 2 334 409 343 412 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 90  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 813 343 408 24 16 NULL    REF 109 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 814 2 332 471 341 465 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 91  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 815 341 451 24 16 NULL    REF 114 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 816 2 332 478 343 483 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 91  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 817 343 481 24 16 NULL    REF 119 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 818 2 365 458 378 458 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 114  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 819 377 448 20 20 NULL    REF 124 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 820 2 397 458 408 456 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 124  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 821 408 448 24 16 NULL    REF 129 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 822 2 432 460 449 467 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 129  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 823 447 460 20 20 NULL    REF 134 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 824 2 367 489 380 489 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 119  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 825 379 479 20 20 NULL    REF 139 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 826 2 399 489 411 488 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 139  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 827 411 480 24 16 NULL    REF 144 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 828 2 435 481 449 475 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 144  
            CH.ifa.draw.figures.ChopEllipseConnector REF 134   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 829 2 367 410 382 403 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 109  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 830 380 389 20 20 NULL    REF 153 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 831 2 367 392 381 397 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 104  
            CH.ifa.draw.figures.ChopEllipseConnector REF 153   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 832 2 400 399 413 399 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 153  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 833 413 391 24 16 NULL    REF 162 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 834 2 437 398 454 398 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 162  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 835 453 388 20 20 NULL    REF 167 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 836 2 470 405 493 426 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 167  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 837 490 426 24 16 NULL    REF 172 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 838 2 465 465 491 442 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 134  
            CH.ifa.draw.standard.ChopBoxConnector REF 172   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 839 281 156 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 840 313 115 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 841 312 183 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 842 2 299 156 318 133 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 177  
            CH.ifa.draw.figures.ChopEllipseConnector REF 178   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 843 2 301 172 316 187 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 177  
            CH.ifa.draw.figures.ChopEllipseConnector REF 179   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 844 2 332 121 342 114 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 178  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 845 342 100 24 16 NULL    REF 192 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 846 2 333 128 342 131 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 178  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 847 342 127 24 16 NULL    REF 197 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 848 2 331 190 340 184 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 179  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 849 340 170 24 16 NULL    REF 202 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 850 2 331 197 342 202 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 179  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 851 342 200 24 16 NULL    REF 207 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 852 2 364 177 377 177 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 202  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 853 376 167 20 20 NULL    REF 212 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 854 2 396 177 407 175 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 212  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 855 407 167 24 16 NULL    REF 217 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 856 2 431 179 448 186 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 217  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 857 446 179 20 20 NULL    REF 222 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 858 2 366 208 379 208 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 207  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 859 378 198 20 20 NULL    REF 227 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 860 2 398 208 410 207 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 227  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 861 410 199 24 16 NULL    REF 232 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 862 2 434 200 448 194 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 232  
            CH.ifa.draw.figures.ChopEllipseConnector REF 222   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 863 2 366 129 381 122 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 197  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 864 379 108 20 20 NULL    REF 241 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 865 2 366 111 380 116 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 192  
            CH.ifa.draw.figures.ChopEllipseConnector REF 241   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 866 2 399 118 412 118 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 241  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 867 412 110 24 16 NULL    REF 250 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 868 2 436 117 453 117 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 250  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 869 452 107 20 20 NULL    REF 255 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 870 2 469 124 492 145 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 255  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 871 489 145 24 16 NULL    REF 260 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 872 2 464 184 490 161 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 222  
            CH.ifa.draw.standard.ChopBoxConnector REF 260   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 873 239 292 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 874 2 252 293 290 172 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 265  
            CH.ifa.draw.standard.ChopBoxConnector REF 177   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 875 2 259 302 283 302 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 265  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 876 533 283 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 877 2 515 292 534 293 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 84  
            CH.ifa.draw.figures.ChopEllipseConnector REF 274   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 878 2 503 161 541 284 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 260  
            CH.ifa.draw.figures.ChopEllipseConnector REF 274   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 879 2 504 426 541 303 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 172  
            CH.ifa.draw.figures.ChopEllipseConnector REF 274   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 880 2 252 312 291 437 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 265  
            CH.ifa.draw.standard.ChopBoxConnector REF 89   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 881 274 720 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 882 306 679 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 883 305 747 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 884 2 292 720 311 697 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 291  
            CH.ifa.draw.figures.ChopEllipseConnector REF 292   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 885 2 294 736 309 751 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 291  
            CH.ifa.draw.figures.ChopEllipseConnector REF 293   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 886 2 325 685 335 678 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 292  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 887 335 664 24 16 NULL    REF 306 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 888 2 326 692 335 695 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 292  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 889 335 691 24 16 NULL    REF 311 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 890 2 324 754 333 748 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 293  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 891 333 734 24 16 NULL    REF 316 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 892 2 324 761 335 766 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 293  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 893 335 764 24 16 NULL    REF 321 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 894 2 357 741 370 741 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 316  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 895 369 731 20 20 NULL    REF 326 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 896 2 389 741 400 739 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 326  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 897 400 731 24 16 NULL    REF 331 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 898 2 424 743 441 750 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 331  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 899 439 743 20 20 NULL    REF 336 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 900 2 359 772 372 772 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 321  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 901 371 762 20 20 NULL    REF 341 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 902 2 391 772 403 771 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 341  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 903 403 763 24 16 NULL    REF 346 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 904 2 427 764 441 758 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 346  
            CH.ifa.draw.figures.ChopEllipseConnector REF 336   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 905 2 359 693 374 686 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 311  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 906 372 672 20 20 NULL    REF 355 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 907 2 359 675 373 680 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 306  
            CH.ifa.draw.figures.ChopEllipseConnector REF 355   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 908 2 392 682 405 682 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 355  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 909 405 674 24 16 NULL    REF 364 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 910 2 429 681 446 681 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 364  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 911 445 671 20 20 NULL    REF 369 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 912 2 462 688 485 709 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 369  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 913 482 709 24 16 NULL    REF 374 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 914 2 457 748 483 725 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 336  
            CH.ifa.draw.standard.ChopBoxConnector REF 374   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 915 273 862 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 916 305 821 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 917 304 889 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 918 2 291 862 310 839 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 379  
            CH.ifa.draw.figures.ChopEllipseConnector REF 380   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 919 2 293 878 308 893 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 379  
            CH.ifa.draw.figures.ChopEllipseConnector REF 381   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 920 2 324 827 334 820 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 380  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 921 334 806 24 16 NULL    REF 394 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 922 2 325 834 334 837 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 380  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 923 334 833 24 16 NULL    REF 399 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 924 2 323 896 332 890 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 381  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 925 332 876 24 16 NULL    REF 404 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 926 2 323 903 334 908 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 381  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 927 334 906 24 16 NULL    REF 409 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 928 2 356 883 369 883 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 404  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 929 368 873 20 20 NULL    REF 414 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 930 2 388 883 399 881 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 414  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 931 399 873 24 16 NULL    REF 419 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 932 2 423 885 440 892 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 419  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 933 438 885 20 20 NULL    REF 424 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 934 2 358 914 371 914 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 409  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 935 370 904 20 20 NULL    REF 429 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 936 2 390 914 402 913 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 429  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 937 402 905 24 16 NULL    REF 434 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 938 2 426 906 440 900 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 434  
            CH.ifa.draw.figures.ChopEllipseConnector REF 424   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 939 2 358 835 373 828 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 399  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 940 371 814 20 20 NULL    REF 443 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 941 2 358 817 372 822 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 394  
            CH.ifa.draw.figures.ChopEllipseConnector REF 443   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 942 2 391 824 404 824 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 443  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 943 404 816 24 16 NULL    REF 452 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 944 2 428 823 445 823 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 452  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 945 444 813 20 20 NULL    REF 457 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 946 2 461 830 484 851 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 457  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 947 481 851 24 16 NULL    REF 462 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 948 2 456 890 482 867 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 424  
            CH.ifa.draw.standard.ChopBoxConnector REF 462   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 949 272 581 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 950 304 540 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 951 303 608 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 952 2 290 581 309 558 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 467  
            CH.ifa.draw.figures.ChopEllipseConnector REF 468   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 953 2 292 597 307 612 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 467  
            CH.ifa.draw.figures.ChopEllipseConnector REF 469   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 954 2 323 546 333 539 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 468  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 955 333 525 24 16 NULL    REF 482 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 956 2 324 553 333 556 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 468  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 957 333 552 24 16 NULL    REF 487 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 958 2 322 615 331 609 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 469  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 959 331 595 24 16 NULL    REF 492 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 960 2 322 622 333 627 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 469  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 961 333 625 24 16 NULL    REF 497 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 962 2 355 602 368 602 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 492  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 963 367 592 20 20 NULL    REF 502 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 964 2 387 602 398 600 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 502  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 965 398 592 24 16 NULL    REF 507 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 966 2 422 604 439 611 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 507  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 967 437 604 20 20 NULL    REF 512 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 968 2 357 633 370 633 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 497  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 969 369 623 20 20 NULL    REF 517 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 970 2 389 633 401 632 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 517  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 971 401 624 24 16 NULL    REF 522 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 972 2 425 625 439 619 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 522  
            CH.ifa.draw.figures.ChopEllipseConnector REF 512   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 973 2 357 554 372 547 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 487  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 974 370 533 20 20 NULL    REF 531 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 975 2 357 536 371 541 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 482  
            CH.ifa.draw.figures.ChopEllipseConnector REF 531   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 976 2 390 543 403 543 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 531  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 977 403 535 24 16 NULL    REF 540 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 978 2 427 542 444 542 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 540  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 979 443 532 20 20 NULL    REF 545 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 980 2 460 549 483 570 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 545  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 981 480 570 24 16 NULL    REF 550 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 982 2 455 609 481 586 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 512  
            CH.ifa.draw.standard.ChopBoxConnector REF 550   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 983 230 717 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 984 2 243 718 281 597 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 555  
            CH.ifa.draw.standard.ChopBoxConnector REF 467   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 985 2 250 727 274 727 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 555  
            CH.ifa.draw.standard.ChopBoxConnector REF 291   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 986 524 708 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 987 2 506 717 525 718 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 374  
            CH.ifa.draw.figures.ChopEllipseConnector REF 564   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 988 2 494 586 532 709 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 550  
            CH.ifa.draw.figures.ChopEllipseConnector REF 564   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 989 2 495 851 532 728 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 462  
            CH.ifa.draw.figures.ChopEllipseConnector REF 564   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 990 2 243 737 282 862 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 555  
            CH.ifa.draw.standard.ChopBoxConnector REF 379   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1101 191 503 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1102 2 204 503 248 312 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 581  
            CH.ifa.draw.figures.ChopEllipseConnector REF 265   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1103 2 204 519 239 718 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 581  
            CH.ifa.draw.figures.ChopEllipseConnector REF 555   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1108 148 503 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1109 2 168 513 191 511 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 590  
            CH.ifa.draw.standard.ChopBoxConnector REF 581   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1351 624 285 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1352 656 244 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1353 655 312 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1354 2 642 285 661 262 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 595  
            CH.ifa.draw.figures.ChopEllipseConnector REF 596   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1355 2 644 301 659 316 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 595  
            CH.ifa.draw.figures.ChopEllipseConnector REF 597   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1356 2 675 250 685 243 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 596  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1357 685 229 24 16 NULL    REF 610 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1358 2 676 257 685 260 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 596  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1359 685 256 24 16 NULL    REF 615 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1360 2 674 319 683 313 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 597  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1361 683 299 24 16 NULL    REF 620 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1362 2 674 326 685 331 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 597  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1363 685 329 24 16 NULL    REF 625 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1364 2 707 306 720 306 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 620  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1365 719 296 20 20 NULL    REF 630 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1366 2 739 306 750 304 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 630  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1367 750 296 24 16 NULL    REF 635 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1368 2 774 308 791 315 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 635  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1369 789 308 20 20 NULL    REF 640 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1370 2 709 337 722 337 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 625  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1371 721 327 20 20 NULL    REF 645 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1372 2 741 337 753 336 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 645  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1373 753 328 24 16 NULL    REF 650 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1374 2 777 329 791 323 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 650  
            CH.ifa.draw.figures.ChopEllipseConnector REF 640   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1375 2 709 258 724 251 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 615  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1376 722 237 20 20 NULL    REF 659 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1377 2 709 240 723 245 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 610  
            CH.ifa.draw.figures.ChopEllipseConnector REF 659   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1378 2 742 247 755 247 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 659  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1379 755 239 24 16 NULL    REF 668 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1380 2 779 246 796 246 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 668  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1381 795 236 20 20 NULL    REF 673 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1382 2 812 253 835 274 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 673  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1383 832 274 24 16 NULL    REF 678 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1384 2 807 313 833 290 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 640  
            CH.ifa.draw.standard.ChopBoxConnector REF 678   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1385 623 427 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1386 655 386 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1387 654 454 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1388 2 641 427 660 404 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 683  
            CH.ifa.draw.figures.ChopEllipseConnector REF 684   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1389 2 643 443 658 458 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 683  
            CH.ifa.draw.figures.ChopEllipseConnector REF 685   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1390 2 674 392 684 385 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 684  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1391 684 371 24 16 NULL    REF 698 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1392 2 675 399 684 402 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 684  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1393 684 398 24 16 NULL    REF 703 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1394 2 673 461 682 455 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 685  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1395 682 441 24 16 NULL    REF 708 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1396 2 673 468 684 473 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 685  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1397 684 471 24 16 NULL    REF 713 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1398 2 706 448 719 448 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 708  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1399 718 438 20 20 NULL    REF 718 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1400 2 738 448 749 446 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 718  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1401 749 438 24 16 NULL    REF 723 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1402 2 773 450 790 457 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 723  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1403 788 450 20 20 NULL    REF 728 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1404 2 708 479 721 479 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 713  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1405 720 469 20 20 NULL    REF 733 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1406 2 740 479 752 478 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 733  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1407 752 470 24 16 NULL    REF 738 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1408 2 776 471 790 465 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 738  
            CH.ifa.draw.figures.ChopEllipseConnector REF 728   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1409 2 708 400 723 393 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 703  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1410 721 379 20 20 NULL    REF 747 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1411 2 708 382 722 387 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 698  
            CH.ifa.draw.figures.ChopEllipseConnector REF 747   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1412 2 741 389 754 389 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 747  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1413 754 381 24 16 NULL    REF 756 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1414 2 778 388 795 388 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 756  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1415 794 378 20 20 NULL    REF 761 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1416 2 811 395 834 416 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 761  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1417 831 416 24 16 NULL    REF 766 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1418 2 806 455 832 432 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 728  
            CH.ifa.draw.standard.ChopBoxConnector REF 766   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1419 622 146 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1420 654 105 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1421 653 173 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1422 2 640 146 659 123 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 771  
            CH.ifa.draw.figures.ChopEllipseConnector REF 772   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1423 2 642 162 657 177 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 771  
            CH.ifa.draw.figures.ChopEllipseConnector REF 773   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1424 2 673 111 683 104 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 772  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1425 683 90 24 16 NULL    REF 786 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1426 2 674 118 683 121 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 772  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1427 683 117 24 16 NULL    REF 791 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1428 2 672 180 681 174 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 773  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1429 681 160 24 16 NULL    REF 796 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1430 2 672 187 683 192 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 773  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1431 683 190 24 16 NULL    REF 801 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1432 2 705 167 718 167 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 796  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1433 717 157 20 20 NULL    REF 806 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1434 2 737 167 748 165 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 806  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1435 748 157 24 16 NULL    REF 811 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1436 2 772 169 789 176 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 811  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1437 787 169 20 20 NULL    REF 816 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1438 2 707 198 720 198 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 801  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1439 719 188 20 20 NULL    REF 821 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1440 2 739 198 751 197 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 821  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1441 751 189 24 16 NULL    REF 826 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1442 2 775 190 789 184 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 826  
            CH.ifa.draw.figures.ChopEllipseConnector REF 816   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1443 2 707 119 722 112 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 791  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1444 720 98 20 20 NULL    REF 835 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1445 2 707 101 721 106 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 786  
            CH.ifa.draw.figures.ChopEllipseConnector REF 835   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1446 2 740 108 753 108 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 835  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1447 753 100 24 16 NULL    REF 844 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1448 2 777 107 794 107 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 844  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1449 793 97 20 20 NULL    REF 849 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1450 2 810 114 833 135 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 849  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1451 830 135 24 16 NULL    REF 854 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1452 2 805 174 831 151 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 816  
            CH.ifa.draw.standard.ChopBoxConnector REF 854   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1453 580 282 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1454 2 593 283 631 162 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 859  
            CH.ifa.draw.standard.ChopBoxConnector REF 771   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1455 2 600 292 624 292 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 859  
            CH.ifa.draw.standard.ChopBoxConnector REF 595   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1456 874 273 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1457 2 856 282 875 283 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 678  
            CH.ifa.draw.figures.ChopEllipseConnector REF 868   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1458 2 844 151 882 274 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 854  
            CH.ifa.draw.figures.ChopEllipseConnector REF 868   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1459 2 845 416 882 293 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 766  
            CH.ifa.draw.figures.ChopEllipseConnector REF 868   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1460 2 593 302 632 427 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 859  
            CH.ifa.draw.standard.ChopBoxConnector REF 683   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1461 615 710 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1462 647 669 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1463 646 737 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1464 2 633 710 652 687 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 885  
            CH.ifa.draw.figures.ChopEllipseConnector REF 886   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1465 2 635 726 650 741 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 885  
            CH.ifa.draw.figures.ChopEllipseConnector REF 887   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1466 2 666 675 676 668 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 886  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1467 676 654 24 16 NULL    REF 900 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1468 2 667 682 676 685 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 886  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1469 676 681 24 16 NULL    REF 905 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1470 2 665 744 674 738 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 887  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1471 674 724 24 16 NULL    REF 910 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1472 2 665 751 676 756 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 887  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1473 676 754 24 16 NULL    REF 915 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1474 2 698 731 711 731 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 910  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1475 710 721 20 20 NULL    REF 920 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1476 2 730 731 741 729 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 920  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1477 741 721 24 16 NULL    REF 925 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1478 2 765 733 782 740 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 925  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1479 780 733 20 20 NULL    REF 930 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1480 2 700 762 713 762 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 915  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1481 712 752 20 20 NULL    REF 935 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1482 2 732 762 744 761 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 935  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1483 744 753 24 16 NULL    REF 940 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1484 2 768 754 782 748 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 940  
            CH.ifa.draw.figures.ChopEllipseConnector REF 930   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1485 2 700 683 715 676 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 905  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1486 713 662 20 20 NULL    REF 949 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1487 2 700 665 714 670 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 900  
            CH.ifa.draw.figures.ChopEllipseConnector REF 949   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1488 2 733 672 746 672 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 949  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1489 746 664 24 16 NULL    REF 958 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1490 2 770 671 787 671 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 958  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1491 786 661 20 20 NULL    REF 963 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1492 2 803 678 826 699 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 963  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1493 823 699 24 16 NULL    REF 968 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1494 2 798 738 824 715 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 930  
            CH.ifa.draw.standard.ChopBoxConnector REF 968   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1495 614 852 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1496 646 811 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1497 645 879 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1498 2 632 852 651 829 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 973  
            CH.ifa.draw.figures.ChopEllipseConnector REF 974   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1499 2 634 868 649 883 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 973  
            CH.ifa.draw.figures.ChopEllipseConnector REF 975   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1500 2 665 817 675 810 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 974  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1501 675 796 24 16 NULL    REF 988 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1502 2 666 824 675 827 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 974  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1503 675 823 24 16 NULL    REF 993 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1504 2 664 886 673 880 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 975  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1505 673 866 24 16 NULL    REF 998 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1506 2 664 893 675 898 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 975  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1507 675 896 24 16 NULL    REF 1003 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1508 2 697 873 710 873 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 998  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1509 709 863 20 20 NULL    REF 1008 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1510 2 729 873 740 871 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1008  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1511 740 863 24 16 NULL    REF 1013 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1512 2 764 875 781 882 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1013  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1513 779 875 20 20 NULL    REF 1018 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1514 2 699 904 712 904 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1003  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1515 711 894 20 20 NULL    REF 1023 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1516 2 731 904 743 903 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1023  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1517 743 895 24 16 NULL    REF 1028 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1518 2 767 896 781 890 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1028  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1018   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1519 2 699 825 714 818 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 993  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1520 712 804 20 20 NULL    REF 1037 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1521 2 699 807 713 812 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 988  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1037   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1522 2 732 814 745 814 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1037  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1523 745 806 24 16 NULL    REF 1046 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1524 2 769 813 786 813 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1046  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1525 785 803 20 20 NULL    REF 1051 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1526 2 802 820 825 841 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1051  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1527 822 841 24 16 NULL    REF 1056 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1528 2 797 880 823 857 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1018  
            CH.ifa.draw.standard.ChopBoxConnector REF 1056   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1529 613 571 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1530 645 530 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1531 644 598 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1532 2 631 571 650 548 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1061  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1062   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1533 2 633 587 648 602 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1061  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1063   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1534 2 664 536 674 529 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1062  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1535 674 515 24 16 NULL    REF 1076 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1536 2 665 543 674 546 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1062  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1537 674 542 24 16 NULL    REF 1081 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1538 2 663 605 672 599 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1063  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1539 672 585 24 16 NULL    REF 1086 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1540 2 663 612 674 617 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1063  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1541 674 615 24 16 NULL    REF 1091 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1542 2 696 592 709 592 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1086  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1543 708 582 20 20 NULL    REF 1096 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1544 2 728 592 739 590 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1096  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1545 739 582 24 16 NULL    REF 1101 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1546 2 763 594 780 601 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1101  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1547 778 594 20 20 NULL    REF 1106 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1548 2 698 623 711 623 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1091  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1549 710 613 20 20 NULL    REF 1111 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1550 2 730 623 742 622 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1111  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1551 742 614 24 16 NULL    REF 1116 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1552 2 766 615 780 609 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1116  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1106   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1553 2 698 544 713 537 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1081  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1554 711 523 20 20 NULL    REF 1125 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1555 2 698 526 712 531 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1076  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1125   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1556 2 731 533 744 533 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1125  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1557 744 525 24 16 NULL    REF 1134 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1558 2 768 532 785 532 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1134  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1559 784 522 20 20 NULL    REF 1139 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1560 2 801 539 824 560 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1139  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1561 821 560 24 16 NULL    REF 1144 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1562 2 796 599 822 576 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1106  
            CH.ifa.draw.standard.ChopBoxConnector REF 1144   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1563 571 707 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1564 2 584 708 622 587 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1149  
            CH.ifa.draw.standard.ChopBoxConnector REF 1061   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1565 2 591 717 615 717 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1149  
            CH.ifa.draw.standard.ChopBoxConnector REF 885   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1566 865 698 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1567 2 847 707 866 708 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 968  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1158   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1568 2 835 576 873 699 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1144  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1158   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1569 2 836 841 873 718 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1056  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1158   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1570 2 584 727 623 852 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1149  
            CH.ifa.draw.standard.ChopBoxConnector REF 973   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1571 954 278 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1572 986 237 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1573 985 305 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1574 2 972 278 991 255 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1175  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1176   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1575 2 974 294 989 309 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1175  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1177   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1576 2 1005 243 1015 236 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1176  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1577 1015 222 24 16 NULL    REF 1190 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1578 2 1006 250 1015 253 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1176  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1579 1015 249 24 16 NULL    REF 1195 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1580 2 1004 312 1013 306 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1177  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1581 1013 292 24 16 NULL    REF 1200 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1582 2 1004 319 1015 324 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1177  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1583 1015 322 24 16 NULL    REF 1205 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1584 2 1037 299 1050 299 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1200  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1585 1049 289 20 20 NULL    REF 1210 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1586 2 1069 299 1080 297 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1210  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1587 1080 289 24 16 NULL    REF 1215 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1588 2 1104 301 1121 308 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1215  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1589 1119 301 20 20 NULL    REF 1220 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1590 2 1039 330 1052 330 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1205  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1591 1051 320 20 20 NULL    REF 1225 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1592 2 1071 330 1083 329 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1225  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1593 1083 321 24 16 NULL    REF 1230 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1594 2 1107 322 1121 316 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1230  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1220   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1595 2 1039 251 1054 244 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1195  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1596 1052 230 20 20 NULL    REF 1239 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1597 2 1039 233 1053 238 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1190  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1239   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1598 2 1072 240 1085 240 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1239  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1599 1085 232 24 16 NULL    REF 1248 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1600 2 1109 239 1126 239 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1248  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1601 1125 229 20 20 NULL    REF 1253 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1602 2 1142 246 1165 267 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1253  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1603 1162 267 24 16 NULL    REF 1258 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1604 2 1137 306 1163 283 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1220  
            CH.ifa.draw.standard.ChopBoxConnector REF 1258   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1605 953 420 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1606 985 379 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1607 984 447 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1608 2 971 420 990 397 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1263  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1264   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1609 2 973 436 988 451 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1263  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1265   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1610 2 1004 385 1014 378 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1264  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1611 1014 364 24 16 NULL    REF 1278 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1612 2 1005 392 1014 395 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1264  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1613 1014 391 24 16 NULL    REF 1283 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1614 2 1003 454 1012 448 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1265  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1615 1012 434 24 16 NULL    REF 1288 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1616 2 1003 461 1014 466 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1265  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1617 1014 464 24 16 NULL    REF 1293 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1618 2 1036 441 1049 441 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1288  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1619 1048 431 20 20 NULL    REF 1298 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1620 2 1068 441 1079 439 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1298  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1621 1079 431 24 16 NULL    REF 1303 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1622 2 1103 443 1120 450 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1303  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1623 1118 443 20 20 NULL    REF 1308 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1624 2 1038 472 1051 472 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1293  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1625 1050 462 20 20 NULL    REF 1313 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1626 2 1070 472 1082 471 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1313  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1627 1082 463 24 16 NULL    REF 1318 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1628 2 1106 464 1120 458 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1318  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1308   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1629 2 1038 393 1053 386 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1283  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1630 1051 372 20 20 NULL    REF 1327 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1631 2 1038 375 1052 380 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1278  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1327   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1632 2 1071 382 1084 382 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1327  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1633 1084 374 24 16 NULL    REF 1336 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1634 2 1108 381 1125 381 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1336  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1635 1124 371 20 20 NULL    REF 1341 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1636 2 1141 388 1164 409 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1341  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1637 1161 409 24 16 NULL    REF 1346 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1638 2 1136 448 1162 425 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1308  
            CH.ifa.draw.standard.ChopBoxConnector REF 1346   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1639 952 139 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1640 984 98 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1641 983 166 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1642 2 970 139 989 116 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1351  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1352   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1643 2 972 155 987 170 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1351  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1353   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1644 2 1003 104 1013 97 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1352  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1645 1013 83 24 16 NULL    REF 1366 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1646 2 1004 111 1013 114 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1352  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1647 1013 110 24 16 NULL    REF 1371 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1648 2 1002 173 1011 167 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1353  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1649 1011 153 24 16 NULL    REF 1376 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1650 2 1002 180 1013 185 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1353  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1651 1013 183 24 16 NULL    REF 1381 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1652 2 1035 160 1048 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1376  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1653 1047 150 20 20 NULL    REF 1386 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1654 2 1067 160 1078 158 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1386  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1655 1078 150 24 16 NULL    REF 1391 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1656 2 1102 162 1119 169 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1391  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1657 1117 162 20 20 NULL    REF 1396 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1658 2 1037 191 1050 191 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1381  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1659 1049 181 20 20 NULL    REF 1401 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1660 2 1069 191 1081 190 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1401  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1661 1081 182 24 16 NULL    REF 1406 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1662 2 1105 183 1119 177 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1406  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1396   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1663 2 1037 112 1052 105 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1371  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1664 1050 91 20 20 NULL    REF 1415 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1665 2 1037 94 1051 99 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1366  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1415   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1666 2 1070 101 1083 101 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1415  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1667 1083 93 24 16 NULL    REF 1424 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1668 2 1107 100 1124 100 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1424  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1669 1123 90 20 20 NULL    REF 1429 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1670 2 1140 107 1163 128 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1429  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1671 1160 128 24 16 NULL    REF 1434 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1672 2 1135 167 1161 144 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1396  
            CH.ifa.draw.standard.ChopBoxConnector REF 1434   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1673 910 275 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1674 2 923 276 961 155 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1439  
            CH.ifa.draw.standard.ChopBoxConnector REF 1351   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1675 2 930 285 954 285 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1439  
            CH.ifa.draw.standard.ChopBoxConnector REF 1175   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1676 1204 266 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1677 2 1186 275 1205 276 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1258  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1448   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1678 2 1174 144 1212 267 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1434  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1448   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1679 2 1175 409 1212 286 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1346  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1448   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1680 2 923 295 962 420 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1439  
            CH.ifa.draw.standard.ChopBoxConnector REF 1263   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1681 945 703 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1682 977 662 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1683 976 730 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1684 2 963 703 982 680 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1465  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1466   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1685 2 965 719 980 734 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1465  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1467   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1686 2 996 668 1006 661 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1466  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1687 1006 647 24 16 NULL    REF 1480 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1688 2 997 675 1006 678 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1466  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1689 1006 674 24 16 NULL    REF 1485 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1690 2 995 737 1004 731 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1467  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1691 1004 717 24 16 NULL    REF 1490 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1692 2 995 744 1006 749 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1467  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1693 1006 747 24 16 NULL    REF 1495 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1694 2 1028 724 1041 724 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1490  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1695 1040 714 20 20 NULL    REF 1500 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1696 2 1060 724 1071 722 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1500  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1697 1071 714 24 16 NULL    REF 1505 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1698 2 1095 726 1112 733 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1505  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1699 1110 726 20 20 NULL    REF 1510 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1700 2 1030 755 1043 755 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1495  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1701 1042 745 20 20 NULL    REF 1515 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1702 2 1062 755 1074 754 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1515  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1703 1074 746 24 16 NULL    REF 1520 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1704 2 1098 747 1112 741 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1520  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1510   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1705 2 1030 676 1045 669 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1485  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1706 1043 655 20 20 NULL    REF 1529 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1707 2 1030 658 1044 663 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1480  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1529   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1708 2 1063 665 1076 665 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1529  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1709 1076 657 24 16 NULL    REF 1538 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1710 2 1100 664 1117 664 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1538  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1711 1116 654 20 20 NULL    REF 1543 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1712 2 1133 671 1156 692 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1543  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1713 1153 692 24 16 NULL    REF 1548 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1714 2 1128 731 1154 708 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1510  
            CH.ifa.draw.standard.ChopBoxConnector REF 1548   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1715 944 845 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1716 976 804 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1717 975 872 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1718 2 962 845 981 822 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1553  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1554   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1719 2 964 861 979 876 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1553  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1555   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1720 2 995 810 1005 803 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1554  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1721 1005 789 24 16 NULL    REF 1568 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1722 2 996 817 1005 820 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1554  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1723 1005 816 24 16 NULL    REF 1573 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1724 2 994 879 1003 873 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1555  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1725 1003 859 24 16 NULL    REF 1578 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1726 2 994 886 1005 891 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1555  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1727 1005 889 24 16 NULL    REF 1583 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1728 2 1027 866 1040 866 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1578  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1729 1039 856 20 20 NULL    REF 1588 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1730 2 1059 866 1070 864 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1588  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1731 1070 856 24 16 NULL    REF 1593 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1732 2 1094 868 1111 875 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1593  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1733 1109 868 20 20 NULL    REF 1598 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1734 2 1029 897 1042 897 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1583  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1735 1041 887 20 20 NULL    REF 1603 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1736 2 1061 897 1073 896 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1603  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1737 1073 888 24 16 NULL    REF 1608 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1738 2 1097 889 1111 883 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1608  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1598   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1739 2 1029 818 1044 811 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1573  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1740 1042 797 20 20 NULL    REF 1617 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1741 2 1029 800 1043 805 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1568  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1617   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1742 2 1062 807 1075 807 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1617  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1743 1075 799 24 16 NULL    REF 1626 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1744 2 1099 806 1116 806 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1626  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1745 1115 796 20 20 NULL    REF 1631 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1746 2 1132 813 1155 834 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1631  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1747 1152 834 24 16 NULL    REF 1636 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1748 2 1127 873 1153 850 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1598  
            CH.ifa.draw.standard.ChopBoxConnector REF 1636   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1749 943 564 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1750 975 523 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1751 974 591 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1752 2 961 564 980 541 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1641  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1642   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1753 2 963 580 978 595 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1641  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1643   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1754 2 994 529 1004 522 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1642  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1755 1004 508 24 16 NULL    REF 1656 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1756 2 995 536 1004 539 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1642  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1757 1004 535 24 16 NULL    REF 1661 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1758 2 993 598 1002 592 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1643  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1759 1002 578 24 16 NULL    REF 1666 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1760 2 993 605 1004 610 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1643  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1761 1004 608 24 16 NULL    REF 1671 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1762 2 1026 585 1039 585 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1666  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1763 1038 575 20 20 NULL    REF 1676 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1764 2 1058 585 1069 583 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1676  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1765 1069 575 24 16 NULL    REF 1681 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1766 2 1093 587 1110 594 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1681  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1767 1108 587 20 20 NULL    REF 1686 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1768 2 1028 616 1041 616 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1671  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1769 1040 606 20 20 NULL    REF 1691 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1770 2 1060 616 1072 615 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1691  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1771 1072 607 24 16 NULL    REF 1696 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1772 2 1096 608 1110 602 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1696  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1686   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1773 2 1028 537 1043 530 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1661  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1774 1041 516 20 20 NULL    REF 1705 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1775 2 1028 519 1042 524 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1656  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1705   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1776 2 1061 526 1074 526 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1705  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1777 1074 518 24 16 NULL    REF 1714 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1778 2 1098 525 1115 525 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1714  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1779 1114 515 20 20 NULL    REF 1719 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1780 2 1131 532 1154 553 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1719  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1781 1151 553 24 16 NULL    REF 1724 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1782 2 1126 592 1152 569 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1686  
            CH.ifa.draw.standard.ChopBoxConnector REF 1724   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1783 901 700 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1784 2 914 701 952 580 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1729  
            CH.ifa.draw.standard.ChopBoxConnector REF 1641   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1785 2 921 710 945 710 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1729  
            CH.ifa.draw.standard.ChopBoxConnector REF 1465   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1786 1195 691 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1787 2 1177 700 1196 701 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1548  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1738   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1788 2 1165 569 1203 692 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1724  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1738   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1789 2 1166 834 1203 711 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1636  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1738   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1790 2 914 720 953 845 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1729  
            CH.ifa.draw.standard.ChopBoxConnector REF 1553   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1792 551 228 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1793 2 546 285 560 244 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 274  
            CH.ifa.draw.standard.ChopBoxConnector REF 1755   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1794 2 566 244 587 284 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1755  
            CH.ifa.draw.figures.ChopEllipseConnector REF 859   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1795 2 537 727 549 762 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 564  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1796 540 762 24 16 NULL    REF 1768 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1797 2 556 762 577 726 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1768  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1149   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1798 2 877 718 884 750 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1158  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1799 874 750 24 16 NULL    REF 1777 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1800 2 890 750 907 719 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1777  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1729   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1801 2 888 275 906 224 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 868  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1802 898 208 24 16 NULL    REF 1786 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1803 2 911 224 920 276 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1786  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1439   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1804 2 1216 286 1257 484 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1448  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1805 1247 484 24 16 NULL    REF 1795 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1806 2 1208 692 1256 500 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1738  
            CH.ifa.draw.standard.ChopBoxConnector REF 1795   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1807 2 1271 491 1303 490 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1795  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1808 1302 479 20 20 NULL    REF 1804 NULL  0 0 1280 985 