7 
    de.renew.gui.CPNDrawing 45 
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 8 2 205 22 205 44 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 180 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 201 7 "..." "Helvetica" 0 12 0 NULL NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 151 "FillColor" "Color" 0 0 0 174 44 63 5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 163 2 182 49 164 63 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 152 "FillColor" "Color" 0 0 0 174 44 23 5   
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 1 "FillColor" "Color" 255 255 255 86 63 112 38 26 38    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 164 2 228 49 245 64 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 153 "FillColor" "Color" 0 0 0 214 44 23 5   
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 147 "FillColor" "Color" 255 255 255 211 64 112 38 26 38    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 166 2 251 212 227 242 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 154 "FillColor" "Color" 255 255 255 211 174 112 38 26 38   
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 16 "FillColor" "Color" 0 0 0 214 242 23 5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 167 2 158 212 183 242 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 149 "FillColor" "Color" 255 255 255 86 174 112 38 26 38   
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 15 "FillColor" "Color" 0 0 0 174 242 23 5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 168 2 205 247 205 263 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 11 "FillColor" "Color" 0 0 0 174 242 63 5   
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 156 "FillColor" "Color" 255 255 255 149 263 112 38 26 38    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 169 2 204 301 204 322 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 36  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 181 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 200 322 "..." "Helvetica" 0 12 0 NULL NULL    
        CH.ifa.draw.figures.GroupFigure 3 REF 6 REF 10 REF 16  
        CH.ifa.draw.figures.GroupFigure 3 REF 34 REF 30 REF 24  REF 4 REF 41 REF 12 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 2 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 114 67 "Produkt\nverpacken" "Helvetica" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 28 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 150 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 113 178 "Produkt\nversenden" "Helvetica" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 22 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 155 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 222 178 "Rechnungsaus-\ndruck versenden" "Helvetica" 0 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 18 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 148 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 239 68 "Rechnung\nerstellen" "Helvetica" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 36 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 157 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 184 267 "Produkt\nprüfen" "Helvetica" 0 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 187 "LineStyle" "Int" 10 2 60 50 93 63 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 182 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 18 34 "_produkt" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 12   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 188 "LineStyle" "Int" 10 2 106 101 73 118 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 12  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 184 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 17 118 "_produkt\n\n[verpackt]" "Helvetica" 0 12 0 NULL NULL
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 189 "LineStyle" "Int" 10 2 71 152 109 174 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 68  
            CH.ifa.draw.standard.ChopBoxConnector REF 28   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 192 "LineStyle" "Int" 10 2 101 212 75 224 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 191 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 17 222 "_produkt\n\n[versandt]" "Helvetica" 0 12 0 NULL NULL
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 193 "LineStyle" "Int" 10 2 75 247 149 267 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 77  
            CH.ifa.draw.standard.ChopBoxConnector REF 36   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 194 "LineStyle" "Int" 10 2 40 50 42 118 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 62  
            CH.ifa.draw.standard.ChopBoxConnector REF 68   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 195 "LineStyle" "Int" 10 2 42 152 43 222 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 68  
            CH.ifa.draw.standard.ChopBoxConnector REF 77   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 198 "LineStyle" "Int" 10 2 303 102 334 118 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 18  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 196 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 339 118 "_rechnung\n\n[erstellt]" "Helvetica" 0 12 0 NULL NULL
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 199 "LineStyle" "Int" 10 2 336 152 299 174 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 94  
            CH.ifa.draw.standard.ChopBoxConnector REF 22   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 200 "LineStyle" "Int" 10 2 323 210 383 229 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 22  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 197 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 388 222 "_rechnung\n\n[versandt]" "Helvetica" 0 12 0 NULL NULL
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 201 "LineStyle" "Int" 10 2 305 256 261 267 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 210 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 310 240 "_rechnung" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 36   REF 68 
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 208 "LineStyle" "Int" 10 2 374 152 406 222 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 94  
            CH.ifa.draw.standard.ChopBoxConnector REF 103   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 203 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 9 172 "«becomes»" "Helvetica" 0 12 0 REF 86 
            CH.ifa.draw.standard.OffsetLocator 0 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 202 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 8 74 "«becomes»" "Helvetica" 0 12 0 REF 82 
            CH.ifa.draw.standard.OffsetLocator 0 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 62 REF 94 
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 213 "LineStyle" "Int" 10 2 291 212 326 240 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 22  
            CH.ifa.draw.standard.ChopBoxConnector REF 107   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 209 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 372 180 "«becomes»" "Helvetica" 0 12 0 REF 109 
            CH.ifa.draw.standard.OffsetLocator 15 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 107 REF 103 
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 2 "FigureWithID" "Int" 217 "LineStyle" "Int" 10 2 361 152 339 240 NULL 
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 94  
            CH.ifa.draw.standard.ChopBoxConnector REF 107   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 219 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 331 189 "«copy»" "Helvetica" 0 12 0 REF 126 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 77 NULL  424 34 512 387 
