11 
    de.renew.gui.CPNDrawing 56 
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 4 "FigureWithID" "Int" 256 "FrameColor" "Color" 224 224 224 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 240 240 240 255 24 217 116 33  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 2 "FigureWithID" "Int" 257 "Visibility" "Boolean" "TRUE" 4 
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 258 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 255 149 223 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 261 "Visibility" "Boolean" "TRUE" 2 67 233 150 233 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 259 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 43 226 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 3   REF 7 REF 1  REF 3 REF 7 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 260 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 165 224 ">" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 4 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 262 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 41 226 ">" "SansSerif" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 263 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 33 253 ":start(p)" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -1 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 4 "FigureWithID" "Int" 264 "FrameColor" "Color" 224 224 224 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 240 240 240 255 428 39 163 220 5  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 2 "FigureWithID" "Int" 265 "Visibility" "Boolean" "TRUE" 15 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 274 "Visibility" "Boolean" "TRUE" 2 459 123 490 166 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 268 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 442 107 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 271 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 485 163 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 275 "Visibility" "Boolean" "TRUE" 2 501 181 533 226 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 25  
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 270 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 527 226 24 16 NULL    
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 266 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 485 223 20 20 NULL  
            de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 267 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 442 226 24 16 NULL  REF 18 REF 23 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 278 "Visibility" "Boolean" "TRUE" 2 466 233 486 233 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 32  
                CH.ifa.draw.figures.ChopEllipseConnector REF 31   
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 269 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 443 169 20 20 NULL  REF 30 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 281 "Visibility" "Boolean" "TRUE" 2 505 233 527 233 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 31  
                CH.ifa.draw.standard.ChopBoxConnector REF 30   REF 25 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 283 "Visibility" "Boolean" "TRUE" 2 551 233 583 233 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 30  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 272 "Visibility" "Boolean" "TRUE" 582 223 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 284 "Visibility" "Boolean" "TRUE" 2 453 226 453 189 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 32  
                CH.ifa.draw.figures.ChopEllipseConnector REF 37   REF 46 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 285 "Visibility" "Boolean" "TRUE" 2 453 170 453 123 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 37  
                CH.ifa.draw.standard.ChopBoxConnector REF 23    REF 31 REF 32 REF 23 REF 37 REF 30 REF 25 REF 46 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 273 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 598 224 ">" "SansSerif" 1 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 20 REF 26 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 276 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 439 85 ":out(p2)" "SansSerif" 0 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 6 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 277 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 478 192 "OUT" "SansSerif" 1 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator -5 -33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 33 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 279 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 449 133 "p2" "SansSerif" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 3 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 280 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 446 199 "p2" "SansSerif" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 38 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 282 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 440 225 ">" "SansSerif" 1 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator -11 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 42 REF 47 REF 51 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 286 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 429 265 "action p2=p.reply(\"inform\",\n\"success\")" "SansSerif" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 46 47 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 4 "FigureWithID" "Int" 287 "FrameColor" "Color" 224 224 224 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 240 240 240 255 208 217 116 33  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 2 "FigureWithID" "Int" 288 "Visibility" "Boolean" "TRUE" 4 
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 289 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 255 333 223 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 292 "Visibility" "Boolean" "TRUE" 2 251 233 334 233 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 290 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 227 226 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 78   REF 82 REF 76  REF 78 REF 82 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 291 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 349 224 ">" "SansSerif" 1 12 0 REF 78 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 79 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 293 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 225 226 ">" "SansSerif" 1 12 0 REF 82 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 294 "Visibility" "Boolean" "TRUE" 2 54 226 54 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 295 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 175 175 255 44 140 20 20 NULL    REF 94 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 296 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 51 185 "p" "SansSerif" 0 12 0 REF 90 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 297 "Visibility" "Boolean" "TRUE" 2 169 233 227 233 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector REF 82   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 298 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 205 254 ":srvc(\"putmail\",\"mail\",null,null)" "SansSerif" 0 12 0 REF 82 
            CH.ifa.draw.standard.OffsetLocator 47 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 303 "Visibility" "Boolean" "TRUE" 2 353 233 442 233 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 78  
            CH.ifa.draw.standard.ChopBoxConnector REF 32   
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 305 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 175 175 255 367 133 20 20 NULL REF 94  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 306 "Visibility" "Boolean" "TRUE" 2 383 151 447 226 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 109  
            CH.ifa.draw.standard.ChopBoxConnector REF 32   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 308 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 412 180 "p" "SansSerif" 0 12 0 REF 110 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 310 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 0 255 0 255 651 225 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 311 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 648 204 ":stop()" "SansSerif" 0 12 0 REF 117 
            CH.ifa.draw.standard.OffsetLocator 2 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 312 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 648 245 "STOP" "SansSerif" 1 12 0 REF 117 
            CH.ifa.draw.standard.OffsetLocator 1 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 313 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 647 224 ">" "SansSerif" 1 12 0 REF 117 
            CH.ifa.draw.standard.OffsetLocator -13 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 314 "Visibility" "Boolean" "TRUE" 2 602 233 651 233 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 46  
            CH.ifa.draw.standard.ChopBoxConnector REF 117   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 316 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 427 8 "[to robot]" "SansSerif" 0 18 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator -47 -129 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 299 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 202 274 "[service call\nto PUTMAIL]" "SansSerif" 0 18 0 REF 77 
            CH.ifa.draw.standard.OffsetLocator -27 65 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.DeclarationFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 136 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 27 34 "import de.renew.agent.repr.acl.*;\nimport de.renew.extras.imagenets.*;\nAclMessage p,p2;\nObject mail;" "SansSerif" 0 12 0 NULL NULL 1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 315 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 378 295 "[ams informs robot about success\nconcerning completion \nservice: putmail]" "SansSerif" 0 18 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 2 182 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    NULL  663 528 742 407 