
    CH.ifa.draw.cpn.CPNDrawing 29 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 319 174 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 320 416 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 330 190 330 417 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 67 124 "[plan\n TRIGGER: [eventIntention\n           EVENT: [newBelief\n                   BELIEF: [location\n                            OBJECT: [waste]\n                            LOCATION: #1[]]]\n           INTENT: #3]\n INTENT: <[pick\n           OBJECT: [waste]]\n          [newGoal\n           BELIEF: [location\n                    OBJECT: [robot]\n                    LOCATION: #2[]]]\n          [drop\n           OBJECT: [waste]]\n          | #3>\n CONTEXT: <[location\n            OBJECT: [robot]\n            LOCATION: #1]\n           [location\n            OBJECT: [bin]\n            LOCATION: #2]\n           >]" "Helvetica" 0 9 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -143 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 468 419 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 340 426 468 426 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 10   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 314 439 "Plans" "Helvetica" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 0 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 353 346 "[plan\n TRIGGER: #1[]\n INTENT: #2[]\n CONTEXT: <#3[]\n           #4[]\n           >]" "Helvetica" 0 9 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator -3 -41 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 479 435 479 545 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector 
                CH.ifa.draw.cpn.PlaceFigure "no_attributes" 469 544 20 20    
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 488 487 "#2[]" "Helvetica" 0 9 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 21 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 317 153 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -1 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 569 417 20 20  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 565 439 "Belief" "Helvetica" 1 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator 2 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.ArcConnection 3 335 190 383 272 472 344 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                CH.ifa.draw.cpn.PlaceFigure "no_attributes" 469 339 21 20    
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 255 255 362 241 "[eventIntention\n EVENT: [newBelief\n         BELIEF: [location\n                  OBJECT: [waste]\n                  LOCATION: [a]]]\n INTENT: <>]" "Helvetica" 0 9 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator 48 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 3 343 181 579 181 579 418 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 31   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 474 186 "[location\n OBJECT: [bin]\n LOCATION: [b]]" "Helvetica" 0 9 0 REF 43 
            CH.ifa.draw.standard.OffsetLocator 51 -92 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 24 REF 39 
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 499 340 "Events" "Helvetica" 1 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 40 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.ArcConnection 2 479 359 479 419 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 39  
            CH.ifa.draw.standard.ChopBoxConnector REF 10   
        CH.ifa.draw.cpn.ArcConnection 2 570 427 492 427 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 31  
            CH.ifa.draw.standard.ChopBoxConnector REF 10   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 522 411 "#4[]" "Helvetica" 0 9 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator 3 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 484 380 "#1[]" "Helvetica" 0 9 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 17 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 495 544 "Intentions" "Helvetica" 1 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 44 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.ArcConnection 3 492 429 537 439 570 430 NULL NULL 0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector REF 31   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 525 444 "#3[]" "Helvetica" 0 9 0 REF 69 
            CH.ifa.draw.standard.OffsetLocator 6 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 3 343 181 590 167 579 418 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 31   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 471 116 "[location\n OBJECT: [robot]\n LOCATION: [a]]" "Helvetica" 0 9 0 REF 75 
            CH.ifa.draw.standard.OffsetLocator 46 -155 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
