1 
    de.renew.gui.CPNDrawing 43 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 144 19 "clear" "Helvetica" 1 12 0 
            de.renew.gui.PlaceFigure "no_attributes" 147 35 20 20  
            CH.ifa.draw.standard.OffsetLocator 1 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 2 
        de.renew.gui.ArcConnection "no_attributes" 2 151 52 112 90 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 92 90 24 16    REF 9 
        de.renew.gui.ArcConnection "no_attributes" 2 111 106 145 142 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 9  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "no_attributes" 126 140 60 29    REF 14 
        de.renew.gui.ArcConnection "no_attributes" 2 167 142 194 107 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 189 91 24 16    REF 19 
        de.renew.gui.ArcConnection "no_attributes" 2 194 91 163 53 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 19  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 133 167 "carrying" "Helvetica" 1 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 1 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 185 123 "b" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 8 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 115 118 "b" "Helvetica" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator -10 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 219 91 ":remove(b)" "Helvetica" 0 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator 47 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 5 91 ":occupyWith(b)" "Helvetica" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -57 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "no_attributes" 235 37 24 16  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 260 37 ":new(n)" "Helvetica" 0 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 33 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 2 235 45 167 45 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 39  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.TransitionFigure "no_attributes" 232 147 24 16  
        de.renew.gui.ArcConnection "no_attributes" 2 232 154 186 154 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 47  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 261 146 ":new(n,b)" "Helvetica" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 43 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 219 140 "b" "Helvetica" 0 12 0 REF 48 
            CH.ifa.draw.standard.OffsetLocator 13 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "no_attributes" 92 37 24 16  
        de.renew.gui.ArcConnection "no_attributes" 2 116 45 148 45 NULL NULL 
            CH.ifa.draw.standard.ChopBoxConnector REF 58  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 78 21 ":isClear()" "Helvetica" 0 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator -1 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 205 73 "remove" "Helvetica" 1 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator 26 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 38 70 "occupyWith" "Helvetica" 1 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -32 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 44 38 "isClear" "Helvetica" 1 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator -40 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "no_attributes" 2 127 154 93 154 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 14  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 69 146 24 16    REF 77 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 6 130 ":isCarrying(b)" "Helvetica" 0 12 0 REF 77 
            CH.ifa.draw.standard.OffsetLocator -38 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 4 147 "isCarrying" "Helvetica" 1 12 0 REF 77 
            CH.ifa.draw.standard.OffsetLocator -47 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "no_attributes" 289 88 20 20  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 291 74 "name" "Helvetica" 1 12 0 REF 84 
            CH.ifa.draw.standard.OffsetLocator 8 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "no_attributes" 2 254 53 293 92 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 39  
            CH.ifa.draw.figures.ChopEllipseConnector REF 84   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 277 59 "n" "Helvetica" 0 12 0 REF 88 
            CH.ifa.draw.standard.OffsetLocator 7 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 2 251 147 293 105 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 47  
            CH.ifa.draw.figures.ChopEllipseConnector REF 84   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 275 122 "n" "Helvetica" 0 12 0 REF 95 
            CH.ifa.draw.standard.OffsetLocator 6 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "no_attributes" 341 91 24 16  
        de.renew.gui.ArcConnection "no_attributes" 2 309 98 341 98 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 84  
            CH.ifa.draw.standard.ChopBoxConnector REF 102   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 318 100 "n" "Helvetica" 0 12 0 REF 103 
            CH.ifa.draw.standard.OffsetLocator -4 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 341 108 ":getName(n)" "Helvetica" 0 12 0 REF 102 
            CH.ifa.draw.standard.OffsetLocator 21 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 343 74 "getName" "Helvetica" 1 12 0 REF 102 
            CH.ifa.draw.standard.OffsetLocator 16 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 107 158 "b" "Helvetica" 0 12 0 REF 74 
            CH.ifa.draw.standard.OffsetLocator 0 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   