
    CH.ifa.draw.cpn.CPNDrawing 4 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 280 138 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 307 122 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 28 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 310 138 "action f=new java.awt.Frame(\"Test\")" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 115 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 311 155 "action f.setSize(200,100)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 86 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
