
    CH.ifa.draw.cpn.CPNDrawing 7 
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 299 121 20 20  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 317 110 "38" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 15 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 321 132 "Magic Number" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 53 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 202 124 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 226 131 300 131 NULL NULL 0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 8  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 241 113 "number" "Helvetica" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -1 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 80 125 ":getNumber(number)" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator -77 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
