
    CH.ifa.draw.cpn.CPNDrawing 2 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 115 91 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 150 90 ":method(question,question.length())" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 120 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
