
    CH.ifa.draw.cpn.CPNDrawing 7 
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 123 109 20 20  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 150 110 "myStandardAnswer" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 74 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 121 185 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 133 129 133 185 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 5   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 142 149 "answer" "Helvetica" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 29 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 103 110 "42" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -23 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 149 185 ":method(dontcare,answer)" "Helvetica" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 87 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
