11 
    de.renew.gui.CPNDrawing 63 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 669 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 119 204 255 255 348 32 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 670 "TraceMode" "Boolean" "FALSE" 2 360 48 360 86 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 674 "FrameColor" "Color" 0 0 0 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 112 219 147 255 350 85 20 20 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 671 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 275 56 "[activity,order]" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -40 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 672 "TraceMode" "Boolean" "FALSE" 208 87 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 673 "TraceMode" "Boolean" "FALSE" 493 87 24 16 NULL  REF 6 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 675 "TraceMode" "Boolean" "FALSE" 2 351 95 232 95 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 10   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 676 "TraceMode" "Boolean" "FALSE" 2 370 95 493 95 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 11   
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 677 "TraceMode" "Boolean" "FALSE" 210 145 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 678 "TraceMode" "Boolean" "FALSE" 495 145 20 20 NULL  
        de.renew.wfnet.TaskFigure "attributes" "attributes" 2 "FigureWithID" "Int" 679 "TraceMode" "Boolean" "FALSE" 208 207 24 16 NULL  
        de.renew.wfnet.TaskFigure "attributes" "attributes" 2 "FigureWithID" "Int" 680 "TraceMode" "Boolean" "FALSE" 493 207 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 681 "TraceMode" "Boolean" "FALSE" 2 220 103 220 146 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector REF 20   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 682 "TraceMode" "Boolean" "FALSE" 2 505 103 505 146 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 11  
            CH.ifa.draw.figures.ChopEllipseConnector REF 21   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 683 "TraceMode" "Boolean" "FALSE" 2 220 165 220 207 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 20  
            CH.ifa.draw.standard.ChopBoxConnector REF 22   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 684 "TraceMode" "Boolean" "FALSE" 2 505 165 505 207 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 21  
            CH.ifa.draw.standard.ChopBoxConnector REF 23   
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 685 "FrameColor" "Color" 0 0 0 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 112 219 147 255 350 205 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 686 "TraceMode" "Boolean" "FALSE" 2 232 215 351 215 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 22  
            CH.ifa.draw.figures.ChopEllipseConnector REF 40   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 687 "TraceMode" "Boolean" "FALSE" 2 493 215 370 215 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 23  
            CH.ifa.draw.figures.ChopEllipseConnector REF 40   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 689 "FrameColor" "Color" 0 0 0 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 112 219 147 255 509 376 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 690 "FrameColor" "Color" 0 0 0 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 112 219 147 255 511 442 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 691 "TraceMode" "Boolean" "FALSE" 2 521 392 521 443 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 49  
            CH.ifa.draw.figures.ChopEllipseConnector REF 50   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 692 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 255 187 187 255 226 377 24 16 NULL  
        de.renew.wfnet.TaskFigure "attributes" "attributes" 2 "FigureWithID" "Int" 693 "TraceMode" "Boolean" "FALSE" 509 500 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 694 "TraceMode" "Boolean" "FALSE" 511 549 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 695 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 255 187 187 255 509 600 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 696 "TraceMode" "Boolean" "FALSE" 2 521 462 521 500 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 50  
            CH.ifa.draw.standard.ChopBoxConnector REF 56   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 697 "TraceMode" "Boolean" "FALSE" 2 521 516 521 550 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 56  
            CH.ifa.draw.figures.ChopEllipseConnector REF 57   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 698 "TraceMode" "Boolean" "FALSE" 2 521 569 521 600 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 57  
            CH.ifa.draw.standard.ChopBoxConnector REF 58   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 699 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 251 98 "[activity,order]" "SansSerif" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 5 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 700 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 381 98 "[activity,order]" "SansSerif" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator -5 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 705 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 255 199 158 255 298 13 ":start(activity,order)" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 2 "FigureWithID" "Int" 706 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 255 199 158 255 -37 208 "[\"CheckCreditCard\",_form,_formInstance]" "SansSerif" 0 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator -130 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 707 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 512 410 "[activity,order,_form]" "SansSerif" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 55 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 2 "FigureWithID" "Int" 709 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 255 199 158 255 -3 38 "guard order.getPayment().getMode().equals(\nPSPaymentModeImpl.CREDIT_CARD);\naction _form=order.getPayment().toForm()" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator -81 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 710 "TraceMode" "Boolean" "FALSE" 2 360 225 360 262 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 40  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 711 "TraceMode" "Boolean" "FALSE" 348 262 24 16 NULL    REF 93 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 712 "TraceMode" "Boolean" "FALSE" 2 360 278 360 331 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 93  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 713 "TraceMode" "Boolean" "FALSE" 350 330 20 20 NULL    REF 98 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 714 "TraceMode" "Boolean" "FALSE" 2 352 343 250 380 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 98  
            CH.ifa.draw.standard.ChopBoxConnector REF 55   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 715 "TraceMode" "Boolean" "FALSE" 2 370 343 509 380 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 98  
            CH.ifa.draw.standard.ChopBoxConnector REF 49   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 719 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 255 199 158 255 395 38 "guard order.getPayment().getMode().equals(\nPSPaymentModeImpl.BANK);\naction _form=order.getPayment().toForm()" "SansSerif" 0 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 32 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 723 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 219 293 "[activity,order,resultVal]" "SansSerif" 0 12 0 REF 94 
            CH.ifa.draw.standard.OffsetLocator -66 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 724 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 255 199 158 255 507 208 "[\"CheckBank\",_form,_formInstance]" "SansSerif" 0 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 111 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 726 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 255 199 158 255 326 618 ":end([activity,PSResultImpl\n.getInstance((PSResult)_formInstance.get(\"result\"))],dummy)" "SansSerif" 0 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator -5 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 727 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 494 521 "[activity,_formInstance]" "SansSerif" 0 12 0 REF 63 
            CH.ifa.draw.standard.OffsetLocator 45 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 728 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 494 572 "[activity,_formInstance]" "SansSerif" 0 12 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator 45 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 729 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 512 469 "[activity,order,_form]" "SansSerif" 0 12 0 REF 59 
            CH.ifa.draw.standard.OffsetLocator 55 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 730 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 255 199 158 255 309 501 "[\"CheckAddress\",_form,_formInstance]" "SansSerif" 0 12 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator -93 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 720 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 255 199 158 255 104 395 "guard !resultVal.equals(PSResultImpl.OK);\n:end([activity,resultVal],dummy)" "SansSerif" 0 12 0 REF 55 
            CH.ifa.draw.standard.OffsetLocator -4 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 701 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 103 117 "[activity,order,_form]" "SansSerif" 0 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator -53 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 702 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 103 174 "[activity,order,_form]" "SansSerif" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator -53 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 703 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 494 174 "[activity,order,_form]" "SansSerif" 0 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 53 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 704 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 498 117 "[activity,order,_form]" "SansSerif" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 57 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 725 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 255 199 158 255 521 369 "guard resultVal.equals(PSResultImpl.OK);\naction _form=order.getCustomer().toForm()" "SansSerif" 0 12 0 REF 49 
            CH.ifa.draw.standard.OffsetLocator 137 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 718 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 413 340 "[activity,order,resultVal]" "SansSerif" 0 12 0 REF 103 
            CH.ifa.draw.standard.OffsetLocator 49 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 717 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 167 343 "[activity,order,resultVal]" "SansSerif" 0 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator -59 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 3319 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 678 53 "Subworkflow CheckOrder" "SansSerif" 0 20 0 NULL NULL  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 667 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 255 199 158 255 102 460 "import de.renew.workflow.form.*;\nimport de.renew.workflow.*;\nimport java.util.HashSet;\nimport de.renew.phoneshop.*;\nPSOrderImpl order;\nFormInstance _form,_formInstance;\nForm _newForm;\nHashSet customers;\nPSResult result;\nPSResult resultVal;\nActivity activity;\nObject _WF_activity,dummy;" "SansSerif" 0 12 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 721 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 255 199 158 255 373 258 "action resultVal = PSResultImpl\n.getInstance((PSResult)_formInstance.get(\"result\"))" "SansSerif" 0 12 0 REF 93 
            CH.ifa.draw.standard.OffsetLocator 174 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 722 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 176 244 "[activity,order,_formInstance]" "SansSerif" 0 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator -93 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 688 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 369 228 "[activity,order,_formInstance]" "SansSerif" 0 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator 29 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 716 "FrameColor" "Color" 255 199 158 255 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 254 254 254 255 224 189 "[activity,order,_formInstance]" "SansSerif" 0 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator 24 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  