1 
    de.renew.gui.CPNDrawing 132 
        de.renew.gui.TransitionFigure "no_attributes" 243 269 24 16  
        de.renew.gui.TransitionFigure "no_attributes" 356 361 24 16  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 145 254 ":attach(problem)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -66 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 394 347 ":detach(problem)" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 72 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "no_attributes" 244 359 20 20  
        de.renew.gui.TransitionFigure "no_attributes" 136 149 24 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 4 136 157 51 157 51 369 245 369 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector REF 9   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 81 168 "storage: new storage" "Helvetica" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator -10 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 114 353 "storage" "Helvetica" 0 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator -14 97 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 123 268 "storage:put(problem)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -75 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 389 359 "storage:get(problem)" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 78 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 178 591 372 591 NULL NULL 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 154 584 24 16   
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "no_attributes" 371 581 20 20    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 229 575 "[storage,wasted]" "Helvetica" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator -2 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "no_attributes" 474 128 24 16  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 227 381 "ready for \nproblems\nto attach" "Helvetica" 1 12 0 NULL NULL 2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 443 112 ":acceptEnergy(n)" "Helvetica" 0 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator 3 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 381 601 381 666 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 31  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 370 666 24 16    REF 44 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 389 626 "[storage,wasted]" "Helvetica" 0 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 52 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 397 655 ":allProblemssolved()" "Helvetica" 0 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator 71 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 398 669 "storage:allProblemssolved()" "Helvetica" 0 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator 92 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 356 369 264 369 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector REF 9   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 294 368 "storage" "Helvetica" 0 12 0 REF 54 
            CH.ifa.draw.standard.OffsetLocator 4 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 254 285 254 360 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 9   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 259 327 "storage" "Helvetica" 0 12 0 REF 62 
            CH.ifa.draw.standard.OffsetLocator 25 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 381 682 381 740 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 44  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "no_attributes" 371 739 20 20    REF 74 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 398 743 "solved" "Helvetica" 1 15 0 REF 74 
            CH.ifa.draw.standard.OffsetLocator 40 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 90 179 ":new(oracle,cID)" "Helvetica" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator -14 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 497 144 578 199 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 35  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "no_attributes" 575 194 20 20    REF 85 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 444 157 "newEA=energy_avail+n" "Helvetica" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator -28 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 601 186 "energy available\nfrom particpants" "Helvetica" 1 12 0 REF 85 
            CH.ifa.draw.standard.OffsetLocator 63 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 3 585 195 585 136 498 136 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 85  
            CH.ifa.draw.standard.ChopBoxConnector REF 35   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 592 145 "energy_avail" "Helvetica" 0 12 0 REF 92 
            CH.ifa.draw.standard.OffsetLocator 86 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "no_attributes" 537 504 24 16  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 567 511 ":solve()" "Helvetica" 0 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator 38 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 3 585 214 585 456 554 504 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 85  
            CH.ifa.draw.standard.ChopBoxConnector REF 99   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 575 476 "energy_avail" "Helvetica" 0 12 0 REF 103 
            CH.ifa.draw.standard.OffsetLocator 41 124 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 502 538 "guard(energy_avail>=energy_req)" "Helvetica" 0 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator 47 33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 584 198 "0" "Helvetica" 0 12 0 REF 85 
            CH.ifa.draw.standard.OffsetLocator 2 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 537 517 390 588 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 99  
            CH.ifa.draw.figures.ChopEllipseConnector REF 31   REF 31 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 266 543 "[storage,energy_avail-energy_req]" "Helvetica" 0 12 0 REF 116 
            CH.ifa.draw.standard.OffsetLocator -102 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "no_attributes" 358 204 20 20  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 326 168 "energy required\nby problems" "Helvetica" 1 12 0 REF 123 
            CH.ifa.draw.standard.OffsetLocator 3 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 106 283 "problem:getEnergyReq(m)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -77 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 389 372 "problem:getEnergyReq(m)" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 93 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 3 254 269 254 214 359 214 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 123   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 360 219 267 270 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 123  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 217 198 "newER=energy_req+m" "Helvetica" 0 12 0 REF 133 
            CH.ifa.draw.standard.OffsetLocator -26 -36 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 266 245 "energy_req" "Helvetica" 0 12 0 REF 137 
            CH.ifa.draw.standard.OffsetLocator -16 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 3 376 220 549 342 549 504 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 123  
            CH.ifa.draw.standard.ChopBoxConnector REF 99   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 519 325 "energy_req" "Helvetica" 0 12 0 REF 147 
            CH.ifa.draw.standard.OffsetLocator 88 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 365 207 "0" "Helvetica" 0 12 0 REF 123 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 29 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 127 600 ":solveProblem(problem)" "Helvetica" 0 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 26 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 129 614 "storage:solve(problem)" "Helvetica" 0 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 26 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 399 582 "waiting for problems\nin solution process" "Helvetica" 1 11 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator 76 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 390 705 "[storage,wasted]" "Helvetica" 0 12 0 REF 70 
            CH.ifa.draw.standard.OffsetLocator 53 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 160 157 229 157 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "no_attributes" 228 147 20 20    REF 173 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 176 142 "oracle" "Helvetica" 0 12 0 REF 169 
            CH.ifa.draw.standard.OffsetLocator -1 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 576 206 267 274 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 85  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 452 230 "energy_avail" "Helvetica" 0 12 0 REF 177 
            CH.ifa.draw.standard.OffsetLocator 66 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 79 190 "oracle:checkin(this,cID)" "Helvetica" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator -6 40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 3 368 205 368 135 474 135 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 123  
            CH.ifa.draw.standard.ChopBoxConnector REF 35   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 379 138 "energy_req" "Helvetica" 0 12 0 REF 186 
            CH.ifa.draw.standard.OffsetLocator -11 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 351 74 "oracle:updateChoice(this,cID,energy_req-newEA)" "Helvetica" 0 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator 2 -55 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 368 224 368 361 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 123  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 323 274 "energy_req" "Helvetica" 0 12 0 REF 195 
            CH.ifa.draw.standard.OffsetLocator -14 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 3 371 361 429 214 378 214 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector REF 123   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 384 200 "newER=energy_req-m" "Helvetica" 0 12 0 REF 202 
            CH.ifa.draw.standard.OffsetLocator 47 -80 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 578 210 378 361 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 85  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 489 253 "energy_avail" "Helvetica" 0 12 0 REF 209 
            CH.ifa.draw.standard.OffsetLocator 46 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 63 296 "oracle:updateChoice(this,cID,newER-energy_avail)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -51 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 317 348 "detach" "Helvetica" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -32 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 271 276 "attach" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 34 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 497 506 "solve" "Helvetica" 1 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator -37 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 336 384 "oracle:updateChoice(this,cID,newER-energy_avail)" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 109 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 13 14 "choice" "Helvetica" 1 15 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator -513 -490 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 517 525 "oracle:checkout(this,cID)" "Helvetica" 0 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator 35 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 263 373 537 506 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 9  
            CH.ifa.draw.standard.ChopBoxConnector REF 99   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 450 451 "storage" "Helvetica" 0 12 0 REF 236 
            CH.ifa.draw.standard.OffsetLocator 70 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "no_attributes" 293 149 24 16  
        de.renew.gui.ArcConnection "no_attributes" 2 248 157 293 157 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 173  
            CH.ifa.draw.standard.ChopBoxConnector REF 243   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 251 143 "oracle" "Helvetica" 0 12 0 REF 244 
            CH.ifa.draw.standard.OffsetLocator -2 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 291 132 ":get(oracle)" "Helvetica" 0 12 0 REF 243 
            CH.ifa.draw.standard.OffsetLocator 17 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 449 100 "this:get(oracle)" "Helvetica" 0 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator 3 -29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 159 240 "this:get(oracle)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -56 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 387 396 "this:get(oracle)" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 59 34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 535 553 "this:get(oracle)" "Helvetica" 0 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator 26 48 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "no_attributes" 138 31 20 20  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 119 32 "id" "Helvetica" 1 12 0 REF 265 
            CH.ifa.draw.standard.OffsetLocator -24 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "no_attributes" 215 34 24 16  
        de.renew.gui.ArcConnection "no_attributes" 2 158 41 215 41 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 265  
            CH.ifa.draw.standard.ChopBoxConnector REF 269   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 182 23 "cID" "Helvetica" 0 12 0 REF 270 
            CH.ifa.draw.standard.OffsetLocator 5 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 245 34 ":getCid(cID)" "Helvetica" 0 12 0 REF 269 
            CH.ifa.draw.standard.OffsetLocator 50 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 451 88 "this:getCid(cID)" "Helvetica" 0 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator 7 -41 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 127 309 "this:getCid(cID)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -86 39 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 388 408 "this:getCid(cID)" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 62 46 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 565 499 "this:getCid(cID)" "Helvetica" 0 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator 58 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 167 226 "this:buffer()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -58 -44 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "no_attributes" 712 349 24 16  
        de.renew.gui.ArcConnection "no_attributes" 2 724 365 724 397 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 296  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "no_attributes" 714 396 20 20    REF 301 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 703 334 ":buffer()" "Helvetica" 0 12 0 REF 296 
            CH.ifa.draw.standard.OffsetLocator 0 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 2 724 416 724 444 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 301  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 712 444 24 16    REF 309 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 681 462 ":check_buffer(x)" "Helvetica" 0 12 0 REF 309 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 739 396 "attached?" "Helvetica" 1 12 0 REF 301 
            CH.ifa.draw.standard.OffsetLocator 43 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 714 422 "x" "Helvetica" 0 12 0 REF 305 
            CH.ifa.draw.standard.OffsetLocator -7 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 721 399 "0" "Helvetica" 0 12 0 REF 301 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 730 374 "x+1" "Helvetica" 0 12 0 REF 297 
            CH.ifa.draw.standard.OffsetLocator 16 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 3 721 398 713 381 720 365 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 301  
            CH.ifa.draw.standard.ChopBoxConnector REF 296   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 705 374 "x" "Helvetica" 0 12 0 REF 325 
            CH.ifa.draw.standard.OffsetLocator -9 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 423 335 "this:buffer2()" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 89 -27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "no_attributes" 716 594 20 20  
        de.renew.gui.ArcConnection "no_attributes" 2 726 595 726 556 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 335  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 714 540 24 16    REF 340 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 708 522 ":buffer2()" "Helvetica" 0 12 0 REF 340 
            CH.ifa.draw.standard.OffsetLocator 6 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 729 568 "y" "Helvetica" 0 12 0 REF 336 
            CH.ifa.draw.standard.OffsetLocator 6 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 3 722 556 712 579 722 596 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 340  
            CH.ifa.draw.figures.ChopEllipseConnector REF 335   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 691 570 "y+1" "Helvetica" 0 12 0 REF 347 
            CH.ifa.draw.standard.OffsetLocator -16 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 723 597 "0" "Helvetica" 0 12 0 REF 335 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 2 726 614 726 644 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 335  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 714 644 24 16    REF 361 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 731 621 "y" "Helvetica" 0 12 0 REF 357 
            CH.ifa.draw.standard.OffsetLocator 8 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 679 661 ":check_buffer2(y)" "Helvetica" 0 12 0 REF 361 
            CH.ifa.draw.standard.OffsetLocator 0 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 741 595 "detached ?" "Helvetica" 1 12 0 REF 335 
            CH.ifa.draw.standard.OffsetLocator 46 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "no_attributes" 2 148 149 148 51 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector REF 265   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 155 102 "cID" "Helvetica" 0 12 0 REF 371 
            CH.ifa.draw.standard.OffsetLocator 16 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   