10 
    de.renew.gui.CPNDrawing 87 
        de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FontSize" "Int" 10 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 717 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 10 6 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 718 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 2 30 16 111 16 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 8 "FontStyle" "Int" 0 "FigureWithID" "Int" 719 "FontName" "String" "Monospaced" "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FillColor" "Color" 112 219 147 "FontSize" "Int" 10 "FrameColor" "Color" 0 0 0 111 8 24 16 NULL    REF 6 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 720 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 4 29 "\"Apple\"" "Monospaced" 0 10 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 5 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 721 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 2 135 15 260 15 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FontSize" "Int" 10 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 722 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 259 5 20 20 NULL    REF 14 
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 723 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 2 135 20 305 90 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FontSize" "Int" 10 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 724 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 303 83 20 20 NULL    REF 19 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 725 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 205 49 "maker" "Monospaced" 0 10 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FontSize" "Int" 10 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 726 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 301 4 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 727 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 293 23 "\"Pear\"" "Monospaced" 0 10 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 0 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 728 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 2 321 14 415 14 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 23  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FigureWithID" "Int" 729 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 415 6 24 16 NULL    REF 31 
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 730 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 2 321 88 415 22 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 19  
            CH.ifa.draw.standard.ChopBoxConnector REF 31   
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 731 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 2 427 22 427 92 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 31  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 732 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 417 91 20 20 NULL    REF 40 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 733 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 166 9 "fruit-jelly" "Monospaced" 0 10 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 734 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 332 7 "other-fruit" "Monospaced" 0 10 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator -3 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 735 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 296 47 "jelly-maker" "Monospaced" 0 10 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator -39 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 736 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 273 123 "The second transition doesn't work, because\nof several rather interesting reasons." "Dialog" 0 12 0 NULL NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FontSize" "Int" 10 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 737 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 17 174 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 738 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 2 37 184 202 184 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 51  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 8 "FontStyle" "Int" 0 "FigureWithID" "Int" 739 "FontName" "String" "Monospaced" "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FillColor" "Color" 112 219 147 "FontSize" "Int" 10 "FrameColor" "Color" 0 0 0 202 176 24 16 NULL    REF 56 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 740 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 104 178 "fruit" "Monospaced" 0 10 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 741 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 11 197 "\"Peach\"" "Monospaced" 0 10 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 5 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 742 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 2 213 192 213 353 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 56  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FontSize" "Int" 10 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 743 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 203 352 20 20 NULL    REF 67 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 744 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 7 237 "(let* ((maker #f)\n       (fruit-jam\n        (string-append\n         (call/cc (lambda (c)\n                    (set! maker c)\n                    fruit))\n         \"-Jam\")))\n  (cons fruit-jam maker))" "Monospaced" 0 10 0 REF 63 
            CH.ifa.draw.standard.OffsetLocator -104 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FontSize" "Int" 10 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 745 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 282 198 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 746 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 257 182 "\"Strawberry\"" "Monospaced" 0 10 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator 1 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 747 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 267 166 "\"Cherry\"" "Monospaced" 0 10 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator -1 -36 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 7 "FontSize" "Int" 10 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 748 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 280 354 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 749 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 2 223 362 280 362 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 67  
            CH.ifa.draw.standard.ChopBoxConnector REF 78   
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 750 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 407 348 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 751 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 2 291 354 290 306 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 78  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FontSize" "Int" 10 "FontName" "String" "Monospaced" "FrameColor" "Color" 0 0 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 752 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 280 286 20 20 NULL    REF 88 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 753 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 260 324 "(cdr pair)" "Monospaced" 0 10 0 REF 84 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 754 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 2 298 291 404 217 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 88  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FigureWithID" "Int" 755 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 404 201 24 16 NULL    REF 96 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 756 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 336 248 "maker" "Monospaced" 0 10 0 REF 92 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 757 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 2 302 208 404 208 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 71  
            CH.ifa.draw.standard.ChopBoxConnector REF 96   
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 758 "MarkingAppearance" "Int" 2 "FontStyle" "Int" 0 "FontSize" "Int" 10 "FontName" "String" "Monospaced" 2 416 217 417 349 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 96  
            CH.ifa.draw.figures.ChopEllipseConnector REF 83   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 759 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 414 268 "(maker new-fruit)" "Monospaced" 0 10 0 REF 104 
            CH.ifa.draw.standard.OffsetLocator 49 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 760 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 54 44 "(begin\n  (define f-jelly\n    (string-append\n     (call/cc (lambda (c)\n                (bind maker c)\n                fruit))\n     \"-Jelly\"))\n  (bind fruit-jelly f-jelly)\n  f-jelly)" "Monospaced" 0 10 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 21 86 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 761 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 238 355 "pair" "Monospaced" 0 10 0 REF 79 
            CH.ifa.draw.standard.OffsetLocator -1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 762 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 329 202 "new-fruit" "Monospaced" 0 10 0 REF 100 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 763 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 377 60 "(jelly-maker other-fruit)" "Monospaced" 0 10 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 25 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 764 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 8 378 "Isolating the continuation works, but using it won't activate the transition, because the\ncontinuation will continue to the code handling the transition where it was captured (!).\nI.e. the LET* expression will be updated, but not (maker new-fruit)\n\n" "Dialog" 0 12 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 765 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 55 10 "fruit" "Monospaced" 0 10 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 637 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 286 519 "(call/cc\n (lambda (c)\n   (maker c\n          new-fruit)))" "Monospaced" 0 10 0 
            de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 630 "MarkingAppearance" "Int" 2 "FontName" "String" "Monospaced" "FontSize" "Int" 10 "FontStyle" "Int" 0 2 440 496 272 610 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 7 "FigureWithID" "Int" 627 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FontName" "String" "Monospaced" "FontSize" "Int" 10 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 440 480 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FigureWithID" "Int" 622 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FontName" "String" "Monospaced" "FontSize" "Int" 10 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 254 605 20 20 NULL    
            CH.ifa.draw.standard.OffsetLocator -4 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 8 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 613 "FrameColor" "Color" 0 0 0 "FontName" "String" "Monospaced" "FontSize" "Int" 10 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 252 480 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 616 "MarkingAppearance" "Int" 2 "FontName" "String" "Monospaced" "FontSize" "Int" 10 "FontStyle" "Int" 0 2 264 496 264 606 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 136  
            CH.ifa.draw.figures.ChopEllipseConnector REF 133   
        de.renew.gui.TransitionFigure "attributes" "attributes" 7 "FigureWithID" "Int" 620 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FontName" "String" "Monospaced" "FontSize" "Int" 10 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 332 607 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 621 "MarkingAppearance" "Int" 2 "FontName" "String" "Monospaced" "FontSize" "Int" 10 "FontStyle" "Int" 0 2 274 615 332 615 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 133  
            CH.ifa.draw.standard.ChopBoxConnector REF 141   REF 133 
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 623 "MarkingAppearance" "Int" 2 "FontName" "String" "Monospaced" "FontSize" "Int" 10 "FontStyle" "Int" 0 2 356 608 444 562 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 141  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FigureWithID" "Int" 624 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FontName" "String" "Monospaced" "FontSize" "Int" 10 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 442 547 20 20 NULL    REF 150 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 625 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 370 579 "(cdr pair)" "Monospaced" 0 10 0 REF 146 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 626 "MarkingAppearance" "Int" 2 "FontName" "String" "Monospaced" "FontSize" "Int" 10 "FontStyle" "Int" 0 2 452 548 452 496 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 150  
            CH.ifa.draw.standard.ChopBoxConnector REF 131   REF 131 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 628 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 437 516 "maker" "Monospaced" 0 10 0 REF 154 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 629 "MarkingAppearance" "Int" 2 "FontName" "String" "Monospaced" "FontSize" "Int" 10 "FontStyle" "Int" 0 2 355 488 440 488 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 6 "FigureWithID" "Int" 2 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FontName" "String" "Monospaced" "FontSize" "Int" 10 "FillColor" "Color" 112 219 147 335 478 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 131   REF 128 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 631 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 290 608 "pair" "Monospaced" 0 10 0 REF 142 
            CH.ifa.draw.standard.OffsetLocator -1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 632 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 373 482 "new-fruit" "Monospaced" 0 10 0 REF 161 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 633 "MarkingAppearance" "Int" 2 "FontName" "String" "Monospaced" "FontSize" "Int" 10 "FontStyle" "Int" 0 2 356 615 443 615 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 141  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 7 "FigureWithID" "Int" 634 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FontName" "String" "Monospaced" "FontSize" "Int" 10 "FontStyle" "Int" 0 "FillColor" "Color" 112 219 147 442 605 20 20 NULL    REF 176 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 635 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 369 609 "(car pair)" "Monospaced" 0 10 0 REF 172 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 164 
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "FigureWithID" "Int" 4 "MarkingAppearance" "Int" 2 "FontName" "String" "Monospaced" "FontSize" "Int" 10 2 336 488 276 488 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 164  
            CH.ifa.draw.standard.ChopBoxConnector REF 136   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 291 482 "fruit" "Monospaced" 0 10 0 REF 180 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 2 "FigureWithID" "Int" 639 "MarkingAppearance" "Int" 2 2 231 567 258 567 NULL NULL "CH.ifa.draw.figures.ArrowTip"  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 618 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 328 462 "\"Lime\"" "Monospaced" 0 10 0 REF 164 
            CH.ifa.draw.standard.OffsetLocator 1 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 321 437 "\"Orange\"" "Monospaced" 0 10 0 REF 164 
            CH.ifa.draw.standard.OffsetLocator 0 -45 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 619 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 323 449 "\"Lemon\"" "Monospaced" 0 10 0 REF 164 
            CH.ifa.draw.standard.OffsetLocator -1 -33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 636 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 6 464 "(let* ((maker #f)\n       (return (lambda (x) x))\n       (marmalade\n        (string-append\n         (call/cc\n          (lambda (c)\n            (set! maker\n                  (lambda (ret fruit)\n                    (set! return ret)\n                    (c fruit)))\n            fruit))\n         \"-Marmalade\")))\n  (return (cons marmalade maker)))" "Monospaced" 0 10 0 REF 137 
            CH.ifa.draw.standard.OffsetLocator -147 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 766 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 324 500 "Orchard" "SansSerif" 1 12 0 REF 164 
            CH.ifa.draw.standard.OffsetLocator 3 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 767 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 239 625 "Kitchen" "SansSerif" 1 12 0 REF 133 
            CH.ifa.draw.standard.OffsetLocator -2 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 768 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 432 573 "Garage" "SansSerif" 1 12 0 REF 150 
            CH.ifa.draw.standard.OffsetLocator 1 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 769 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 432 628 "Fridge" "SansSerif" 1 12 0 REF 176 
            CH.ifa.draw.standard.OffsetLocator -1 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 770 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 165 460 "pick and first try" "SansSerif" 1 12 0 REF 136 
            CH.ifa.draw.standard.OffsetLocator -47 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 771 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 320 626 "separate" "SansSerif" 1 12 0 REF 141 
            CH.ifa.draw.standard.OffsetLocator 2 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 772 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 387 456 "pick and make" "SansSerif" 1 12 0 REF 131 
            CH.ifa.draw.standard.OffsetLocator -20 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 773 276 437 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 774 2 282 456 268 480 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 221  
            CH.ifa.draw.standard.ChopBoxConnector REF 136   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 775 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 282 440 "()" "SansSerif" 0 12 0 REF 221 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 716 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 4 648 "\"Limiting\" the extent of the captured continuation by passing in the outer continuation helps.\nA framework for delimited continuations should help if you seriously want to use\ncontinuations as token objects. Also the workaround chosen here will not work in the general\ncase." "Dialog" 0 12 0 NULL NULL  NULL  562 141 590 749 