7 
    de.renew.gui.CPNDrawing 53 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 178 "FillColor" "Color" 255 255 255 4 62 281 62 261 201 261 201 242 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 177 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 21 281 "NaturalPerson" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 174 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 181 226 "Person" "Helvetica" 0 12 0 NULL NULL   1
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 180 "FillColor" "Color" 255 255 255 2 201 281 201 242 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 179 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 124 281 "RepresentedNaturalPerson\n\nfirstName: String\ndateOfBirth: Date" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 181 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 301 281 "LegalEntity\n\nvatNumber: String\nlegalName: String\nlegalStatus: String" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 182 "FillColor" "Color" 255 255 255 4 350 281 350 261 201 261 201 242 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 12  
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 183 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 423 281 "OfficeHolder\n\nofficialPosition: String" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 184 "FillColor" "Color" 255 255 255 4 481 281 481 261 201 261 201 242 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 17  
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 190 2 355 25 301 25 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 189 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 360 18 "Contract" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 146 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 186 17 "CompoundContract" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 219 2 366 185 218 126 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 218 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 371 185 "Task" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 187 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 188 111 "Role" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 220 2 493 186 530 127 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 222 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 470 186 "Action" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 192 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 507 111 "Obligation" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 223 2 404 193 465 193 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 31  
            CH.ifa.draw.standard.ChopBoxConnector REF 37   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 225 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 498 149 "what" "Helvetica" 0 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 226 "FillColor" "Color" 255 255 255 2 200 171 200 127 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 185 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 186 171 "Party" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 33  0  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 234 2 384 34 384 111 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 233 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 330 111 "WorkflowDefinition\n\nnet: String" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 221 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 257 144 "participant" "Helvetica" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator -7 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 10 
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 236 3 176 233 80 233 80 212 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 170 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 21 133 "Address\n\nroad: String\nhouseNumber: String\ncity: String\n..." "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 241 2 201 187 201 226 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 50  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 244 2 384 145 384 185 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 56  
            CH.ifa.draw.standard.ChopBoxConnector REF 31   
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 246 2 301 25 355 25 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 27  
            CH.ifa.draw.standard.ChopBoxConnector REF 25   
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 249 2 368 34 216 111 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector REF 33   
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 253 3 414 25 441 25 527 111 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector REF 39   REF 50 REF 39 
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 193 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 563 148 "Right" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "FigureWithID" "Int" 255 "FillColor" "Color" 255 255 255 3 558 155 535 155 535 127 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 85  
            CH.ifa.draw.standard.ChopBoxConnector REF 39   
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 196 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 563 172 "Service" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "FigureWithID" "Int" 256 "FillColor" "Color" 255 255 255 3 558 178 535 178 535 127 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 90  
            CH.ifa.draw.standard.ChopBoxConnector REF 39   
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 198 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 563 198 "Good" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "FigureWithID" "Int" 257 "FillColor" "Color" 255 255 255 3 558 205 535 205 535 127 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 95  
            CH.ifa.draw.standard.ChopBoxConnector REF 39   
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "FigureWithID" "Int" 258 "FillColor" "Color" 255 255 255 3 558 259 535 259 535 127 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 200 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 563 229 "Payment\n\namount: long\ncurrency: String\nmethod: String" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 39   REF 37 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 224 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 411 185 "perform" "Helvetica" 0 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator -2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FillColor" "Color" 255 255 255 "FrameColor" "Color" 255 199 158 "FigureWithID" "Int" 247 177 146 "«roleOf»" "Helvetica" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 0 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 242 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 176 194 "members" "Helvetica" 0 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator 2 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 243 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 210 216 "*" "Helvetica" 0 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator 11 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 25 REF 27 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 248 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 347 9 "*" "Helvetica" 0 12 0 REF 73 
            CH.ifa.draw.standard.OffsetLocator 21 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 4 REF 31 REF 6 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 235 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 367 41 "wfdef" "Helvetica" 0 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator -3 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 56 
        de.renew.gui.fs.UMLNoteFigure "attributes" "attributes" 3 "FigureWithID" "Int" 262 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 397 63 "Ausführung\n(how)" "Helvetica" 2 12 0 NULL NULL
        de.renew.gui.fs.UMLNoteFigure "attributes" "attributes" 3 "FigureWithID" "Int" 263 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 509 49 "Vertragsgegenstände\n(what)" "Helvetica" 2 12 0 NULL NULL
        de.renew.gui.fs.UMLNoteFigure "attributes" "attributes" 3 "FillColor" "Color" 255 255 255 "FrameColor" "Color" 0 0 0 "FigureWithID" "Int" 261 159 54 "Teilnehmer\n(who)" "Helvetica" 2 12 0 NULL NULL  REF 103 REF 33
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 250 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 210 99 "*" "Helvetica" 0 12 0 REF 77 
            CH.ifa.draw.standard.OffsetLocator -80 34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 245 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 394 174 "*" "Helvetica" 0 12 0 REF 69 
            CH.ifa.draw.standard.OffsetLocator 12 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 254 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 530 95 "*" "Helvetica" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 62 34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 64 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 240 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 65 214 "*" "Helvetica" 0 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator -61 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  -6 -1 689 400 
