10 
    de.renew.gui.CPNDrawing 15 
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 25 67 33 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 26 3 86 47 122 63 162 47 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 27 162 35 24 16 NULL    REF 6 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 28 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 157 58 "count" "SansSerif" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 0 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 29 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 50 13 "unsigned" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -1 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 30 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 118 76 "x" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -3 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 31 3 162 40 120 32 87 42 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 32 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 72 35 "0" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 33 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 113 7 "+x" "SansSerif" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator -3 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 34 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 6 54 "counter" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -48 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 35 2 77 53 77 140 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 36 66 140 24 16 NULL    REF 33 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 37 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 59 159 "finish" "SansSerif" 1 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator -1 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 38 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 74 89 "x" "SansSerif" 0 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "FigureWithID" "Int" 39 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 204 4 "/* It is impossible for maria\n  * to unfold this net, because\n  * it has an infinite number of\n  * states.\n  */\ndeadlock true;" "SansSerif" 0 12 0 NULL NULL 1  NULL  0 141 407 220 