11 
    de.renew.gui.CPNDrawing 16 
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 652 58 122 18 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 653 55 207 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 654 2 67 142 67 207 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 655 2 79 214 129 214 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 661 128 204 18 20 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 657 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 61 124 "1" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 658 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 61 101 "A" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -2 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 659 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 62 188 "b" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -1 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 11 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 666 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 130 183 "D" "SansSerif" 1 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator -2 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 673 2 137 205 137 141 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 674 125 125 24 16 NULL    REF 28 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 675 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 133 106 "a" "SansSerif" 1 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator -1 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 676 2 125 132 76 132 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 28  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 679 177 122 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 680 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 198 95 "X" "SansSerif" 1 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 15 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 682 2 149 132 178 132 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 28  
            CH.ifa.draw.figures.ChopEllipseConnector REF 36   NULL  680 162 407 502 