11 
    de.renew.gui.CPNDrawing 10 
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 4 "MarkingAppearance" "Int" 3 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 37 22 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5 "MarkingAppearance" "Int" 3 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 174 24 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 8 "MarkingAppearance" "Int" 3 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 106 94 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 9 "MarkingAppearance" "Int" 3 "FrameColor" "Color" 0 0 0 255 2 54 39 109 94 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 10 "MarkingAppearance" "Int" 3 "FrameColor" "Color" 0 0 0 255 2 178 41 125 94 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13 "MarkingAppearance" "Int" 3 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 67 67 "x" "SansSerif" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -11 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 14 "MarkingAppearance" "Int" 3 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 158 67 "y" "SansSerif" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 10 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 15 "MarkingAppearance" "Int" 3 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 68 119 "(not (equal? x y))" "SansSerif" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -2 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 20 "MarkingAppearance" "Int" 3 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 5 5 "(new 'othernet)" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 1 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 21 "MarkingAppearance" "Int" 3 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 142 7 "(new 'othernet)" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 1 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  897 141 255 179 