10 
    de.renew.gui.CPNDrawing 81 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 478 464 400 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 479 282 537 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 480 400 457 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 481 690 269 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 482 577 650 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 483 129 607 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 484 174 191 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 485 "FillColor" "Color" 255 0 0 779 138 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 2 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 487 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 650 287 "exclusion" "SansSerif" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -21 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 488 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 115 626 "received" "SansSerif" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 1 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 492 2 420 467 791 413 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 493 791 404 24 16 NULL    REF 19 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 494 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 602 433 "s" "SansSerif" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 495 2 706 287 796 404 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector REF 19   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 497 2 790 158 802 404 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 19   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 498 2 791 411 484 410 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 19  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 499 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 634 403 "s" "SansSerif" 0 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 500 2 796 420 594 653 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 19  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 501 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 633 529 "db_t t ( t != s): { s, t }" "SansSerif" 0 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 502 2 474 401 448 222 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 503 435 206 24 16 NULL    REF 49 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 504 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 458 304 "s" "SansSerif" 0 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 505 2 194 201 435 213 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector REF 49   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 506 2 445 222 411 458 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 49  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 507 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 425 333 "s" "SansSerif" 0 12 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 508 2 459 217 691 278 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 49  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 509 2 459 211 780 150 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 49  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 510 2 410 477 403 618 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 511 391 618 24 16 NULL    REF 76 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 512 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 404 540 "r" "SansSerif" 0 12 0 REF 72 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 514 2 578 659 415 628 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 76   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 515 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 479 636 "{ s, r }" "SansSerif" 0 12 0 REF 80 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 516 2 391 618 300 553 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 76  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 517 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 343 578 "r" "SansSerif" 0 12 0 REF 87 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 518 2 391 625 149 617 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 76  
            CH.ifa.draw.figures.ChopEllipseConnector REF 6   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 519 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 253 614 "{ s, r }" "SansSerif" 0 12 0 REF 94 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 520 2 289 539 176 276 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 521 161 260 24 16 NULL    REF 105 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 523 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 230 400 "r" "SansSerif" 0 12 0 REF 101 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 524 2 140 608 172 276 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 105   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 525 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 139 435 "{ s, r }" "SansSerif" 0 12 0 REF 109 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 526 2 182 276 403 462 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 105  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 527 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 290 362 "r" "SansSerif" 0 12 0 REF 116 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 528 2 174 260 183 211 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 105  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 531 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 781 85 "(db_pair_t p (p.first != p.second): p)\nminus\n(db_t t: (map s { place waiting } {s, t}))" "SansSerif" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 101 -41 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 539 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 803 137 "unused" "SansSerif" 1 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 37 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 546 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 743 272 "db_t t (t != s): { s, t }" "SansSerif" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 7 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 548 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 170 231 "{ s, r }" "SansSerif" 0 12 0 REF 123 
            CH.ifa.draw.standard.OffsetLocator 9 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 536 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 417 500 "(db_t d: d)\nminus\n(place waiting\nunion\nplace performing)" "SansSerif" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 58 70 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 538 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 4 6 "// Distributed data base management model for Maria by Marko Mäkelä\n\n// First presented by Genrich and Lautenbach; later by Jensen\n\n// converted to Renew MariaNets plugin by Friedrich Delgado Friedrichs\n\n// Delete the \"unused\" place and/or the \"!\" at the \"receive message\" place\n// to emulate behaviour without the -DUNUSED and -DPRIORITY switches.\n\ntypedef id[10] db_t;\ntypedef struct {\n  db_t first;\n  db_t second;\n} db_pair_t;" "SansSerif" 0 12 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 496 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 736 334 "{}" "SansSerif" 0 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator -11 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 537 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 575 242 "{}" "SansSerif" 0 12 0 REF 64 
            CH.ifa.draw.standard.OffsetLocator 4 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 513 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 0 0 398 640 "!" "SansSerif" 0 21 0 REF 76 
            CH.ifa.draw.standard.OffsetLocator -2 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 2 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 490 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 677 299 "(0..1)" "SansSerif" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -7 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 2 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 555 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 665 312 "struct {}" "SansSerif" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -13 40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 2 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 545 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 528 327 "(place waiting equals empty)#{}" "SansSerif" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -82 55 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 550 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 417 475 "(0..#db_t)" "SansSerif" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 36 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 556 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 418 488 "db_t" "SansSerif" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 21 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 529 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 565 171 "db_t t (t != s): { s, t }" "SansSerif" 0 12 0 REF 68 
            CH.ifa.draw.standard.OffsetLocator 6 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 530 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 793 420 "\"update and send messages\"" "SansSerif" 1 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator 80 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 543 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 576 682 "(0..#db_t-1)" "SansSerif" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 25 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 557 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 577 699 "db_pair_t" "SansSerif" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 17 46 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 542 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 577 668 "sent" "SansSerif" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 3 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 541 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 483 359 "waiting" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 32 -44 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 540 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 483 372 "(0..1)" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 25 -31 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 558 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 483 386 "db_t" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 22 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 547 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 177 159 "(0..#db_t-1)" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 29 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 559 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 175 175 "db_pair_t" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 18 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 535 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 175 145 "acknowledged" "SansSerif" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 36 -49 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 534 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 254 206 "db_t t (t != s): { s, t }" "SansSerif" 0 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 0 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 522 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 3 261 "\"send acknowledgement\"" "SansSerif" 1 12 0 REF 105 
            CH.ifa.draw.standard.OffsetLocator -91 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 486 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 230 557 "performing" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -27 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 549 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 420 444 "inactive" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 34 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 533 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 470 206 "\"receive acknowledgements\"" "SansSerif" 1 12 0 REF 49 
            CH.ifa.draw.standard.OffsetLocator 112 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 489 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 228 570 "(0..#db_t-1)" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -28 30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 560 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 229 584 "db_t" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -50 44 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 491 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 113 639 "(0..#db_t-1)" "SansSerif" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 10 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 561 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 112 654 "db_pair_t" "SansSerif" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 0 44 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 532 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 783 36 "(1+#db_pair_t-2*#db_t,\n #db_pair_t-#db_t)" "SansSerif" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 66 -97 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 563 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 782 68 "db_pair_t" "SansSerif" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 20 -73 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "ArrowTip" "String" "CH.ifa.draw.figures.ArrowTip" "FigureWithID" "Int" 544 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 406 600 "\"receive message\"" "SansSerif" 1 12 0 REF 76 
            CH.ifa.draw.standard.OffsetLocator 59 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  0 141 1031 762 