11 
    de.renew.gui.CPNDrawing 18 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63190 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -82 -6 "dc-web-send-answer" "SansSerif" 1 12 0 
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63174 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 -35 -30 54 25 NULL  
            CH.ifa.draw.standard.OffsetLocator 0 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63170 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -120 -76 198 152 6  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63171 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 8 
            de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63172 "FillColor" "Color" 255 255 255 255 -125 -8 24 16 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63176 2 -101 0 89 0 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 7  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63173 "FillColor" "Color" 255 255 255 255 88 -10 20 20 NULL    REF 12 REF 2 
            de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 63175 "FillColor" "Color" 192 192 192 255 -74 -65 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63181 2 -106 -8 -70 -48 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 7  
                CH.ifa.draw.figures.ChopEllipseConnector REF 13   REF 5 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63182 2 -32 -14 -101 -3 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 2  
                CH.ifa.draw.standard.ChopBoxConnector REF 7    REF 7 REF 12 REF 2 REF 13 REF 8 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63177 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 -129 -7 ">" "SansSerif" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63178 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 105 -8 ">" "SansSerif" 1 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 12 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63179 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -69 8 ":exchange(s,o,id);" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 100 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63180 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 -160 80 "[receive web event response]" "SansSerif" 0 18 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -6 91 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 14 REF 18 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63183 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 -89 -39 "o" "SansSerif" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 3 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63184 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 -70 -16 "s" "SansSerif" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63188 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -98 -39 "AgentletHelper.\nDC_ACTION_WEB_EVENT_REQUEST" "SansSerif" 0 11 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 7 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63189 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 -168 -122 "[@param id Request ID\n@result o Content of response message]" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -30 -89 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   4  NULL  375 168 706 600 