11 
    de.renew.gui.CPNDrawing 17 
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63082 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -1 -78 198 152 6  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63083 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 8 
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63084 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 84 -32 54 25 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63091 2 -32 -55 0 -10 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FillColor" "Color" 192 192 192 255 "FigureWithID" "Int" 63087 -48 -73 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FillColor" "Color" 255 255 255 255 "FigureWithID" "Int" 63085 -6 -10 24 16 NULL    REF 9 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63093 2 18 -2 208 -2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 9  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FillColor" "Color" 255 255 255 255 "FigureWithID" "Int" 63086 207 -12 20 20 NULL    REF 14 REF 7 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 63095 2 87 -16 18 -5 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 3  
                CH.ifa.draw.standard.ChopBoxConnector REF 9   REF 1  REF 3 REF 9 REF 14 REF 7 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextColor" "Color" 0 0 255 255 "FigureWithID" "Int" 63065 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 -48 -124 "[@param name Name of WebEventAction\n@result seq VTSequence of WebEvents]" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -17 -107 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 63088 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 49 -18 "s" "SansSerif" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 63089 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 50 6 ":exchange(s,o,id);" "SansSerif" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 100 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextColor" "Color" 0 0 255 255 "FigureWithID" "Int" 63090 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 -28 78 "[send web event response]" "SansSerif" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -6 91 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 4 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 63092 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 -33 -42 "[id,o]" "SansSerif" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -1 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 10 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextColor" "Color" 255 0 0 255 "FigureWithID" "Int" 63094 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 224 -10 ">" "SansSerif" 1 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 12 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 15 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextColor" "Color" 255 0 0 255 "FigureWithID" "Int" 63096 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 -10 -9 ">" "SansSerif" 1 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 63097 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 29 -42 "AgentletHelper.\nDC_ACTION_HANDLE_WEB_EVENTS" "SansSerif" 0 11 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 15 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  496 196 706 600 