11 
    de.renew.gui.CPNDrawing 40 
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "LineStyle" "String" "1 2" "FigureWithID" "Int" 1559 4 614 423 618 423 618 51 561 51 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1553 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 619 392 "SearchDistributorImpl\n\nsearchers: Map<Long, SearcherAccessor>\n\ncreateExecutables(): Collection<Executable>\nabort()" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1555 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 329 13 "«remote interface»\nSearcherAccessor\n\nsearchCall(RemoteSuccessNotifier, ...)\ncreateBinding(DistributeBindingAwaiter)\nabort()" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 1522 "FillColor" "Color" 255 255 255 255 2 855 94 855 62 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1544 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 654 94 "DistributeSearcher\n\ngetPrimaryTriggerableAccessor(): TriggerableAccessor\ngetDistributor(): SearchDistributor\ncreateDistributor(): SearchDistributorImpl\ndeleteDistributor()\nsearchFirstCall(ChannelTarget, String, Variable, boolean)\nsearchAdditionalCall(Finder, ChannelTarget, String, Variable, boolean)" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1545 "FrameColor" "Color" 0 0 255 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 707 28 "Searcher\n\nsearchAndRecover(Finder, Searchable, Triggerable)" "SansSerif" 0 12 0 NULL NULL   0
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1523 2 823 203 762 306 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1552 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 640 306 "«remote interface»\nSearchDistributor\n\nsearchCall(RemoteSuccessNotifier, ...)" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1524 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 762 247 "distributor" "SansSerif" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 1525 "FillColor" "Color" 255 255 255 255 2 748 392 748 355 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector REF 17  0  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 1526 "FillColor" "Color" 255 255 255 255 2 442 124 442 92 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1554 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 349 124 "SearcherAccessorImpl\n\nprimaryTriggerable: Triggerable\nabortRequested: boolean" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  0  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1527 2 483 173 707 306 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector REF 17   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1528 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 565 232 "distributor" "SansSerif" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1529 2 541 148 649 148 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector REF 10   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1530 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 555 141 "searcher" "SansSerif" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator -15 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "LineStyle" "String" "1 2" "FigureWithID" "Int" 1531 2 376 173 298 202 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1546 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 113 202 "RemoteSuccessNotifierAdapter\n\nreturnVar: Variable\n\nreportSuccess()\nsetReturnVariable(Variable)" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1532 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 313 180 "«create»" "SansSerif" 0 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1533 2 208 269 208 306 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 48  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1547 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 137 306 "«remote interface»\nRemoteSuccessNotifier\n\nreportSuccess(Object)" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1534 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 187 280 "internal" "SansSerif" 0 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "LineStyle" "String" "1 2" "FigureWithID" "Int" 1535 2 415 338 234 392 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1550 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 382 322 "SendChannelBinder" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1557 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 123 392 "RemoteSuccessNotifierImpl" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "LineStyle" "String" "1 2" "FigureWithID" "Int" 1536 2 508 330 635 330 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 63  
            CH.ifa.draw.standard.ChopBoxConnector REF 17   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1537 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 555 323 "«use»" "SansSerif" 0 12 0 REF 66 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 1538 "FillColor" "Color" 255 255 255 255 2 128 133 128 77 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1543 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 17 133 "anonymous Finder\nin SearcherAccessorImpl.searchCall(...)" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1551 "FrameColor" "Color" 0 0 255 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 61 13 "«interface»\nFinder\n\nfound(Searcher)\nisCompleted(): boolean" "SansSerif" 0 12 0 NULL NULL   0
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "LineStyle" "String" "1 2" "FigureWithID" "Int" 1539 2 142 164 177 202 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 76  
            CH.ifa.draw.standard.ChopBoxConnector REF 48   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1540 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 143 175 "«use»" "SansSerif" 0 12 0 REF 79 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "LineStyle" "String" "1 2" "FigureWithID" "Int" 1541 2 344 148 245 148 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector REF 76   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1542 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 270 141 "«create»" "SansSerif" 0 12 0 REF 86 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 76 REF 10 REF 48 REF 56 
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1548 "FrameColor" "Color" 0 0 255 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 400 235 "«interface»\nBinder\n\nbind(Searcher)" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 1549 "FillColor" "Color" 255 255 255 255 2 442 322 442 284 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 63  
            CH.ifa.draw.standard.ChopBoxConnector REF 93  0  REF 63 REF 78 REF 17 REF 4 REF 28 REF 6 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1556 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 300 358 "«create»" "SansSerif" 0 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 65 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 1558 "FillColor" "Color" 255 255 255 255 2 208 392 208 355 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 65  
            CH.ifa.draw.standard.ChopBoxConnector REF 56  0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 1560 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 579 45 "«use»" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 6 -185 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 1561 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 566 38 "*" "SansSerif" 0 12 0 NULL NULL  REF 12 NULL  77 272 1101 506 