11 
    de.renew.gui.CPNDrawing 52 
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 2 "LineStyle" "String" "10" "FigureWithID" "Int" 4212 2 692 139 692 684 NULL NULL "CH.ifa.draw.figures.ArrowTip"  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 2 "LineStyle" "String" "10" "FigureWithID" "Int" 4213 2 435 140 435 685 NULL NULL "CH.ifa.draw.figures.ArrowTip"  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 2 "LineStyle" "String" "10" "FigureWithID" "Int" 4214 2 176 144 176 689 NULL NULL "CH.ifa.draw.figures.ArrowTip"  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4216 166 191 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4218 118 273 118 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4219 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 125 275 "determinePaperTopic" "SansSerif" 1 9 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4222 294 270 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4223 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 171 194 "[]" "SansSerif" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4224 371 271 129 19 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4225 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 390 274 "providePaperFrame" "SansSerif" 1 9 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4226 2 314 280 371 280 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 9  
            CH.ifa.draw.standard.ChopBoxConnector REF 13   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4227 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 281 289 "sps:topic" "SansSerif" 1 9 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -1 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4228 2 435 290 435 371 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 13  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4283 425 370 20 20 NULL    
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4230 558 270 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4231 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 544 292 "ppf:frame" "SansSerif" 1 9 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 0 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4232 2 500 280 559 280 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 13  
            CH.ifa.draw.figures.ChopEllipseConnector REF 29   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4234 628 382 129 19 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4235 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 654 385 "writePaperBody" "SansSerif" 1 9 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4236 3 578 280 692 280 692 382 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 29  
            CH.ifa.draw.standard.ChopBoxConnector REF 37   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4237 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 706 362 "role=writePaperBody;" "SansSerif" 2 9 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator 62 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4238 563 497 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4239 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 553 519 "wpb:body" "SansSerif" 1 9 0 REF 48 
            CH.ifa.draw.standard.OffsetLocator 4 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4244 371 498 129 19 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4245 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 387 502 "integratePaperBody" "SansSerif" 1 9 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator 0 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4246 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 446 477 "role=providePaperFrame;" "SansSerif" 2 9 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator 68 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4250 2 564 507 500 507 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 48  
            CH.ifa.draw.standard.ChopBoxConnector REF 52   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4251 3 692 401 692 507 583 507 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 37  
            CH.ifa.draw.figures.ChopEllipseConnector REF 48   
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4252 296 497 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4253 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 286 519 "ppf:paper" "SansSerif" 1 9 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator 4 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4254 2 371 507 316 507 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 52  
            CH.ifa.draw.figures.ChopEllipseConnector REF 67   
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4255 118 499 118 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4256 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 154 502 "editPaper" "SansSerif" 1 9 0 REF 75 
            CH.ifa.draw.standard.OffsetLocator 0 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4257 2 297 507 236 507 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 67  
            CH.ifa.draw.standard.ChopBoxConnector REF 75   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4260 2 176 390 176 499 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4281 166 370 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 75   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4261 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 186 478 "role=supervisePaperSubmission;" "SansSerif" 2 9 0 REF 75 
            CH.ifa.draw.standard.OffsetLocator 84 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4262 2 176 515 176 566 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 75  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4263 166 565 20 20 NULL    REF 95 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4264 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 199 158 255 72 116 " supervisePaperSubmission " "SansSerif" 0 15 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -2 -291 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4265 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 199 158 255 353 117 " providePaperFrame " "SansSerif" 0 16 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -1 -286 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4266 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 199 158 255 628 114 " writePaperBody " "SansSerif" 0 16 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 2 -288 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4267 2 435 390 435 498 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector REF 52   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4233 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 452 247 "role=providePaperFrame;" "SansSerif" 2 9 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 74 -28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 4215 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 29 24 "DWF;\nname=sp;\norganization=paper;" "SansSerif" 0 18 0 NULL NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4274 2 236 280 295 280 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.figures.ChopEllipseConnector REF 9   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4275 2 176 289 176 371 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.figures.ChopEllipseConnector REF 86   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4276 2 176 211 176 273 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector REF 5   REF 86 REF 28 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4284 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 449 374 "frame" "SansSerif" 1 9 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 28 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4282 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 195 372 "topic" "SansSerif" 1 9 0 REF 86 
            CH.ifa.draw.standard.OffsetLocator 31 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4220 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 189 253 "role=supervisePaperSubmission;\n" "SansSerif" 2 9 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 87 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4285 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 198 569 "editedPaper" "SansSerif" 1 9 0 REF 95 
            CH.ifa.draw.standard.OffsetLocator 51 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  958 61 962 932 