5 
    de.renew.gui.CPNDrawing 38 
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 120 207 20 20 NULL  
        de.renew.gui.ArcConnection "no_attributes" 2 139 220 287 270 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 287 267 24 16 NULL    REF 6 
        de.renew.gui.ArcConnection "no_attributes" 2 311 270 456 220 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 454 207 20 20 NULL    REF 11 
        de.renew.gui.TransitionFigure "no_attributes" 286 152 24 16 NULL  
        de.renew.gui.ArcConnection "no_attributes" 2 286 164 139 215 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL 
            CH.ifa.draw.standard.ChopBoxConnector REF 12  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 197 207 20 20 NULL  
        de.renew.gui.ArcConnection "no_attributes" 2 215 222 287 267 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 17  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.ArcConnection "no_attributes" 2 217 217 343 217 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 17  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 343 209 24 16 NULL    REF 26 
        de.renew.gui.ArcConnection "no_attributes" 2 367 217 455 217 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 26  
            CH.ifa.draw.figures.ChopEllipseConnector REF 11   
        de.renew.gui.ArcConnection "no_attributes" 2 456 215 310 164 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector REF 12   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 192 246 "[x,z]" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -11 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DoubleArcConnection "no_attributes" 2 286 167 215 213 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 12  
            CH.ifa.draw.figures.ChopEllipseConnector REF 17   
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 288 96 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 2 129 116 129 152 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 119 96 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 118 152 24 16 NULL    REF 49 
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 2 130 168 130 208 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 49  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 207 167 "[x,y]" "Helvetica" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 5 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 47 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 126 99 "[]" "Helvetica" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 192 192 192 2 289 109 142 156 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 43  
            CH.ifa.draw.standard.ChopBoxConnector REF 49   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 33 182 "t.pairs(t.nodes())" "Helvetica" 0 12 0 REF 50 
            CH.ifa.draw.standard.OffsetLocator -53 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 192 192 192 2 298 116 298 152 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 43  
            CH.ifa.draw.standard.ChopBoxConnector REF 12   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 307 126 "t" "Helvetica" 0 12 0 REF 66 
            CH.ifa.draw.standard.OffsetLocator 10 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 272 284 "guard z>y" "Helvetica" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 0 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 219 131 "t" "Helvetica" 0 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator 5 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 323 226 "guard z<=y" "Helvetica" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator -2 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 253 189 "t.prod(t.neighbors(x),y)" "Helvetica" 0 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 64 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 395 218 "[x,y]" "Helvetica" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator -6 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 402 239 "[x,y]" "Helvetica" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 29 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 175 50 "new UnionTopology(\n  x=new StarTopology(8),\n  new InverseTopology(x))" "Helvetica" 0 12 0 REF 43 
            CH.ifa.draw.standard.OffsetLocator -53 -34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 376 169 "[x,y]" "Helvetica" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 3 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 70 207 "pending" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -38 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 344 113 "import samples.reisig.*;" "Helvetica" 0 12 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 267 238 "[x,z]" "Helvetica" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 26 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 269 220 "[x,z]" "Helvetica" 0 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator -1 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  416 354 710 667 