5 
    de.renew.gui.CPNDrawing 139 
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 560 71 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 470 21 "new UnionTopology(\n  x=new LineTopology(9),\n  new InverseTopology(x))" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -30 -38 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 253 387 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 286 386 ":show(3,n)" "Helvetica" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 49 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 255 436 20 20 NULL  
        de.renew.gui.ArcConnection "no_attributes" 3 272 440 291 421 273 403 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 9  
            CH.ifa.draw.standard.ChopBoxConnector REF 5   
        de.renew.gui.ArcConnection "no_attributes" 3 256 403 239 420 259 440 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.figures.ChopEllipseConnector REF 9   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 275 414 "o" "Helvetica" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 249 414 "n" "Helvetica" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 277 439 "\"?\"" "Helvetica" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 19 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 252 480 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 285 479 ":show(4,n)" "Helvetica" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 49 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 254 529 20 20 NULL  
        de.renew.gui.ArcConnection "no_attributes" 3 271 533 290 514 272 496 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 31  
            CH.ifa.draw.standard.ChopBoxConnector REF 27   
        de.renew.gui.ArcConnection "no_attributes" 3 255 496 238 513 258 533 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 27  
            CH.ifa.draw.figures.ChopEllipseConnector REF 31   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 274 507 "o" "Helvetica" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 248 507 "n" "Helvetica" 0 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 286 542 "\"?\"" "Helvetica" 0 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator 29 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 400 389 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 434 388 ":show(6,n)" "Helvetica" 0 12 0 REF 49 
            CH.ifa.draw.standard.OffsetLocator 50 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 402 438 20 20 NULL  
        de.renew.gui.ArcConnection "no_attributes" 3 419 442 438 423 420 405 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 53  
            CH.ifa.draw.standard.ChopBoxConnector REF 49   
        de.renew.gui.ArcConnection "no_attributes" 3 403 405 386 422 406 442 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 49  
            CH.ifa.draw.figures.ChopEllipseConnector REF 53   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 423 416 "o" "Helvetica" 0 12 0 REF 54 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 397 416 "n" "Helvetica" 0 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator 4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 425 441 "\"?\"" "Helvetica" 0 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 401 483 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 435 482 ":show(7,n)" "Helvetica" 0 12 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator 50 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 403 532 20 20 NULL  
        de.renew.gui.ArcConnection "no_attributes" 3 420 536 439 517 421 499 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 75  
            CH.ifa.draw.standard.ChopBoxConnector REF 71   
        de.renew.gui.ArcConnection "no_attributes" 3 404 499 387 516 407 536 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 71  
            CH.ifa.draw.figures.ChopEllipseConnector REF 75   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 424 510 "o" "Helvetica" 0 12 0 REF 76 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 398 510 "n" "Helvetica" 0 12 0 REF 80 
            CH.ifa.draw.standard.OffsetLocator 4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 426 535 "\"?\"" "Helvetica" 0 12 0 REF 75 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 250 582 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 282 590 ":show(5,n)" "Helvetica" 0 12 0 REF 93 
            CH.ifa.draw.standard.OffsetLocator 48 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 252 631 20 20 NULL  
        de.renew.gui.ArcConnection "no_attributes" 3 269 635 288 616 270 598 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 97  
            CH.ifa.draw.standard.ChopBoxConnector REF 93   
        de.renew.gui.ArcConnection "no_attributes" 3 253 598 236 615 256 635 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 93  
            CH.ifa.draw.figures.ChopEllipseConnector REF 97   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 273 609 "o" "Helvetica" 0 12 0 REF 98 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 247 609 "n" "Helvetica" 0 12 0 REF 102 
            CH.ifa.draw.standard.OffsetLocator 4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 275 634 "\"?\"" "Helvetica" 0 12 0 REF 97 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 400 583 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 434 582 ":show(8,n)" "Helvetica" 0 12 0 REF 115 
            CH.ifa.draw.standard.OffsetLocator 50 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 402 632 20 20 NULL  
        de.renew.gui.ArcConnection "no_attributes" 3 419 636 438 617 420 599 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 119  
            CH.ifa.draw.standard.ChopBoxConnector REF 115   
        de.renew.gui.ArcConnection "no_attributes" 3 403 599 386 616 406 636 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 115  
            CH.ifa.draw.figures.ChopEllipseConnector REF 119   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 423 610 "o" "Helvetica" 0 12 0 REF 120 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 397 610 "n" "Helvetica" 0 12 0 REF 124 
            CH.ifa.draw.standard.OffsetLocator 4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 425 635 "\"?\"" "Helvetica" 0 12 0 REF 119 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 98 484 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 131 483 ":show(1,n)" "Helvetica" 0 12 0 REF 137 
            CH.ifa.draw.standard.OffsetLocator 49 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 100 533 20 20 NULL  
        de.renew.gui.ArcConnection "no_attributes" 3 117 537 136 518 118 500 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 141  
            CH.ifa.draw.standard.ChopBoxConnector REF 137   
        de.renew.gui.ArcConnection "no_attributes" 3 101 500 84 517 104 537 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 137  
            CH.ifa.draw.figures.ChopEllipseConnector REF 141   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 120 511 "o" "Helvetica" 0 12 0 REF 142 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 94 511 "n" "Helvetica" 0 12 0 REF 146 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 122 536 "\"?\"" "Helvetica" 0 12 0 REF 141 
            CH.ifa.draw.standard.OffsetLocator 19 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 99 581 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 132 580 ":show(2,n)" "Helvetica" 0 12 0 REF 159 
            CH.ifa.draw.standard.OffsetLocator 49 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 101 630 20 20 NULL  
        de.renew.gui.ArcConnection "no_attributes" 3 118 634 137 615 119 597 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 163  
            CH.ifa.draw.standard.ChopBoxConnector REF 159   
        de.renew.gui.ArcConnection "no_attributes" 3 102 597 85 614 105 634 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 159  
            CH.ifa.draw.figures.ChopEllipseConnector REF 163   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 121 608 "o" "Helvetica" 0 12 0 REF 164 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 95 608 "n" "Helvetica" 0 12 0 REF 168 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 123 633 "\"?\"" "Helvetica" 0 12 0 REF 163 
            CH.ifa.draw.standard.OffsetLocator 19 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 95 389 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 128 388 ":show(0,n)" "Helvetica" 0 12 0 REF 181 
            CH.ifa.draw.standard.OffsetLocator 49 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 97 438 20 20 NULL  
        de.renew.gui.ArcConnection "no_attributes" 3 114 442 133 423 115 405 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 185  
            CH.ifa.draw.standard.ChopBoxConnector REF 181   
        de.renew.gui.ArcConnection "no_attributes" 3 98 405 81 422 101 442 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 181  
            CH.ifa.draw.figures.ChopEllipseConnector REF 185   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 117 416 "o" "Helvetica" 0 12 0 REF 186 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 91 416 "n" "Helvetica" 0 12 0 REF 190 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 119 441 "\"?\"" "Helvetica" 0 12 0 REF 185 
            CH.ifa.draw.standard.OffsetLocator 19 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 65 316 20 20 NULL REF 185  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 132 316 20 20 NULL REF 141  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 196 316 20 20 NULL REF 163  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 263 316 20 20 NULL REF 9  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 326 316 20 20 NULL REF 31  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 391 316 20 20 NULL REF 97  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 453 316 20 20 NULL REF 53  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 517 316 20 20 NULL REF 75  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 577 316 20 20 NULL REF 119  
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 2 578 326 537 326 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 211  
            CH.ifa.draw.figures.ChopEllipseConnector REF 210   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 2 85 326 133 326 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 203  
            CH.ifa.draw.figures.ChopEllipseConnector REF 204   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 2 152 326 197 326 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 204  
            CH.ifa.draw.figures.ChopEllipseConnector REF 205   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 2 216 326 264 326 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 205  
            CH.ifa.draw.figures.ChopEllipseConnector REF 206   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 2 283 326 327 326 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 206  
            CH.ifa.draw.figures.ChopEllipseConnector REF 207   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 2 346 326 392 326 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 207  
            CH.ifa.draw.figures.ChopEllipseConnector REF 208   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 2 411 326 454 326 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 208  
            CH.ifa.draw.figures.ChopEllipseConnector REF 209   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 2 518 326 473 326 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 210  
            CH.ifa.draw.figures.ChopEllipseConnector REF 209   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 596 298 "8" "Helvetica" 1 12 0 REF 211 
            CH.ifa.draw.standard.OffsetLocator 12 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 538 298 "7" "Helvetica" 1 12 0 REF 210 
            CH.ifa.draw.standard.OffsetLocator 14 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 472 298 "6" "Helvetica" 1 12 0 REF 209 
            CH.ifa.draw.standard.OffsetLocator 12 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 409 298 "5" "Helvetica" 1 12 0 REF 208 
            CH.ifa.draw.standard.OffsetLocator 11 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 348 298 "4" "Helvetica" 1 12 0 REF 207 
            CH.ifa.draw.standard.OffsetLocator 15 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 284 298 "3" "Helvetica" 1 12 0 REF 206 
            CH.ifa.draw.standard.OffsetLocator 14 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 216 298 "2" "Helvetica" 1 12 0 REF 205 
            CH.ifa.draw.standard.OffsetLocator 13 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 151 298 "1" "Helvetica" 1 12 0 REF 204 
            CH.ifa.draw.standard.OffsetLocator 12 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 86 298 "0" "Helvetica" 1 12 0 REF 203 
            CH.ifa.draw.standard.OffsetLocator 14 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 130 193 20 20 NULL  
        de.renew.gui.ArcConnection "no_attributes" 2 149 206 297 256 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 279  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 297 253 24 16 NULL    REF 284 
        de.renew.gui.ArcConnection "no_attributes" 2 321 256 466 206 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL 
            CH.ifa.draw.standard.ChopBoxConnector REF 284  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 464 193 20 20 NULL    REF 289 
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 296 138 24 16 NULL  
        de.renew.gui.ArcConnection "no_attributes" 2 296 150 149 201 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL 
            CH.ifa.draw.standard.ChopBoxConnector REF 290  
            CH.ifa.draw.figures.ChopEllipseConnector REF 279   
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 207 193 20 20 NULL  
        de.renew.gui.ArcConnection "no_attributes" 2 225 208 297 253 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 295  
            CH.ifa.draw.standard.ChopBoxConnector REF 284   
        de.renew.gui.ArcConnection "no_attributes" 2 227 203 353 203 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 295  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 353 195 24 16 NULL    REF 304 
        de.renew.gui.ArcConnection "no_attributes" 2 377 203 465 203 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 304  
            CH.ifa.draw.figures.ChopEllipseConnector REF 289   
        de.renew.gui.ArcConnection "no_attributes" 2 466 201 320 150 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 289  
            CH.ifa.draw.standard.ChopBoxConnector REF 290   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 202 232 "[x,z]" "Helvetica" 0 12 0 REF 280 
            CH.ifa.draw.standard.OffsetLocator -11 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DoubleArcConnection "no_attributes" 2 296 153 225 199 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 290  
            CH.ifa.draw.figures.ChopEllipseConnector REF 295   
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 298 82 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 2 139 102 139 138 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 129 82 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 128 138 24 16 NULL    REF 327 
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 2 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 2 140 154 140 194 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 327  
            CH.ifa.draw.figures.ChopEllipseConnector REF 279   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 217 153 "[x,y]" "Helvetica" 0 12 0 REF 291 
            CH.ifa.draw.standard.OffsetLocator 5 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 325 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 136 85 "[]" "Helvetica" 0 12 0 REF 325 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 192 192 192 2 299 95 152 142 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 321  
            CH.ifa.draw.standard.ChopBoxConnector REF 327   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 43 168 "t.pairs(t.nodes())" "Helvetica" 0 12 0 REF 328 
            CH.ifa.draw.standard.OffsetLocator -53 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 192 192 192 2 308 102 308 138 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 321  
            CH.ifa.draw.standard.ChopBoxConnector REF 290   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 317 112 "t" "Helvetica" 0 12 0 REF 344 
            CH.ifa.draw.standard.OffsetLocator 10 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 229 117 "t" "Helvetica" 0 12 0 REF 338 
            CH.ifa.draw.standard.OffsetLocator 5 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 263 175 "t.prod(t.neighbors(x),y)" "Helvetica" 0 12 0 REF 317 
            CH.ifa.draw.standard.OffsetLocator 64 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 405 204 "[x,y]" "Helvetica" 0 12 0 REF 305 
            CH.ifa.draw.standard.OffsetLocator -6 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 412 225 "[x,y]" "Helvetica" 0 12 0 REF 285 
            CH.ifa.draw.standard.OffsetLocator 29 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 185 36 "new UnionTopology(\n  x=new LineTopology(9),\n  new InverseTopology(x))" "Helvetica" 0 12 0 REF 321 
            CH.ifa.draw.standard.OffsetLocator -53 -34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 386 155 "[x,y]" "Helvetica" 0 12 0 REF 310 
            CH.ifa.draw.standard.OffsetLocator 3 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 80 193 "pending" "Helvetica" 1 12 0 REF 279 
            CH.ifa.draw.standard.OffsetLocator -38 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 354 99 "import samples.reisig.*;" "Helvetica" 0 12 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 329 131 "this:show(x,y)" "Helvetica" 0 12 0 REF 290 
            CH.ifa.draw.standard.OffsetLocator 58 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 333 212 "guard z<=y" "Helvetica" 0 12 0 REF 304 
            CH.ifa.draw.standard.OffsetLocator -2 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 288 204 "[x,z]" "Helvetica" 0 12 0 REF 300 
            CH.ifa.draw.standard.OffsetLocator 8 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 282 270 "guard z>y" "Helvetica" 0 12 0 REF 284 
            CH.ifa.draw.standard.OffsetLocator 0 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 274 222 "[x,z]" "Helvetica" 0 12 0 REF 296 
            CH.ifa.draw.standard.OffsetLocator 23 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  -27 143 661 712 