
    CH.ifa.draw.cpn.CPNDrawing 25 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 126 99 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 163 98 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 38 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "attributes" "attributes" 2 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 0 0 0 142 175 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 139 115 151 176 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 208 175 24 16  
        CH.ifa.draw.cpn.PlaceFigure "attributes" "attributes" 2 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 0 0 0 212 240 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 220 191 222 241 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector REF 11   
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 285 241 24 16  
        CH.ifa.draw.cpn.PlaceFigure "attributes" "attributes" 2 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 0 0 0 290 302 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 297 257 300 303 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 17   
        CH.ifa.draw.cpn.ArcConnection 2 232 250 285 249 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector REF 16   
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 359 310 24 16  
        CH.ifa.draw.cpn.PlaceFigure "attributes" "attributes" 2 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 0 0 0 363 375 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 371 326 373 376 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 26  
            CH.ifa.draw.figures.ChopEllipseConnector REF 27   
        CH.ifa.draw.cpn.ArcConnection 2 310 313 359 316 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 17  
            CH.ifa.draw.standard.ChopBoxConnector REF 26   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 158 136 "1" "Helvetica" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 16 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 3 161 181 180 168 208 178 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 10   
        CH.ifa.draw.cpn.ArcConnection 2 208 183 162 185 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 195 151 "i" "Helvetica" 0 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 12 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 174 190 "i+1" "Helvetica" 0 12 0 REF 43 
            CH.ifa.draw.standard.OffsetLocator -3 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 231 206 "i" "Helvetica" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 11 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 258 233 "i" "Helvetica" 0 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator 1 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 303 271 "i" "Helvetica" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 6 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 332 297 "i" "Helvetica" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator -1 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 382 339 "i" "Helvetica" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 11 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
