
    CH.ifa.draw.cpn.CPNDrawing 11 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 263 144 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 294 142 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 32 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 265 261 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 275 160 275 262 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 284 171 "<[robot\n  CARRYING:[waste]]\n [robot\n  LOCATION:[a]]\n>" "Helvetica" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 66 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 263 322 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 265 393 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 275 281 275 322 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 13   
        CH.ifa.draw.cpn.ArcConnection 2 275 338 275 394 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 13  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 287 293 "fs" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 16 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 282 355 "fs@HEAD == (fs@TAIL)@HEAD" "Helvetica" 0 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator 94 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
