2 
    de.renew.gui.CPNDrawing 49 
        de.renew.gui.PlaceFigure "no_attributes" 97 114 20 20  
        de.renew.gui.PlaceFigure "no_attributes" 159 114 20 20  
        de.renew.gui.TransitionFigure "no_attributes" 158 175 24 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 114 131 161 175 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 169 134 169 175 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 121 145 "x" "Helvetica" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -13 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "no_attributes" 219 115 20 20  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 223 132 178 175 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 15  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 175 145 "y" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 9 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 210 145 "x+y" "Helvetica" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 19 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "no_attributes" 97 232 20 20  
        de.renew.gui.PlaceFigure "no_attributes" 219 233 20 20  
        de.renew.gui.PlaceFigure "no_attributes" 159 232 20 20  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 161 191 114 236 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 26   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 169 191 169 233 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 177 191 223 237 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 27   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 96 206 "2*x-y" "Helvetica" 0 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator -26 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 172 206 "x+y" "Helvetica" 0 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator 12 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 209 206 "x+y" "Helvetica" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator 18 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "no_attributes" 348 116 20 20  
        de.renew.gui.PlaceFigure "no_attributes" 410 116 20 20  
        de.renew.gui.TransitionFigure "no_attributes" 409 177 24 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 365 133 412 177 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 50  
            CH.ifa.draw.standard.ChopBoxConnector REF 52   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 420 136 420 177 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 51  
            CH.ifa.draw.standard.ChopBoxConnector REF 52   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 372 146 "x" "Helvetica" 0 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator -13 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "no_attributes" 470 117 20 20  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 474 134 429 177 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 64  
            CH.ifa.draw.standard.ChopBoxConnector REF 52   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 426 146 "y" "Helvetica" 0 12 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator 9 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 467 146 "z" "Helvetica" 0 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator 19 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "no_attributes" 348 234 20 20  
        de.renew.gui.PlaceFigure "no_attributes" 470 235 20 20  
        de.renew.gui.PlaceFigure "no_attributes" 410 234 20 20  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 412 193 365 238 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 52  
            CH.ifa.draw.figures.ChopEllipseConnector REF 75   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 420 193 420 235 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 52  
            CH.ifa.draw.figures.ChopEllipseConnector REF 77   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 428 193 474 239 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 52  
            CH.ifa.draw.figures.ChopEllipseConnector REF 76   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 347 207 "2*x-y" "Helvetica" 0 12 0 REF 78 
            CH.ifa.draw.standard.OffsetLocator -26 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 429 207 "z" "Helvetica" 0 12 0 REF 82 
            CH.ifa.draw.standard.OffsetLocator 12 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 464 206 "z" "Helvetica" 0 12 0 REF 86 
            CH.ifa.draw.standard.OffsetLocator 16 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 439 176 "z=x+y" "Helvetica" 0 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator 34 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 101 94 "22" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 1 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 165 95 "2" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -1 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 223 95 "24" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 1 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 240 102 "25" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 18 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 177 104 "10" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 15 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 352 97 "22" "Helvetica" 0 12 0 REF 50 
            CH.ifa.draw.standard.OffsetLocator 1 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 413 96 "2" "Helvetica" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator -4 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 473 98 "24" "Helvetica" 0 12 0 REF 64 
            CH.ifa.draw.standard.OffsetLocator 0 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 424 105 "10" "Helvetica" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 11 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 491 107 "25" "Helvetica" 0 12 0 REF 64 
            CH.ifa.draw.standard.OffsetLocator 18 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  