2 
    de.renew.gui.CPNDrawing 59 
        de.renew.gui.TransitionFigure "no_attributes" 200 100 24 16  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 231 98 ":notify(E)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 44 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 112 219 147 201 223 20 20  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 152 223 "Events" "Helvetica" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -36 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 211 116 211 224 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 217 145 "[EventIntention\n event: (E)\n intent: <>]" "Helvetica" 0 10 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 41 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "no_attributes" 200 329 24 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 211 243 211 329 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 16   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 193 269 "T" "Helvetica" 0 10 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator -15 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 112 219 147 344 326 20 20  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 224 336 345 336 NULL NULL 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 112 219 147 100 326 20 20  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 120 336 200 336 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector REF 16   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 157 317 "P" "Helvetica" 0 10 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 0 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 298 318 "kb" "Helvetica" 0 10 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 19 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 369 328 "KB" "Helvetica" 1 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 24 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 93 351 "Plans" "Helvetica" 1 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 2 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "no_attributes" 99 214 24 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 110 230 110 327 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 44  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 117 254 "P" "Helvetica" 0 10 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator 10 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 77 195 ":addPlan(P)" "Helvetica" 0 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator 1 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "no_attributes" 443 523 24 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 450 523 359 345 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 55  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 475 521 ":new(kb,perf)" "Helvetica" 0 12 0 REF 55 
            CH.ifa.draw.standard.OffsetLocator 58 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 446 493 "kb" "Helvetica" 0 10 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator 47 65 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 112 219 147 201 440 20 20  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 211 345 211 441 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 66   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 225 343 "guard T >= P@trigger" "Helvetica" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 77 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 227 361 "TP = P+[Plan trigger:(T)]" "Helvetica" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 86 32 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 330 377 "KB:belief(TPC,A)" "Helvetica" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 168 48 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 139 425 "Intentions" "Helvetica" 1 12 0 REF 66 
            CH.ifa.draw.standard.OffsetLocator -39 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "no_attributes" 200 522 24 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 211 460 211 522 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 66  
            CH.ifa.draw.standard.ChopBoxConnector REF 83   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 3 215 522 232 488 216 459 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 83  
            CH.ifa.draw.figures.ChopEllipseConnector REF 66   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 159 483 "Intentions" "Helvetica" 0 10 0 REF 84 
            CH.ifa.draw.standard.OffsetLocator -29 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 238 481 "Intentions@tl" "Helvetica" 0 10 0 REF 88 
            CH.ifa.draw.standard.OffsetLocator 46 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "no_attributes" 98 442 24 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 202 450 122 450 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 66  
            CH.ifa.draw.standard.ChopBoxConnector REF 98   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 140 451 "<>" "Helvetica" 0 10 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator -16 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 164 544 "perf:perform(Intentions@hd)" "Helvetica" 0 12 0 REF 83 
            CH.ifa.draw.standard.OffsetLocator 34 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "no_attributes" 426 443 24 16  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 221 450 426 450 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 66  
            CH.ifa.draw.standard.ChopBoxConnector REF 109   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 296 453 "Intentions" "Helvetica" 0 10 0 REF 110 
            CH.ifa.draw.standard.OffsetLocator -4 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 3 437 443 437 153 220 231 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 109  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 458 333 "[intent:#3(Intentions) \n list: #3<#1 | #2 >\n ei: [EventIntention\n      event:#1[Event]\n      intent:#2]\n]@ei" "Helvetica" 0 10 0 REF 117 
            CH.ifa.draw.standard.OffsetLocator 180 74 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 375 463 "generateInternalEvent" "Helvetica" 1 12 0 REF 109 
            CH.ifa.draw.standard.OffsetLocator 13 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 100 521 "performAction" "Helvetica" 1 12 0 REF 83 
            CH.ifa.draw.standard.OffsetLocator -64 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 217 310 "applyPlan" "Helvetica" 1 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 40 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 66 391 "System.out.println(\"FOUND CONTEXT \"+A.toString())" "Helvetica" 2 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 10 62 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "TraceMode" "Boolean" "FALSE" "FillColor" "Color" 112 219 147 316 520 20 20  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 291 505 "Performer" "Helvetica" 1 12 0 REF 136 
            CH.ifa.draw.standard.OffsetLocator -1 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 224 530 317 530 NULL NULL 
            CH.ifa.draw.standard.ChopBoxConnector REF 83  
            CH.ifa.draw.figures.ChopEllipseConnector REF 136   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FrameColor" "Color" 0 0 0 2 443 530 336 530 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 55  
            CH.ifa.draw.figures.ChopEllipseConnector REF 136   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 394 511 "perf" "Helvetica" 0 12 0 REF 143 
            CH.ifa.draw.standard.OffsetLocator 16 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 251 512 "perf" "Helvetica" 0 12 0 REF 140 
            CH.ifa.draw.standard.OffsetLocator -8 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 69 376 "KB=[wait:(TPC) it:(kb)]@it.getJavaObject()" "Helvetica" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator -20 47 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 224 248 "System.out.println(\"TRYING CONTEXT \"+TPC.toString())" "Helvetica" 2 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 178 -81 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 79 362 "TPC = TP@context" "Helvetica" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator -76 33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 239 409 "(TP+[context:(A)])@intent" "Helvetica" 0 10 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator 89 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  
