
    CH.ifa.draw.cpn.CPNDrawing 9 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 127 171 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 128 105 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 138 125 138 171 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 128 238 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 138 187 138 239 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 152 106 "new NetListener()" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 62 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 150 138 "x" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 15 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 162 174 "action x.actionPerformed(new ActionEvent(\"a\",0,\"b\"))" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 165 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 148 204 "x" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 13 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   