11 
    de.renew.gui.CPNDrawing 25 
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7708 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -45 -88 245 102 0  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 1 "FigureWithID" "Int" 7732 14 
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7712 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 68 -8 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7724 2 107 -16 149 -2 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7722 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 40 -38 78 27 NULL   
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 7711 "FillColor" "Color" 192 192 192 255 149 -5 24 16 NULL    REF 1 REF 8 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7717 2 14 2 69 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7710 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 -10 -6 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 3   
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7713 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 255 214 -8 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7716 2 11 -6 70 -55 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 12  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7709 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 67 -71 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7720 2 173 2 215 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 8  
                CH.ifa.draw.figures.ChopEllipseConnector REF 14   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7719 2 88 2 149 2 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 3  
                CH.ifa.draw.standard.ChopBoxConnector REF 8   REF 6 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7723 2 14 -3 53 -16 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 12  
                CH.ifa.draw.figures.ChopEllipseConnector REF 6   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7718 2 85 -55 150 -5 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 19  
                CH.ifa.draw.standard.ChopBoxConnector REF 8   REF 12 REF 19  REF 3 REF 8 REF 14 REF 6 REF 12 REF 19 REF 4 REF 9 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7730 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 120 -42 "id" "SansSerif" 0 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator 8 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7726 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 30 -17 "s" "SansSerif" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7725 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 125 -16 "s" "SansSerif" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7729 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 59 -32 "$descr" "SansSerif" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 15 REF 20 REF 24 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7714 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 -14 -5 ">" "SansSerif" 1 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 28 REF 31 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7715 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 228 -6 ">" "SansSerif" 1 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7731 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 23 -40 "id" "SansSerif" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -12 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7721 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 28 -118 "$comment" "SansSerif" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -2 -70 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7727 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 130 25 ":dcExchange(\ns, bool, id)" "SansSerif" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 7 37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7728 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -69 23 ":dcNewExchange(\ns, o, id)" "SansSerif" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator -20 36 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  109 22 655 434 