11 
    de.renew.gui.CPNDrawing 2 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6988 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 "FontName" "String" "Arial" -1 -1 97 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6989 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 25 5 "execute" "Arial" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  530 276 830 600 