8 
    de.renew.gui.CPNDrawing 36 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 13 "FillColor" "Color" 255 255 255 3 301 195 344 195 344 175 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0  "de.renew.gui.fs.IsaArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 202 186 "CallExpression" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 252 69 "«interface»\nExpression\n\n+ isInvertible(): boolean\n+ startEvaluation(...): Object\n+ registerCalculation(...): Object\n+ getType(): Class" "SansSerif" 0 12 0 NULL NULL   0
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 14 "FillColor" "Color" 255 255 255 3 319 302 344 302 344 175 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0  "de.renew.gui.fs.IsaArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 186 293 "InvertibleExpression" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  0  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 15 "FillColor" "Color" 255 255 255 3 381 195 344 195 344 175 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0  "de.renew.gui.fs.IsaArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 386 186 "AggregateExpression" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  0  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 16 "FillColor" "Color" 255 255 255 3 469 229 452 229 452 204 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0  "de.renew.gui.fs.IsaArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 474 220 "ListExpression" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 15  0  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 17 "FillColor" "Color" 255 255 255 4 464 261 452 261 452 233 452 204 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0  "de.renew.gui.fs.IsaArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 10 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 469 252 "TupleExpression" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 15  0  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 18 "FillColor" "Color" 255 255 255 3 387 302 344 302 344 175 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0  "de.renew.gui.fs.IsaArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 11 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 392 293 "VariableExpression" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  0  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 19 "FillColor" "Color" 255 255 255 3 311 371 344 371 344 175 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0  "de.renew.gui.fs.IsaArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 6 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 193 362 "EqualsExpression" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  0  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 20 "FillColor" "Color" 255 255 255 3 392 371 344 371 344 175 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0  "de.renew.gui.fs.IsaArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 397 363 "NoArgExpression" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  0  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 21 2 249 204 250 222 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1  "de.renew.gui.fs.AssocArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 177 222 "«interface»\nFunction\n\n+ function(Object): Object" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 22 2 250 293 250 277 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1  "de.renew.gui.fs.AssocArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.standard.ChopBoxConnector REF 46   
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 24 "FillColor" "Color" 255 255 255 3 385 335 344 335 344 175 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0  "de.renew.gui.fs.IsaArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 23 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 390 317 "ConstantExpression\n\n- constant: Object" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  0  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 25 2 511 372 550 372 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1  "de.renew.gui.fs.AssocArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector REF 40  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 555 345 "«interface»\nNoArgFunction\n\n+ function(): Object" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 26 3 452 186 452 116 442 116 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1  "de.renew.gui.fs.AssocArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector REF 15  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 27 5 188 370 128 370 128 44 343 44 343 69 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1  "de.renew.gui.fs.AssocArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector REF 35  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 29 2 518 302 542 302 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1  "de.renew.gui.fs.AssocArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector REF 30  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 12 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 547 275 "LocalVariable\n\n+ name: String\n+ isVisible: boolean" "SansSerif" 0 12 0 NULL NULL    REF 20
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 31 4 197 193 156 193 156 120 247 120 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1  "de.renew.gui.fs.AssocArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 32 4 181 302 156 302 156 120 247 120 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1  "de.renew.gui.fs.AssocArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 33 4 190 335 156 335 156 120 247 120 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1  "de.renew.gui.fs.AssocArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 30 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 195 328 "GuardExpression" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6   REF 10 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 28 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 256 272 "2" "SansSerif" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 14 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 85 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 34 "FillColor" "Color" 255 255 255 3 308 335 344 335 344 175 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0  "de.renew.gui.fs.IsaArrowTip"
            CH.ifa.draw.standard.ChopBoxConnector REF 85  
            CH.ifa.draw.standard.ChopBoxConnector REF 6  0  REF 35 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 35 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 346 38 "2" "SansSerif" 0 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator 114 -161 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 25 REF 4 REF 60 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 36 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 463 113 "*" "SansSerif" 0 12 0 REF 61 
            CH.ifa.draw.standard.OffsetLocator 18 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 46 REF 30 REF 73 REF 40 REF 54 REF 15 REF 6 NULL  0 153 826 649 