
    CH.ifa.draw.cpn.CPNDrawing 94 
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 1 "FillColor" "Color" 192 192 192 130 180 80 104  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 72 199 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 158 201 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 92 209 158 209 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 70 123 24 16  
        CH.ifa.draw.cpn.ArcConnection 3 86 139 101 162 86 201 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 8  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 72 101 ":new()" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 3 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 104 113 "t: new Task" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 52 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 103 128 "t: new()" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 37 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 106 154 "t" "Helvetica" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 15 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 122 193 "t" "Helvetica" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -2 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 140 184 "t:recording()" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 3 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 255 199 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 182 209 256 209 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 31   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 223 194 "t" "Helvetica" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 5 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 157 249 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 91 214 157 250 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 39   
        CH.ifa.draw.cpn.ArcConnection 2 181 251 257 213 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 39  
            CH.ifa.draw.figures.ChopEllipseConnector REF 31   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 116 235 "t" "Helvetica" 0 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator -7 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 222 235 "t" "Helvetica" 0 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator 4 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 157 231 "t:ex()" "Helvetica" 0 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 1 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 308 201 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 275 209 308 209 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 31  
            CH.ifa.draw.standard.ChopBoxConnector REF 57   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 289 192 "t" "Helvetica" 0 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator -1 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 293 173 "t:printing()" "Helvetica" 0 12 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator 0 -29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 148 216 "official1" "Helvetica" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 0 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 147 265 "official1" "Helvetica" 1 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 0 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 302 225 "printer" "Helvetica" 1 12 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator 1 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 368 162 20 20  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 373 238 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 332 201 371 177 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 57  
            CH.ifa.draw.figures.ChopEllipseConnector REF 77   
        CH.ifa.draw.cpn.ArcConnection 2 332 216 375 244 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 57  
            CH.ifa.draw.figures.ChopEllipseConnector REF 78   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 358 186 "t" "Helvetica" 0 12 0 REF 79 
            CH.ifa.draw.standard.OffsetLocator 8 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 361 220 "t" "Helvetica" 0 12 0 REF 83 
            CH.ifa.draw.standard.OffsetLocator 9 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 419 164 24 16  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 422 240 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 478 162 20 20  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 479 237 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 530 201 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 388 172 419 172 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 77  
            CH.ifa.draw.standard.ChopBoxConnector REF 93   
        CH.ifa.draw.cpn.ArcConnection 2 443 172 479 172 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 93  
            CH.ifa.draw.figures.ChopEllipseConnector REF 95   
        CH.ifa.draw.cpn.ArcConnection 2 393 248 422 248 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 78  
            CH.ifa.draw.standard.ChopBoxConnector REF 94   
        CH.ifa.draw.cpn.ArcConnection 2 446 247 480 247 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 94  
            CH.ifa.draw.figures.ChopEllipseConnector REF 96   
        CH.ifa.draw.cpn.ArcConnection 2 496 178 530 201 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 95  
            CH.ifa.draw.standard.ChopBoxConnector REF 97   
        CH.ifa.draw.cpn.ArcConnection 2 497 242 530 217 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 96  
            CH.ifa.draw.standard.ChopBoxConnector REF 97   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 395 158 "t" "Helvetica" 0 12 0 REF 98 
            CH.ifa.draw.standard.OffsetLocator -7 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 463 158 "t" "Helvetica" 0 12 0 REF 102 
            CH.ifa.draw.standard.OffsetLocator 3 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 405 231 "t" "Helvetica" 0 12 0 REF 106 
            CH.ifa.draw.standard.OffsetLocator -1 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 462 231 "t" "Helvetica" 0 12 0 REF 110 
            CH.ifa.draw.standard.OffsetLocator 0 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 508 186 "t" "Helvetica" 0 12 0 REF 114 
            CH.ifa.draw.standard.OffsetLocator -4 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 507 218 "t" "Helvetica" 0 12 0 REF 118 
            CH.ifa.draw.standard.OffsetLocator -5 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 403 146 "t:verifying()" "Helvetica" 0 12 0 REF 93 
            CH.ifa.draw.standard.OffsetLocator 2 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 404 183 "secretary" "Helvetica" 1 12 0 REF 93 
            CH.ifa.draw.standard.OffsetLocator 1 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 410 223 "t:compl()" "Helvetica" 0 12 0 REF 94 
            CH.ifa.draw.standard.OffsetLocator -1 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 413 256 "official2" "Helvetica" 1 12 0 REF 94 
            CH.ifa.draw.standard.OffsetLocator 1 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 524 224 "put_together" "Helvetica" 1 12 0 REF 97 
            CH.ifa.draw.standard.OffsetLocator 18 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 546 181 "t:join1()" "Helvetica" 0 12 0 REF 97 
            CH.ifa.draw.standard.OffsetLocator 24 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 4 542 201 542 119 185 119 90 203 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 97  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 253 292 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 265 219 265 292 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 31  
            CH.ifa.draw.standard.ChopBoxConnector REF 162   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 270 244 "t" "Helvetica" 0 12 0 REF 163 
            CH.ifa.draw.standard.OffsetLocator 6 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 280 283 "t:decide(x)" "Helvetica" 0 12 0 REF 162 
            CH.ifa.draw.standard.OffsetLocator 43 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 281 297 "prosecutor" "Helvetica" 1 12 0 REF 162 
            CH.ifa.draw.standard.OffsetLocator 47 5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 255 350 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 265 308 265 351 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 162  
            CH.ifa.draw.figures.ChopEllipseConnector REF 176   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 269 321 "t" "Helvetica" 0 12 0 REF 177 
            CH.ifa.draw.standard.OffsetLocator 5 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 1 "FillColor" "Color" 192 192 192 147 399 107 80  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 169 432 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 150 408 "t:summ()" "Helvetica" 0 12 0 REF 185 
            CH.ifa.draw.standard.OffsetLocator -8 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 210 433 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 204 409 "t:charg()" "Helvetica" 0 12 0 REF 189 
            CH.ifa.draw.standard.OffsetLocator 4 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 164 460 "tribunal" "Helvetica" 1 12 0 REF 189 
            CH.ifa.draw.standard.OffsetLocator -37 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 164 460 "tribunal" "Helvetica" 1 12 0 REF 185 
            CH.ifa.draw.standard.OffsetLocator 4 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.ArcConnection 2 259 367 189 432 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 176  
            CH.ifa.draw.standard.ChopBoxConnector REF 185   
        CH.ifa.draw.cpn.ArcConnection 2 261 369 226 433 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 176  
            CH.ifa.draw.standard.ChopBoxConnector REF 189   
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 259 519 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 188 448 263 523 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 185  
            CH.ifa.draw.figures.ChopEllipseConnector REF 207   
        CH.ifa.draw.cpn.ArcConnection 2 226 449 265 521 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 189  
            CH.ifa.draw.figures.ChopEllipseConnector REF 207   
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 305 431 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 270 368 311 431 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 176  
            CH.ifa.draw.standard.ChopBoxConnector REF 216   
        CH.ifa.draw.cpn.ArcConnection 2 312 447 274 521 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 216  
            CH.ifa.draw.figures.ChopEllipseConnector REF 207   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 254 382 "t" "Helvetica" 0 12 0 REF 203 
            CH.ifa.draw.standard.OffsetLocator 12 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 224 380 "t" "Helvetica" 0 12 0 REF 199 
            CH.ifa.draw.standard.OffsetLocator 1 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 291 386 "t" "Helvetica" 0 12 0 REF 217 
            CH.ifa.draw.standard.OffsetLocator 2 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 251 480 "t" "Helvetica" 0 12 0 REF 212 
            CH.ifa.draw.standard.OffsetLocator 7 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 215 485 "t" "Helvetica" 0 12 0 REF 208 
            CH.ifa.draw.standard.OffsetLocator -9 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 298 480 "t" "Helvetica" 0 12 0 REF 221 
            CH.ifa.draw.standard.OffsetLocator 6 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 334 425 "t:susp()" "Helvetica" 0 12 0 REF 216 
            CH.ifa.draw.standard.OffsetLocator 37 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 334 440 "official3" "Helvetica" 1 12 0 REF 216 
            CH.ifa.draw.standard.OffsetLocator 39 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "TRUE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 547 151 "t" "Helvetica" 0 12 0 REF 158 
            CH.ifa.draw.standard.OffsetLocator 232 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 117 102 "t1:new Task" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 68 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 186 99 "t1:new()" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 125 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 82 139 82 200 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 8  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 74 159 "t1" "Helvetica" 0 12 0 REF 258 
            CH.ifa.draw.standard.OffsetLocator -3 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
