
    CH.ifa.draw.cpn.CPNDrawing 75 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 355 166 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 387 127 "init" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 28 -39 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.PlaceFigure "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 283 442 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 355 176 206 204 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                CH.ifa.draw.cpn.PlaceFigure "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 186 195 20 20    
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 337 165 "b" "Helvetica" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 60 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 388 161 "b: new Bucket" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 59 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 389 178 "b: new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 40 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 184 117 24 16  
        CH.ifa.draw.cpn.ArcConnection 3 195 196 185 162 193 133 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 10  
            CH.ifa.draw.standard.ChopBoxConnector REF 20   
        CH.ifa.draw.cpn.PlaceFigure "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 283 598 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 196 133 196 196 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 20  
            CH.ifa.draw.figures.ChopEllipseConnector REF 10   
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 341 517 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 157 141 "bOld" "Helvetica" 0 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator -20 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 201 141 "bNew" "Helvetica" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 21 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 82 118 ":exch(bOld,bNew)" "Helvetica" 0 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator -65 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 370 549 "this:exch(bf,be)" "Helvetica" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 58 31 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 312 667 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 344 683 ":approachFire()" "Helvetica" 0 12 0 REF 43 
            CH.ifa.draw.standard.OffsetLocator 62 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 314 390 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 344 390 ":retreat()" "Helvetica" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 41 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 242 227 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 274 241 "b:fill()" "Helvetica" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 35 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 271 227 ":fillBucket()" "Helvetica" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 47 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 470 520 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 189 211 137 248 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 10  
            CH.ifa.draw.standard.ChopBoxConnector 
                CH.ifa.draw.cpn.TransitionFigure "no_attributes" 115 248 24 16    
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 130 220 "b" "Helvetica" 0 12 0 REF 59 
            CH.ifa.draw.standard.OffsetLocator -30 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 499 520 ":extinguish()" "Helvetica" 0 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator 50 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 489 535 "this:emptyBucket()" "Helvetica" 0 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator 57 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 343 599 20 20  
        CH.ifa.draw.cpn.PlaceFigure "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 342 445 20 20  REF 10 
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 139 196 "Bucket" "Helvetica" 1 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator -37 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.ArcConnection 2 364 182 296 443 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        CH.ifa.draw.cpn.ArcConnection 2 205 210 242 228 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 10  
            CH.ifa.draw.standard.ChopBoxConnector REF 51   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 209 222 "b" "Helvetica" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator -11 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 281 518 24 15  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 369 515 ":exchange(bf,be)" "Helvetica" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 62 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 62 
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 99 283 ":emptyBucket()" "Helvetica" 0 12 0 REF 62 
            CH.ifa.draw.standard.OffsetLocator 12 34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 100 298 "b:empty()" "Helvetica" 0 12 0 REF 62 
            CH.ifa.draw.standard.OffsetLocator -2 49 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 148 516 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 182 517 ":exchange(be,bf)" "Helvetica" 0 12 0 REF 87 
            CH.ifa.draw.standard.OffsetLocator -65 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 193 546 "this:exch(be,bf)" "Helvetica" 0 12 0 REF 87 
            CH.ifa.draw.standard.OffsetLocator -59 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 98 516 ":refill()" "Helvetica" 0 12 0 REF 97 
            CH.ifa.draw.standard.OffsetLocator -45 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 77 535 "this:fillBucket()" "Helvetica" 0 12 0 REF 97 
            CH.ifa.draw.standard.OffsetLocator -44 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 191 432 "WaitingForWater" "Helvetica" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -55 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 173 614 "WantsToApprochFire" "Helvetica" 1 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator -60 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 356 614 "WaitingToGetRidOfWater" "Helvetica" 1 12 0 REF 72 
            CH.ifa.draw.standard.OffsetLocator 85 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 364 433 "WantsToRetreat" "Helvetica" 1 12 0 REF 73 
            CH.ifa.draw.standard.OffsetLocator 58 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 73 81 "FUNCTIONAL MODEL" "Helvetica" 3 12 0 NULL NULL 0  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 75 326 "DYNAMIC MODEL" "Helvetica" 3 12 0 NULL NULL 0  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 224 531 "bf:isFull()" "Helvetica" 0 12 0 REF 87 
            CH.ifa.draw.standard.OffsetLocator -42 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 370 531 "be:isEmpty()" "Helvetica" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 51 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 321 406 298 444 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 47  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        CH.ifa.draw.cpn.ArcConnection 2 293 462 293 518 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 87   
        CH.ifa.draw.cpn.ArcConnection 2 285 457 172 517 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 97   
        CH.ifa.draw.cpn.ArcConnection 2 172 531 286 604 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 97  
            CH.ifa.draw.figures.ChopEllipseConnector REF 25   
        CH.ifa.draw.cpn.ArcConnection 2 293 533 293 599 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 87  
            CH.ifa.draw.figures.ChopEllipseConnector REF 25   
        CH.ifa.draw.cpn.ArcConnection 2 297 617 320 667 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector REF 43   
        CH.ifa.draw.cpn.ArcConnection 2 327 667 350 618 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 43  
            CH.ifa.draw.figures.ChopEllipseConnector REF 72   
        CH.ifa.draw.cpn.ArcConnection 2 353 600 353 533 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 72  
            CH.ifa.draw.standard.ChopBoxConnector REF 30   
        CH.ifa.draw.cpn.ArcConnection 2 361 605 470 535 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 72  
            CH.ifa.draw.standard.ChopBoxConnector REF 58   
        CH.ifa.draw.cpn.ArcConnection 2 352 517 352 465 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 30  
            CH.ifa.draw.figures.ChopEllipseConnector REF 73   
        CH.ifa.draw.cpn.ArcConnection 2 470 521 361 460 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 58  
            CH.ifa.draw.figures.ChopEllipseConnector REF 73   
        CH.ifa.draw.cpn.ArcConnection 2 349 447 329 406 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 73  
            CH.ifa.draw.standard.ChopBoxConnector REF 47   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 386 145 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 33 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 155 101 "exch" "Helvetica" 1 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator -27 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 343 663 "approachFire" "Helvetica" 1 12 0 REF 43 
            CH.ifa.draw.standard.OffsetLocator 57 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 345 374 "retreat" "Helvetica" 1 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 38 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 272 210 "fillBucket" "Helvetica" 1 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 45 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 497 504 "extinguish" "Helvetica" 1 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator 44 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 360 498 "exchange2" "Helvetica" 1 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 38 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 97 266 "emptyBucket" "Helvetica" 1 12 0 REF 62 
            CH.ifa.draw.standard.OffsetLocator 8 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 222 498 "exchange1" "Helvetica" 1 12 0 REF 87 
            CH.ifa.draw.standard.OffsetLocator -40 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 117 494 "refill" "Helvetica" 1 12 0 REF 97 
            CH.ifa.draw.standard.OffsetLocator -31 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2   
