
    CH.ifa.draw.cpn.CPNDrawing 50 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 211 112 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 208 90 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -1 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 121 109 20 20  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 307 109 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 211 119 141 119 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        CH.ifa.draw.cpn.ArcConnection 2 235 119 308 119 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 6   
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 120 207 24 16  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 305 203 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 131 129 131 207 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 15   
        CH.ifa.draw.cpn.ArcConnection 2 317 129 317 203 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 16   
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 122 308 20 20  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 306 308 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 132 223 132 309 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 15  
            CH.ifa.draw.figures.ChopEllipseConnector REF 25   
        CH.ifa.draw.cpn.ArcConnection 2 316 219 316 309 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 26   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 139 256 "f" "Helvetica" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 8 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 327 249 "b" "Helvetica" 0 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator 14 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 151 205 "f=new java.awt.Frame()" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 84 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 346 204 "b=new java.awt.Button(\"Jaba-daba-doo\")" "Helvetica" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 148 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 305 390 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 219 303 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 139 223 223 307 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 15  
            CH.ifa.draw.figures.ChopEllipseConnector REF 48   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 189 248 "f" "Helvetica" 0 12 0 REF 49 
            CH.ifa.draw.standard.OffsetLocator 9 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 236 320 308 390 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 48  
            CH.ifa.draw.standard.ChopBoxConnector REF 47   
        CH.ifa.draw.cpn.ArcConnection 2 316 328 316 390 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector REF 47   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 262 360 "f" "Helvetica" 0 12 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator -9 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 341 339 "b" "Helvetica" 0 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator 28 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 306 479 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 316 406 316 480 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 47  
            CH.ifa.draw.figures.ChopEllipseConnector REF 70   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 376 391 "f.add(b)" "Helvetica" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 80 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 121 392 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 122 479 20 20  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 340 436 "f" "Helvetica" 0 12 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator 25 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 132 328 132 392 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector REF 78   
        CH.ifa.draw.cpn.ArcConnection 2 132 408 132 480 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 78  
            CH.ifa.draw.figures.ChopEllipseConnector REF 79   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 138 350 "f" "Helvetica" 0 12 0 REF 83 
            CH.ifa.draw.standard.OffsetLocator 7 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 137 436 "f" "Helvetica" 0 12 0 REF 87 
            CH.ifa.draw.standard.OffsetLocator 6 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 166 394 "f.setSize(500,500)" "Helvetica" 0 12 0 REF 78 
            CH.ifa.draw.standard.OffsetLocator 83 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 209 482 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 142 489 209 489 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 79  
            CH.ifa.draw.standard.ChopBoxConnector REF 100   
        CH.ifa.draw.cpn.ArcConnection 2 307 489 233 489 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 70  
            CH.ifa.draw.standard.ChopBoxConnector REF 100   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 172 470 "f" "Helvetica" 0 12 0 REF 101 
            CH.ifa.draw.standard.OffsetLocator -2 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 275 467 "fr" "Helvetica" 0 12 0 REF 105 
            CH.ifa.draw.standard.OffsetLocator 8 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 211 556 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 221 498 221 557 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 100  
            CH.ifa.draw.figures.ChopEllipseConnector REF 115   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 206 456 "f.show()" "Helvetica" 0 12 0 REF 100 
            CH.ifa.draw.standard.OffsetLocator 6 -27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 228 510 "f" "Helvetica" 0 12 0 REF 116 
            CH.ifa.draw.standard.OffsetLocator 8 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 209 643 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 221 576 221 643 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 115  
            CH.ifa.draw.standard.ChopBoxConnector REF 126   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 231 597 "f" "Helvetica" 0 12 0 REF 127 
            CH.ifa.draw.standard.OffsetLocator 11 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 190 663 "f.dispose()" "Helvetica" 0 12 0 REF 126 
            CH.ifa.draw.standard.OffsetLocator -3 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
