
    CH.ifa.draw.cpn.CPNDrawing 24 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 276 171 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 318 195 "a=[A: #1(x) B:#1]" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 75 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 313 162 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 38 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 281 285 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 288 187 291 286 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 300 233 "a" "Helvetica" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 14 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 309 177 "x: new FSsyntax" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 65 5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 230 90 "location" "Helvetica" 0 12 1 NULL NULL 0  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 281 344 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 291 305 292 344 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 20   
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 284 408 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 293 360 294 409 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 20  
            CH.ifa.draw.figures.ChopEllipseConnector REF 25   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 302 376 "net" "Helvetica" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 17 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 302 316 "fs" "Helvetica" 0 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator 15 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 315 343 "net = fs.at(\"A\").getAtom()" "Helvetica" 0 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 88 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 289 472 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 295 428 300 472 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector REF 39   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 306 439 "net" "Helvetica" 0 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 17 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 325 472 "net:test()" "Helvetica" 0 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 47 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 549 132 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 510 129 ":test()" "Helvetica" 0 12 0 REF 50 
            CH.ifa.draw.standard.OffsetLocator -36 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 551 195 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 561 148 561 196 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 50  
            CH.ifa.draw.figures.ChopEllipseConnector REF 54   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 522 195 "Test" "Helvetica" 1 12 0 REF 54 
            CH.ifa.draw.standard.OffsetLocator -27 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2   
