
    CH.ifa.draw.cpn.CPNDrawing 48 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 117 311 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 153 315 "f1 = f2.parseSource(\"plan.fs\")" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 103 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 119 412 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 129 327 129 413 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 135 368 "f3" "Helvetica" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 11 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 153 330 "f2 = fs.parse(\"[IN: #1 OUT: #1]\")" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 108 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 117 475 24 16  
        CH.ifa.draw.cpn.ArcConnection 3 136 429 157 451 136 475 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 16   
        CH.ifa.draw.cpn.ArcConnection 2 129 432 129 475 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 16   
        CH.ifa.draw.cpn.ArcConnection 3 129 491 129 510 129 532 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector 
                CH.ifa.draw.cpn.PlaceFigure "no_attributes" 119 531 20 20    
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 146 414 "FSpool" "Helvetica" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 36 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 117 446 "f1" "Helvetica" 0 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator -7 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 166 444 "f2" "Helvetica" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 26 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 147 477 "f3 = f1.unify(f2)" "Helvetica" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 58 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 29 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 117 588 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 129 551 129 588 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 29  
            CH.ifa.draw.standard.ChopBoxConnector REF 42   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 147 588 "f2 = f.at(\"OUT\")" "Helvetica" 0 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator 58 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 119 644 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 129 604 129 645 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 42  
            CH.ifa.draw.figures.ChopEllipseConnector REF 50   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 133 501 "f3" "Helvetica" 0 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 9 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 153 558 "f" "Helvetica" 0 12 0 REF 43 
            CH.ifa.draw.standard.OffsetLocator 10 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 136 615 "f2" "Helvetica" 0 12 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 12 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 276 79 " event " "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 341 82 " action " "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 395 82 " belief " "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 454 79 " object " "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 208 80 " plan " "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 103 81 " eventIntention " "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 222 119 " newBelief " "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 267 144 " newGoal " "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 367 150 " location " "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 362 127 " pick " "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 323 131 " drop " "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 420 149 " robot " "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 462 152 " bin " "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 494 146 " waste " "Helvetica" 0 12 1 NULL NULL 0  
        fs.IsaConnection 2 508 146 477 94 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 77  
            CH.ifa.draw.standard.ChopBoxConnector REF 67   
        fs.IsaConnection 2 473 152 473 94 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 76  
            CH.ifa.draw.standard.ChopBoxConnector REF 67   
        fs.IsaConnection 2 440 149 469 94 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 75  
            CH.ifa.draw.standard.ChopBoxConnector REF 67   
        fs.IsaConnection 2 393 150 410 97 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 72  
            CH.ifa.draw.standard.ChopBoxConnector REF 66   
        fs.IsaConnection 2 373 127 363 97 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 73  
            CH.ifa.draw.standard.ChopBoxConnector REF 65   
        fs.IsaConnection 2 341 131 357 97 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 74  
            CH.ifa.draw.standard.ChopBoxConnector REF 65   
        fs.IsaConnection 2 294 144 294 94 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 71  
            CH.ifa.draw.standard.ChopBoxConnector REF 64   
        fs.IsaConnection 2 259 119 286 94 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 70  
            CH.ifa.draw.standard.ChopBoxConnector REF 64   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 153 348 "f3 = f1.unify(f2)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 64 36 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 153 297 "fs = new fs.FS()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 65 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 153 277 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 37 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
