
    CH.ifa.draw.cpn.CPNDrawing 58 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 118 321 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 151 266 "plan = fs.parseSource(\"plan.fs\")" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 106 -56 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 119 412 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 129 337 129 413 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 101 367 "plan" "Helvetica" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator -16 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 147 281 "e1 = fs.parse(\"[newBelief BELIEF: [location OBJECT: [waste] LOCATION: [a]]]\")" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 228 -41 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 240 467 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 138 426 240 469 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 16   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 79 413 "Plans" "Helvetica" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -34 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 166 454 "plan" "Helvetica" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator -11 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 276 487 "can = plan.canUnify(b)" "Helvetica" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 85 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 251 483 249 582 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector 
                CH.ifa.draw.cpn.PlaceFigure "no_attributes" 239 581 20 20    
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 210 530 "intent" "Helvetica" 0 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator -25 5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 276 79 "event" "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 341 82 "action" "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 395 82 "belief" "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 454 79 "object" "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 208 80 "plan" "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 103 81 "eventIntention" "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 222 119 "newBelief" "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 267 144 "newGoal" "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 367 150 "location" "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 362 127 "pick" "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 323 131 "drop" "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 424 149 "robot" "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 468 152 "bin" "Helvetica" 0 12 1 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 500 146 "waste" "Helvetica" 0 12 1 NULL NULL 0  
        fs.IsaConnection 2 516 146 481 94 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 50  
            CH.ifa.draw.standard.ChopBoxConnector REF 40   
        fs.IsaConnection 2 481 152 477 94 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 49  
            CH.ifa.draw.standard.ChopBoxConnector REF 40   
        fs.IsaConnection 2 447 149 473 94 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 48  
            CH.ifa.draw.standard.ChopBoxConnector REF 40   
        fs.IsaConnection 2 396 150 413 97 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 45  
            CH.ifa.draw.standard.ChopBoxConnector REF 39   
        fs.IsaConnection 2 376 127 366 97 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 46  
            CH.ifa.draw.standard.ChopBoxConnector REF 38   
        fs.IsaConnection 2 344 131 360 97 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 47  
            CH.ifa.draw.standard.ChopBoxConnector REF 38   
        fs.IsaConnection 2 297 144 297 94 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 44  
            CH.ifa.draw.standard.ChopBoxConnector REF 37   
        fs.IsaConnection 2 262 119 289 94 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 43  
            CH.ifa.draw.standard.ChopBoxConnector REF 37   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 149 250 "fs = new fs.FS()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 60 -72 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 149 230 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 32 -92 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 152 299 "b1 = fs.parse(\"[location OBJECT: [robot] LOCATION: [a]]\")" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 176 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 156 316 "b2 = fs.parse(\"[location OBJECT: [bin] LOCATION: [a]]\")" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 174 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 548 80 "a" "Helvetica" 0 12 1 NULL NULL 0  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 382 428 20 20  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 408 430 "Beliefs" "Helvetica" 1 12 0 REF 96 
            CH.ifa.draw.standard.OffsetLocator 36 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.ArcConnection 3 142 331 356 367 388 430 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 96   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 257 354 "b1" "Helvetica" 0 12 0 REF 100 
            CH.ifa.draw.standard.OffsetLocator -1 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 3 138 337 184 380 252 398 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                CH.ifa.draw.cpn.PlaceFigure "no_attributes" 251 390 20 20    
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 187 364 "e1" "Helvetica" 0 12 0 REF 107 
            CH.ifa.draw.standard.OffsetLocator -1 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 3 142 329 393 339 392 429 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 96   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 315 341 "b2" "Helvetica" 0 12 0 REF 115 
            CH.ifa.draw.standard.OffsetLocator 55 -31 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 3 383 439 333 444 264 470 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 96  
            CH.ifa.draw.standard.ChopBoxConnector REF 16   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 310 430 "b1" "Helvetica" 0 12 0 REF 122 
            CH.ifa.draw.standard.OffsetLocator -6 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 277 526 "action b1=plan.unify(b)" "Helvetica" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 87 58 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 277 506 "guard can" "Helvetica" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 52 38 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 33 REF 111 
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 281 391 "Events" "Helvetica" 1 12 0 REF 111 
            CH.ifa.draw.standard.OffsetLocator 40 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.ArcConnection 2 261 410 252 467 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 111  
            CH.ifa.draw.standard.ChopBoxConnector REF 16   
        CH.ifa.draw.cpn.ArcConnection 2 383 441 264 471 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 96  
            CH.ifa.draw.standard.ChopBoxConnector REF 16   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 333 454 "b2" "Helvetica" 0 12 0 REF 142 
            CH.ifa.draw.standard.OffsetLocator 17 5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
