
    CH.ifa.draw.cpn.CPNDrawing 3 
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 193 121 ":function(arg,arg+1)" "Helvetica" 0 12 0 
            CH.ifa.draw.cpn.TransitionFigure "no_attributes" 159 120 24 16  
            CH.ifa.draw.standard.OffsetLocator 75 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 374 126 "func" "Helvetica" 1 12 0 NULL NULL 2  REF 2  
