6 
    de.renew.gui.CPNDrawing 2 
        de.renew.gui.DeclarationFigure "attributes" "attributes" 3 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 "FigureWithID" "Int" 1 246 38 "import de.uni_hamburg.fs.*;" "Helvetica" 0 12 0 NULL NULL 1  
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FillColor" "Color" 255 255 255 "FrameColor" "Color" 0 0 0 "FigureWithID" "Int" 2 325 96 "A\nx: FSNode" "Helvetica" 0 12 0 NULL NULL  NULL  0 97 884 600
