11 
    de.renew.gui.CPNDrawing 10 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 280 "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FillColor" "Color" 255 255 255 255 107 117 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 282 2 131 125 186 125 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 283 "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FillColor" "Color" 255 255 255 255 185 115 20 20 NULL    REF 6 
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "FigureWithID" "Int" 285 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 7 6 "import de.renew.net.NetInstance;\nNetInstance ma, dealer, buyer;" "SansSerif" 0 12 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 288 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 109 99 "init" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 297 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 136 103 "ma;\ndealer;\nbuyer;" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 299 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 44 53 "ma: new manufacturer;\ndealer: new dealer(ma);\nbuyer: new buyer(dealer);" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 -50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 300 "FrameColor" "Color" 0 0 0 255 "MarkingAppearance" "Int" 2 "FillColor" "Color" 255 255 255 255 33 115 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 302 2 53 125 107 125 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 17  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 303 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 39 118 "[]" "SansSerif" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  315 394 628 600 