
    CH.ifa.draw.cpn.CPNDrawing 14 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 183 110 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 185 217 20 20  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 185 406 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 183 316 24 16  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 183 517 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 195 126 195 218 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.ArcConnection 2 195 237 195 316 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 4   
        CH.ifa.draw.cpn.ArcConnection 2 195 332 195 407 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 4  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        CH.ifa.draw.cpn.ArcConnection 2 195 426 195 517 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector REF 5   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 215 109 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 34 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 201 361 "x" "Helvetica" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 201 458 "x" "Helvetica" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 9 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 217 316 "action x=new Display(\"Titel\")" "Helvetica" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 103 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 217 516 "action x.meldeFehler(\"Yepp.\")" "Helvetica" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 106 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
