
    CH.ifa.draw.cpn.CPNDrawing 14 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 101 105 24 16  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 102 250 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 103 176 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 113 121 113 177 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        CH.ifa.draw.cpn.ArcConnection 2 113 196 113 250 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 103 314 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 101 386 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 113 266 113 315 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector REF 12   
        CH.ifa.draw.cpn.ArcConnection 2 113 334 113 386 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 12  
            CH.ifa.draw.standard.ChopBoxConnector REF 13   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 138 107 ":actionPerformed(null,x)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 90 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 123 140 "x" "Helvetica" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 13 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 123 210 "x" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 13 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 131 251 "action System.out.println(x)" "Helvetica" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 90 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 134 388 ":result(null)" "Helvetica" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 51 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
