
    CH.ifa.draw.cpn.CPNDrawing 19 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 143 121 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 145 207 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 155 137 155 208 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 174 121 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 33 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 171 161 "[1,[2,[3,[4,[5,[6,[]]]]]]]" "Helvetica" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 70 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 176 207 "list" "Helvetica" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 30 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 144 293 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 155 227 155 293 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 16   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 173 250 "list" "Helvetica" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 26 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 200 295 "this:dissect(list)" "Helvetica" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 87 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 432 125 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 433 207 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 432 295 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 443 141 443 208 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 27  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 467 114 ":dissect([head,tail])" "Helvetica" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 76 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 460 166 "head" "Helvetica" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 31 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 462 209 "components" "Helvetica" 1 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 55 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 469 296 ":dissect([])" "Helvetica" 0 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 53 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 469 132 "this:dissect(tail)" "Helvetica" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 69 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
