11 
    de.renew.gui.CPNDrawing 49 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 492 125 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 436 122 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5 2 456 132 492 132 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 11 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 486 107 "ni:ch(y)" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 1 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 12 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 0 255 556 123 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13 2 557 133 516 133 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 10  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 22 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 245 43 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 23 2 255 63 254 122 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 14  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 24 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 242 122 24 16 NULL    REF 19 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 25 2 266 130 313 131 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 19  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 26 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 312 121 20 20 NULL    REF 24 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 27 2 332 131 368 131 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 24  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 28 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 368 124 24 16 NULL    REF 29 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 29 2 392 132 437 132 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 29  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 41 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 287 122 "y" "SansSerif" 0 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 45 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 348 123 "y" "SansSerif" 0 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 49 2 322 122 321 62 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 24  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 50 309 45 24 17 NULL    REF 44 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 51 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 247 17 "action Thread.sleep(1000);" "SansSerif" 0 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator 0 -28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52 2 309 53 265 53 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 44  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 54 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 412 124 "y" "SansSerif" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 55 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 472 124 "y" "SansSerif" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 56 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 144 261 "import de.renew.cloudnative.spring.resilientdistribute.adapter.ResDistPluginAdapter;" "SansSerif" 0 12 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 57 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 319 84 "y" "SansSerif" 0 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 58 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 281 30 "guard y == null;" "SansSerif" 0 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator 1 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 60 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 0 255 75 118 20 20 NULL REF 10  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 15 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 535 108 "ni" "SansSerif" 0 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 4 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 64 2 242 129 205 129 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 19  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 65 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 185 119 20 20 NULL    REF 73 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 66 2 186 129 154 129 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 73  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 67 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 130 121 24 16 NULL    REF 78 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 68 2 130 128 95 128 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 78  
            CH.ifa.draw.figures.ChopEllipseConnector REF 65   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 72 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 580 124 "Referenz auf \"consumer\"" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 82 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 73 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 107 120 "ni" "SansSerif" 0 12 0 REF 79 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 74 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 59 45 20 19 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 75 2 79 54 127 54 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 89  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 76 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 127 46 24 16 NULL    REF 94 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 77 2 151 53 246 53 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 94  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 80 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 38 68 "create local KafkaMessageConsumer" "SansSerif" 0 12 0 REF 94 
            CH.ifa.draw.standard.OffsetLocator 2 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 78 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 5 3 "action ResDistPluginAdapter.getNetInstance(\"consumer\");" "SansSerif" 0 12 0 REF 94 
            CH.ifa.draw.standard.OffsetLocator 25 -43 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 81 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 66 46 "[]" "SansSerif" 0 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 82 133 153 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 83 2 143 154 142 137 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 108  
            CH.ifa.draw.standard.ChopBoxConnector REF 78   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 84 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 140 155 "[]" "SansSerif" 0 12 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 39 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 168 164 "action y = ResDistPluginAdapter.getLastMessage(\"consumer\");" "SansSerif" 0 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator 87 42 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 46 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 348 86 " \nguard y != null;" "SansSerif" 0 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 7 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 3 142 "Referenz auf \"consumer\"" "SansSerif" 0 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator -14 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 70 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 6 198 "action ni = ResDistPluginAdapter.getLocalInstance(\"consumer\");" "SansSerif" 0 12 0 REF 78 
            CH.ifa.draw.standard.OffsetLocator 40 77 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 21 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 387 193 "Netz \"consumerAdapter\"" "SansSerif" 1 18 0 NULL NULL  NULL  