11 
    de.renew.gui.CPNDrawing 9 
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 6221 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 218 114 116 33  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6222 "FrameColor" "Color" 255 199 158 255 "LineStyle" "String" "1 2" "FillColor" "Color" 255 199 158 255 4 
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6223 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 "Visibility" "Boolean" "TRUE" 343 122 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 6226 2 261 132 344 132 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6224 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 "Visibility" "Boolean" "TRUE" 237 124 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 3   REF 7 REF 1  REF 3 REF 7 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 6225 "TextAlignment" "Int" 1 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" 357 124 ">" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 4 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextColor" "Color" 255 0 0 255 "FigureWithID" "Int" 6227 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 233 125 ">" "SansSerif" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextColor" "Color" 0 0 255 255 "FigureWithID" "Int" 6229 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 216 163 "[Execute mapcalc]" "SansSerif" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 21 44 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6305 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 215 145 "r.mapcalc" "SansSerif" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 0 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  228 308 584 600 