
    CH.ifa.draw.cpn.CPNDrawing 6 
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 248 188 20 20  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 254 190 "A" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 246 108 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 278 109 ":new()" "Helvetica" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 33 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.ArcConnection 2 258 124 258 189 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 5  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 146 142 "[robot LOCATION:[a] CARRYING:[waste]].without(\"LOCATION\")" "Helvetica" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 58 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
