11 
    de.renew.gui.CPNDrawing 23 
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 4 "Location" "Boolean" "FALSE" "FigureWithID" "Int" 6960 "FontName" "String" "Arial" "FillColor" "Color" 204 204 204 255 20 62 787 501 8 8  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 6961 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "TextType" "Int" 0 "FillColor" "Color" 255 255 255 255 228 147 205 85 NULL  
        de.renew.gui.fs.UMLNoteFigure "attributes" "attributes" 3 "FigureWithID" "Int" 6970 "FrameColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 161 128 "initial task:\ntaskName" "Arial" 0 16 0 REF 2
            CH.ifa.draw.standard.OffsetLocator -116 -37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6988 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 282 275 97 27 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7042 3 310 230 298 251 318 275 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 6989 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 307 281 "execute" "Arial" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7085 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 269 170 "dwf_submitPaper\n[providePaperBody]" "Arial" 1 13 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 2 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 4 "Location" "Boolean" "FALSE" "FigureWithID" "Int" 7086 "FontName" "String" "Arial" "FillColor" "Color" 204 204 204 255 39 438 410 328 8 8  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7087 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 255 255 255 "TextType" "Int" 0 "FillColor" "Color" 64 64 64 255 59 568 "position;\nname=pos2;" "Arial" 0 18 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator -136 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 7092 "FrameColor" "Color" 0 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 255 255 255 "FontName" "String" "Arial" 568 160 205 85 NULL  
        de.renew.gui.fs.UMLNoteFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7093 "FrameColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 501 141 "initial task:\ntaskName" "Arial" 0 16 0 REF 21
            CH.ifa.draw.standard.OffsetLocator -116 -37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6973 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 628 194 "DWF[rollName]" "SansSerif" 1 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7094 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 "FontName" "String" "Arial" 614 282 97 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7095 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 640 288 "execute" "Arial" 1 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7096 2 667 244 663 282 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 21  
            CH.ifa.draw.standard.ChopBoxConnector REF 28   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7097 3 359 229 381 259 354 275 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 7098 "FrameColor" "Color" 0 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 255 255 255 "FontName" "String" "Arial" 239 466 205 85 NULL  
        de.renew.gui.fs.UMLNoteFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7099 "FrameColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 172 447 "initial task:\ntaskName" "Arial" 0 16 0 REF 40
            CH.ifa.draw.standard.OffsetLocator -116 -37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7100 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 285 492 "dwf_submitPaper\n[providePaperBody]" "SansSerif" 1 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7101 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 "FontName" "String" "Arial" 289 599 97 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7102 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 315 605 "execute" "Arial" 1 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 7103 2 340 550 338 599 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 40  
            CH.ifa.draw.standard.ChopBoxConnector REF 47   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7041 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 255 255 255 "TextType" "Int" 0 "FillColor" "Color" 64 64 64 255 35 367 "position;\nname=pos1;" "Arial" 0 18 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -329 77 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    NULL  950 171 578 600 