5 
    de.renew.gui.CPNDrawing 142 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 11 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" 2 234 94 401 94 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 195 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 214 84 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FigureWithID" "Int" 12 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 401 86 24 16 NULL    REF 6 
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 18 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 215 365 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 25 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 402 178 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 27 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" 2 403 188 237 188 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FigureWithID" "Int" 28 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 213 180 24 16 NULL    REF 13 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 29 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" 3 226 196 238 276 226 366 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 13  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 32 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" 3 224 366 209 279 223 196 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector REF 13   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 35 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" 2 406 195 327 274 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FigureWithID" "Int" 36 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 308 274 24 16 NULL    REF 26 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 37 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" 2 232 369 311 290 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector REF 26   
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FigureWithID" "Int" 46 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 400 367 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 48 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" 2 412 198 412 367 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 32   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 26 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 427 177 "candidate" "Helvetica" 1 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 43 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 50 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" 2 235 375 400 375 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector REF 32   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FigureWithID" "Int" 56 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" 2 424 375 509 375 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 32  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 57 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 0 0 508 365 20 20 NULL    REF 49 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 67 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 453 359 "myid" "Helvetica" 0 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator 0 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 20 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 192 387 "highest" "Helvetica" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -12 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 58 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 487 387 "terminated\nas leader" "Helvetica" 1 12 0 REF 49 
            CH.ifa.draw.standard.OffsetLocator 0 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 74 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 266 482 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 75 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 299 481 ":show(3,n)" "Helvetica" 0 12 0 REF 59 
            CH.ifa.draw.standard.OffsetLocator 49 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 76 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 268 531 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 77 3 285 535 304 516 286 498 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 63  
            CH.ifa.draw.standard.ChopBoxConnector REF 59   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4 3 269 498 252 515 272 535 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 59  
            CH.ifa.draw.figures.ChopEllipseConnector REF 63   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 288 509 "o" "Helvetica" 0 12 0 REF 64 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 78 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 262 509 "n" "Helvetica" 0 12 0 REF 68 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 290 534 "\"?\"" "Helvetica" 0 12 0 REF 63 
            CH.ifa.draw.standard.OffsetLocator 19 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 79 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 265 575 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 80 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 298 574 ":show(4,n)" "Helvetica" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 49 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 81 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 267 624 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 82 3 284 628 303 609 285 591 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 85  
            CH.ifa.draw.standard.ChopBoxConnector REF 81   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 83 3 268 591 251 608 271 628 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 81  
            CH.ifa.draw.figures.ChopEllipseConnector REF 85   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 84 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 287 602 "o" "Helvetica" 0 12 0 REF 86 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 85 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 261 602 "n" "Helvetica" 0 12 0 REF 90 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 86 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 299 637 "\"?\"" "Helvetica" 0 12 0 REF 85 
            CH.ifa.draw.standard.OffsetLocator 29 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 87 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 413 484 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 88 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 447 483 ":show(6,n)" "Helvetica" 0 12 0 REF 103 
            CH.ifa.draw.standard.OffsetLocator 50 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 89 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 415 533 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 90 3 432 537 451 518 433 500 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 107  
            CH.ifa.draw.standard.ChopBoxConnector REF 103   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 91 3 416 500 399 517 419 537 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 103  
            CH.ifa.draw.figures.ChopEllipseConnector REF 107   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 92 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 436 511 "o" "Helvetica" 0 12 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 93 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 410 511 "n" "Helvetica" 0 12 0 REF 112 
            CH.ifa.draw.standard.OffsetLocator 4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 94 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 438 536 "\"?\"" "Helvetica" 0 12 0 REF 107 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 95 "FillColor" "Color" 235 199 158 414 578 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 96 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 448 577 ":show(7,n)" "Helvetica" 0 12 0 REF 125 
            CH.ifa.draw.standard.OffsetLocator 50 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 97 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 416 627 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 98 3 433 631 452 612 434 594 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 129  
            CH.ifa.draw.standard.ChopBoxConnector REF 125   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 99 3 417 594 400 611 420 631 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 125  
            CH.ifa.draw.figures.ChopEllipseConnector REF 129   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 100 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 437 605 "o" "Helvetica" 0 12 0 REF 130 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 101 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 411 605 "n" "Helvetica" 0 12 0 REF 134 
            CH.ifa.draw.standard.OffsetLocator 4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 102 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 439 630 "\"?\"" "Helvetica" 0 12 0 REF 129 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 103 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 263 677 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 104 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 295 685 ":show(5,n)" "Helvetica" 0 12 0 REF 147 
            CH.ifa.draw.standard.OffsetLocator 48 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 105 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 265 726 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 106 3 282 730 301 711 283 693 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 151  
            CH.ifa.draw.standard.ChopBoxConnector REF 147   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 107 3 266 693 249 710 269 730 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 147  
            CH.ifa.draw.figures.ChopEllipseConnector REF 151   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 108 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 286 704 "o" "Helvetica" 0 12 0 REF 152 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 109 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 260 704 "n" "Helvetica" 0 12 0 REF 156 
            CH.ifa.draw.standard.OffsetLocator 4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 110 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 288 729 "\"?\"" "Helvetica" 0 12 0 REF 151 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 111 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 111 481 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 41 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 145 480 ":show(0,n)" "Helvetica" 0 12 0 REF 169 
            CH.ifa.draw.standard.OffsetLocator 50 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 42 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 113 530 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 43 3 130 534 149 515 131 497 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 173  
            CH.ifa.draw.standard.ChopBoxConnector REF 169   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 44 3 114 497 96 514 117 534 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 169  
            CH.ifa.draw.figures.ChopEllipseConnector REF 173   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 45 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 134 508 "o" "Helvetica" 0 12 0 REF 174 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 112 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 108 508 "n" "Helvetica" 0 12 0 REF 178 
            CH.ifa.draw.standard.OffsetLocator 5 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 47 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 136 533 "\"?\"" "Helvetica" 0 12 0 REF 173 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 113 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 111 579 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 114 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 144 578 ":show(1,n)" "Helvetica" 0 12 0 REF 191 
            CH.ifa.draw.standard.OffsetLocator 49 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 115 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 113 628 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 116 3 130 632 149 613 131 595 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 195  
            CH.ifa.draw.standard.ChopBoxConnector REF 191   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52 3 114 595 97 612 117 632 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 191  
            CH.ifa.draw.figures.ChopEllipseConnector REF 195   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 53 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 133 606 "o" "Helvetica" 0 12 0 REF 196 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 117 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 107 606 "n" "Helvetica" 0 12 0 REF 200 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 55 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 135 631 "\"?\"" "Helvetica" 0 12 0 REF 195 
            CH.ifa.draw.standard.OffsetLocator 19 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 118 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 112 676 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 119 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 145 675 ":show(2,n)" "Helvetica" 0 12 0 REF 213 
            CH.ifa.draw.standard.OffsetLocator 49 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 120 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 114 725 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 59 3 131 729 150 710 132 692 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 217  
            CH.ifa.draw.standard.ChopBoxConnector REF 213   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 60 3 115 692 98 709 118 729 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 213  
            CH.ifa.draw.figures.ChopEllipseConnector REF 217   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 61 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 134 703 "o" "Helvetica" 0 12 0 REF 218 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 62 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 108 703 "n" "Helvetica" 0 12 0 REF 222 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 136 728 "\"?\"" "Helvetica" 0 12 0 REF 217 
            CH.ifa.draw.standard.OffsetLocator 19 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 127 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 618 154 20 20 NULL REF 195  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 128 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 663 173 20 20 NULL REF 217  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 129 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 680 219 20 20 NULL REF 63  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 130 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 664 265 20 20 NULL REF 85  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 131 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 618 282 20 20 NULL REF 151  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 132 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 573 264 20 20 NULL REF 107  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 133 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 554 219 20 20 NULL REF 129  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 134 "MarkingAppearance" "Int" 2 "ArrowMode" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 235 199 158 574 175 20 20 NULL REF 173  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 144 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 623 135 "1" "Helvetica" 1 12 0 REF 235 
            CH.ifa.draw.standard.OffsetLocator -2 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 145 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 683 159 "2" "Helvetica" 1 12 0 REF 236 
            CH.ifa.draw.standard.OffsetLocator 13 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 146 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 706 220 "3" "Helvetica" 1 12 0 REF 237 
            CH.ifa.draw.standard.OffsetLocator 19 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 147 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 685 284 "4" "Helvetica" 1 12 0 REF 238 
            CH.ifa.draw.standard.OffsetLocator 14 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 148 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 624 305 "5" "Helvetica" 1 12 0 REF 239 
            CH.ifa.draw.standard.OffsetLocator -1 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 149 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 564 276 "6" "Helvetica" 1 12 0 REF 240 
            CH.ifa.draw.standard.OffsetLocator -16 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 150 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 567 164 "0" "Helvetica" 1 12 0 REF 242 
            CH.ifa.draw.standard.OffsetLocator -14 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 151 "ArrowMode" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 544 216 "7" "Helvetica" 1 12 0 REF 241 
            CH.ifa.draw.standard.OffsetLocator -17 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 152 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 55 81 20 20 NULL  
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 160 2 581 194 568 221 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 242  
            CH.ifa.draw.figures.ChopEllipseConnector REF 241   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 164 2 677 267 688 238 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 238  
            CH.ifa.draw.figures.ChopEllipseConnector REF 237   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 165 2 688 221 676 192 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 237  
            CH.ifa.draw.figures.ChopEllipseConnector REF 236   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 166 2 665 180 637 168 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 236  
            CH.ifa.draw.figures.ChopEllipseConnector REF 235   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 167 2 620 168 593 182 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 235  
            CH.ifa.draw.figures.ChopEllipseConnector REF 242   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 168 2 637 290 666 278 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 239  
            CH.ifa.draw.figures.ChopEllipseConnector REF 238   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 169 2 592 278 620 289 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 240  
            CH.ifa.draw.figures.ChopEllipseConnector REF 239   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 170 2 568 238 580 266 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 241  
            CH.ifa.draw.figures.ChopEllipseConnector REF 240   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 172 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 54 260 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 173 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 61 263 "[]" "Helvetica" 0 12 0 REF 300 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 174 "FrameColor" "Color" 192 192 192 2 64 261 64 192 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 300  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 175 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 53 176 24 16 NULL    REF 308 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 176 "FrameColor" "Color" 192 192 192 2 65 101 65 176 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 267  
            CH.ifa.draw.standard.ChopBoxConnector REF 308   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 180 "FrameColor" "Color" 192 192 192 2 509 93 425 93 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 200 "FrameColor" "Color" 192 192 192 "FillColor" "Color" 255 255 0 508 83 20 20 NULL REF 267   
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 181 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 470 76 "t" "Helvetica" 0 12 0 REF 312 
            CH.ifa.draw.standard.OffsetLocator 4 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 183 "FrameColor" "Color" 192 192 192 2 77 177 216 99 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 308  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 188 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 274 332 "[myid,oldid]" "Helvetica" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 34 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 192 2 412 102 412 179 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   REF 4 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 196 2 224 180 224 104 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 13  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 10 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 196 66 "must send" "Helvetica" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 2 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 314 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 191 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 345 255 "[myid,id]" "Helvetica" 0 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator 1 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 187 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 229 131 "[myid,id]" "Helvetica" 0 12 0 REF 330 
            CH.ifa.draw.standard.OffsetLocator 27 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 16 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 300 97 "[myid,id]" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 5 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 185 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 299 171 "[myid,id]" "Helvetica" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 1 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 177 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 56 126 "t" "Helvetica" 0 12 0 REF 309 
            CH.ifa.draw.standard.OffsetLocator -8 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 186 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 147 232 "[myid,oldid]" "Helvetica" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator -38 -42 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 184 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 242 287 "[myid,id]" "Helvetica" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 32 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 34 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 166 174 "guard\noldid<id" "Helvetica" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator -37 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 189 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 304 355 "[myid,myid]" "Helvetica" 0 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 17 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 201 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 425 265 "[myid,myid]" "Helvetica" 0 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator 43 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 40 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 326 292 "guard\noldid>id" "Helvetica" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 28 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 3 "FigureWithID" "Int" 171 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 585 53 "import samples.reisig.*;" "Helvetica" 0 12 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 158 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 56 36 "new InverseTopology(\n  new RingTopology(8))" "Helvetica" 0 12 0 REF 267 
            CH.ifa.draw.standard.OffsetLocator 55 -40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 179 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 98 94 "t.pairs(t.nodes())" "Helvetica" 0 12 0 REF 319 
            CH.ifa.draw.standard.OffsetLocator -4 -37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DoubleArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 203 "FrameColor" "Color" 192 192 192 2 71 192 220 368 NULL 
            de.renew.gui.DoubleArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 308  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 199 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 96 331 "t.pairs(t.nodes())" "Helvetica" 0 12 0 REF 377 
            CH.ifa.draw.standard.OffsetLocator -5 58 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 193 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 421 114 "t.prod(\n  t.neighbors(myid),\n  id)" "Helvetica" 0 12 0 REF 326 
            CH.ifa.draw.standard.OffsetLocator 61 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 194 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 239 200 "this:show(myid,id)" "Helvetica" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 63 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 204 "TextColor" "Color" 192 192 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 360 387 "this:show(myid,myid)" "Helvetica" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 5 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  -30 82 818 843 