
    CH.ifa.draw.cpn.CPNDrawing 9 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 162 155 24 16  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 191 156 ":new(pred)" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 46 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 163 225 20 20  
        CH.ifa.draw.cpn.ArcConnection 2 173 171 173 226 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 180 191 "pred" "Helvetica" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 19 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 162 299 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 173 245 173 299 NULL NULL 0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 13   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 182 260 "pred" "Helvetica" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 21 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FillColor" "Color" 255 199 158 "FrameColor" "Color" 255 199 158 190 300 ":pred(pred)" "Helvetica" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 46 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
