7 
    de.renew.gui.CPNDrawing 51 
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 167 "FillColor" "Color" 235 199 158 "Visibility" "Boolean" "TRUE" 444 62 132 199  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 2 "Visibility" "Boolean" "TRUE" 2 120 115 230 43 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 119 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 64 106 64 46 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 213 23 67 20 NULL    REF 7 
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 4 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 197 82 98 94 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 5 "Visibility" "Boolean" "TRUE" 2 246 43 246 83 NULL NULL 
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 11 "Visibility" "Boolean" "TRUE" 2 280 33 434 33 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 12 "MarkingAppearance" "Int" 1 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 433 23 20 20 NULL    REF 16 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 14 "Visibility" "Boolean" "TRUE" 2 120 144 231 216 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 15 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 200 216 93 20 NULL    REF 21 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 19 "Visibility" "Boolean" "TRUE" 2 293 226 435 226 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 21  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 20 "MarkingAppearance" "Int" 1 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 434 216 20 20 NULL    REF 26 
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 44 "MarkingAppearance" "Int" 1 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 433 119 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 45 "Visibility" "Boolean" "TRUE" 2 434 129 397 129 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 27  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 46 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 330 119 67 20 NULL    REF 32 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 47 "Visibility" "Boolean" "TRUE" 2 330 129 295 129 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 32  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 50 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 454 26 "[DeliveryNote]" "Helvetica" 0 12 0 REF 16
            CH.ifa.draw.standard.OffsetLocator 51 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0 0  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 102 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 493 152 67 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 103 "Visibility" "Boolean" "TRUE" 2 452 221 513 172 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector REF 40   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 104 "Visibility" "Boolean" "TRUE" 2 501 152 452 133 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 40  
            CH.ifa.draw.figures.ChopEllipseConnector REF 27   REF 5 
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 157 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 471 135 "#2" "Helvetica" 0 9 0 REF 45
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 42 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 458 216 "Requests" "Helvetica" 1 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 41 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 155 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 454 179 "[Request\n product: #2]" "Helvetica" 0 9 0 REF 41
            CH.ifa.draw.standard.OffsetLocator -2 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 2 "" "product"  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 51 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 461 116 "[Product]" "Helvetica" 0 12 0 REF 27
            CH.ifa.draw.standard.OffsetLocator 45 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0 0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 52 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 457 231 "[Request]" "Helvetica" 0 12 0 REF 26
            CH.ifa.draw.standard.OffsetLocator 41 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0 0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 48 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 336 122 "stock_up" "Helvetica" 1 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator -1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 38 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 334 215 "#1[Request\n from: (\"SCS\")]" "Helvetica" 0 9 0 REF 22
            CH.ifa.draw.standard.OffsetLocator -1 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 2 "" "from"  
        de.renew.gui.InhibitorConnection "attributes" "attributes" 2 "FigureWithID" "Int" 25 "Visibility" "Boolean" "TRUE" 2 246 216 246 176 
            de.renew.gui.CircleDecoration  
            de.renew.gui.CircleDecoration  
            CH.ifa.draw.standard.ChopBoxConnector REF 21  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 203 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 241 190 "#2" "Helvetica" 0 9 0 REF 70
            CH.ifa.draw.standard.OffsetLocator 0 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 54 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 141 126 "[Product]" "Helvetica" 0 12 0 REF 8
            CH.ifa.draw.standard.OffsetLocator -78 5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0 1 ""  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 163 112 "Stock" "Helvetica" 1 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator -67 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 160 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 455 9 "Delivery Notes" "Helvetica" 1 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 52 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 31 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 228 155 "[CPU\n name: (\"PIII\")\n serialno:(\"123\")\n price: (323.45)\n brand: (\"Intel\")\n type: (\"Slot1\")\n mhz: (800)]" "Helvetica" 0 9 0 REF 8
            CH.ifa.draw.standard.OffsetLocator 1 33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 6 "mhz" "brand" "name" "serialno" "type" "price"  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 39 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 218 26 "ship_item" "Helvetica" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 40 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 203 219 "delegate_order" "Helvetica" 1 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 34 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 241 55 "#2" "Helvetica" 0 9 0 REF 9
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 35 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 320 27 "#1[DeliveryNote]" "Helvetica" 0 9 0 REF 12
            CH.ifa.draw.standard.OffsetLocator -1 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 123 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 2 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 10 105 "incoming\nOrders" "Helvetica" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -60 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 158 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 507 154 "deliver" "Helvetica" 1 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 36 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 142 160 "#1[Order\n product: #2]" "Helvetica" 0 9 0 REF 17
            CH.ifa.draw.standard.OffsetLocator -7 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 2 "product" ""  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 33 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 145 66 "#1[Order\n     product: #2]" "Helvetica" 0 9 0 REF 2
            CH.ifa.draw.standard.OffsetLocator -4 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 2 "" "product"  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 120 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 19 135 "[Order]" "Helvetica" 0 12 0 REF 5
            CH.ifa.draw.standard.OffsetLocator -56 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0 0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 49 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 428 101 "stock_receipts" "Helvetica" 1 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 28 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 92 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 214 105 "[Mainboard\n name: (\"97a\")\n serialno:(\"4711\")\n brand: (\"ABit\")\n price: (249.44)\n type: (\"SlotA\")]" "Helvetica" 0 9 0 REF 8
            CH.ifa.draw.standard.OffsetLocator 1 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 5 "serialno" "type" "price" "name" "brand"  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 204 "FrameColor" "Color" 255 199 158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 458 64 "company's central\nwarehouse" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 -82 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 196 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 226 88 "[CPU\n name: (\"Athlon\")\n serialno:(\"K7a\")\n price: (303.45)\n brand: (\"AMD\")\n type: (\"SlotA\")\n mhz: (800)]" "Helvetica" 0 9 0 REF 8
            CH.ifa.draw.standard.OffsetLocator -1 -34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 6 "price" "brand" "type" "mhz" "name" "serialno"  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 170 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 206 139 "[Mousepad\n name: (\"Roller\")\n serialno:(\"9999\")\n brand: (\"boeder\")\n price: (4.99)\n size: (\"L\")]" "Helvetica" 0 9 0 REF 8
            CH.ifa.draw.standard.OffsetLocator -8 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 5 "name" "brand" "serialno" "price" "size"  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 197 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 221 122 "[Mainboard\n name: (\"xyz\")\n serialno:(\"1234\")\n brand: (\"Chaintec\")\n price: (229.44)\n type: (\"Slot1\")]" "Helvetica" 0 9 0 REF 8
            CH.ifa.draw.standard.OffsetLocator 8 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 5 "serialno" "brand" "name" "type" "price"  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "FigureWithID" "Int" 192 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 10 11 "access OrderTypesSimple;" "Helvetica" 0 12 0 NULL NULL 1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 122 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 74 116 "[Order\n customer: [Person name: (\"Frank\")]\n product: [Mainboard type:(\"SlotA\")]]" "Helvetica" 0 9 0 REF 5
            CH.ifa.draw.standard.OffsetLocator 0 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 4 "product" "customer" "customer:name" "product:type"  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 121 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 74 133 "[Order\n customer: [Person name: (\"Uli\")]\n product: [Mousepad size:(\"S\")]]" "Helvetica" 0 9 0 REF 5
            CH.ifa.draw.standard.OffsetLocator 0 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 3 "customer:name" "product:size" "customer"  NULL  0 153 618 306 
