11 
    de.renew.gui.CPNDrawing 78 
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 5524 "FillColor" "Color" 204 204 204 255 845 560 180 88 8 8  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5525 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "TextType" "Int" 0 "FillColor" "Color" 255 199 158 255 869 610 "position;\nname=student2;" "SansSerif" 0 17 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 5 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 5526 "FillColor" "Color" 204 204 204 255 526 559 304 88 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 5527 "FillColor" "Color" 204 204 204 255 4 336 962 204 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 5528 "FillColor" "Color" 204 204 204 255 3 2 800 315 8 8  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5529 "FrameColor" "Color" 0 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 200 0 255 "FontName" "String" "Arial" 259 16 176 78 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5530 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 304 23 "submitPaper" "Arial" 1 14 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 1 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5531 2 347 94 347 128 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5532 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 320 128 56 27 NULL    REF 16 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5533 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 340 134 "SP" "SansSerif" 1 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5534 "FrameColor" "Color" 0 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 200 0 255 "FontName" "String" "Arial" 15 189 213 53 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5535 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 24 206 "supervisePaperSubmission" "Arial" 1 15 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5536 "FrameColor" "Color" 0 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 200 0 255 "FontName" "String" "Arial" 248 189 199 53 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5537 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 279 206 "providePaperFrame" "Arial" 1 15 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5538 "FrameColor" "Color" 0 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 200 0 255 "FontName" "String" "Arial" 507 189 176 53 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5539 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 539 207 "writePaperBody" "Arial" 1 15 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 0 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5540 2 320 150 185 195 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 20   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5541 2 347 155 347 190 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5542 2 376 149 534 198 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5543 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 94 267 56 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5544 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 114 273 "SP" "SansSerif" 1 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5545 2 121 241 121 267 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 20  
            CH.ifa.draw.standard.ChopBoxConnector REF 44   
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 5546 "FillColor" "Color" 255 200 0 255 239 267 56 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5547 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 259 273 "SP" "SansSerif" 1 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5548 2 317 240 283 267 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 24  
            CH.ifa.draw.standard.ChopBoxConnector REF 52   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5549 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 568 266 56 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5550 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 588 272 "SP" "SansSerif" 1 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5551 2 595 241 595 266 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector REF 60   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5552 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 354 359 56 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5553 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 374 365 "SP" "SansSerif" 1 12 0 REF 68 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5554 3 365 241 381 264 381 359 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 24  
            CH.ifa.draw.standard.ChopBoxConnector REF 68   
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5555 "FrameColor" "Color" 0 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 200 0 255 "FontName" "String" "Arial" 764 408 187 53 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5556 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 808 424 "writeMainPart" "Arial" 1 15 0 REF 76 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5557 "FrameColor" "Color" 0 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 200 0 255 "FontName" "String" "Arial" 111 408 176 53 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5558 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 122 424 "definePaperStructure" "Arial" 1 15 0 REF 80 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5559 "FrameColor" "Color" 0 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 200 0 255 "FontName" "String" "Arial" 291 408 182 53 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5560 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 295 424 "writeIntroAndConclusion" "Arial" 1 15 0 REF 84 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5561 "FrameColor" "Color" 0 0 0 255 "TextType" "Int" 0 "FillColor" "Color" 255 200 0 255 "FontName" "String" "Arial" 547 408 188 53 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5562 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 551 424 "writeRelatedWorkSection" "Arial" 1 15 0 REF 88 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5563 2 382 386 382 409 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 68  
            CH.ifa.draw.figures.ChopEllipseConnector REF 84   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5564 2 354 381 257 416 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 68  
            CH.ifa.draw.figures.ChopEllipseConnector REF 80   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5565 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 172 488 56 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5566 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 188 494 "PPF" "SansSerif" 1 12 0 REF 100 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5567 2 199 460 199 488 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 80  
            CH.ifa.draw.standard.ChopBoxConnector REF 100   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5568 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 615 488 56 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5569 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 628 495 "WPB" "SansSerif" 1 12 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator 1 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5570 2 642 460 642 488 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 88  
            CH.ifa.draw.standard.ChopBoxConnector REF 108   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5571 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 831 488 56 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5572 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 844 494 "WPB" "SansSerif" 1 12 0 REF 116 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5573 2 858 460 858 488 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 76  
            CH.ifa.draw.standard.ChopBoxConnector REF 116   
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 5574 "FillColor" "Color" 255 200 0 255 454 266 56 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5575 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 470 272 "PPF" "SansSerif" 1 12 0 REF 124 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5576 4 399 460 427 503 482 503 482 293 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 84  
            CH.ifa.draw.standard.ChopBoxConnector REF 124   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5577 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 615 355 56 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5578 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 635 361 "SP" "SansSerif" 1 12 0 REF 132 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5579 3 619 240 643 265 643 355 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector REF 132   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5580 2 642 382 642 409 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 132  
            CH.ifa.draw.figures.ChopEllipseConnector REF 88   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5581 2 671 377 795 416 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 132  
            CH.ifa.draw.figures.ChopEllipseConnector REF 76   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5582 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 753 579 56 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5583 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 766 585 "WPB" "SansSerif" 1 12 0 REF 148 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5584 3 824 458 780 490 780 579 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 76  
            CH.ifa.draw.standard.ChopBoxConnector REF 148   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5585 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 557 579 56 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5586 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 570 586 "WPB" "SansSerif" 1 12 0 REF 156 
            CH.ifa.draw.standard.OffsetLocator 1 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5587 3 617 459 585 491 585 579 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 88  
            CH.ifa.draw.standard.ChopBoxConnector REF 156   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5588 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 717 266 56 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5589 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 730 273 "WPB" "SansSerif" 1 12 0 REF 164 
            CH.ifa.draw.standard.OffsetLocator 1 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5590 4 676 458 714 486 745 486 745 293 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 88  
            CH.ifa.draw.standard.ChopBoxConnector REF 164   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5591 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 170 360 56 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5592 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 190 366 "SP" "SansSerif" 1 12 0 REF 172 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5593 4 363 241 378 264 372 343 226 368 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 24  
            CH.ifa.draw.standard.ChopBoxConnector REF 172   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5594 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "TextType" "Int" 0 "FillColor" "Color" 255 199 158 255 267 41 "{supervisePaperSubmission,\nprovidePaperFrame,\nwritePaperBody}" "Arial" 0 13 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 2 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5595 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "TextType" "Int" 0 "FillColor" "Color" 255 199 158 255 22 15 "position;\nname=supervisor;" "SansSerif" 0 18 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -300 -122 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5596 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "TextType" "Int" 0 "FillColor" "Color" 255 199 158 255 9 496 "position;\nname=phdStudent;" "SansSerif" 0 17 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator -393 78 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 5597 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "TextType" "Int" 0 "FillColor" "Color" 255 199 158 255 615 602 "position;\nname=student1;" "SansSerif" 0 18 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 10 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5598 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 858 33 "organization;\nname=paper;" "SansSerif" 0 22 0 NULL NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5599 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 911 577 56 27 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 5600 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 924 583 "WPB" "SansSerif" 1 12 0 REF 193 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5601 3 892 458 938 491 938 577 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 76  
            CH.ifa.draw.standard.ChopBoxConnector REF 193   NULL  -91 25 1458 1032 