11 
    de.renew.gui.CPNDrawing 68 
        CH.ifa.draw.figures.GroupFigure 2 
            CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5638 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -24 -201 127 220 5  
            CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5639 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 -24 -201 127 220 3   
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 46067 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 18 68 130 33  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 46068 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 63 96 42 81  
        de.renew.bpmn.roundtrip.RoundtripNetComponentFigure "attributes" "attributes" 3 "FigureWithID" "Int" 46069 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 37 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3631 "Visibility" "Boolean" "TRUE" 2 -2 -63 -2 -109 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3632 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -12 -64 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3628 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -13 -125 24 16 NULL    
            de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5650 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 29 148 20 20 NULL 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3621 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 255 255 255 30 -64 20 20 NULL   
            de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3627 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 -14 -7 24 16 NULL  REF 1 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5649 2 91 48 121 77 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5646 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 74 31 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5648 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 118 77 24 16 NULL    
            de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 46065 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 71 152 24 16 NULL  REF 12 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 46075 2 49 158 71 159 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 13  
                CH.ifa.draw.standard.ChopBoxConnector REF 22   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 46073 2 51 85 74 85 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 749 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 27 77 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 46072 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 73 75 20 20 NULL    
            de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3619 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 71 -6 24 16 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3623 "Visibility" "Boolean" "TRUE" 2 83 -109 83 -63 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3620 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 71 -125 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3624 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 73 -64 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5645 2 83 10 84 32 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 33  
                CH.ifa.draw.figures.ChopEllipseConnector REF 19   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 46074 2 83 95 83 152 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 32  
                CH.ifa.draw.standard.ChopBoxConnector REF 22   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5642 2 1 -109 37 -7 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 12  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5643 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 29 -9 20 20 NULL    REF 30 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3636 2 95 -5 142 -32 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 33  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3638 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 224 224 255 255 140 -47 20 20 NULL 
                        de.renew.gui.PlaceFigure "attributes" "attributes" 2 "FigureWithID" "Int" 3637 "FillColor" "Color" 224 224 255 255 37 -305 20 20 NULL     REF 57 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3622 "Visibility" "Boolean" "TRUE" 2 46 -61 77 -109 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 14  
                CH.ifa.draw.standard.ChopBoxConnector REF 37   
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3635 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 126 -9 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3625 "Visibility" "Boolean" "TRUE" 2 83 -44 83 -6 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 39  
                CH.ifa.draw.standard.ChopBoxConnector REF 33   REF 21 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5647 2 93 85 118 85 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 32  
                CH.ifa.draw.standard.ChopBoxConnector REF 21   REF 4 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3629 "Visibility" "Boolean" "TRUE" 2 4 -109 36 -61 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 12  
                CH.ifa.draw.figures.ChopEllipseConnector REF 14   REF 19 REF 37 REF 14 REF 39 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 751 2 95 160 128 161 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 22  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 748 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 255 127 151 20 20 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3630 "Visibility" "Boolean" "TRUE" 2 -2 -7 -2 -44 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 15  
                CH.ifa.draw.figures.ChopEllipseConnector REF 10   REF 5 REF 32 REF 52 REF 10 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 46066 2 39 11 39 77 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 52  
                CH.ifa.draw.standard.ChopBoxConnector REF 30   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3634 2 95 1 127 1 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 33  
                CH.ifa.draw.figures.ChopEllipseConnector REF 63   REF 80 "out-in-timeout"  REF 13 REF 15 REF 22 REF 12 REF 33 REF 30 REF 57 REF 63 REF 21 REF 19 REF 37 REF 14 REF 39 REF 32 REF 52 REF 10 REF 80 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3655 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 109 -35 "p" "SansSerif" 0 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator -5 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 6 "TextAlignment" "Int" 1 "FigureWithID" "Int" 750 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 141 153 ">" "SansSerif" 1 12 0 REF 80 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3657 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 143 -42 "P3" "SansSerif" 1 12 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator 0 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 7 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3626 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 84 -93 "p" "SansSerif" 0 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator 5 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3652 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 -17 -146 ":out(p2)" "SansSerif" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 7 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 16 REF 23 REF 27 REF 34 REF 40 REF 44 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3656 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 84 -34 "p" "SansSerif" 0 12 0 REF 64 
            CH.ifa.draw.standard.OffsetLocator 5 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 48 REF 53 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3650 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 -9 -33 "p2" "SansSerif" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 752 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 23 78 ">" "SansSerif" 1 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator -11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 59 REF 64 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 46063 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -1 103 "action Thread.\nsleep(15000)" "SansSerif" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 2 33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 68 REF 72 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3653 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 255 66 -145 ":in(p)" "SansSerif" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator -2 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3659 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 140 -7 ">" "SansSerif" 1 12 0 REF 63 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 76 REF 81 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3651 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 -10 -87 "p2" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 0 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3658 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 -18 -7 ">" "SansSerif" 1 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -11 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 85 REF 89 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3640 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 85 -302 24 16 NULL  REF 58 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3647 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 224 224 255 255 153 -277 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3643 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 224 224 255 255 152 -305 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3649 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 181 -302 "Perf3" "SansSerif" 1 12 0 REF 134 
            CH.ifa.draw.standard.OffsetLocator 35 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3642 2 109 -295 153 -295 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 132  
            CH.ifa.draw.figures.ChopEllipseConnector REF 134   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3648 3 97 -286 98 -267 154 -267 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 132  
            CH.ifa.draw.figures.ChopEllipseConnector REF 133   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3645 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 41 -301 "P3" "SansSerif" 1 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator 1 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3644 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 127 -302 "p" "SansSerif" 0 12 0 REF 138 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3641 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 67 -302 "p" "SansSerif" 0 12 0 
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3639 2 57 -295 85 -295 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 58  
                CH.ifa.draw.standard.ChopBoxConnector REF 132   
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 153 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4319 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 34 -240 "[fromAgent]" "SansSerif" 0 18 0 
            de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3654 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 13 -32 "OUT-IN" "SansSerif" 1 12 0 REF 14 
                CH.ifa.draw.standard.OffsetLocator -3 29 
                    CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
            CH.ifa.draw.standard.OffsetLocator 49 -204 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 160 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5644 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 -82 -242 "[toAgent]" "SansSerif" 0 18 0 REF 160 
            CH.ifa.draw.standard.OffsetLocator -79 -206 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 5640 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 -11 235 "this is completely experimental" "SansSerif" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4320 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 -42 199 "[wait 15 seconds]" "SansSerif" 0 18 0 REF 160 
            CH.ifa.draw.standard.OffsetLocator -3 235 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 5641 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -89 23 "action p2=Sl0Creator.\ncreateActionRequest(\n    aid,\n    \"content\")" "SansSerif" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -23 52 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  212 190 857 683 