10 
    de.renew.gui.CPNDrawing 38 
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 3 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 309 241 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 5 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 288 262 "start-time" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 1 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 6 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 18 133 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 8 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 8 155 "iterations" "SansSerif" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 10 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 9 3 30 153 40 207 97 220 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 34 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 97 215 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 13 2 100 215 35 150 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 13  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 15 2 38 143 207 143 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 16 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 207 135 24 16 NULL    REF 22 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 17 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 118 136 "0" "SansSerif" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 18 2 313 245 226 151 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 22   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 22 2 231 143 313 143 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 22  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 23 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 312 133 20 20 NULL    REF 34 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 7 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 3 116 "1000" "SansSerif" 0 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -9 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 21 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 232 184 "startTime" "SansSerif" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator -10 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 1 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 34 379 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "TextAlignment" "Int" 0 "FigureWithID" "Int" 25 "MarkingAppearance" "Int" 2 2 54 389 94 389 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 41  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 26 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 94 382 24 16 NULL    REF 46 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 27 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 13 359 "{1,2,3,4}" "SansSerif" 0 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator -5 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "TextAlignment" "Int" 0 "FigureWithID" "Int" 28 "MarkingAppearance" "Int" 2 2 118 390 206 390 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 46  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 29 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 205 380 20 20 NULL    REF 54 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "TextAlignment" "Int" 0 "FigureWithID" "Int" 30 "MarkingAppearance" "Int" 2 2 207 394 115 439 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 54  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 31 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 91 437 24 16 NULL    REF 59 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "TextAlignment" "Int" 0 "FigureWithID" "Int" 32 "MarkingAppearance" "Int" 2 2 94 437 51 396 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 59  
            CH.ifa.draw.figures.ChopEllipseConnector REF 41   REF 13 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "TextAlignment" "Int" 0 "FigureWithID" "Int" 35 "MarkingAppearance" "Int" 2 3 216 381 223 295 121 230 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 54  
            CH.ifa.draw.standard.ChopBoxConnector REF 13   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "TextAlignment" "Int" 0 "FigureWithID" "Int" 36 "MarkingAppearance" "Int" 2 2 114 231 211 383 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 13  
            CH.ifa.draw.figures.ChopEllipseConnector REF 54   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 37 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 70 370 "li" "SansSerif" 0 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator -1 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 19 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 67 397 "li" "SansSerif" 0 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator -2 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 12 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 29 212 "it" "SansSerif" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -31 33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 14 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 73 168 "it - 1" "SansSerif" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 21 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 38 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 156 424 "[{},li]" "SansSerif" 0 12 0 REF 55 
            CH.ifa.draw.standard.OffsetLocator 8 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 39 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 129 369 "[li,{}]" "SansSerif" 0 12 0 REF 50 
            CH.ifa.draw.standard.OffsetLocator -20 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 41 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 232 291 "[{hd:tl},li]" "SansSerif" 0 12 0 REF 64 
            CH.ifa.draw.standard.OffsetLocator 86 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "FigureWithID" "Int" 24 "FrameColor" "Color" 255 199 158 "MarkingAppearance" "Int" 2 "TextAlignment" "Int" 0 "FillColor" "Color" 254 254 254 141 96 "java.lang.System.currentTimeMillis()\n  - startTime" "SansSerif" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator -28 -32 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 2 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 45 2 270 111 270 138 NULL NULL "CH.ifa.draw.figures.ArrowTip"  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 11 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 128 212 "guard it > 0" "SansSerif" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 54 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 2 "FigureWithID" "Int" 46 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 222 230 "java.lang.System\n .currentTimeMillis()" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -40 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 40 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 104 311 "[tl,{hd:li}]" "SansSerif" 0 12 0 REF 68 
            CH.ifa.draw.standard.OffsetLocator -32 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  769 141 383 505 