7 
    de.renew.gui.CPNDrawing 21 
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 2 2 184 331 184 286 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FillColor" "Color" 255 255 255 "FrameColor" "Color" 0 0 0 "FigureWithID" "Int" 1 87 331 "PlaceEvent\n\n+ getPlaceInstance(): PlaceInstance" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 49 236 "PlaceInstance\n\n+ addPlaceEventListener(PlaceEventListener)\n+ removePlaceEventListener(PlaceEventListener)" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 6 2 184 236 184 191 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FillColor" "Color" 255 255 255 "FrameColor" "Color" 0 0 0 "FigureWithID" "Int" 5 49 141 "Place\n\n+ addPlaceEventListener(PlaceEventListener)\n+ removePlaceEventListener(PlaceEventListener)" "Helvetica" 0 12 0 NULL NULL    REF 4
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FillColor" "Color" 255 255 255 "FigureWithID" "Int" 9 2 184 412 184 366 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FillColor" "Color" 255 255 255 "FrameColor" "Color" 0 0 0 "FigureWithID" "Int" 8 131 412 "TokenEvent\n\n# token: Object\n\n+ Object getToken()" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 4  0  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "Int" 10 "FillColor" "Color" 255 255 255 "FigureWithID" "Int" 13 2 184 141 184 96 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FillColor" "Color" 255 255 255 "FrameColor" "Color" 0 0 0 "FigureWithID" "Int" 11 54 31 "«interface»\nPlaceEventProducer\n\naddPlaceEventListener(PlaceEventListener)\nremovePlaceEventListener(PlaceEventListener)" "Helvetica" 0 12 0 NULL NULL   0
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "Int" 10 "FillColor" "Color" 255 255 255 "FigureWithID" "Int" 14 4 44 258 14 258 14 64 49 64 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 21  0  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "Int" 10 "FillColor" "Color" 255 255 255 "FigureWithID" "Int" 15 2 471 358 471 315 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FillColor" "Color" 255 255 255 "FrameColor" "Color" 0 0 0 "FigureWithID" "Int" 12 384 358 "PlaceEventAdapter\n\n+ markingChanged(PlaceEvent)\n+ tokenAdded(TokenEvent)\n+ tokenRemoved(TokenEvent)\n+ tokenTested(TokenEvent)\n+ tokenUntested(TokenEvent)" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FillColor" "Color" 255 255 255 "FrameColor" "Color" 0 0 0 "FigureWithID" "Int" 10 389 205 "«interface»\nPlaceEventListener\n\nmarkingChanged(PlaceEvent)\ntokenAdded(TokenEvent)\ntokenRemoved(TokenEvent)\ntokenTested(TokenEvent)\ntokenUntested(TokenEvent)" "Helvetica" 0 12 0 NULL NULL   0  REF 11
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 16 3 325 165 472 165 472 205 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector REF 31   REF 6 
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 17 2 325 260 384 260 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 31   REF 21 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 190 207 "place" "Helvetica" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 21 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 194 302 "placeInstance" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 48 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 31 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 20 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 482 178 "*" "Helvetica" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 86 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 21 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 369 266 "*" "Helvetica" 0 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 17 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 29 REF 15 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 18 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 329 146 "listeners" "Helvetica" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator -46 -32 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 19 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 329 241 "listeners" "Helvetica" 0 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator -2 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  -2 169 903 600 