10 
    de.renew.gui.CPNDrawing 66 
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1 "FrameColor" "Color" 0 0 0 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 339 217 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 2 "FrameColor" "Color" 0 0 0 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 392 340 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 7 "Visibility" "Boolean" "TRUE" 2 353 236 400 340 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 11 "FrameColor" "Color" 0 0 0 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 337 152 24 16 
            CH.ifa.draw.figures.ImageFigure "attributes" "attributes" 2 "FigureWithID" "Int" 136 "Visibility" "Boolean" "TRUE" 397 82 157 140 "../bilder/chat.gif"   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 13 "Visibility" "Boolean" "TRUE" 2 349 168 349 218 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 14 "Visibility" "Boolean" "TRUE" 4 356 168 371 183 371 206 356 221 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 19 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 339 185 "abs" "SansSerif" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 17 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 379 187 "empf" "SansSerif" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 30 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 33 "FrameColor" "Color" 0 0 0 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 228 356 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 34 "Visibility" "Boolean" "TRUE" 2 246 356 344 235 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 21  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 44 "FrameColor" "Color" 0 0 0 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 559 220 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 45 "Visibility" "Boolean" "TRUE" 2 559 227 359 227 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 26  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 48 "Visibility" "Boolean" "TRUE" 2 340 227 102 227 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 59 "FrameColor" "Color" 0 0 0 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 78 219 24 16 NULL    REF 33 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 50 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 590 220 "abs:aus(p)" "SansSerif" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 49 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 84 "FrameColor" "Color" 0 0 0 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 112 219 147 476 275 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 85 "Visibility" "Boolean" "TRUE" 2 358 231 476 278 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 37   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 86 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 405 246 "ams" "SansSerif" 0 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 53 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 76 200 ":ein(p)" "SansSerif" 0 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator 3 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 28 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 306 134 "empf:ein(name,p)" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 6 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 152 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 468 290 "Service" "SansSerif" 1 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator 1 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 4 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 281 234 "Agenten " "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -43 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 27 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 323 121 "abs:aus(p)" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 4 -31 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 24 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 366 288 "agent" "SansSerif" 0 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 5 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 46 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 509 219 "abs" "SansSerif" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 60 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 55 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 112 205 "empf:ein(name,p)" "SansSerif" 0 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator 71 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 49 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 211 220 "empf" "SansSerif" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 4 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 157 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 25 249 "guard new AclMessage\n(null,null,name,null).subsumes(p)" "SansSerif" 0 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator 28 38 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 153 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 47 168 "Nachrichten_\neingang" "SansSerif" 1 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator -5 -43 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 151 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 396 132 "interne \nKommunikation" "SansSerif" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 91 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 154 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 531 174 "Nachrichten_\nausgang" "SansSerif" 1 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator -2 -38 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 29 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 244 88 "guard new AclMessage\n(null,null,name,null).subsumes(p)" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -12 -56 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 56 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 197 379 ":move_in(agent,p)" "SansSerif" 0 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator 6 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 205 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 479 326 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 206 2 357 233 480 326 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 89   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 207 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 403 271 "agent" "SansSerif" 0 12 0 REF 90 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 208 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 472 312 "forName" "SansSerif" 1 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator 5 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 209 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 512 327 ":forName(name,agent)" "SansSerif" 0 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator 83 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 210 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 510 338 "agent:name(name)" "SansSerif" 0 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator 72 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 58 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 307 336 "(Mobilität)" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -69 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 230 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 114 104 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 234 2 138 118 341 223 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 108  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 236 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 227 162 "ams" "SansSerif" 0 12 0 REF 109 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 87 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 460 253 ":service(key,value,name,p)" "SansSerif" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator 44 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 88 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 497 273 "ams:service(key,value,name,p)" "SansSerif" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator 94 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 235 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 88 75 "Init." "SansSerif" 1 12 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator -28 -29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 237 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 117 45 "ams:new ams_agent\n(AgentIdentifier.AMS,\npfName,this)" "SansSerif" 0 12 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator 49 -43 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 242 2 138 111 215 110 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 108  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 243 "MarkingAppearance" "Int" 3 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 214 100 20 20 NULL    REF 132 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 244 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 154 102 "pfName" "SansSerif" 0 12 0 REF 128 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 241 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 121 29 ":new(pfName)" "SansSerif" 0 12 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator 34 -75 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 245 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 588 234 "guard false" "SansSerif" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 48 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 250 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 359 391 "agent:name(name)" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 8 51 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 254 189 322 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 255 2 212 322 342 233 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 145  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 256 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 114 336 ":newAgent(agent)" "SansSerif" 0 12 0 REF 145 
            CH.ifa.draw.standard.OffsetLocator -39 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 257 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 240 281 "agent" "SansSerif" 0 12 0 REF 146 
            CH.ifa.draw.standard.OffsetLocator -22 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 246 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 349 374 "this:service(\"move\",dest,name,p)" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 35 34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 69 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 350 358 ":move_out(agent,p,dest)" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 12 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 31 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 255 199 158 523 34 "import de.renew.agent.repr.acl.*;\nimport de.renew.net.*;\nNetInstance abs,empf,agent,ams;\nAclMessage p,muster,antw;\nAgentIdentifier name;\nString dest,assignment,key,value,pfName;" "SansSerif" 0 12 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 35 "FrameColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 303 298 "agent" "SansSerif" 0 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator 23 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 247 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 187 406 "agent:ein(name,p)" "SansSerif" 0 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator -3 50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 262 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 191 392 "agent:name(name)" "SansSerif" 0 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator 4 36 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 263 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 -4 356 "action ((de.renew.extras.imagenets.\nImageNetInstanceImpl)this).\nnewImageFile(\"robot.gif\")" "SansSerif" 0 12 0 REF 145 
            CH.ifa.draw.standard.OffsetLocator -107 50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 264 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 147 421 "action ((de.renew.extras.imagenets.\nImageNetInstanceImpl)this).\nnewImageFile(\"robot.gif\")" "SansSerif" 0 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator 5 81 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 265 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 324 411 "action ((de.renew.extras.imagenets.\nImageNetInstanceImpl)this).\nnewImageFile(\"\")" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 18 87 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  86 194 814 837 