1 
    de.renew.gui.CPNDrawing 45 
        de.renew.gui.ArcConnection "no_attributes" 2 158 78 187 171 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "no_attributes" 90 18 118 61   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 178 171 24 16    
        de.renew.gui.ArcConnection "no_attributes" 2 138 77 100 168 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 85 168 24 16    
        de.renew.gui.PlaceFigure "no_attributes" 136 115 20 20  
        de.renew.gui.ArcConnection "no_attributes" 2 140 132 104 168 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14  
            CH.ifa.draw.standard.ChopBoxConnector REF 13   REF 13 
        de.renew.gui.ArcConnection "no_attributes" 2 103 184 133 221 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 13  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "no_attributes" 116 218 60 40    REF 23 
        de.renew.gui.ArcConnection "no_attributes" 2 159 221 184 187 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 23  
            CH.ifa.draw.standard.ChopBoxConnector REF 7   REF 7 
        de.renew.gui.ArcConnection "no_attributes" 2 183 171 152 133 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 135 98 "hand_empty" "Helvetica" 1 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 25 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 126 259 "holding" "Helvetica" 1 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 0 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 176 204 "b" "Helvetica" 0 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 8 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 103 197 "b" "Helvetica" 0 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator -12 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 143 118 "[]" "Helvetica" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 18 159 "b:isClear()" "Helvetica" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator -51 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 208 171 "x:occupyWith(b)" "Helvetica" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 63 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 15 175 "x:remove(b)" "Helvetica" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator -50 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 5 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 207 23 "containers" "Helvetica" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator 89 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "no_attributes" 10 42 24 16  
        de.renew.gui.ArcConnection "no_attributes" 2 34 49 91 49 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 59  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 61 51 "x" "Helvetica" 0 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator 2 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 7 25 ":introduce(x)" "Helvetica" 0 12 0 REF 59 
            CH.ifa.draw.standard.OffsetLocator 19 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 110 102 "x" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator -6 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 3 120 74 97 93 97 168 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 13   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 86 92 "b" "Helvetica" 0 12 0 REF 73 
            CH.ifa.draw.standard.OffsetLocator -19 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 178 112 "x" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 9 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 34 144 "pickup" "Helvetica" 1 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator -44 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 206 156 "putdown" "Helvetica" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 41 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "no_attributes" 3 189 171 189 87 177 75 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 195 119 "b" "Helvetica" 0 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator 15 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "no_attributes" 2 203 60 272 76 NULL NULL 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "no_attributes" 272 71 24 16    REF 99 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 217 45 "a" "Helvetica" 0 12 0 REF 96 
            CH.ifa.draw.standard.OffsetLocator -17 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 233 49 "b" "Helvetica" 0 12 0 REF 96 
            CH.ifa.draw.standard.OffsetLocator -1 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 247 53 "c" "Helvetica" 0 12 0 REF 96 
            CH.ifa.draw.standard.OffsetLocator 13 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 301 53 "a:getName(\"A\")" "Helvetica" 0 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator 60 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 301 68 "b:getName(\"B\")" "Helvetica" 0 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator 59 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 301 83 "c:getName(\"C\")" "Helvetica" 0 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator 60 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 301 98 "a:isCarrying(b)" "Helvetica" 0 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator 58 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 301 112 "b:isCarrying(c)" "Helvetica" 0 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator 58 40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 301 37 "solution" "Helvetica" 1 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator 40 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "no_attributes" 2 284 87 284 127 NULL 
            CH.ifa.draw.figures.ArrowTip  
            CH.ifa.draw.standard.ChopBoxConnector REF 99  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "no_attributes" 274 126 20 20    REF 131  