7 
    de.renew.gui.CPNDrawing 19 
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 2 2 300 281 244 291 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 305 196 "Searcher\n\n+ isCompleted(): boolean\n+ insertTriggerable(TriggerableCollection)\n- selectBestBinder(): Binder\n+ search()\n+ addBinder(Binder)\n+ removeBinder(Binder)\n# searchOnce(Finder,Searchable, Triggerable)" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 3 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 111 271 "«interface»\nFinder\n\nfound(Searcher)\nisCompleted(): boolean" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5 2 432 196 432 138 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 349 73 "«interface»\nBinder\n\nbindingBadness(Searcher): int\nbind(Searcher)" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "Int" 10 "FillColor" "Color" 255 255 255 "FigureWithID" "Int" 12 2 175 179 175 138 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FillColor" "Color" 255 255 255 "FrameColor" "Color" 0 0 0 "FigureWithID" "Int" 10 115 179 "«interface»\nSearchable\n\nstartSearch(Searcher)" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FillColor" "Color" 255 255 255 "FrameColor" "Color" 0 0 0 "FigureWithID" "Int" 11 101 73 "«interface»\nTriggerable\n\ntriggers(): TriggerCollection\nproposeSearch()" "Helvetica" 0 12 0 NULL NULL   0
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 14 2 327 196 230 138 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector REF 17   
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 18 2 432 321 432 371 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 19 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 284 371 "CalculationChecker\n\n+ reset()\n+ addEarlyVariable(Variable, StateRecorder)\n+ addCalculated(Class, Object, Object, StateRecorder)\n+ addLateVariable(Variable, StateRecorder)\n+ isConsistent(): boolean" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 24 2 331 321 239 378 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FillColor" "Color" 255 255 255 "FrameColor" "Color" 0 0 0 "FigureWithID" "Int" 23 111 378 "StateRecorder\n\n+ record(StateRestorer)\n+ checkpoint(): int\n+ restore(int)\n+ restore()" "Helvetica" 0 12 0 NULL NULL    REF 4 REF 17 REF 15 REF 6
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 438 166 "binders" "Helvetica" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 26 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 11 REF 26 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 20 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 441 339 "calcChecker" "Helvetica" 0 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator 43 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 420 149 "*" "Helvetica" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -10 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 31 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 256 266 "finder" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -1 -13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 25 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 307 338 "recorder" "Helvetica" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 45 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 15 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 280 152 "primaryTriggerable" "Helvetica" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 54 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  58 213 1071 803 