
    CH.ifa.draw.cpn.CPNDrawing 17 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 270 164 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 195 247 20 20  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 340 245 20 20  
        CH.ifa.draw.cpn.ArcConnection 3 270 176 207 199 205 248 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.ArcConnection 3 294 178 340 202 349 246 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        CH.ifa.draw.cpn.ArcConnection 3 280 180 263 250 215 257 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.ArcConnection 3 284 180 309 252 341 255 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 206 174 "\"a\"" "Helvetica" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -23 -31 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 243 227 "\"b\"" "Helvetica" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 4 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 301 218 "\"b\"" "Helvetica" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator -3 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 326 174 "\"c\"" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 13 -31 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 256 342 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 211 265 262 342 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 32   
        CH.ifa.draw.cpn.ArcConnection 2 344 263 274 342 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector REF 32   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 247 287 "x" "Helvetica" 0 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator 14 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 292 284 "x" "Helvetica" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator -14 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 264 147 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -4 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
