11 
    de.renew.gui.CPNDrawing 46 
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 714 2 713 539 713 579 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 731 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 581 442 "SendChannelBinder\n\ntargetVariable: Variable\nname: String\nparams: Variable\nreturnVariable: Variable\n\ngetCreatedDistributor(): SearchDistributorImpl" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 752 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 584 579 "SearchDistributorImpl\n\nsearchers: Map<Long, SearcherAccessor>\n\nabort()\ncreateExecutables(): Collection<Executable>" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 715 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 656 548 "createdDistributor" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -5 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 716 2 587 774 587 815 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 749 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 507 758 "RemoteBindingExecutable" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 757 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 534 815 "«remote interface»\nBindingAccessor" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 717 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 566 787 "binding" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 718 "FillColor" "Color" 255 255 255 255 2 576 490 269 490 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 730 "FrameColor" "Color" 0 0 255 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 93 459 "«interface»\nBinder\n\nbindingBadness(Searcher): int\nbind(Searcher)" "SansSerif" 0 12 0 NULL NULL   0
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 719 "FillColor" "Color" 255 255 255 255 2 630 219 583 219 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 727 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 635 174 "SendDownlinkInscription\n\nname: String\nparams: Expression\ncallee: Expression\nreturnExpr: Expression\ntransition: Transition" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 720 "FrameColor" "Color" 0 0 255 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 93 191 "«interface»\nTransitionInscription\n\nmakeOccurrences(VariableMapper, NetInstance, Searcher): Collection<Occurrence>" "SansSerif" 0 12 0 NULL NULL   0  REF 29
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "LineStyle" "String" "1 2" "FigureWithID" "Int" 721 2 713 268 713 308 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 27  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 729 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 634 308 "SendDownlinkOccurrence\n\nname: String\nparams: Expression\ncallee: Expression\nreturnExpr: Expression\nmapper: VariableMapper" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 722 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 689 276 "«create»" "SansSerif" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 0 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 723 2 713 402 713 442 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 34  
            CH.ifa.draw.standard.ChopBoxConnector REF 4   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 724 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 694 411 "binder" "SansSerif" 0 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 0 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "LineStyle" "String" "1 2" "FigureWithID" "Int" 725 2 587 717 587 758 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 754 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 460 686 "DistributeBindingAwaiterImpl\nin SearchDistributorImpl.createExecutables()" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 13   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 726 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 563 730 "«create»" "SansSerif" 0 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 27 
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 728 "FrameColor" "Color" 0 0 255 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 93 324 "«interface»\nOccurrence\n\nmakeBinders(Searcher): Collection<Binder>\nmakeExecutables(VariableMapperCopier): Collection<Executable>" "SansSerif" 0 12 0 NULL NULL  REF 34 REF 23 REF 4
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 732 "FillColor" "Color" 255 255 255 255 2 629 355 484 355 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 34  
            CH.ifa.draw.standard.ChopBoxConnector REF 53  0  
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 733 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 639 118 "DistributeJavaNetParser" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 734 "FrameColor" "Color" 0 0 255 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 93 103 "«interface»\nInscriptionParser\n\nTransitionInscription(boolean, Transition): Collection<TransitionInscription>" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 735 "FillColor" "Color" 255 255 255 255 2 634 126 532 126 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 58  
            CH.ifa.draw.standard.ChopBoxConnector REF 59  0  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "LineStyle" "String" "1 2" "FigureWithID" "Int" 736 2 713 134 713 174 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 58  
            CH.ifa.draw.standard.ChopBoxConnector REF 27   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 737 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 689 142 "«create»" "SansSerif" 0 12 0 REF 64 
            CH.ifa.draw.standard.OffsetLocator 0 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 738 "FrameColor" "Color" 0 0 255 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 93 45 "«interface»\nShadowCompiler\n\ncompile(ShadowNet)" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 739 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 611 62 "DistributeSingleJavaNetCompiler" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 740 "FillColor" "Color" 255 255 255 255 2 606 69 215 69 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 72  
            CH.ifa.draw.standard.ChopBoxConnector REF 71  0  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "LineStyle" "String" "1 2" "FigureWithID" "Int" 741 2 713 78 713 118 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 72  
            CH.ifa.draw.standard.ChopBoxConnector REF 58   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 742 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 697 86 "«use»" "SansSerif" 0 12 0 REF 77 
            CH.ifa.draw.standard.OffsetLocator 0 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 743 "FillColor" "Color" 255 255 255 255 2 579 612 398 612 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 755 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 284 588 "«remote interface»\nSearchDistributor\n\nsearchCall(...)" "SansSerif" 0 12 0 NULL NULL   0
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 744 "FillColor" "Color" 255 255 255 255 2 455 701 423 701 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 48  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 756 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 258 677 "«remote interface»\nDistributeBindingAwaiter\n\nsetBinding(BindingAccessor)" "SansSerif" 0 12 0 NULL NULL   0
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "LineStyle" "String" "1 2" "FigureWithID" "Int" 745 2 666 646 609 686 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 48   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 746 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 613 658 "«create»" "SansSerif" 0 12 0 REF 94 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 747 "FillColor" "Color" 255 255 255 255 2 502 766 194 766 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 0.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 13  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 4 "FigureWithID" "Int" 748 "FrameColor" "Color" 0 0 255 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 255 255 255 93 751 "«interface»\nEarlyExecutable" "SansSerif" 0 12 0 NULL NULL   0  REF 105 REF 13
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 2 "LineStyle" "String" "1 2" "FigureWithID" "Int" 750 2 754 646 802 686 NULL
            de.renew.gui.AssocArrowTip 0.4 11.0 11.0 1  "de.renew.gui.AssocArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 753 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 737 686 "«remote interface»\nSearcherAccessor\n\nsearchCall(...)\ncreateBinding(DistributeBindingAwaiter)\nabort()" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 751 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 762 658 "«use»" "SansSerif" 0 12 0 REF 106 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 6 REF 110 REF 48 REF 88 REF 93 REF 15 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 758 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 628 675 "*" "SansSerif" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 759 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 804 675 "*" "SansSerif" 0 12 0 NULL NULL  NULL  15 23 1004 746 