7 
    de.renew.gui.CPNDrawing 41 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 51 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 35 122 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52 2 47 122 47 45 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 53 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 37 25 20 20 NULL    REF 6 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 54 2 57 35 160 35 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 55 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 160 27 24 16 NULL    REF 11 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 56 2 164 43 134 74 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 11  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 57 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 117 70 20 20 NULL    REF 16 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 58 2 180 43 211 74 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 11  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 59 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 207 70 20 20 NULL    REF 21 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 60 2 217 90 217 127 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 21  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 61 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 205 127 24 16 NULL    REF 26 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 62 2 127 90 127 127 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 115 127 24 16 NULL    REF 31 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 64 2 127 143 127 181 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 31  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 65 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 117 180 20 20 NULL    REF 36 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 66 2 217 143 217 181 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 26  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 67 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 207 180 20 20 NULL    REF 41 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 68 2 212 198 183 232 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 41  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 69 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 165 232 24 16 NULL    REF 46 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 70 2 134 197 169 232 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 36  
            CH.ifa.draw.standard.ChopBoxConnector REF 46   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 71 2 165 240 57 240 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 46  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 72 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 37 230 20 20 NULL    REF 55 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 73 2 47 231 47 138 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 55  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 76 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 167 28 "t1" "Helvetica" 1 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 78 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 140 183 "p3" "Helvetica" 1 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 80 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 190 183 "p5" "Helvetica" 1 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator -20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 81 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 20 233 "p6" "Helvetica" 1 12 0 REF 55 
            CH.ifa.draw.standard.OffsetLocator -20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 82 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 122 128 "t2" "Helvetica" 1 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 83 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 212 128 "t3" "Helvetica" 1 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 84 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 172 233 "t7" "Helvetica" 1 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 85 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 42 123 "t8" "Helvetica" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 75 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 40 8 "p1" "Helvetica" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 0 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 77 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 140 73 "p2" "Helvetica" 1 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 79 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 190 73 "p4" "Helvetica" 1 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator -20 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 95 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 190 28 "<i1>" "Helvetica" 1 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 30 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 98 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 140 128 "<i2>" "Helvetica" 1 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator 25 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 104 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 180 128 "<i3>" "Helvetica" 1 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator -25 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 107 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 195 233 "<i4>" "Helvetica" 1 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 30 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 110 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 43 27 "[]" "Helvetica" 0 12 0 REF 6
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1 1 ""  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 93 "MarkingAppearance" "Int" 0 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 9 79 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 94 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 6 63 "proc" "Helvetica" 1 12 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  288 153 282 324 
