8 
    de.renew.gui.CPNDrawing 42 
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 59 "FillColor" "Color" 255 255 255 378 10 413 376 8 8  
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 5 "FillColor" "Color" 0 0 0 316 58 14 14  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 8 "FillColor" "Color" 255 255 255 411 19 148 93 8 8  
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 12 2 330 65 411 65 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13 "FillColor" "Color" 255 255 255 412 143 368 234 8 8  
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 15 "FillColor" "Color" 0 0 0 429 218 14 14  
        CH.ifa.draw.contrib.DiamondFigure "attributes" "attributes" 2 "FigureWithID" "Int" 10 "FillColor" "Color" 255 255 255 463 214 42 23  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 16 "FillColor" "Color" 255 255 255 606 183 163 41 8 8  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 2 "LineStyle" "String" "10" "FigureWithID" "Int" 18 2 779 275 412 275 NULL NULL "CH.ifa.draw.figures.ArrowTip"  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 19 "FillColor" "Color" 255 255 255 606 228 163 41 8 8  
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 21 3 559 64 594 64 594 143 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector REF 8   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 22 2 443 225 463 225 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 9  
            CH.ifa.draw.contrib.ChopPolygonConnector REF 10   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 23 3 484 214 484 203 606 203 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.contrib.ChopPolygonConnector REF 10  
            CH.ifa.draw.standard.ChopBoxConnector REF 11   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 24 3 484 237 484 248 606 248 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.contrib.ChopPolygonConnector REF 10  
            CH.ifa.draw.standard.ChopBoxConnector REF 13   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 25 3 378 333 378 333 333 333 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 7 "FillColor" "Color" 255 255 255 313 323 20 20    
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 35 "FillColor" "Color" 0 0 0 429 318 14 14  
        CH.ifa.draw.contrib.DiamondFigure "attributes" "attributes" 2 "FigureWithID" "Int" 36 "FillColor" "Color" 255 255 255 463 314 42 23  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 37 "FillColor" "Color" 255 255 255 606 283 163 41 8 8  
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 38 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 255 255 611 286 "First\n\nentry / downButton.disable()" "SansSerif" 0 12 0 NULL NULL
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 39 "FillColor" "Color" 255 255 255 606 328 163 41 8 8  
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 40 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 255 255 611 331 "NotFirst\n\nentry / downButton.enable() " "SansSerif" 0 12 0 NULL NULL
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 41 2 443 325 463 325 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 35  
            CH.ifa.draw.contrib.ChopPolygonConnector REF 36   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 42 3 484 314 484 303 606 303 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.contrib.ChopPolygonConnector REF 36  
            CH.ifa.draw.standard.ChopBoxConnector REF 37   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 43 3 484 337 484 348 606 348 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.contrib.ChopPolygonConnector REF 36  
            CH.ifa.draw.standard.ChopBoxConnector REF 39   
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 49 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 528 347 "[else]" "SansSerif" 0 12 0 REF 49 
            CH.ifa.draw.standard.OffsetLocator -2 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 48 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 519 286 "[index=0]" "SansSerif" 0 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator -2 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 47 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 528 247 "[else]" "SansSerif" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator -2 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 14 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 255 255 417 145 "SomeSelection\n\nentry / removeButton.enable()                                                                  " "SansSerif" 0 12 0 NULL NULL
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 50 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 255 255 414 179 23 19  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 46 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 492 186 "[index=list.size()-1]" "SansSerif" 0 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator -2 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 17 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 255 255 611 185 "Last\n\nentry / downButton.disable()" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 20 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 255 255 611 230 "NotLast\n\nentry / downButton.enable() " "SansSerif" 0 12 0 NULL NULL
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 54 3 491 143 485 136 485 112 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        CH.ifa.draw.figures.LineConnection "attributes" "attributes" 1 "FigureWithID" "Int" 57 5 701 143 701 143 701 112 671 112 655 143 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 8   REF 34 
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 6 "FillColor" "Color" 0 0 0 316 326 14 14  
        CH.ifa.draw.figures.ImageFigure "attributes" "attributes" 1 "FigureWithID" "Int" 65 10 128 356 141 "ToDo-List.gif"  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 340 314 "close" "SansSerif" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 0 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 11 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 255 255 416 23 "NoSelection\n\nentry /\n  removeButton.disable();\n  upButton.disable();\n  downButton.disable()" "SansSerif" 0 12 0 NULL NULL
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 58 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 625 96 "select(index) [index>=0]" "SansSerif" 0 12 0 REF 73 
            CH.ifa.draw.standard.OffsetLocator 11 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 53 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 564 47 "select(index) [index>=0]" "SansSerif" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 52 -48 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 55 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 414 121 "select(index) [index<0]" "SansSerif" 0 12 0 REF 69 
            CH.ifa.draw.standard.OffsetLocator -13 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    NULL  -2 151 836 446 