6 
    de.renew.gui.CPNDrawing 39 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 146 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 "Visibility" "Boolean" "TRUE" 81 137 "q" "Helvetica" 0 12 0 
            de.renew.gui.InhibitorConnection "attributes" "attributes" 2 "FigureWithID" "Int" 25 "Visibility" "Boolean" "TRUE" 2 83 172 83 123 
                de.renew.gui.CircleDecoration  
                de.renew.gui.CircleDecoration  
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 15 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 27 172 113 20 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FigureWithID" "Int" 4 "MarkingAppearance" "Int" 1 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 73 103 20 20 NULL    
            CH.ifa.draw.standard.OffsetLocator 1 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 148 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 "Visibility" "Boolean" "TRUE" 116 102 "p" "Helvetica" 0 12 0 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 47 "Visibility" "Boolean" "TRUE" 2 138 113 93 113 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 46 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 138 103 67 20 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 8   
            CH.ifa.draw.standard.OffsetLocator 4 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 85 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 "Visibility" "Boolean" "TRUE" 80 76 "p" "Helvetica" 0 12 0 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 5 "Visibility" "Boolean" "TRUE" 2 83 61 83 104 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 3 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 50 41 67 20 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 8   
            CH.ifa.draw.standard.OffsetLocator 0 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 23 REF 8 REF 20 REF 6 REF 2 REF 15 REF 12 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 48 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 145 106 "stock_up" "Helvetica" 1 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 39 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 58 44 "get_item" "Helvetica" 1 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 108 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 274 41 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 109 "Visibility" "Boolean" "TRUE" 2 232 51 275 51 NULL NULL 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 164 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 192 192 192 "Visibility" "Boolean" "TRUE" 136 41 96 20 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 33   
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 54 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 19 111 "[Product]" "Helvetica" 0 12 0 REF 8
            CH.ifa.draw.standard.OffsetLocator -39 5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 7 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 36 95 "Stock" "Helvetica" 1 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator -31 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 34 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 80 78 "#1" "Helvetica" 0 9 0 REF 20
            CH.ifa.draw.standard.OffsetLocator 1 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 63 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 115 107 "#1" "Helvetica" 0 9 0 REF 12
            CH.ifa.draw.standard.OffsetLocator 4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 163 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 298 56 "[Product]" "Helvetica" 0 12 0 REF 33
            CH.ifa.draw.standard.OffsetLocator 39 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 36 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 35 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 141 44 "report_existing" "Helvetica" 1 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 156 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 250 45 "#1" "Helvetica" 0 9 0 REF 34
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 168 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 62 23 ":get(q,q+p)" "Helvetica" 0 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 8 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 37 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 137 85 ":stockup( p )" "Helvetica" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -1 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 162 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 300 26 "existing\nProducts" "Helvetica" 1 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator 42 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 36 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 143 21 ":exists( p )" "Helvetica" 0 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator -13 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 38 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 38 195 ":unavailable( q )" "Helvetica" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator -2 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 165 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 157 4 "[Link\n param: [Exists prod:#1]]" "Helvetica" 0 12 0 REF 36
            CH.ifa.draw.standard.OffsetLocator -1 -29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 43 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 208 93 "[Link\n param: [StockUp prod:#1]]" "Helvetica" 0 12 0 REF 15
            CH.ifa.draw.standard.OffsetLocator 67 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 42 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 142 164 "[Link\n param: [Unavailable prod:#1]]" "Helvetica" 0 12 0 REF 6
            CH.ifa.draw.standard.OffsetLocator 97 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 40 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 31 174 "report_unavailable" "Helvetica" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 31 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 118 235 "[Perfume\n serialno:(\"123\")\n name: (\"beauty\")\n price: (123.45)\n brand: (\"bubui\")]" "Helvetica" 0 9 0 REF 8
            CH.ifa.draw.standard.OffsetLocator 87 159 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 114 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 239 231 "[Perfume\n serialno:(\"4711\")\n name: (\"smeller\")\n price: (49.44)\n brand: (\"neavi\")]" "Helvetica" 0 9 0 REF 33
            CH.ifa.draw.standard.OffsetLocator 4 217 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 113 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 339 231 "[Perfume\n serialno:(\"123\")\n name: (\"beauty\")\n price: (123.45)\n brand: (\"bubui\")]" "Helvetica" 0 9 0 REF 33
            CH.ifa.draw.standard.OffsetLocator 107 217 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 115 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 240 310 "[BodyLotion\n serialno: (\"BL6\")\n name: (\"Pflegi\")\n price: (12.99)]" "Helvetica" 0 9 0 REF 33
            CH.ifa.draw.standard.OffsetLocator 5 289 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 92 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "FALSE" 18 235 "[Perfume\n serialno:(\"4711\")\n name: (\"smeller\")\n price: (49.44)\n brand: (\"neavi\")]" "Helvetica" 0 9 0 REF 8
            CH.ifa.draw.standard.OffsetLocator -16 159 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 3 "FigureWithID" "Int" 166 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 54 4 "[Link\n param: [Get prod:#1]]" "Helvetica" 0 12 0 REF 23
            CH.ifa.draw.standard.OffsetLocator -3 -29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 116 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 "Visibility" "Boolean" "FALSE" 251 44 "p" "Helvetica" 0 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.FSFigure "attributes" "attributes" 4 "FigureWithID" "Int" 167 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 "Visibility" "Boolean" "TRUE" 79 140 "#1" "Helvetica" 0 9 0 REF 2
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  NULL  60 260 389 257 
