11 
    de.renew.gui.CPNDrawing 55 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 520 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 55 150 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 521 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 151 150 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 522 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 249 150 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 523 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 340 150 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 524 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 441 150 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 525 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 527 150 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 526 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 629 150 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 527 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 340 64 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 462 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 340 218 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 528 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 108 150 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 529 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 200 150 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 530 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 292 150 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 531 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 389 150 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 532 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 486 150 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 533 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 577 150 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 534 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 340 252 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 535 2 547 160 577 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 15   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 536 2 75 160 108 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 10   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 537 2 597 160 630 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 15  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 538 2 128 160 152 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 539 2 631 163 360 258 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector REF 16   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 540 2 171 160 200 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 11   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 541 2 340 258 74 163 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 542 2 220 160 250 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 11  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 543 2 307 150 346 83 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 12  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 544 2 269 160 292 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector REF 12   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 545 2 355 83 393 150 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 13   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 546 2 312 160 341 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 12  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 547 2 577 156 359 77 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 15  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 548 2 360 160 389 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector REF 13   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 549 2 342 225 220 164 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 9  
            CH.ifa.draw.standard.ChopBoxConnector REF 11   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 550 2 409 160 442 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 13  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 551 2 486 164 359 225 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 14  
            CH.ifa.draw.figures.ChopEllipseConnector REF 9   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 552 2 461 160 486 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 14   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 553 2 342 77 128 156 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 10   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 554 2 506 160 528 160 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 14  
            CH.ifa.draw.figures.ChopEllipseConnector REF 6   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 555 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 583 133 "t6" "SansSerif" 1 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 1 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 556 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 630 133 "p8" "SansSerif" 1 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -2 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 557 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 69 131 "p1" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 11 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 558 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 437 134 "p5" "SansSerif" 1 12 0 REF 5 
            CH.ifa.draw.standard.OffsetLocator -7 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 559 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 531 168 "p6" "SansSerif" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 1 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 560 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 489 133 "t5" "SansSerif" 1 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator -2 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 561 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 116 133 "t1" "SansSerif" 1 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 3 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 562 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 205 133 "t2" "SansSerif" 1 12 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 563 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 258 134 "p3" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 6 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 564 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 298 174 "t3" "SansSerif" 1 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 1 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 565 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 395 173 "t4" "SansSerif" 1 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 1 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 566 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 161 172 "p2" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 7 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 567 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 364 59 "p7" "SansSerif" 1 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 21 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 568 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 343 201 "p9" "SansSerif" 1 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 569 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 367 258 "t7" "SansSerif" 1 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 22 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 570 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 341 134 "p4" "SansSerif" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -2 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 578 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 347 66 "[]" "SansSerif" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 579 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 636 152 "[]" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 580 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 347 220 "[]" "SansSerif" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  27 514 720 411 