11 
    de.renew.gui.CPNDrawing 282 
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71017 "FrameColor" "Color" 255 199 158 255 "FontName" "String" "Arial" "FillColor" "Color" 153 153 255 255 286 48 924 430 8 8  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71018 "FrameColor" "Color" 255 199 158 255 "FontName" "String" "Arial" "FillColor" "Color" 255 102 102 255 439 207 101 122  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71019 "FrameColor" "Color" 255 199 158 255 "FontName" "String" "Arial" "FillColor" "Color" 153 153 255 255 26 145 227 228 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71020 "FrameColor" "Color" 255 199 158 255 "FontName" "String" "Arial" "FillColor" "Color" 153 153 255 255 975 1102 1076 572 8 8  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 71021 "FrameColor" "Color" 255 199 158 255 "FontName" "String" "Arial" 1189 1407 578 95  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 71022 "FrameColor" "Color" 255 199 158 255 "FontName" "String" "Arial" 1189 1467 382 163  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71023 "FrameColor" "Color" 255 199 158 255 "FontName" "String" "Arial" "FillColor" "Color" 153 153 255 255 736 531 1093 532 8 8  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 71024 "FrameColor" "Color" 255 199 158 255 "FontName" "String" "Arial" 822 764 396 252  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71025 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 873 400 77 47 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71026 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 883 408 "determine\nsubtasks" "Arial" 1 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71027 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 316 206 62 22 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71028 "FontName" "String" "Arial" 2 135 217 317 217 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71030 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 99 207 36 22 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 13   
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71029 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 255 0 255 155 275 20 20 NULL  REF 17 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71031 "FontName" "String" "Arial" 2 124 229 160 278 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 17  
            CH.ifa.draw.figures.ChopEllipseConnector REF 19   
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71032 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1057 194 62 22 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71033 "FontName" "String" "Arial" 2 378 217 449 217 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 13  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71141 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 102 102 255 449 210 47 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71034 "FontName" "String" "Arial" 2 496 316 633 316 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71142 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 102 102 255 449 309 47 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71035 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 632 305 62 22 NULL    REF 35 
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71036 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 255 0 255 572 253 20 20 NULL REF 19  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71037 "FontName" "String" "Arial" 2 574 260 492 226 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 36  
            CH.ifa.draw.standard.ChopBoxConnector REF 29   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71038 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 58 191 ":new(teamID,pos,task,org,dir)" "Arial" 0 9 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 3 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71039 "FontName" "String" "Arial" 2 911 447 911 646 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 9  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71040 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 901 645 20 20 NULL    REF 47 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71041 "FontName" "String" "Arial" 2 921 655 1219 655 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 47  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71042 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 102 102 255 1219 627 114 58 NULL    REF 52 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71043 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1035 649 "[pos,task,impl,{}]" "Arial" 0 9 0 REF 48 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71044 "FontName" "String" "Arial" 2 1275 685 1275 753 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 52  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71045 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1265 752 20 20 NULL    REF 60 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71046 "FontName" "String" "Arial" 2 1267 766 1150 815 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 60  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71047 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1126 813 24 16 NULL    REF 65 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71048 "FontName" "String" "Arial" 3 921 893 1065 893 1129 829 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71052 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 901 883 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 65   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71049 "FontName" "String" "Arial" 2 911 665 911 787 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 47  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71050 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 899 787 24 16 NULL    REF 75 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71051 "FontName" "String" "Arial" 2 911 803 911 884 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 75  
            CH.ifa.draw.figures.ChopEllipseConnector REF 69   REF 69 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71053 "FontName" "String" "Arial" 3 1126 821 1012 821 919 888 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 65  
            CH.ifa.draw.figures.ChopEllipseConnector REF 69   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71054 "FontName" "String" "Arial" 3 920 896 1016 928 1071 928 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 69  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71055 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 102 102 255 1071 911 139 34 NULL    REF 88 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71056 "FontName" "String" "Arial" 3 1187 911 1275 879 1275 772 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 88  
            CH.ifa.draw.figures.ChopEllipseConnector REF 60   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71057 "FontName" "String" "Arial" 2 1284 766 1401 815 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 60  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71058 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1401 813 24 16 NULL    REF 97 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71059 "FontName" "String" "Arial" 2 116 229 116 276 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 17  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71060 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 235 199 158 255 106 275 20 20 NULL    REF 102 
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71061 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 235 199 158 255 1402 762 20 20 NULL REF 102  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71062 "FontName" "String" "Arial" 2 1412 782 1412 813 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 103  
            CH.ifa.draw.standard.ChopBoxConnector REF 97   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71063 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1402 791 "rtask" "Arial" 0 9 0 REF 104 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71064 "FontName" "String" "Arial" 2 1413 829 1413 1235 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 97  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71065 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1403 1234 20 20 NULL    REF 114 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71066 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 859 906 "waiting\nsuper teams" "Arial" 1 12 0 REF 69 
            CH.ifa.draw.standard.OffsetLocator -16 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71067 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1581 1170 136 32 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71068 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1602 1545 44 41 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71069 "FontName" "String" "Arial" 2 1624 1585 1624 1622 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 119  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71070 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1612 1622 24 16 NULL    REF 124 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71071 "FontName" "String" "Arial" 2 1636 1630 1788 1630 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 124  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71072 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 255 255 255 1787 1620 20 20 NULL    REF 129 
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 71073 "BSplineDegree" "Int" 2 "FontName" "String" "Arial" "LineShape" "Int" 0 "BSplineSegments" "Int" 15 4 1333 679 1352 687 1503 687 1547 659 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 52  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71074 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1544 644 20 20 NULL    REF 134 
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 71075 "BSplineDegree" "Int" 2 "FontName" "String" "Arial" "LineShape" "Int" 0 "BSplineSegments" "Int" 15 4 1546 650 1500 622 1366 622 1333 634 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 134  
            CH.ifa.draw.standard.ChopBoxConnector REF 52   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71076 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1551 648 "{}" "Arial" 0 9 0 REF 134 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71077 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 255 0 255 1265 583 20 20 NULL REF 19  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71078 "FontName" "String" "Arial" 2 1275 603 1275 627 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 142  
            CH.ifa.draw.standard.ChopBoxConnector REF 52   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71079 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1261 609 "[id,org]" "Arial" 0 9 0 REF 143 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71080 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1583 1642 "dwf:finishDWF();\n:finishTW(dwf)" "Arial" 0 9 0 REF 124 
            CH.ifa.draw.standard.OffsetLocator -5 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71081 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1678 1623 "[teamservice,dwf]" "Arial" 0 9 0 REF 125 
            CH.ifa.draw.standard.OffsetLocator 4 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71082 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 108 246 "task" "Arial" 0 9 0 REF 98 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71083 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 141 244 "[teamID,org]" "Arial" 0 9 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 25 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71084 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 866 718 "[pos,task,impl,{st:sts}]" "Arial" 0 9 0 REF 71 
            CH.ifa.draw.standard.OffsetLocator 2 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71085 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 813 636 "team structure" "Arial" 1 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator -56 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71086 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 923 773 "select inner team" "Arial" 1 12 0 REF 75 
            CH.ifa.draw.standard.OffsetLocator 61 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71087 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1614 1409 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71088 "FontName" "String" "Arial" 2 1624 1429 1624 1470 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 170  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71089 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1612 1470 24 16 NULL    REF 175 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71090 "FontName" "String" "Arial" 2 1624 1486 1624 1546 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 175  
            CH.ifa.draw.figures.ChopEllipseConnector REF 119   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71091 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 102 102 255 1357 1463 113 31 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71092 "FontName" "String" "Arial" 2 1521 1478 1470 1478 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71104 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1520 1468 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 180   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71093 "FontName" "String" "Arial" 3 1466 1494 1518 1509 1527 1487 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 180  
            CH.ifa.draw.figures.ChopEllipseConnector REF 184   
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71094 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1403 1550 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71095 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1410 1554 "{}" "Arial" 0 9 0 REF 190 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71096 "FontName" "String" "Arial" 3 1418 1552 1432 1526 1419 1494 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 190  
            CH.ifa.draw.standard.ChopBoxConnector REF 180   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71097 "FontName" "String" "Arial" 3 1405 1494 1391 1522 1409 1552 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 180  
            CH.ifa.draw.figures.ChopEllipseConnector REF 190   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71098 "FontName" "String" "Arial" 2 1540 1478 1612 1478 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 184  
            CH.ifa.draw.standard.ChopBoxConnector REF 175   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71099 "FontName" "String" "Arial" 3 1423 1560 1492 1560 1612 1485 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 190  
            CH.ifa.draw.standard.ChopBoxConnector REF 175   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71100 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1395 1574 "controlers of\nteam agents" "Arial" 1 12 0 REF 190 
            CH.ifa.draw.standard.OffsetLocator 18 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71101 "FontName" "String" "Arial" 2 1413 1463 1413 1254 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 180  
            CH.ifa.draw.figures.ChopEllipseConnector REF 114   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71102 "FontName" "String" "Arial" 2 1549 662 1419 813 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 134  
            CH.ifa.draw.standard.ChopBoxConnector REF 97   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71103 "FontName" "String" "Arial" 3 1418 829 1530 987 1530 1469 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 97  
            CH.ifa.draw.figures.ChopEllipseConnector REF 184   REF 184 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71105 "FontName" "String" "Arial" 3 1423 829 1649 994 1649 1118 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 97  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71106 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1639 1117 20 20 NULL    REF 228 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71107 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1615 1440 "dwf" "Arial" 0 9 0 REF 171 
            CH.ifa.draw.standard.OffsetLocator -2 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 71108 "BSplineDegree" "Int" 2 "FontName" "String" "Arial" "LineShape" "Int" 0 "BSplineSegments" "Int" 15 4 1316 685 1375 727 1615 727 1679 663 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 52  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71109 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1675 646 20 20 NULL    REF 236 
        de.renew.gui.ArcConnection "attributes" "attributes" 5 "FigureWithID" "Int" 71110 "BSplineDegree" "Int" 2 "FontName" "String" "Arial" "LineShape" "Int" 0 "BSplineSegments" "Int" 15 4 1680 649 1625 583 1367 583 1312 627 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 236  
            CH.ifa.draw.standard.ChopBoxConnector REF 52   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71111 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1682 650 "{}" "Arial" 0 9 0 REF 236 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71112 "FontName" "String" "Arial" 3 1685 666 1685 820 1425 820 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 236  
            CH.ifa.draw.standard.ChopBoxConnector REF 97   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71113 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1403 1385 "plan" "Arial" 0 9 0 REF 213 
            CH.ifa.draw.standard.OffsetLocator -2 33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71114 "FontName" "String" "Arial" 2 1649 1137 1649 1170 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 228  
            CH.ifa.draw.standard.ChopBoxConnector REF 118   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71115 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1434 818 "get compromise \nat the root" "Arial" 1 12 0 REF 97 
            CH.ifa.draw.standard.OffsetLocator 69 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71116 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1394 748 "root task" "Arial" 1 12 0 REF 103 
            CH.ifa.draw.standard.OffsetLocator 7 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71117 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1435 1528 "ctrls" "Arial" 0 9 0 REF 194 
            CH.ifa.draw.standard.OffsetLocator 19 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71118 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1020 860 "[{teamroot,subteams},\n{task:ts},plans]" "Arial" 0 9 0 REF 66 
            CH.ifa.draw.standard.OffsetLocator 41 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71119 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1049 946 ":getOpaForPosition(pos,opa);\nopa:makeCompromise(task,impl,plans,plan)" "Arial" 0 9 0 REF 88 
            CH.ifa.draw.standard.OffsetLocator 0 30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71120 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1273 806 "[team,\n{},plan]" "Arial" 0 9 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator 56 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71121 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 946 899 "[team,\n{},plans]" "Arial" 0 9 0 REF 84 
            CH.ifa.draw.standard.OffsetLocator -32 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71122 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 865 835 "[{{pos,task,impl}, {}},\n{st:sts},{}]" "Arial" 0 9 0 REF 76 
            CH.ifa.draw.standard.OffsetLocator -3 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71123 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1303 781 "[{{pos,rtask,impl},\nsubteams}, {}, plan]" "Arial" 0 9 0 REF 93 
            CH.ifa.draw.standard.OffsetLocator 2 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71124 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 255 0 255 1564 1279 20 20 NULL REF 19  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71125 "FontName" "String" "Arial" 2 1582 1294 1623 1320 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 282  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71170 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1581 1320 136 32 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71126 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1640 1143 "roles" "Arial" 0 9 0 REF 251 
            CH.ifa.draw.standard.OffsetLocator 1 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71127 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1594 1171 "compose DWF from\nrole fragments" "Arial" 1 12 0 REF 118 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71128 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1473 1446 "{[roles,pos]:\nmembers}" "Arial" 0 9 0 REF 181 
            CH.ifa.draw.standard.OffsetLocator 3 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71129 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1339 1535 "{[roles,ctrl]\n:ctrls}" "Arial" 0 9 0 REF 198 
            CH.ifa.draw.standard.OffsetLocator -39 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71130 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1642 1446 "attach controlers\nto DWF" "Arial" 1 12 0 REF 175 
            CH.ifa.draw.standard.OffsetLocator 67 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71131 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1163 780 "[{{pos,task,impl},subs},\n{},plan]" "Arial" 0 9 0 REF 61 
            CH.ifa.draw.standard.OffsetLocator 3 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71132 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1089 777 "process\nsubteam p" "Arial" 1 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator -19 -29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71133 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 921 811 "[{teamroot,{{{pos,task,impl},subs}:subteams}},\nts,{plan:plans}]" "Arial" 0 9 0 REF 80 
            CH.ifa.draw.standard.OffsetLocator -5 -31 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71134 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1577 1469 "{}" "Arial" 0 9 0 REF 202 
            CH.ifa.draw.standard.OffsetLocator 4 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71135 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 255 255 255 1668 1408 20 20 NULL REF 129  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71136 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1813 1622 "log" "Arial" 1 12 0 REF 129 
            CH.ifa.draw.standard.OffsetLocator 24 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71137 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1698 1412 "log" "Arial" 1 12 0 REF 314 
            CH.ifa.draw.standard.OffsetLocator 28 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71138 "FontName" "String" "Arial" 3 1788 1632 1711 1652 1636 1633 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 129  
            CH.ifa.draw.standard.ChopBoxConnector REF 124   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71139 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1686 1647 "teamservice" "Arial" 0 9 0 REF 321 
            CH.ifa.draw.standard.OffsetLocator 0 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71140 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1586 1621 "stop" "Arial" 1 12 0 REF 124 
            CH.ifa.draw.standard.OffsetLocator -26 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 29 REF 33 
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71143 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 466 262 13 13 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71144 "FontName" "String" "Arial" 2 472 226 472 263 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 29  
            CH.ifa.draw.figures.ChopEllipseConnector REF 331   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71145 "FontName" "String" "Arial" 2 472 274 472 309 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 331  
            CH.ifa.draw.standard.ChopBoxConnector REF 33   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71146 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 451 281 "[task,pos]" "Arial" 0 9 0 REF 336 
            CH.ifa.draw.standard.OffsetLocator 0 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71147 "FontName" "String" "Arial" 2 574 267 488 309 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 36  
            CH.ifa.draw.standard.ChopBoxConnector REF 33   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71148 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1672 1117 "roles of final agents" "Arial" 1 12 0 REF 228 
            CH.ifa.draw.standard.OffsetLocator 79 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71149 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 103 296 "root\ntask" "Arial" 1 12 0 REF 102 
            CH.ifa.draw.standard.OffsetLocator -1 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71150 "FontName" "String" "Arial" 2 108 229 69 278 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 17  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71151 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 0 255 0 255 53 275 20 20 NULL    REF 356 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71152 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 80 247 "dir" "Arial" 0 9 0 REF 352 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71153 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 50 297 "spec\ndir" "Arial" 1 12 0 REF 356 
            CH.ifa.draw.standard.OffsetLocator 1 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71154 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 149 296 "organization\nmodel" "Arial" 1 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator 19 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71155 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 0 255 0 255 1564 1243 20 20 NULL REF 356  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71156 "FontName" "String" "Arial" 2 1581 1247 1631 1202 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 366  
            CH.ifa.draw.standard.ChopBoxConnector REF 118   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71157 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1601 1218 "dir" "Arial" 0 9 0 REF 367 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71158 "FontName" "String" "Arial" 2 1717 1186 1806 1186 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 118  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71159 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1805 1176 20 20 NULL    REF 377 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71160 "FontName" "String" "Arial" 2 1654 1352 1676 1410 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 286  
            CH.ifa.draw.figures.ChopEllipseConnector REF 314   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71161 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1655 1375 "dwfName" "Arial" 0 9 0 REF 378 
            CH.ifa.draw.standard.OffsetLocator 10 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FigureWithID" "Int" 71162 "FrameColor" "Color" 255 0 0 255 "FontName" "String" "Arial" "FontSize" "Int" 9 "FillColor" "Color" 255 200 0 255 1925 1157 70 59 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71163 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1935 1163 "show\nabstract\nDWF" "Arial" 1 13 0 REF 385 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71164 "FontName" "String" "Arial" 2 1825 1186 1925 1186 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 377  
            CH.ifa.draw.standard.ChopBoxConnector REF 385   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71165 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1731 1181 "abstractDWF" "Arial" 0 9 0 REF 373 
            CH.ifa.draw.standard.OffsetLocator -2 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71166 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1843 1181 "abstractDWF" "Arial" 0 9 0 REF 389 
            CH.ifa.draw.standard.OffsetLocator -4 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71167 "FontName" "String" "Arial" 2 1644 1352 1627 1410 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 286  
            CH.ifa.draw.figures.ChopEllipseConnector REF 170   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71168 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1623 1375 "dwf" "Arial" 0 9 0 REF 399 
            CH.ifa.draw.standard.OffsetLocator -5 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71169 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1638 1479 "dwf:addControlers(ctrls);" "Arial" 0 9 0 REF 175 
            CH.ifa.draw.standard.OffsetLocator 65 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 286 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71171 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1592 1321 "generate executable\nDWF and activate" "Arial" 1 12 0 REF 286 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71172 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1689 1145 "action abstractDWF=DWFCompositor.\ncomposeDWFFromRoleFragments(dir, roles);" "Arial" 0 9 0 REF 118 
            CH.ifa.draw.standard.OffsetLocator 135 -29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71173 "FontName" "String" "Arial" 2 1648 1202 1648 1242 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 118  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71174 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1638 1241 20 20 NULL    REF 419 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71175 "FontName" "String" "Arial" 2 1648 1261 1648 1320 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 419  
            CH.ifa.draw.standard.ChopBoxConnector REF 286   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71176 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1405 1046 "plan" "Arial" 0 9 0 REF 110 
            CH.ifa.draw.standard.OffsetLocator 0 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71177 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1620 1217 "abstractDWF" "Arial" 0 9 0 REF 415 
            CH.ifa.draw.standard.OffsetLocator 0 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71178 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1620 1284 "abstractDWF" "Arial" 0 9 0 REF 420 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71179 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1886 1217 "manual;\naction GuiPlugin.getCurrent().\ngetGui().openDrawing(abstractDWF)" "Arial" 0 9 0 REF 385 
            CH.ifa.draw.standard.OffsetLocator 1 49 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71180 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1797 1325 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FigureWithID" "Int" 71181 "FrameColor" "Color" 255 0 0 255 "FontName" "String" "Arial" "FontSize" "Int" 9 "FillColor" "Color" 255 200 0 255 1919 1306 92 59 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71182 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1929 1313 "show exec.\nDWF\npattern" "Arial" 1 13 0 REF 437 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71183 "FontName" "String" "Arial" 2 1717 1335 1798 1335 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 286  
            CH.ifa.draw.figures.ChopEllipseConnector REF 436   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71184 "FontName" "String" "Arial" 2 1817 1335 1919 1335 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 436  
            CH.ifa.draw.standard.ChopBoxConnector REF 437   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71185 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1887 1368 "manual;\naction GuiPlugin.getCurrent().\ngetGui().openDrawing(dwfPattern)" "Arial" 0 9 0 REF 437 
            CH.ifa.draw.standard.OffsetLocator -8 51 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71186 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1679 1261 "action dwfPattern=ExecutableDWFGenerator.\ngenerateExecutableDWF(abstractDWF, new Vector());\naction dwfName=ExecutableDWFGenerator.\ninsertDWFIntoSimulation(dwfPattern, id, dir);\naction dwf=Net.forName(dwfName).buildInstance()" "Arial" 0 9 0 REF 286 
            CH.ifa.draw.standard.OffsetLocator 143 -45 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71187 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1735 1329 "dwfPattern" "Arial" 0 9 0 REF 441 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71188 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1846 1329 "dwfPattern" "Arial" 0 9 0 REF 445 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71189 "FontName" "String" "Arial" 2 1581 1260 1634 1320 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 366  
            CH.ifa.draw.standard.ChopBoxConnector REF 286   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71190 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1602 1284 "dir" "Arial" 0 9 0 REF 461 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71191 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1616 1516 "dwf" "Arial" 0 9 0 REF 176 
            CH.ifa.draw.standard.OffsetLocator -1 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71192 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1617 1596 "dwf" "Arial" 0 9 0 REF 120 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71193 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1650 1537 "ongoing team DWF\ninteraction" "Arial" 1 21 0 REF 119 
            CH.ifa.draw.standard.OffsetLocator 123 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71194 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1458 753 "roles" "Arial" 0 9 0 REF 216 
            CH.ifa.draw.standard.OffsetLocator -16 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71195 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1305 1236 "global team plan" "Arial" 1 12 0 REF 114 
            CH.ifa.draw.standard.OffsetLocator -62 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71196 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1509 1047 "rolepos" "Arial" 0 9 0 REF 220 
            CH.ifa.draw.standard.OffsetLocator 50 -96 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71197 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1639 1048 "roles" "Arial" 0 9 0 REF 224 
            CH.ifa.draw.standard.OffsetLocator 113 81 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71198 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1568 642 "roles of\n final agents" "Arial" 1 12 0 REF 134 
            CH.ifa.draw.standard.OffsetLocator 48 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71199 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1435 616 "roles" "Arial" 0 9 0 REF 135 
            CH.ifa.draw.standard.OffsetLocator 6 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71200 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1424 680 "{role:roles}" "Arial" 0 9 0 REF 130 
            CH.ifa.draw.standard.OffsetLocator 6 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71201 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1624 814 "rolepos" "Arial" 0 9 0 REF 244 
            CH.ifa.draw.standard.OffsetLocator 84 77 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71202 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1239 709 "[{{pos,task,impl},\n{}}, {}, plan]" "Arial" 0 9 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator -1 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71203 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1543 722 "{[role,pos]:rps}" "Arial" 0 9 0 REF 232 
            CH.ifa.draw.standard.OffsetLocator 76 33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71204 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1558 576 "rps" "Arial" 0 9 0 REF 237 
            CH.ifa.draw.standard.OffsetLocator 68 -34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71205 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1700 642 "role/position \nof final agents" "Arial" 1 12 0 REF 236 
            CH.ifa.draw.standard.OffsetLocator 55 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.RectangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 71206 "FontName" "String" "Arial" "FillColor" "Color" 255 102 102 255 34 586 168 63  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71207 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 45 594 "connection\npoints for OPAs" "Arial" 1 19 0 REF 512 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71208 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 803 195 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71209 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 109 211 "init" "Arial" 1 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 71210 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 153 153 153 255 "FillColor" "Color" 255 199 158 255 294 49 "team formation" "Arial" 0 29 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 71211 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 293 47 "team formation" "Arial" 0 29 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 71212 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 153 153 153 255 "FillColor" "Color" 255 199 158 255 37 147 "init" "Arial" 0 29 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 71213 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 36 145 "init" "Arial" 0 29 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 71214 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 153 153 153 255 "FillColor" "Color" 255 199 158 255 751 536 "team plan\nformation" "Arial" 0 29 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 71215 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 750 533 "team plan\nformation" "Arial" 0 29 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71216 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1080 912 "calculate partial plan\nfrom subteams' plans" "Arial" 1 12 0 REF 88 
            CH.ifa.draw.standard.OffsetLocator 2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "FigureWithID" "Int" 71217 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 153 153 153 255 "FillColor" "Color" 255 199 158 255 986 1107 "localize team plan and execute" "Arial" 0 29 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 71218 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 985 1105 "localize team plan and execute" "Arial" 0 29 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71219 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1362 1464 "generate controler\nfrom plan" "Arial" 1 12 0 REF 180 
            CH.ifa.draw.standard.OffsetLocator 2 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71220 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1480 1496 "members" "Arial" 0 9 0 REF 186 
            CH.ifa.draw.standard.OffsetLocator 3 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71221 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1518 1538 "ctrls" "Arial" 0 9 0 REF 206 
            CH.ifa.draw.standard.OffsetLocator 10 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71222 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1536 1427 "DWF roles\nwithout\ncontroler" "Arial" 1 12 0 REF 184 
            CH.ifa.draw.standard.OffsetLocator 35 -29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71223 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1227 633 "generate a\nlocal plan for \na final team agent" "Arial" 1 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator 1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71225 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1290 733 "partial plans\nof subteams" "Arial" 1 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator 50 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71226 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1587 1304 "[id,org]" "Arial" 0 9 0 REF 283 
            CH.ifa.draw.standard.OffsetLocator -1 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71227 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1258 552 "org.\nmodel" "Arial" 1 12 0 REF 142 
            CH.ifa.draw.standard.OffsetLocator 0 -26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71228 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1203 1483 ":getOpaForPosition(pos,opa);\nopa:controlerForRolesInPlan(plan,roles,ctrl);" "Arial" 0 9 0 REF 180 
            CH.ifa.draw.standard.OffsetLocator -119 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 71229 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 112 219 147 255 1165 1393 "localise team plan:\ngenerate controlers" "Arial" 1 18 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71232 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 390 212 "[task,pos]" "Arial" 0 9 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator -2 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71233 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 453 236 "[task,pos]" "Arial" 0 9 0 REF 332 
            CH.ifa.draw.standard.OffsetLocator 2 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71234 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 102 102 255 486 249 "select\n impl." "Arial" 1 14 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 18 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71235 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 462 211 "call" "Arial" 1 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71236 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 457 309 "return" "Arial" 1 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator 2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71237 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 592 250 "org.\nmodel" "Arial" 1 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 27 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71238 "FontName" "String" "Arial" 2 676 307 722 272 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 35  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71239 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 710 241 67 31 NULL    REF 581 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71240 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 668 283 "[task,pos,impl]" "Arial" 0 9 0 REF 577 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71241 "FontName" "String" "Arial" 2 764 241 806 211 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 581  
            CH.ifa.draw.figures.ChopEllipseConnector REF 516   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71242 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 750 221 "[task,pos,impl]" "Arial" 0 9 0 REF 585 
            CH.ifa.draw.standard.OffsetLocator -4 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71243 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 873 182 77 47 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71244 "FontName" "String" "Arial" 2 823 205 873 205 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 516  
            CH.ifa.draw.standard.ChopBoxConnector REF 592   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71245 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 831 191 "[task,\npos,\nimpl]" "Arial" 0 9 0 REF 593 
            CH.ifa.draw.standard.OffsetLocator -5 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71246 "FontName" "String" "Arial" 2 677 326 720 358 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 35  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71253 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 688 358 110 32 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71247 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 663 336 "[task,pos,impl]" "Arial" 0 9 0 REF 600 
            CH.ifa.draw.standard.OffsetLocator -4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71248 "FontName" "String" "Arial" 2 950 205 1058 205 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 592  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71249 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 882 183 "determine\ndelegation\npartner" "Arial" 1 12 0 REF 592 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71250 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 830 152 "org:getDelegationForPosAndTaskAndImpl\n(pos,task,impl,deleg)" "Arial" 0 9 0 REF 592 
            CH.ifa.draw.standard.OffsetLocator 5 -41 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71251 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 978 199 "[task,deleg]" "Arial" 0 9 0 REF 608 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71252 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 714 241 "is\ndelegation" "Arial" 1 12 0 REF 581 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 604 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71254 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 693 359 "is not delegation\n(but exec. or split)" "Arial" 1 12 0 REF 604 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71255 "FontName" "String" "Arial" 2 765 390 806 418 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 604  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71256 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 803 413 20 20 NULL    REF 631 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71257 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 751 397 "[task,pos,impl]" "Arial" 0 9 0 REF 627 
            CH.ifa.draw.standard.OffsetLocator -3 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71258 "FontName" "String" "Arial" 2 823 423 873 423 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 631  
            CH.ifa.draw.standard.ChopBoxConnector REF 9   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71259 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 695 301 "implementation\nfor task" "Arial" 1 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator 76 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71260 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 836 405 "[task,\npos,\nimpl]" "Arial" 0 9 0 REF 635 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71261 "FontName" "String" "Arial" 2 950 423 1017 423 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 9  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71262 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1016 413 20 20 NULL    REF 649 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71263 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 961 411 "[subtasks,\npos]" "Arial" 0 9 0 REF 645 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71264 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 255 255 0 255 901 300 20 20 NULL REF 19  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71265 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 930 294 "org.\nmodel" "Arial" 1 12 0 REF 653 
            CH.ifa.draw.standard.OffsetLocator 36 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71266 "FontName" "String" "Arial" 2 911 301 911 229 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 653  
            CH.ifa.draw.standard.ChopBoxConnector REF 592   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71267 "FontName" "String" "Arial" 2 911 320 911 400 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 653  
            CH.ifa.draw.standard.ChopBoxConnector REF 9   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71268 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 897 259 "[id,org]" "Arial" 0 9 0 REF 657 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71269 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 897 354 "[id,org]" "Arial" 0 9 0 REF 660 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71270 "FontName" "String" "Arial" 2 1033 417 1080 364 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 649  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 71271 "FrameColor" "Color" 0 0 0 255 "FontName" "String" "Arial" "FillColor" "Color" 112 219 147 255 1076 348 24 16 NULL    REF 673 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71272 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 995 383 "[{subtask:subtasks},\npos]" "Arial" 0 9 0 REF 669 
            CH.ifa.draw.standard.OffsetLocator -18 5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71273 "FontName" "String" "Arial" 3 1087 364 1087 423 1036 423 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 673  
            CH.ifa.draw.figures.ChopEllipseConnector REF 649   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71274 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1067 410 "[subtasks,\npos]" "Arial" 0 9 0 REF 677 
            CH.ifa.draw.standard.OffsetLocator 28 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 71275 "FontName" "String" "Arial" 2 1088 348 1088 216 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 673  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71276 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1060 276 "[subtask,pos]" "Arial" 0 9 0 REF 684 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71278 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 366 169 ":getOpaForPosition(pos,opa);\norg:getImplementationsForPosAndTask(pos,task,impls);\nopa:callImplSelection(id,task,impls);" "Arial" 0 9 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 11 -31 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71279 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 329 229 "open\ntasks" "Arial" 1 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator -2 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 71280 3 1088 195 1088 93 742 93 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 24  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 71281 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 718 85 24 16 NULL    REF 701 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 71282 3 718 93 347 93 347 207 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 701  
            CH.ifa.draw.figures.ChopEllipseConnector REF 13   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71283 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 388 331 ":getOpaForPosition(pos,opa);\nopa:returnImplSelection(id,task,impl);\norg:validImplementation(pos,task,impl);" "Arial" 0 9 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator -2 32 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71284 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 529 281 "[id,org]" "Arial" 0 9 0 REF 343 
            CH.ifa.draw.standard.OffsetLocator 12 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71285 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 534 235 "[id,org]" "Arial" 0 9 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator 15 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71286 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 546 310 "[task,pos,impl]" "Arial" 0 9 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 13 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71287 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 906 87 "[task,pos]" "SansSerif" 0 9 0 REF 697 
            CH.ifa.draw.standard.OffsetLocator 15 -51 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71289 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 817 451 "org:subtasks\n(task,impl,subtasks)" "Arial" 0 9 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -52 40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71290 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 742 263 "guard\n(impl.contains(\"delegate\"))" "Arial" 0 9 0 REF 581 
            CH.ifa.draw.standard.OffsetLocator 53 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71291 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 740 332 "guard\n(! impl.contains(\"delegate\"))" "Arial" 0 9 0 REF 604 
            CH.ifa.draw.standard.OffsetLocator 54 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71292 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 850 501 "[pos,task,impl,subtasks]" "SansSerif" 0 9 0 REF 43 
            CH.ifa.draw.standard.OffsetLocator -3 -39 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 71293 2 1026 433 1026 458 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 649  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 71294 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1014 458 24 16 NULL    REF 737 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71295 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1007 439 "[{},pos]" "SansSerif" 0 9 0 REF 733 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 71302 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 32 467 "import de.renew.net.Net;\nimport de.renew.net.NetInstance;\nimport de.renew.sonarnetprototype.SonarNetPrototypeHelper;\nimport de.renew.sonarnetprototype.generation.DWFCompositor;\nimport de.renew.sonarnetprototype.generation.ExecutableDWFGenerator;\nimport java.util.Vector;\nimport de.renew.gui.GuiPlugin;" "Arial" 0 12 0 NULL NULL 1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71288 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 513 88 "[task,pos]" "SansSerif" 0 9 0 REF 702 
            CH.ifa.draw.standard.OffsetLocator 5 -56 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71277 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1125 190 "open\ntasks" "Arial" 1 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 53 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71303 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1553 1274 "org.\nmodel" "SansSerif" 1 12 0 REF 282 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71304 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1558 1238 "spec\ndir" "SansSerif" 1 12 0 REF 366 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71230 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 112 219 147 255 859 1005 "compute compromise (from partial plans)" "Arial" 1 17 0 REF 88 
            CH.ifa.draw.standard.OffsetLocator -120 87 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71231 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 249 211 "[task,pos]" "Arial" 0 9 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 44 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71224 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1075 577 "role = SonarNetPrototypeHelper.\ngetNestedTupleElementFromTupleString\n(task, \"2.0\");\n:getOpaForPosition(pos,opa);\nopa:getPlan(pos,task,plan);" "Arial" 0 9 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator -118 -49 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  106 78 1384 862 