11 
    de.renew.gui.CPNDrawing 4 
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8059 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 97 62 "superconcept\n\nvalue: String" "SansSerif" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 8134 "FillColor" "Color" 255 255 255 255 4 192 172 192 134 138 134 138 96 NULL
            de.renew.gui.IsaArrowTip 0.6 15.0 12.0 0  "de.renew.gui.IsaArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 8042 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 126 172 "some-concept\n\nanother-value: int\nsuper-copy: superconcept" "SansSerif" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 1  1  REF 5 
        de.renew.gui.DeclarationFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 8137 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 168 342 "//de.renew.agent.ontology.test;" "SansSerif" 0 12 0 NULL NULL 1  NULL  637 336 538 597 