8 
    de.renew.gui.CPNDrawing 28 
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 1 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 224 224 255 118 63 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 140 52 "[]" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 16 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3 2 128 83 128 135 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 224 224 255 116 135 24 16 NULL    REF 9 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 5 2 128 151 128 197 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 9  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 224 224 255 118 196 20 20 NULL    REF 14 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 129 167 "root" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 12 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 8 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 145 129 "root:new treemutexloc" "SansSerif" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 81 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 147 143 "root:token()" "SansSerif" 0 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 52 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 10 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 224 224 255 116 269 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 11 3 127 216 120 242 126 269 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 14  
            CH.ifa.draw.standard.ChopBoxConnector REF 24   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 12 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 86 234 "node" "SansSerif" 0 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator -23 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13 3 129 269 136 243 130 216 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 24  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14   
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 14 "MarkingAppearance" "Int" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 224 224 255 118 341 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 15 2 128 285 128 342 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 24  
            CH.ifa.draw.figures.ChopEllipseConnector REF 37   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 16 2 128 361 128 413 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 37  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 17 "FillColor" "Color" 224 224 255 116 413 24 16 NULL    REF 47 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 18 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 144 338 "[]" "SansSerif" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator 20 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 19 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 45 136 "create root" "SansSerif" 1 12 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -50 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 20 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 5 413 "stop enlargement" "SansSerif" 1 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator -68 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 21 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 37 270 "enlarge tree" "SansSerif" 1 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator -54 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 22 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 76 199 "nodes" "SansSerif" 1 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator -33 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 23 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 37 343 "may enlarge" "SansSerif" 1 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator -53 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 24 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 142 234 "newnode" "SansSerif" 0 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator 36 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 26 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 142 278 "newnode:compass(node)" "SansSerif" 0 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 86 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 27 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 142 292 "manual" "SansSerif" 0 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 35 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 28 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 145 413 "manual" "SansSerif" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 38 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 25 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 142 264 "newnode:new treemutexloc" "SansSerif" 0 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 93 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  1 137 353 506 