5 
    de.renew.gui.CPNDrawing 111 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 4 762 151 762 128 908 128 908 106 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 732 151 "Init\np1: Tok" "Helvetica" 0 18 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 903 84 "T" "Helvetica" 0 18 0 NULL NULL   1
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 4 856 151 856 128 908 128 908 106 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 826 151 "T1\np2: Tok\np3: Tok" "Helvetica" 0 18 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 4 950 151 950 128 908 128 908 106 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 920 151 "T2\np1: Tok" "Helvetica" 0 18 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 4 1022 151 1022 128 908 128 908 106 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 1012 151 "T3" "Helvetica" 0 18 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 4 870 58 870 41 824 41 824 25 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 864 58 "E" "Helvetica" 0 18 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 812 9 "Tok" "Helvetica" 0 12 0 NULL NULL   1
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 14 12 163 162 NULL  REF 15 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 361 234 13 33 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 567 459 31 30 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 582 391 582 460 NULL NULL 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 570 375 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 30   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 3 352 168 339 208 361 240 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 294 8 163 165 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 29   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 3 374 236 387 208 383 172 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 29  
            CH.ifa.draw.figures.ChopEllipseConnector REF 38   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 573 417 "fire" "Helvetica" 0 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 340 196 "pre" "Helvetica" 0 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 56 404 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 76 414 109 414 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 50  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 109 406 24 16 NULL    REF 55 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 131 406 154 390 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 55  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 151 374 20 20 NULL    REF 60 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 153 381 133 373 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 60  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 109 361 24 16 NULL    REF 65 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 111 377 74 409 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 65  
            CH.ifa.draw.figures.ChopEllipseConnector REF 50   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 129 422 150 443 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 55  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 146 439 20 20 NULL    REF 74 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 169 391 186 406 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 60  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 184 406 24 16 NULL    REF 79 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 164 443 186 422 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 74  
            CH.ifa.draw.standard.ChopBoxConnector REF 79   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 58 406 "p1" "Helvetica" 1 12 0 REF 50 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 112 406 "T1" "Helvetica" 1 12 0 REF 55 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 153 376 "p2" "Helvetica" 1 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 148 441 "p3" "Helvetica" 1 12 0 REF 74 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 187 406 "T3" "Helvetica" 1 12 0 REF 79 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 42 401 "[]" "Helvetica" 0 12 0 REF 50 
            CH.ifa.draw.standard.OffsetLocator -20 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    REF 6 REF 33 REF 38 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 84 242 13 33 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 3 79 172 70 208 84 242 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector REF 102   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 3 97 246 114 212 108 173 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 102  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 112 361 "T2" "Helvetica" 1 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 112 340 "<i1>" "Helvetica" 0 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator 3 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 210 405 "<i2>" "Helvetica" 0 12 0 REF 79 
            CH.ifa.draw.standard.OffsetLocator 26 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 1045 91 "i1" "Helvetica" 0 18 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "TraceMode" "Boolean" "FALSE" "FontSize" "Int" 18 4 1052 91 1052 67 1080 67 1080 44 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 120  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 1058 22 "Event" "Helvetica" 0 18 0 NULL NULL   1
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "TraceMode" "Boolean" "FALSE" "FontSize" "Int" 18 4 1101 91 1101 67 1080 67 1080 44 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 1095 91 "i2" "Helvetica" 0 18 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 125  1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 572 355 ":fire(event,pre,post)" "Helvetica" 0 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator 47 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 665 400 "T1" "Helvetica" 0 24 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 812 400 "T2" "Helvetica" 0 24 0 NULL NULL  REF 129 
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 1133 90 "iE" "Helvetica" 0 18 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "TraceMode" "Boolean" "FALSE" "FontSize" "Int" 18 4 1141 90 1141 67 1080 67 1080 44 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 136  
            CH.ifa.draw.standard.ChopBoxConnector REF 125  1  REF 125 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 569 322 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 597 314 ":fire(pre,post);\nthis:fire([iE],pre,post)" "Helvetica" 0 12 0 REF 141 
            CH.ifa.draw.standard.OffsetLocator 76 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 366 195 "post" "Helvetica" 0 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator -1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 232 74 17 36 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 176 93 232 92 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector REF 148   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 249 91 295 91 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 148  
            CH.ifa.draw.figures.ChopEllipseConnector REF 38   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 63 199 "pre" "Helvetica" 0 12 0 REF 103 
            CH.ifa.draw.standard.OffsetLocator -4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 98 201 "post" "Helvetica" 0 12 0 REF 107 
            CH.ifa.draw.standard.OffsetLocator 6 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 256 83 "post" "Helvetica" 0 12 0 REF 153 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 47 275 "this:fire(pre,post)" "Helvetica" 0 12 0 REF 102 
            CH.ifa.draw.standard.OffsetLocator 6 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 184 50 "this:fire([i1],pre,post)" "Helvetica" 0 12 0 REF 148 
            CH.ifa.draw.standard.OffsetLocator 3 -34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 649 232 13 33 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 3 639 166 632 203 649 235 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 2 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 569 1 165 166 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 172   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 3 662 236 680 203 671 165 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 172  
            CH.ifa.draw.figures.ChopEllipseConnector REF 176   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 630 192 "pre" "Helvetica" 0 12 0 REF 173 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 176 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 609 268 "this:fire(pre,post)" "Helvetica" 0 12 0 REF 172 
            CH.ifa.draw.standard.OffsetLocator 3 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 657 191 "post" "Helvetica" 0 12 0 REF 178 
            CH.ifa.draw.standard.OffsetLocator -1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 503 72 17 36 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 456 90 503 90 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 38  
            CH.ifa.draw.standard.ChopBoxConnector REF 191   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 520 89 570 88 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 191  
            CH.ifa.draw.figures.ChopEllipseConnector REF 176   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 470 81 "pre" "Helvetica" 0 12 0 REF 192 
            CH.ifa.draw.standard.OffsetLocator 1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 529 80 "post" "Helvetica" 0 12 0 REF 196 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 455 48 "this:fire([i2],pre,post)" "Helvetica" 0 12 0 REF 191 
            CH.ifa.draw.standard.OffsetLocator 3 -34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 112 219 147 223 141 17 36 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 303 125 240 154 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 38  
            CH.ifa.draw.standard.ChopBoxConnector REF 209   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 223 154 168 129 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 209  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 195 83 "pre" "Helvetica" 0 12 0 REF 149 
            CH.ifa.draw.standard.OffsetLocator 1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 266 131 "p" "Helvetica" 0 12 0 REF 210 
            CH.ifa.draw.standard.OffsetLocator -1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 193 134 "p" "Helvetica" 0 12 0 REF 214 
            CH.ifa.draw.standard.OffsetLocator 2 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 2 166 449 183 449 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 74  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 183 441 24 16 NULL    REF 231 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 186 441 "T4" "Helvetica" 1 12 0 REF 231 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 1 "TraceMode" "Boolean" "FALSE" 4 1055 151 1055 128 908 128 908 106 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 1045 151 "T4" "Helvetica" 0 18 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  REF 238 
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 956 400 "T3" "Helvetica" 0 24 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 1090 404 "T4" "Helvetica" 0 24 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 321 270 "this:fire(pre,post)" "Helvetica" 0 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 3 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.IsaConnection "no_attributes" 4 902 278 902 260 930 260 930 242 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 819 278 "State\nproc: Init\nmark: Marking" "Helvetica" 0 18 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 923 226 "Rule" "Helvetica" 0 12 0 NULL NULL   0
        de.renew.gui.fs.IsaConnection "no_attributes" 4 964 263 964 252 944 252 944 242 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 955 263 "Firing\nevent: Event\nvalues: Marking\nmark: Marking\npost: Marking" "Helvetica" 0 18 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 250  0  REF 248 REF 250 REF 20 REF 10 REF 4 
        de.renew.gui.fs.IsaConnection "no_attributes" 4 790 53 790 39 824 39 824 25 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 767 53 "ValTok\nval" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 27  1  REF 25 
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 1082 171 "Marking\np1: Tok\np2: Tok\np3: Tok" "Helvetica" 0 18 0 NULL NULL  REF 27 REF 259
        de.renew.gui.fs.IsaConnection "no_attributes" 2 788 106 788 85 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 761 106 "ConsTok\ncons: T" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 259  0  REF 265 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 54 63 "[Init\n p1: [ValTok\n         val: [E]]]" "Helvetica" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator -3 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 597 369 "ppre=de.renew.formalism.fs.MarkingNetInstance.processMarking(pre);\npost=(fire+ppre+[Firing event:(event) values:(ppre@mark)])@proc" "Helvetica" 0 12 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator 223 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 254 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 1086 481 "[Firing\n event: [iE]\n mark: [p3: [ConsTok\n                       cons: [T4]]]\n post: [p3: [E]]\n]" "Helvetica" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 572 55 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 951 469 "[Firing\n event: [i2]\n mark: [p2: [ConsTok\n                       cons: [T3]]]\n]" "Helvetica" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 437 35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 798 461 "[Firing\n event: [i1]\n values: [p1: [ConsTok\n                           val: #1]]\n mark: [p1: [E]\n              p2: [ConsTok\n                     cons: [T2\n                                 p1: [ValTok\n                                          val: #1]]]]\n]" "Helvetica" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 306 67 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "TraceMode" "Boolean" "FALSE" "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 607 448 "[Firing\n event: [iE]\n values: [p1: [ConsTok\n                          val: #1]]\n mark: [p1: [ConsTok\n                       cons: [T1\n                                   p2: [ValTok\n                                            val: #1]\n                                   p3: [ValTok\n                                            val: #1]]]\n                p2: [E]\n                p3: [E]]\n]\n" "Helvetica" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 116 78 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  88 136 1277 793 
