
    CH.ifa.draw.cpn.CPNDrawing 84 
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 168 149 "Käufer" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 214 96 "Person" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 244 148 "Verkäufer" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 192 149 226 111 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        fs.IsaConnection 2 265 148 238 111 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 367 93 "Geschick" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 357 141 "gut" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 369 141 387 108 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 13  
            CH.ifa.draw.standard.ChopBoxConnector REF 12   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 423 143 "schlecht" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 437 143 399 108 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 18  
            CH.ifa.draw.standard.ChopBoxConnector REF 12   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 232 204 "Peter" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 319 207 "Paul" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 405 211 "Mary" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 238 204 194 164 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 23  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        fs.IsaConnection 2 266 205 421 158 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 23  
            CH.ifa.draw.standard.ChopBoxConnector REF 18   
        fs.IsaConnection 2 323 207 278 163 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 24  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        fs.IsaConnection 2 344 207 432 158 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 24  
            CH.ifa.draw.standard.ChopBoxConnector REF 18   
        fs.IsaConnection 2 400 211 288 163 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        fs.IsaConnection 2 412 211 371 156 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 25  
            CH.ifa.draw.standard.ChopBoxConnector REF 13   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 155 264 "Fahrzeug\nhersteller: Marke\nlackierung: Farbe" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 79 331 "PKW\nhersteller: PKWMarke" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 210 332 "Motorad\nhersteller: MotoradMarke" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 154 331 178 309 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 51  
            CH.ifa.draw.standard.ChopBoxConnector REF 50   
        fs.IsaConnection 2 259 332 230 309 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 52  
            CH.ifa.draw.standard.ChopBoxConnector REF 50   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 485 273 "Farbe" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 377 311 "metallic" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 444 319 "grün" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 463 319 493 288 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 63  
            CH.ifa.draw.standard.ChopBoxConnector REF 61   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 399 371 "grünMetallic" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 428 371 402 326 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 68  
            CH.ifa.draw.standard.ChopBoxConnector REF 62   
        fs.IsaConnection 2 435 371 453 334 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 68  
            CH.ifa.draw.standard.ChopBoxConnector REF 63   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 546 318 "*rot" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 546 318 510 288 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 77  
            CH.ifa.draw.standard.ChopBoxConnector REF 61   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 337 369 "silber" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 357 369 392 326 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 82  
            CH.ifa.draw.standard.ChopBoxConnector REF 62   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 494 318 "blau" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 418 311 480 288 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 62  
            CH.ifa.draw.standard.ChopBoxConnector REF 61   
        fs.IsaConnection 2 505 318 501 288 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 87  
            CH.ifa.draw.standard.ChopBoxConnector REF 61   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 478 371 "blauMetallic" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 496 371 412 326 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 96  
            CH.ifa.draw.standard.ChopBoxConnector REF 62   
        fs.IsaConnection 2 510 371 506 333 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 96  
            CH.ifa.draw.standard.ChopBoxConnector REF 87   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 193 431 "Marke" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 193 575 "BMW" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 349 577 "Audi" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 287 576 "VW" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 400 571 "Honda" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 459 570 "Daihatsu" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 525 567 "Kawasaki" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 503 420 "Land" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 555 452 528 435 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector 
                fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 548 452 "*Japan" "Helvetica" 0 12 0 NULL NULL 0   
            CH.ifa.draw.standard.ChopBoxConnector REF 112   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 461 452 "*Deutschland" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 502 452 512 435 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 118  
            CH.ifa.draw.standard.ChopBoxConnector REF 112   REF 116 
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 217 391 "Kombi" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 220 391 165 361 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 123  
            CH.ifa.draw.standard.ChopBoxConnector REF 51   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 163 391 "Cabrio" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 175 391 150 361 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 128  
            CH.ifa.draw.standard.ChopBoxConnector REF 51   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 223 476 "PKWMarke" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 122 476 "MotoradMarke" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 169 476 201 446 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 134  
            CH.ifa.draw.standard.ChopBoxConnector REF 105   
        fs.IsaConnection 2 246 476 217 446 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 133  
            CH.ifa.draw.standard.ChopBoxConnector REF 105   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 142 519 "PKWundMotoradMarke" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 197 519 169 491 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 143  
            CH.ifa.draw.standard.ChopBoxConnector REF 134   
        fs.IsaConnection 2 213 519 245 491 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 143  
            CH.ifa.draw.standard.ChopBoxConnector REF 133   
        fs.IsaConnection 2 207 575 205 534 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 106  
            CH.ifa.draw.standard.ChopBoxConnector REF 143   
        fs.IsaConnection 2 304 576 326 555 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 108  
            CH.ifa.draw.standard.ChopBoxConnector 
                fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 299 540 "DPKWMarke" "Helvetica" 0 12 0 NULL NULL 0    REF 160 
        fs.IsaConnection 2 324 540 262 491 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 160  
            CH.ifa.draw.standard.ChopBoxConnector REF 133   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 367 418 "*Herkunft\nland: Land" "Helvetica" 0 12 0 NULL NULL 0  
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 302 460 "Deutsch\nland: Deutschland" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 367 460 379 448 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 166  
            CH.ifa.draw.standard.ChopBoxConnector REF 165   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 420 472 "Japanisch\nland: Japan" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 436 472 411 448 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 171  
            CH.ifa.draw.standard.ChopBoxConnector REF 165   
        fs.IsaConnection 2 335 540 347 490 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 160  
            CH.ifa.draw.standard.ChopBoxConnector REF 166   
        fs.IsaConnection 2 217 575 331 490 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 106  
            CH.ifa.draw.standard.ChopBoxConnector REF 166   
        fs.IsaConnection 2 356 577 339 555 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 107  
            CH.ifa.draw.standard.ChopBoxConnector REF 160   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 71 391 "StandardPKW" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 113 391 129 361 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 188  
            CH.ifa.draw.standard.ChopBoxConnector REF 51   
        fs.TypeFigure "attributes" "attributes" 2 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 199 158 422 522 "JPKWMotoradMarke" "Helvetica" 0 12 0 NULL NULL 0  
        fs.IsaConnection 2 427 571 468 537 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 109  
            CH.ifa.draw.standard.ChopBoxConnector REF 193   
        fs.IsaConnection 2 482 570 478 537 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 110  
            CH.ifa.draw.standard.ChopBoxConnector REF 193   
        fs.IsaConnection 2 539 567 490 537 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 111  
            CH.ifa.draw.standard.ChopBoxConnector REF 193   
        fs.IsaConnection 2 473 522 461 502 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 193  
            CH.ifa.draw.standard.ChopBoxConnector REF 171   
        fs.IsaConnection 2 417 528 274 527 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 193  
            CH.ifa.draw.standard.ChopBoxConnector REF 143    
