
    CH.ifa.draw.cpn.CPNDrawing 8 
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 205 171 24 16  
        CH.ifa.draw.cpn.PlaceFigure "no_attributes" 206 267 20 20  
        CH.ifa.draw.cpn.TransitionFigure "no_attributes" 204 364 24 16  
        CH.ifa.draw.cpn.ArcConnection 2 216 187 216 268 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        CH.ifa.draw.cpn.ArcConnection 2 216 287 216 364 NULL 
            CH.ifa.draw.figures.ArrowTip  0 0 0 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 234 172 ":new()" "Helvetica" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 31 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 222 220 "[\"a\",\"b\"]" "Helvetica" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 28 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.cpn.CPNTextFigure "attributes" "attributes" 2 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 255 199 158 221 313 "[x,y]" "Helvetica" 0 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 16 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1   
