11 
    de.renew.gui.CPNDrawing 21 
        CH.ifa.draw.contrib.TriangleFigure "attributes" "attributes" 3 "FigureWithID" "Int" 6270 "FrameColor" "Color" 224 224 224 255 "FillColor" "Color" 240 240 240 255 154 124 135 264 6  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 4 "LineStyle" "String" "1 2" "FigureWithID" "Int" 6271 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 12 
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 6272 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 292 168 20 20 NULL  
            de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6273 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 160 246 24 16 NULL  
            de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6274 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 255 207 24 16 NULL  
            de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 6275 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 291 318 20 20 NULL  
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 6278 2 275 302 295 322 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6277 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 255 286 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 6   
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FigureWithID" "Int" 6276 "FrameColor" "Color" 0 0 0 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 192 192 192 255 216 244 20 20 NULL  REF 10 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 6282 "Visibility" "Boolean" "TRUE" 2 233 261 258 286 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 12  
                CH.ifa.draw.standard.ChopBoxConnector REF 10   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 6283 "Visibility" "Boolean" "TRUE" 2 233 248 258 223 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 12  
                CH.ifa.draw.standard.ChopBoxConnector REF 5   REF 1 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 6284 "Visibility" "Boolean" "TRUE" 2 184 254 217 254 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 4  
                CH.ifa.draw.figures.ChopEllipseConnector REF 12   
            de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 6286 2 274 207 296 185 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 5  
                CH.ifa.draw.figures.ChopEllipseConnector REF 3    REF 3 REF 4 REF 5 REF 6 REF 12 REF 10 REF 7 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 6279 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 157 246 ">" "SansSerif" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator -10 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 6280 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 305 320 ">" "SansSerif" 1 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 6281 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 222 219 "IF" "SansSerif" 1 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 2 -28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 13 REF 17 REF 21 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 6285 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 255 0 0 255 "FillColor" "Color" 255 199 158 255 306 170 ">" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   0  REF 25 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 6287 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 250 232 "sucess" "SansSerif" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 27 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 6288 "FrameColor" "Color" 255 199 158 255 "Visibility" "Boolean" "TRUE" "FillColor" "Color" 254 254 254 255 252 263 "failure" "SansSerif" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 26 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 6289 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 151 273 "Load \nImages" "SansSerif" 0 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 1 34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "FigureWithID" "Int" 6290 "FrameColor" "Color" 255 199 158 255 "TextColor" "Color" 0 0 255 255 "FillColor" "Color" 255 199 158 255 178 378 "[Load  Images]" "SansSerif" 0 18 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 10 133 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    NULL  63 168 584 600 