7 
    de.renew.gui.CPNDrawing 59 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3 "FillColor" "Color" 255 255 255 4 346 241 346 225 309 225 309 209 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 64 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 343 241 "c" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 76 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 296 193 "Lane" "Helvetica" 0 12 0 NULL NULL   1
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 4 "FillColor" "Color" 255 255 255 2 309 241 309 209 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 63 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 306 241 "b" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 5 "FillColor" "Color" 255 255 255 4 272 241 272 225 309 225 309 209 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 269 241 "a" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 6 "FillColor" "Color" 255 255 255 4 239 69 239 49 324 49 324 30 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 55 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 217 69 "Located" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 42 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 269 14 "_BDItypes::Predicate" "Helvetica" 0 12 0 NULL NULL   1
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 8 "FillColor" "Color" 255 255 255 4 342 69 342 49 324 49 324 30 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 45 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 317 69 "Adjacent" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 22  1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 16 "FillColor" "Color" 255 255 255 4 151 69 151 49 105 49 105 30 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 54 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 138 69 "Drop" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 29 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 59 14 "_BDItypes::Action" "Helvetica" 0 12 0 NULL NULL   1
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 17 "FillColor" "Color" 255 255 255 4 114 69 114 49 105 49 105 30 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 31 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 102 69 "Pick" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 33  1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 18 "FillColor" "Color" 255 255 255 4 53 69 53 49 105 49 105 30 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 28 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 19 69 "Move\n\ndir: Direction" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 33  1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 22 "FillColor" "Color" 255 255 255 4 233 241 233 225 214 225 214 209 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 73 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 225 241 "bin" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 91 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 187 193 "Container" "Helvetica" 0 12 0 NULL NULL   1
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 23 "FillColor" "Color" 255 255 255 4 87 193 87 175 132 175 132 158 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 25 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 52 193 "Waste\n\nname: String" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 71 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 117 142 "Entity" "Helvetica" 0 12 0 NULL NULL   1
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 24 "FillColor" "Color" 255 255 255 4 191 241 191 225 214 225 214 209 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 66 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 177 241 "robot" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 49  1  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 32 2 116 85 130 142 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 37  
            CH.ifa.draw.standard.ChopBoxConnector REF 55   
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 33 2 149 85 134 142 NULL
            de.renew.gui.fs.AssocArrowTip 0.6 12.0 10.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 31  
            CH.ifa.draw.standard.ChopBoxConnector REF 55   REF 31 REF 4 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 67 "FillColor" "Color" 255 255 255 2 229 193 294 158 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 49  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 69 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 285 142 "Location" "Helvetica" 0 12 0 NULL NULL   0
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 75 "FillColor" "Color" 255 255 255 2 309 193 309 158 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 73  1  REF 47 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 80 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 129 99 "what" "Helvetica" 0 12 0 REF 65 
            CH.ifa.draw.standard.OffsetLocator 1 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 15 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 92 "FillColor" "Color" 255 255 255 4 214 193 214 175 132 175 132 158 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 49  
            CH.ifa.draw.standard.ChopBoxConnector REF 55  1  REF 59 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 94 "FillColor" "Color" 255 255 255 4 290 69 290 49 324 49 324 30 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 93 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 280 69 "Idle" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 22  1  REF 37 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 79 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 98 99 "what" "Helvetica" 0 12 0 REF 61 
            CH.ifa.draw.standard.OffsetLocator -12 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 98 "FillColor" "Color" 255 255 255 2 153 150 191 150 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 55  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 97 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 196 142 "Object" "Helvetica" 0 12 0 NULL NULL   0
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 99 "FillColor" "Color" 255 255 255 2 280 150 238 150 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 73  
            CH.ifa.draw.standard.ChopBoxConnector REF 97  0  REF 10 REF 97 REF 6 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 101 "FillColor" "Color" 255 255 255 4 395 217 395 202 415 202 415 187 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 100 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 384 217 "Left" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 53 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 390 171 "Direction" "Helvetica" 0 12 0 NULL NULL   1
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 103 "FillColor" "Color" 255 255 255 4 435 217 435 202 415 202 415 187 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 102 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 421 217 "Right" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 107  1  REF 111 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 105 "FillColor" "Color" 255 255 255 4 419 69 419 49 324 49 324 30 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 104 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 385 69 "InDirection\n\ndir: Direction" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector REF 22  1  REF 22 REF 88 
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 106 2 228 85 144 142 NULL
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 20  
            CH.ifa.draw.standard.ChopBoxConnector REF 55   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 107 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 173 106 "what" "Helvetica" 0 12 0 REF 118 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 108 2 247 85 301 142 NULL
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 20  
            CH.ifa.draw.standard.ChopBoxConnector REF 73   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 109 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 269 106 "at" "Helvetica" 0 12 0 REF 125 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 110 3 332 85 309 105 309 142 NULL
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector REF 73   REF 26 
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 112 3 342 85 345 112 317 142 NULL
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector REF 73   
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 114 3 402 103 382 123 331 142 NULL
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 116  
            CH.ifa.draw.standard.ChopBoxConnector REF 73   
        de.renew.gui.fs.AssocConnection "attributes" "attributes" 1 "FigureWithID" "Int" 116 3 414 103 406 134 339 145 NULL
            de.renew.gui.fs.AssocArrowTip 0.4 11.0 11.0 1
            CH.ifa.draw.standard.ChopBoxConnector REF 116  
            CH.ifa.draw.standard.ChopBoxConnector REF 73   REF 116 REF 107 REF 33 REF 55 REF 53 REF 73 REF 49 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 115 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 369 115 "from" "Helvetica" 0 12 0 REF 140 
            CH.ifa.draw.standard.OffsetLocator 15 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 117 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 401 127 "to" "Helvetica" 0 12 0 REF 144 
            CH.ifa.draw.standard.OffsetLocator 30 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 111 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 301 96 "left" "Helvetica" 0 12 0 REF 132 
            CH.ifa.draw.standard.OffsetLocator -11 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 113 "FrameColor" "Color" 255 199 158 "FillColor" "Color" 254 254 254 330 105 "right" "Helvetica" 0 12 0 REF 136 
            CH.ifa.draw.standard.OffsetLocator 11 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 20 REF 42 REF 105 NULL  479 429 541 313 
