6 
    de.renew.gui.CPNDrawing 10 
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 14 "FillColor" "Color" 255 255 255 4 50 72 50 53 139 53 139 35 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 1 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 41 72 "Get" "Helvetica" 0 12 0 NULL NULL
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 11 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 92 5 "LinkWithProduct\nprod: Product" "Helvetica" 0 12 0 NULL NULL   1
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 5 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 76 72 "Unavailable" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 15 "FillColor" "Color" 255 255 255 4 108 72 108 53 139 53 139 35 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 6 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 156 72 "Exists" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 16 "FillColor" "Color" 255 255 255 4 173 72 173 53 139 53 139 35 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 12  
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 7 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 206 72 "StockUp" "Helvetica" 0 12 0 NULL NULL
        de.renew.gui.fs.IsaConnection "attributes" "attributes" 2 "FigureWithID" "Int" 17 "FillColor" "Color" 255 255 255 4 229 72 229 53 139 53 139 35 NULL
            de.renew.gui.fs.IsaArrowTip 0.6 15.0 12.0 0
            CH.ifa.draw.standard.ChopBoxConnector REF 17  
            CH.ifa.draw.standard.ChopBoxConnector REF 6  1  
        de.renew.gui.fs.ConceptFigure "attributes" "attributes" 3 "FigureWithID" "Int" 4 "FrameColor" "Color" 0 0 0 "FillColor" "Color" 255 255 255 41 5 "New" "Helvetica" 0 12 0 NULL NULL  REF 6 REF 4 NULL  454 437 303 151
